8GadgetPack.net.8GadgetPack version 36.0.0
microsoft/winget-pkgs pull request #100052
Opened 2023-03-19 18:21 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-03-20 12:49 UTC, Trenly requested changes

2023-03-20 12:49 UTC, Trenly commented on manifests/8/8GadgetPack/net/8GadgetPack/36.0.0/8GadgetPack.net.8GadgetPack.installer.yaml
> +PackageIdentifier: 8GadgetPack.net.8GadgetPack
```suggestion
PackageIdentifier: 8GadgetPack.8GadgetPack
```
Package folder will need to be updated when identifier is changed

2023-03-20 12:49 UTC, Trenly commented on manifests/8/8GadgetPack/net/8GadgetPack/36.0.0/8GadgetPack.net.8GadgetPack.locale.en-US.yaml
> +PackageIdentifier: 8GadgetPack.net.8GadgetPack
```suggestion
PackageIdentifier: 8GadgetPack.8GadgetPack
```
Package folder will need to be updated when identifier is changed

2023-03-20 12:49 UTC, Trenly commented on manifests/8/8GadgetPack/net/8GadgetPack/36.0.0/8GadgetPack.net.8GadgetPack.yaml
> +PackageIdentifier: 8GadgetPack.net.8GadgetPack
```suggestion
PackageIdentifier: 8GadgetPack.8GadgetPack
```
Package folder will need to be updated when identifier is changed

2023-03-21 21:04 UTC, stephengillie commented
Manifest validation error:
>  Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 'manifests\8\8GadgetPack\net\8GadgetPack\36.0.0', expected 'manifests\8\8GadgetPack\8GadgetPack\36.0.0'

There's a `\net` in the file path that needs to be removed.

2023-04-03 21:11 UTC, Trenly commented
Close with reason: Stale PR;

2023-04-03 21:11 UTC, closed without merging