KardinoDX.TouchHLEG version 2.0
microsoft/winget-pkgs pull request #100051
Opened 2023-03-19 18:15 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-03-20 12:56 UTC, Trenly commented
![image](https://user-images.githubusercontent.com/12611259/226345206-77546410-49b7-4122-ac65-acd0cd3b014b.png)

<!--
[Policy] Dependencies
-->

2023-03-20 13:01 UTC, Trenly requested changes
This may not be a good fit for WinGet due to the requirement of touchHLE and touchHLEG being extracted to the same folder; You may need to set `InstallLocationRequired: true` for this package
![image](https://user-images.githubusercontent.com/12611259/226346232-5c6bd730-8534-45e6-a3e8-612220902b12.png)

2023-03-23 22:27 UTC, stephengillie commented
> ![image](https://user-images.githubusercontent.com/12611259/226345206-77546410-49b7-4122-ac65-acd0cd3b014b.png)

I'm not sure how it passed validation, as the application still shows this message when launched.

2023-03-27 11:06 UTC, ItzLevvie commented
[Policy] Blocking-Issue

2023-12-27 20:03 UTC, stephengillie commented
/AzurePipelines run

2023-12-28 18:39 UTC, stephengillie commented on manifests/k/KardinoDX/TouchHLEG/2.0/KardinoDX.TouchHLEG.installer.yaml
> +PackageVersion: 2.0
```suggestion
PackageVersion: 2.0
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
```

2024-01-06 05:16 UTC, closed without merging