NeumetrixLimited.HttpWatchBasic14.0Setup version 14.0.16
microsoft/winget-pkgs pull request #100055
Opened 2023-03-19 18:44 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-03-20 12:51 UTC, Trenly requested changes

2023-03-20 12:51 UTC, Trenly commented on manifests/n/NeumetrixLimited/HttpWatchBasic14/0Setup/14.0.16/NeumetrixLimited.HttpWatchBasic14.0Setup.installer.yaml
> +PackageIdentifier: NeumetrixLimited.HttpWatchBasic14.0Setup
```suggestion
PackageIdentifier: NeumetrixLimited.HttpWatchBasic.14
```
Package folder will need to be updated when identifier is changed

2023-03-20 12:51 UTC, Trenly commented on manifests/n/NeumetrixLimited/HttpWatchBasic14/0Setup/14.0.16/NeumetrixLimited.HttpWatchBasic14.0Setup.locale.en-US.yaml
> +PackageIdentifier: NeumetrixLimited.HttpWatchBasic14.0Setup
```suggestion
PackageIdentifier: NeumetrixLimited.HttpWatchBasic.14
```
Package folder will need to be updated when identifier is changed

2023-03-20 12:51 UTC, Trenly commented on manifests/n/NeumetrixLimited/HttpWatchBasic14/0Setup/14.0.16/NeumetrixLimited.HttpWatchBasic14.0Setup.yaml
> +PackageIdentifier: NeumetrixLimited.HttpWatchBasic14.0Setup
```suggestion
PackageIdentifier: NeumetrixLimited.HttpWatchBasic.14
```
Package folder will need to be updated when identifier is changed

2023-03-20 12:51 UTC, Trenly commented on manifests/n/NeumetrixLimited/HttpWatchBasic14/0Setup/14.0.16/NeumetrixLimited.HttpWatchBasic14.0Setup.locale.en-US.yaml
> +PackageName: HttpWatch Basic 14.0 Setup
```suggestion
PackageName: HttpWatch Basic
```
Should match control panel as closely as possible

2023-03-27 21:06 UTC, stephengillie commented
Manual Validation failed with:
>  Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 'manifests\n\NeumetrixLimited\HttpWatchBasic14\0Setup\14.0.16', expected 'manifests\n\NeumetrixLimited\HttpWatchBasic\14\14.0.16'

2023-04-17 16:48 UTC, stephengillie commented
Closing as No Recent Activity.

2023-04-17 16:48 UTC, closed without merging