GLab.GLab version 1.27.0
microsoft/winget-pkgs pull request #101308
Opened 2023-04-01 02:24 UTC by unwillinglyawesome

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-04-02 18:18 UTC, mdanish-kh requested changes

2023-04-02 18:18 UTC, mdanish-kh commented on manifests/g/GLab/GLab/1.27.0/GLab.GLab.locale.en-US.yaml
> +- gitlab-ci
```suggestion
- gitlab-cli
```
Looks like a typo

2023-04-02 18:18 UTC, mdanish-kh commented on manifests/g/GLab/GLab/1.27.0/GLab.GLab.locale.en-US.yaml
> +PackageName: GitLab CLI
```suggestion
PackageName: glab
```
Must match Control Panel / Apps&Features

2023-04-03 20:27 UTC, stephengillie approved these changes

2023-04-03 20:27 UTC, merged