TELUS.TELUSBusinessConnectPhone version 23.1.1.45971
microsoft/winget-pkgs pull request #101468
Opened 2023-04-03 22:20 UTC by VA6DAH

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-04-03 22:27 UTC, VA6DAH commented
@microsoft-github-policy-service agree

2023-04-04 00:49 UTC, Trenly requested changes

2023-04-04 00:49 UTC, Trenly commented on manifests/t/TELUS/TELUSBusinessConnectPhone/23.1.1.45971/TELUS.TELUSBusinessConnectPhone.installer.yaml
> +PackageIdentifier: TELUS.TELUSBusinessConnectPhone
```suggestion
PackageIdentifier: TELUS.BusinessConnectPhone
```
Best practice is to not repeat the publisher. After making this change, the folder and file names will need to be updated also

2023-04-04 00:49 UTC, Trenly commented on manifests/t/TELUS/TELUSBusinessConnectPhone/23.1.1.45971/TELUS.TELUSBusinessConnectPhone.locale.en-US.yaml
> +PackageIdentifier: TELUS.TELUSBusinessConnectPhone
```suggestion
PackageIdentifier: TELUS.BusinessConnectPhone
```
Best practice is to not repeat the publisher. After making this change, the folder and file names will need to be updated also

2023-04-04 00:49 UTC, Trenly commented on manifests/t/TELUS/TELUSBusinessConnectPhone/23.1.1.45971/TELUS.TELUSBusinessConnectPhone.yaml
> +PackageIdentifier: TELUS.TELUSBusinessConnectPhone
```suggestion
PackageIdentifier: TELUS.BusinessConnectPhone
```
Best practice is to not repeat the publisher. After making this change, the folder and file names will need to be updated also

2023-04-04 00:49 UTC, Trenly commented on manifests/t/TELUS/TELUSBusinessConnectPhone/23.1.1.45971/TELUS.TELUSBusinessConnectPhone.locale.en-US.yaml
> +License: http://telus.com/BusinessConnect/ServiceTerms
```suggestion
License: Proprietary
LicenseUrl: http://telus.com/BusinessConnect/ServiceTerms
```
A URL is not a License

2023-04-04 15:54 UTC, VA6DAH commented
/AzurePipelines run

2023-04-04 22:20 UTC, stephengillie approved these changes

2023-04-04 22:20 UTC, merged