Elcomsoft.ElcomsoftCloudeXplorer version 2.32.37098.6840
microsoft/winget-pkgs pull request #102153
Opened 2023-04-11 01:43 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-04-11 02:01 UTC, Trenly requested changes

2023-04-11 02:01 UTC, Trenly commented on manifests/e/Elcomsoft/ElcomsoftCloudeXplorer/2.32.37098.6840/Elcomsoft.ElcomsoftCloudeXplorer.installer.yaml
> +PackageIdentifier: Elcomsoft.ElcomsoftCloudeXplorer
```suggestion
PackageIdentifier: Elcomsoft.CloudeXplorer
```

2023-04-11 02:01 UTC, Trenly commented on manifests/e/Elcomsoft/ElcomsoftCloudeXplorer/2.32.37098.6840/Elcomsoft.ElcomsoftCloudeXplorer.yaml
> +PackageIdentifier: Elcomsoft.ElcomsoftCloudeXplorer
```suggestion
PackageIdentifier: Elcomsoft.CloudeXplorer
```

2023-04-12 18:39 UTC, stephengillie commented
Automatic Validation failed with:
```
Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 
'manifests\e\Elcomsoft\ElcomsoftCloudeXplorer\2.32.37098.6840', expected 
'manifests\e\Elcomsoft\CloudeXplorer\2.32.37098.6840' 
```

There's an extra `Elcomsoft` in the path, before `CloudeXplorer`.

2023-04-24 23:53 UTC, upintheairsheep commented
Seriously GitHub, just add the multiple item moving feature.

2023-05-11 19:31 UTC, stephengillie approved these changes

2023-05-11 19:31 UTC, merged