Andrelouis.NokiaS30MidiSim version 1.0
microsoft/winget-pkgs pull request #102951
Opened 2023-04-19 21:45 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-04-27 02:42 UTC, upintheairsheep commented
portable app

2023-04-28 19:47 UTC, stephengillie commented on manifests/a/Andrelouis/NokiaS30MidiSim/1.0/Andrelouis.NokiaS30MidiSim.installer.yaml
> +  NestedInstallerType: exe
```suggestion
  NestedInstallerType: portable
```

2023-05-01 19:18 UTC, stephengillie commented
This package installed normally, but errors when launched: 
> Faulting application name: Simulator-050518-ADPCM_support.exe, version: 1.0.0.1, time stamp: 0x428aeafc 
> Faulting module name: Simulator-050518-ADPCM_support.exe, version: 1.0.0.1, time stamp: 0x428aeafc 
> Exception code: 0xc0000005 Fault offset: 0x00008f24 
> Faulting process id: 0x0x2388 
> Faulting application start time: 0x0x1D97C6128661D22 
> Faulting application path: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Andrelouis.NokiaS30MidiSim__DefaultSource\Simulator-050518-ADPCM_support.exe 
> Faulting module path: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Andrelouis.NokiaS30MidiSim__DefaultSource\Simulator-050518-ADPCM_support.exe 
> Report Id: 5bcd677d-9c83-4b75-8f14-bc4d7b01debf 
> Faulting package full name:  
> Faulting package-relative application ID:  

![image](https://user-images.githubusercontent.com/114952565/235514317-bbba1294-74d8-4fbb-828e-eabb9a849949.png)

2023-06-11 21:22 UTC, ItzLevvie requested changes
See https://github.com/microsoft/winget-pkgs/pull/102951#issuecomment-1530101546

2023-06-24 20:15 UTC, ItzLevvie commented
[Policy] Blocking-Issue

2023-06-24 20:15 UTC, ItzLevvie commented
[Policy] Hardware

2023-12-20 19:02 UTC, stephengillie commented
/AzurePipelines run

2024-07-04 23:46 UTC, ItzLevvie commented
[Policy] Hardware

2024-07-04 23:49 UTC, ItzLevvie commented
[Policy] Blocking-Issue

2024-09-07 11:06 UTC, ItzLevvie commented
@wingetbot run

2024-09-07 11:46 UTC, ItzLevvie commented
[Policy] Blocking-Issue

2024-12-18 01:03 UTC, denelon commented
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504

2024-12-18 01:04 UTC, closed without merging