Mariocube.EasyCSM version 1.4
microsoft/winget-pkgs pull request #103189
Opened 2023-04-22 16:43 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-04-23 03:57 UTC, mdanish-kh requested changes

2023-04-23 03:57 UTC, mdanish-kh commented on manifests/m/Mariocube/EasyCSM/1.4/Mariocube.EasyCSM.installer.yaml
> +PackageVersion: 1.4
```suggestion
PackageVersion: 1.4
AppsAndFeaturesEntries:
  - DisplayVersion:
```
The installer doesn't write a display version string to registry

2023-04-23 03:57 UTC, mdanish-kh commented on manifests/m/Mariocube/EasyCSM/1.4/Mariocube.EasyCSM.installer.yaml
> +  InstallerType: inno
```suggestion
  InstallerType: inno
  Scope: machine
  ProductCode: '{C8AB2AA8-501D-4553-B096-CD78EFB90366}_is1'
```
For better package matching

2023-04-23 03:57 UTC, mdanish-kh commented on manifests/m/Mariocube/EasyCSM/1.4/Mariocube.EasyCSM.locale.en-US.yaml
> +PackageName: Easy CSAM
```suggestion
PackageName: ECSM
```
Must match whatever is written to registry (shown in Apps&Features or `appwiz.cpl`)

2023-04-23 03:57 UTC, mdanish-kh commented on manifests/m/Mariocube/EasyCSM/1.4/Mariocube.EasyCSM.locale.en-US.yaml
> +Publisher: Mariocube
```suggestion
Publisher: c0mputeRb0y
```
Must match whatever is written to registry (shown in Apps&Features or `appwiz.cpl`)

2023-04-24 21:23 UTC, stephengillie approved these changes

2023-04-24 21:23 UTC, merged