Move Valve.Steam to ValveCorporation, update it
microsoft/winget-pkgs pull request #103269
Opened 2023-04-23 13:53 UTC by kbdharun

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-04-23 14:08 UTC, kbdharun commented
@stephengillie I have a doubt, Since Steam and Steam Link are published under ValveCorporation and not just Valve, I moved the manifest to the latter and updated it. Is this anything else, I must do in this PR to fix the Validation warning? Or is it not possible to change the publisher at all?

2023-04-23 16:27 UTC, russellbanks requested changes
Addition and deletion are only allowed in the same directory. This would have to be two PRs. I'll wait on another moderator though for whether this should be moved

2023-04-23 17:21 UTC, kbdharun commented
> Addition and deletion are only allowed in the same directory. This would have to be two PRs. I'll wait on another moderator though for whether this should be moved

If required, I will separate the move and change to separate PRs. I don't know if this change will break existing users.

2023-04-24 06:17 UTC, mdanish-kh requested changes
Since Valve.Steam is a popular (I guess?) package and the fact it was added earlier in the repo, I would advise against moving this package to avoid breaking any existing scripts that people may be using to install this package.

I would much rather prefer if we moved `ValveCorporation.SteamLink` into `Valve.SteamLink` and avoid duplicate directories

2023-04-24 06:49 UTC, SpecterShell commented
Short publisher name is preferred, for example `Microsoft.*` instead of `MicrosoftCorporation.*`

2023-04-24 06:51 UTC, kbdharun commented
> Short publisher name is preferred, for example `Microsoft.*` instead of `MicrosoftCorporation.*`

Noted, I will move the Steam link to the shorter Valve directory later today.

2023-04-24 18:22 UTC, mdanish-kh requested changes
Only one manifest can be modified per PR. You'll have to revert the changes you've made to `Valve.Steam`

For the move process, you'll have to create two separate PRs, one for deleting `ValveCorportation.SteamLink` and the other for adding `Valve.SteamLink`. If you're confused, you can take a look at this example

- Deletion PR https://github.com/microsoft/winget-pkgs/pull/101303
- Addition PR https://github.com/microsoft/winget-pkgs/pull/101305

2023-04-24 20:07 UTC, stephengillie commented
Automatic Validation failed with:
>  The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

2023-04-25 16:30 UTC, kbdharun commented
> For the move process, you'll have to create two separate PRs, one for deleting `ValveCorportation.SteamLink` and the other for adding `Valve.SteamLink`. If you're confused, you can take a look at this example

Thanks for the heads up, I have separated the changes into 3 separate PRs, the other 2 being 
- https://github.com/microsoft/winget-pkgs/pull/103450 and 
- https://github.com/microsoft/winget-pkgs/pull/103451.

Sorry for the delay 😄 (I had some work).

2023-04-25 16:35 UTC, mdanish-kh commented
The other two PRs look good, this one needs a tiny change to pass the pipelines:

`ValveCorporation.SteamLink` was deleted in this PR/branch, you'll have to revert this change and put it back in it's folder as the deletion is handled in separate PR #103450

2023-04-25 16:43 UTC, mdanish-kh commented
Or update your branch and merge changes from the master branch as the deletion PR is now merged

2023-04-25 16:44 UTC, kbdharun commented
> ...and you beat me to it 😅

Lol

2023-04-25 17:03 UTC, mdanish-kh requested changes

2023-04-25 17:03 UTC, mdanish-kh commented on manifests/v/Valve/SteamLink/1.2.0/Valve.SteamLink.locale.en-US.yaml
> +PackageName: Steam Link
```suggestion
PackageName: Steam Link
PackageUrl: https://store.steampowered.com/app/353380/Steam_Link/
```
Additional metadata

2023-04-25 17:15 UTC, kbdharun commented on manifests/v/Valve/SteamLink/1.2.0/Valve.SteamLink.installer.yaml
> +  ProductCode: '{BF6669C3-9C1D-4D0C-9468-38A91F6BA95B}'
Updated the SHA, there is no change in product code, so left it as is.

2023-04-25 18:32 UTC, mdanish-kh approved these changes

2023-04-25 21:50 UTC, merged