Submitting digiCamControl version 2.1.6.0
microsoft/winget-pkgs pull request #103689
Opened 2023-04-27 01:41 UTC by daymickcorr

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
no 

- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
yes 
- [ ] This PR only modifies one (1) manifest
yes 
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
yes
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
yes
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?
yes 
Note: `<path>` is the name of the directory containing the manifest you're submitting.
yes
-----

2023-04-27 01:46 UTC, daymickcorr commented
@microsoft-github-policy-service agree

2023-04-27 18:17 UTC, stephengillie commented on manifests/d/dukus/digiCamControl/2.1.6.0/dukus.digiCamControl.locale.en-US.yaml
> +PackageName: digiCamControl
```suggestion
PublisherUrl: https://digicamcontrol.com/
PublisherSupportUrl: https://sourceforge.net/projects/digicamcontrol/support
PackageName: digiCamControl
PackageUrl: https://digicamcontrol.com/download
```

2023-04-27 18:18 UTC, stephengillie commented
@wingetbot waivers Add Validation-Unapproved-URL

2023-04-28 17:14 UTC, Trenly requested changes

2023-04-28 17:14 UTC, Trenly commented on manifests/d/dukus/digiCamControl/2.1.6.0/dukus.digiCamControl.locale.en-US.yaml
> +ShortDescription: digiCamControl
Please provide a better description of what digiCamControl is used for / does

2023-04-28 17:14 UTC, Trenly commented on manifests/d/dukus/digiCamControl/2.1.6.0/dukus.digiCamControl.locale.en-US.yaml
> +License: MIT License
```suggestion
License: MIT
```

2023-04-28 22:14 UTC, stephengillie approved these changes

2023-04-28 22:14 UTC, merged