AtomixProductions.VirtualDJ2023 version 8.5.7482.0
microsoft/winget-pkgs pull request #103688
Opened 2023-04-27 00:32 UTC by tompipe

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-04-27 23:08 UTC, tompipe commented
> @microsoft-github-policy-service agree

2023-04-28 17:15 UTC, Trenly requested changes

2023-04-28 17:15 UTC, Trenly commented on manifests/a/AtomixProductions/VirtualDJ2023/8.5.7482.0/AtomixProductions.VirtualDJ2023.locale.en-US.yaml
> +License: https://www.virtualdj.com/EULA/
```suggestion
License: Proprietary
LicenseUrl: https://www.virtualdj.com/EULA/

```

2023-04-28 17:15 UTC, Trenly commented on manifests/a/AtomixProductions/VirtualDJ2023/8.5.7482.0/AtomixProductions.VirtualDJ2023.locale.en-US.yaml
> +ShortDescription: VirtualDJ
Please provide a better short description of what this package is used for

2023-05-13 01:46 UTC, closed without merging