Markdown Monster
microsoft/winget-pkgs pull request #1038
Opened 2020-05-25 11:10 UTC by alanlima

2020-05-25 17:34 UTC, superusercode requested changes

2020-05-28 18:27 UTC, superusercode commented
@alanlima static links to releases are kept here: https://github.com/RickStrahl/MarkdownMonsterReleases

2020-05-29 20:03 UTC, alanlima commented
Thanks @superusercode 
I updated the manifest 😁

2020-05-30 02:02 UTC, ghost approved these changes
Validation has completed

2020-05-30 02:03 UTC, merged