Apple.iPod13Update version 1.3
microsoft/winget-pkgs pull request #106244
Opened 2023-05-09 02:14 UTC by upintheairsheep

Here we go, reopening all stale pulls and fixing them.

2023-05-09 05:35 UTC, Trenly requested changes

2023-05-09 05:35 UTC, Trenly commented on manifests/a/Apple/iPod13Update/1.3/Apple.iPod13Update.locale.en-US.yaml
> +Copyright: 751
This doesn't look like a valid copyright

2023-05-09 21:47 UTC, stephengillie commented
Automatic Validation ended with:
> Installation failed with exit code -1978335226 2023-05-08 
> 19:24:10.711 [CLI ] ShellExecute installer failed: 4294967293 
![InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230509022410](https://github.com/microsoft/winget-pkgs/assets/114952565/ba108a33-ca9c-41e1-b8c7-f4349d0de80f)

2023-05-09 22:14 UTC, stephengillie commented on manifests/a/Apple/iPod13Update/1.3/Apple.iPod13Update.locale.en-US.yaml
> +Copyright: 751
```suggestion
Publisher: Apple Computer, Inc.
PublisherUrl: https://www.apple.com/
PublisherSupportUrl: https://support.apple.com/
PrivacyUrl:   https://www.apple.com/legal/privacy/en-ww/
PackageName: iPod Software 1.3 Updater
PackageUrl: https://support.apple.com/kb/DL729?viewlocale=en_US&locale=en_US
License: Propretary
Copyright: ©2003 Apple Computer, Inc.
```

2023-05-09 22:15 UTC, stephengillie commented on manifests/a/Apple/iPod13Update/1.3/Apple.iPod13Update.locale.en-US.yaml
> +Copyright: 751
Copyright was found in the `readme.doc` file accompanying the package.

2023-05-09 23:33 UTC, stephengillie commented
This package is failing to install correctly, and I'm having difficulty determining why.

2023-05-12 21:55 UTC, stephengillie commented
>  Manifest Error: Duplicate field found in the manifest. [Publisher]

2023-05-12 21:55 UTC, stephengillie commented on manifests/a/Apple/iPod13Update/1.3/Apple.iPod13Update.locale.en-US.yaml
> +Publisher: Apple Computer, Inc.
```suggestion
```

2023-05-21 20:19 UTC, upintheairsheep commented
Merge?

2023-05-24 21:19 UTC, stephengillie commented
Running interactive, it asks to reboot. It's the only guess I have. 
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/8fd70a94-ef8b-4083-9d40-95c1b2c80b4b)

2023-05-27 07:48 UTC, upintheairsheep commented
> Running interactive, it asks to reboot. It's the only guess I have. ![image](https://user-images.githubusercontent.com/114952565/240744147-8fd70a94-ef8b-4083-9d40-95c1b2c80b4b.png)

Interactive only?

2023-06-06 01:43 UTC, upintheairsheep commented
???

2023-06-12 23:26 UTC, stephengillie commented
This is unexpected - WinGet fails due to an installer error, but the installer logged success to the Application Log: 
> Windows Installer installed the product. Product Name: iPod Software 1.3 Updater. Product Version: 1.3. Product Language: 1033. Manufacturer: Apple Computer, Inc.. Installation success or error status: 0.

2023-06-13 19:38 UTC, stephengillie commented
> This is unexpected - WinGet fails due to an installer error, but the installer logged success to the Application Log:
> 
> > Windows Installer installed the product. Product Name: iPod Software 1.3 Updater. Product Version: 1.3. Product Language: 1033. Manufacturer: Apple Computer, Inc.. Installation success or error status: 0.

Re-running this, the installer appears to return 0 regardless of install outcome. The installer's silent installer switches don't result in a successful install.

2023-12-10 03:55 UTC, closed without merging