Autogenerated/samsung electronics.samsung magician/9f3139d7 bdf9 4e05 b8df e0353ec37ab8
microsoft/winget-pkgs pull request #106259
Opened 2023-05-09 02:44 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-05-09 02:59 UTC, Trenly requested changes
The folder and files need to be renamed to match the package identifier

2023-05-09 03:01 UTC, Trenly commented on manifests/s/SamsungElectronics/SamsungMagician/4.1/SamsungElectronics.SamsungMagician.locale.en-US.yaml
> +ShortDescription: Samsung Magician
Please provide a better description of what Samsung Magician is used for

2023-05-09 03:02 UTC, Trenly requested changes

2023-05-09 03:02 UTC, Trenly commented on manifests/s/SamsungElectronics/SamsungMagician/4.1/SamsungElectronics.SamsungMagician.installer.yaml
> +PackageVersion: 4.1
```suggestion
PackageVersion: 4.1.0
```
This should match control panel. The version folder name will also need to be updated

2023-05-09 03:02 UTC, Trenly commented on manifests/s/SamsungElectronics/SamsungMagician/4.1/SamsungElectronics.SamsungMagician.locale.en-US.yaml
> +PackageVersion: 4.1
```suggestion
PackageVersion: 4.1.0
```
This should match control panel. The version folder name will also need to be updated

2023-05-09 03:02 UTC, Trenly commented on manifests/s/SamsungElectronics/SamsungMagician/4.1/SamsungElectronics.SamsungMagician.yaml
> +PackageVersion: 4.1
```suggestion
PackageVersion: 4.1.0
```
This should match control panel. The version folder name will also need to be updated

2023-05-09 23:18 UTC, stephengillie commented
Automatic Validation ended with:
> Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 
> 'manifests\s\SamsungElectronics\SamsungMagician\4.1', expected 
> 'manifests\s\Samsung\SamsungMagician\4.1'

2023-05-12 20:25 UTC, stephengillie approved these changes, later dismissed

2023-05-12 22:57 UTC, stephengillie commented on manifests/s/Samsung/SamsungMagician/4.1.0/Samsung.SamsungMagician.locale.en-US.yaml
> +Copyright: Copyright © 2023 Samsung Electronics Co., Ltd. All rights reserved.
```suggestion
Description: Samsung Magician is designed to help users easily manage their Samsung SSD(s) and conveniently update the firmware as well as optimize their SSD(s) for performance and reliability.
Copyright: Copyright © 2023 Samsung Electronics Co., Ltd. All rights reserved.
```

2023-05-15 19:41 UTC, stephengillie approved these changes

2023-05-15 19:41 UTC, stephengillie approved these changes

2023-05-15 19:42 UTC, merged