Submitting M-Files Online Client 23.4.12528.8
microsoft/winget-pkgs pull request #106311
Opened 2023-05-09 13:37 UTC by aurel-bul

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-05-09 13:38 UTC, aurel-bul commented
@microsoft-github-policy-service agree

2023-05-09 18:42 UTC, mdanish-kh requested changes

2023-05-09 18:42 UTC, mdanish-kh commented on manifests/m/M-FilesCorporation/M-FilesOnline/23.4.12528.8/M-FilesCorporation.M-FilesOnline.locale.eng.yaml
> +License: © 2022 M-Files, All Rights Reserved
```suggestion
License: Proprietary
```
A copyright isn't a license

2023-05-09 18:42 UTC, mdanish-kh commented on manifests/m/M-FilesCorporation/M-FilesOnline/23.4.12528.8/M-FilesCorporation.M-FilesOnline.locale.eng.yaml
> +PackageLocale: eng
```suggestion
PackageLocale: en-US
```
Please use the BCP-47 language codes.

2023-05-09 18:42 UTC, mdanish-kh commented on manifests/m/M-FilesCorporation/M-FilesOnline/23.4.12528.8/M-FilesCorporation.M-FilesOnline.yaml
> +DefaultLocale: eng
```suggestion
DefaultLocale: en-US
```
Please use the BCP-47 language codes.

2023-05-10 02:36 UTC, stephengillie commented
Automatic Validation failed with:
>  Manifest: The filename must match the PackageIdentifier and ManifestType properties from the manifest. actual 
> 'M-FilesCorporation.M-FilesOnline.locale.eng.yaml', expected 
> 'M-FilesCorporation.M-FilesOnline.locale.en-US.yaml'  

The filename has a `g` instead of `-US`.

2023-05-10 09:34 UTC, mdanish-kh approved these changes

2023-05-10 09:34 UTC, merged