Metadata: TominLab.WonderPen version 2.1.10
microsoft/winget-pkgs pull request #106695
Opened 2023-05-12 23:01 UTC by SpecterShell

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-05-13 20:08 UTC, mdanish-kh requested changes
`ElevationRequirement: elevationRequired` can be modified to `elevatesSelf` for machine scope

2023-05-15 19:13 UTC, stephengillie commented on manifests/t/TominLab/WonderPen/2.1.10/TominLab.WonderPen.installer.yaml
>    ElevationRequirement: elevationRequired
```suggestion
  ElevationRequirement: elevatesSelf
```

2023-05-15 19:14 UTC, stephengillie commented on manifests/t/TominLab/WonderPen/2.1.10/TominLab.WonderPen.installer.yaml
>    ElevationRequirement: elevationRequired
GitHub's single comment suggestion doesn't seem to work after unfolding the page to reveal the other replacement location. So maybe @SpecterShell will have to modify that one.

2023-05-16 19:16 UTC, stephengillie approved these changes

2023-05-16 19:16 UTC, merged