GlobalMarineNet.XWeb version 1.7
microsoft/winget-pkgs pull request #107506
Opened 2023-05-20 05:07 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-05-21 18:30 UTC, Trenly requested changes
This package doesn't write the Publisher or DisplayVersion to the apps and features entries and so users might not be able to upgrade it

2023-05-21 18:30 UTC, Trenly commented on manifests/g/GlobalMarineNet/XWeb/1.7/GlobalMarineNet.XWeb.locale.en-US.yaml
> +Publisher: GlobalMarineNer
```suggestion
Publisher: GlobalMarineNet
```

2023-05-22 20:03 UTC, stephengillie commented
This package appears to install Firefox.

2023-05-23 04:42 UTC, upintheairsheep commented
> This package appears to install Firefox.

Screenshot please.

2023-05-24 21:33 UTC, stephengillie commented
> > This package appears to install Firefox.
> 
> Screenshot please.

![image](https://github.com/microsoft/winget-pkgs/assets/114952565/7460828a-4687-4ff5-be17-dc3fbcc0e834)

2023-05-27 07:42 UTC, upintheairsheep commented
> > > This package appears to install Firefox.
> > 
> > 
> > Screenshot please.
> 
> ![image](https://user-images.githubusercontent.com/114952565/240746387-7460828a-4687-4ff5-be17-dc3fbcc0e834.png)

OK, yes it's just firefox I guess.

2023-05-27 07:43 UTC, upintheairsheep commented
So, close this? or merge?

2023-06-12 10:28 UTC, ItzLevvie requested changes
> So, close this? or merge?

It's probably best to close it since we have Firefox in the package repository already.

2023-06-12 18:45 UTC, upintheairsheep commented
It’s just Firefox.

2023-06-12 18:45 UTC, closed without merging