MilosParipovic.OneCommander version 3.44.1
microsoft/winget-pkgs pull request #107523
Opened 2023-05-20 06:07 UTC by BrandonWanHuanSheng

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-05-20 06:17 UTC, BrandonWanHuanSheng commented
I called out Windows Features. This one is most likely using the app features.

2023-05-20 12:13 UTC, BrandonWanHuanSheng commented
It look like everything install correctly

2023-05-20 12:42 UTC, BrandonWanHuanSheng commented
@stephengillie  What is this error causing on it.

2023-05-21 15:58 UTC, mdanish-kh requested changes
`user` scope for MSI installers generally does not work well because of a bug/design issue? with WiX installers in that the installer installs per-user but incorrectly writes the uninstall entries to HKEY_LOCAL_MACHINE that makes WinGet think it's a per-machine install. This causes users not being able to upgrade the package after installation through WinGet. For best UX, it's best to remove the user scope from the manifest

2023-05-21 16:02 UTC, mdanish-kh requested changes

2023-05-21 16:02 UTC, mdanish-kh commented on manifests/m/MilosParipovic/OneCommander/3.44.1/MilosParipovic.OneCommander.locale.en-US.yaml
> +- File-Manager
```suggestion
Moniker: onecommander
Tags:
- onecommander
- modern
- file-manager
```
Best practice is to write moniker and tags in lower-case

2023-05-21 16:02 UTC, mdanish-kh commented on manifests/m/MilosParipovic/OneCommander/3.44.1/MilosParipovic.OneCommander.locale.en-US.yaml
> +PublisherSupportUrl: https://twitter.com/OneCommander
```suggestion
PublisherSupportUrl: https://onecommander.com/help
```
A social media account is not considered as the

2023-05-21 16:02 UTC, mdanish-kh commented on manifests/m/MilosParipovic/OneCommander/3.44.1/MilosParipovic.OneCommander.locale.en-US.yaml
> +Copyright: Copyright Milos Paripovic (©). All Rights Reserved
```suggestion
Copyright: Copyright Milos Paripovic © 2013-2023. All Rights Reserved.
```

2023-05-21 16:15 UTC, BrandonWanHuanSheng commented
> `user` scope for MSI installers generally does not work well because of a bug with WiX installers in that the installer installs per-user but incorrectly writes the uninstall entries to HKEY_LOCAL_MACHINE that makes WinGet think it's a per-machine install. This causes users not being able to upgrade the package after installation through WinGet. For best UX, it's best to remove the user scope from the manifest

What is the bug of MSI installer?

2023-05-21 16:22 UTC, mdanish-kh commented
I'm not really sure if it's a bug or a design issue, but related conversation can be found here https://github.com/microsoft/winget-cli/issues/3011

2023-05-21 16:39 UTC, BrandonWanHuanSheng commented
> I'm not really sure if it's a bug or a design issue, but related conversation can be found here [microsoft/winget-cli#3011](https://github.com/microsoft/winget-cli/issues/3011)

Thanks for reporting to the winget-cli.

2023-05-21 17:13 UTC, BrandonWanHuanSheng commented
This error is quite happening. It look like we were unable to merged, it look like it still failed on general stage.

2023-05-21 18:37 UTC, Trenly requested changes

2023-05-21 18:37 UTC, Trenly commented on manifests/m/MilosParipovic/OneCommander/3.44.1/MilosParipovic.OneCommander.installer.yaml
> +  ProductCode: '{524E8270-31DB-4D4A-A420-266E7F79E86E}'
```suggestion
```
> MSI (s) (A0:AC) [09:17:14:208]: Windows Installer installed the product. Product Name: OneCommander. Product Version: 3.44.1. Product Language: 1033. Manufacturer: Milos Paripovic. Installation success or error status: 1633.
> 
> This installation package is not supported by this processor type. Contact your product vendor.

2023-05-22 20:04 UTC, stephengillie approved these changes

2023-05-22 20:04 UTC, merged