HHDSoftware.DupeCare version 1.01.00.0159
microsoft/winget-pkgs pull request #108438
Opened 2023-05-30 14:01 UTC by AlexBAV

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-05-30 14:56 UTC, Trenly requested changes

2023-05-30 14:56 UTC, Trenly commented on manifests/h/HHDSoftware/DupeCare/1.01.00.0159/HHDSoftware.DupeCare.locale.en-US.yaml
> +Publisher: HHD Software Ltd.
```suggestion
Publisher: HHD Software, Ltd.
```
Should match control panel exactly

2023-05-30 14:56 UTC, Trenly commented on manifests/h/HHDSoftware/DupeCare/1.01.00.0159/HHDSoftware.DupeCare.locale.en-US.yaml
> +PackageName: DupeCare
```suggestion
PackageName: HHD Software DupeCare
```
Should match control panel as closely as possible

2023-05-30 14:56 UTC, Trenly commented on manifests/h/HHDSoftware/DupeCare/1.01.00.0159/HHDSoftware.DupeCare.locale.en-US.yaml
> +License: Beta License
```suggestion
License: Proprietary
LicenseUrl: https://www.hhdsoftware.com/company/licenses/regular
```

2023-05-31 00:24 UTC, stephengillie approved these changes

2023-05-31 00:24 UTC, merged