OracleCorporation.Java(TM)PlatformSE19.0.2 version 19.0.2.0
microsoft/winget-pkgs pull request #108620
Opened 2023-06-01 11:09 UTC by palladinoandrea

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-06-01 11:27 UTC, russellbanks requested changes
Oracle JDK is already present under `Oracle.JDK`

2023-06-01 17:39 UTC, stephengillie commented on manifests/o/OracleCorporation/Java(TM)PlatformSE19/0/2/19.0.2.0/OracleCorporation.Java(TM)PlatformSE19.0.2.installer.yaml
> +PackageIdentifier: OracleCorporation.Java(TM)PlatformSE19.0.2
```suggestion
PackageIdentifier: Oracle.JDK.19
```

2023-06-01 17:39 UTC, stephengillie commented on manifests/o/OracleCorporation/Java(TM)PlatformSE19/0/2/19.0.2.0/OracleCorporation.Java(TM)PlatformSE19.0.2.locale.en-US.yaml
> +PackageIdentifier: OracleCorporation.Java(TM)PlatformSE19.0.2
```suggestion
PackageIdentifier: Oracle.JDK.19
```

2023-06-01 17:39 UTC, stephengillie commented on manifests/o/OracleCorporation/Java(TM)PlatformSE19/0/2/19.0.2.0/OracleCorporation.Java(TM)PlatformSE19.0.2.yaml
> +PackageIdentifier: OracleCorporation.Java(TM)PlatformSE19.0.2
```suggestion
PackageIdentifier: Oracle.JDK.19
```

2023-06-01 17:40 UTC, stephengillie commented on manifests/o/OracleCorporation/Java(TM)PlatformSE19/0/2/19.0.2.0/OracleCorporation.Java(TM)PlatformSE19.0.2.locale.en-US.yaml
> +PackageIdentifier: OracleCorporation.Java(TM)PlatformSE19.0.2
Please update file name and path to match this change.

2023-06-01 17:40 UTC, stephengillie commented on manifests/o/OracleCorporation/Java(TM)PlatformSE19/0/2/19.0.2.0/OracleCorporation.Java(TM)PlatformSE19.0.2.installer.yaml
> +PackageIdentifier: OracleCorporation.Java(TM)PlatformSE19.0.2
Please update file name and path to match this change.

2023-06-01 17:41 UTC, stephengillie commented
Readds #105298

2023-06-01 17:41 UTC, stephengillie commented
Automatic Validation ended with:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/dce78d5f-2f6d-4e22-8571-f27f8a98d727)

2023-06-01 17:42 UTC, stephengillie commented on manifests/o/OracleCorporation/Java(TM)PlatformSE19/0/2/19.0.2.0/OracleCorporation.Java(TM)PlatformSE19.0.2.yaml
> +PackageIdentifier: OracleCorporation.Java(TM)PlatformSE19.0.2
Please update file name and path to match this change.

2023-06-01 17:42 UTC, stephengillie commented on manifests/o/OracleCorporation/Java(TM)PlatformSE19/0/2/19.0.2.0/OracleCorporation.Java(TM)PlatformSE19.0.2.locale.en-US.yaml
> +PackageIdentifier: OracleCorporation.Java(TM)PlatformSE19.0.2
Please update file name and path to match this change.

2023-06-01 18:10 UTC, stephengillie commented on manifests/o/OracleCorporation/Java(TM)PlatformSE19/0/2/19.0.2.0/OracleCorporation.Java(TM)PlatformSE19.0.2.installer.yaml
> +  InstallerSha256: 17412499045FA442059AAB83F5480B9808F7C2DD94FAE9175811774D9E859B7C
```suggestion
  InstallerSha256: 17412499045FA442059AAB83F5480B9808F7C2DD94FAE9175811774D9E859B7C
  InstallerSwitches:
    Silent: /s
```

2023-06-24 20:14 UTC, ItzLevvie commented
Close with reason: Stale pull request;

2023-06-24 20:15 UTC, closed without merging