New version: FrostWire.FrostWire version 6.12.0
microsoft/winget-pkgs pull request #109315
Opened 2023-06-09 00:28 UTC by superusercode

### Pull request has been created with [Komac](https://github.com/russellbanks/Komac) v1.6.0 :rocket:
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109315&drop=dogfoodAlpha

2023-06-09 01:10 UTC, ItzLevvie requested changes

2023-06-09 01:10 UTC, ItzLevvie commented on manifests/f/FrostWire/FrostWire/6.12.0/FrostWire.FrostWire.locale.en-US.yaml
> +PackageVersion: 6.12.0
```suggestion
PackageVersion: 6.12.0.318
```
This must match Control Panel.

2023-06-09 01:10 UTC, ItzLevvie commented on manifests/f/FrostWire/FrostWire/6.12.0/FrostWire.FrostWire.yaml
> +PackageVersion: 6.12.0
```suggestion
PackageVersion: 6.12.0.318
```
This must match Control Panel.

2023-06-09 01:10 UTC, ItzLevvie commented on manifests/f/FrostWire/FrostWire/6.12.0/FrostWire.FrostWire.installer.yaml
> +  InstallerSha256: BFF81F44AC4D64E16E1F5FDA4A684FE4B764AB86BBEC153B535F0D4DE30138C4
```suggestion
  InstallerSha256: BFF81F44AC4D64E16E1F5FDA4A684FE4B764AB86BBEC153B535F0D4DE30138C4
  ProductCode: FrostWire 6
```

2023-06-10 17:07 UTC, mdanish-kh approved these changes

2023-06-10 17:07 UTC, merged