Chatterino 2.4.4
microsoft/winget-pkgs pull request #109519
Opened 2023-06-11 05:35 UTC by ktnjared

Chatterino 2.4.4 for request #22593
- Manifest validated locally
- Sandbox validated
- The previous blocker on #22593 was addressed by the Chatterino team: vcdist installation is now handled by the package Installer.

--

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-06-12 09:52 UTC, ItzLevvie requested changes

2023-06-12 09:52 UTC, ItzLevvie commented on manifests/c/Chatterino/Chatterino/2.4.4/Chatterino.Chatterino.installer.yaml
> +Scope: user
```suggestion
```

2023-06-12 09:52 UTC, ItzLevvie commented on manifests/c/Chatterino/Chatterino/2.4.4/Chatterino.Chatterino.installer.yaml
> +  InstallerSha256: 0B3A2BAC515499E4F90C2844E67EB449A1437302E54B4B8B1EDA976806F16423
```suggestion
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://github.com/Chatterino/chatterino2/releases/download/v2.4.4/Chatterino.Installer.exe
  InstallerSha256: 0B3A2BAC515499E4F90C2844E67EB449A1437302E54B4B8B1EDA976806F16423
  Scope: user
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://github.com/Chatterino/chatterino2/releases/download/v2.4.4/Chatterino.Installer.exe
  InstallerSha256: 0B3A2BAC515499E4F90C2844E67EB449A1437302E54B4B8B1EDA976806F16423
  Scope: machine
  InstallerSwitches:
    Custom: /ALLUSERS
```

2023-06-12 17:25 UTC, stephengillie commented
Automatic Validation ended with:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/dfd133e6-531e-4df5-a000-c9f82f2a8151)

2023-06-12 21:49 UTC, Felanbird commented on manifests/c/Chatterino/Chatterino/2.4.4/Chatterino.Chatterino.installer.yaml
> +  InstallerUrl: https://github.com/Chatterino/chatterino2/releases/download/v2.4.4/Chatterino.Installer.exe
I just want to note that the installer from Github releases is just a re-upload of the one listed on the website, hosted on digitalocean.

```suggestion
  InstallerUrl: https://chatterino.fra1.digitaloceanspaces.com/bin/2.4.4/Chatterino%20Installer.exe
```

2023-06-18 19:58 UTC, ItzLevvie commented
[Policy] Interactive-Only-Installer

2023-06-18 19:58 UTC, ItzLevvie commented
[Policy] Blocking-Issue

2023-06-18 19:59 UTC, ItzLevvie commented
![image](https://github.com/microsoft/winget-pkgs/assets/11600822/2a1ca15c-785b-46de-8cfc-e673c4440bbf)

2023-08-26 16:03 UTC, pajlada commented
@ktnjared v2.4.5 has been released now, using an updated installer. The new installer URL is `https://github.com/Chatterino/chatterino2/releases/download/v2.4.5/Chatterino.Installer.exe` and its sha256 is `60fbcd77d637b529e0a056e7c743c819e1bdb5ab376c0da27b6df3f167ca8767`

2023-12-10 03:54 UTC, closed without merging