New version: IDRIX.DirHash 1.24.0
microsoft/winget-pkgs pull request #110118
Opened 2023-06-18 20:28 UTC by w3lld0ne

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-06-18 21:11 UTC, ItzLevvie requested changes
I'm seeing this:
![image](https://github.com/microsoft/winget-pkgs/assets/11600822/22cf2fb4-74d2-4fd6-9f88-07e7118e4764)

2023-06-18 21:26 UTC, w3lld0ne commented
False-positive? I'm not sure what to do with that info :/

2023-06-19 21:47 UTC, stephengillie commented
Manual Validation failed with:
> 2:46:14 PM:  > 2023-06-19 14:46:13.215 [FAIL] Installer failed security check. Url: https://github.com/idrassi/DirHash/releases/download/DirHash_1.24.0/DirHash-1.24.0-x64.zip Result: 0x80004005

2023-06-19 21:49 UTC, stephengillie commented on manifests/i/IDRIX/DirHash/1.24.0/IDRIX.DirHash.locale.en-US.yaml
> +PublisherUrl: https://www.idrix.fr/
```suggestion
PublisherUrl: https://github.com/idrassi/
```

2023-06-19 21:51 UTC, stephengillie commented on manifests/i/IDRIX/DirHash/1.24.0/IDRIX.DirHash.locale.en-US.yaml
> +PackageUrl: https://idrassi.github.io/DirHash/
```suggestion
PackageUrl: https://www.idrix.fr/Root/content/category/7/31/55/
```

2023-06-19 21:53 UTC, stephengillie commented on manifests/i/IDRIX/DirHash/1.24.0/IDRIX.DirHash.locale.en-US.yaml
> +PackageUrl: https://idrassi.github.io/DirHash/
This helps justify IDRIX as the ISV, since the GitHub page appears to be the personal page of Mounir IDRASSI when viewed in isolation.

2023-06-24 07:52 UTC, idrassi commented
@stephengillie 
I'm the author of DirHash and I would like to query about the cause of the failed security check because the error 0x80004005 indicated in your comment translates to "Unspecified error" which is not very specific.

I have run a check on VirtusTotal for the exe file inside DirHash-1.24.0-x64.zip and no issues were found: https://www.virustotal.com/gui/file/d02ecc173f4427c407fa140750021bbfb34124b5af7f3f418b8b8beae543acf8?nocache=1

Also, the exe file inside the zip is digitally signed using a valid EV code signing certificate from GlobalSign.

Could it be that the check is failing because it is a zip file and not an exe file?

Thank you for your help.

2023-06-24 11:01 UTC, ItzLevvie commented
@wingetbot run

2023-06-25 18:26 UTC, w3lld0ne commented
@ItzLevvie any updates on this?

2023-06-27 02:49 UTC, stephengillie commented
> @stephengillie I'm the author of DirHash and I would like to query about the cause of the failed security check because the error 0x80004005 indicated in your comment translates to "Unspecified error" which is not very specific.
> 
> I have run a check on VirtusTotal for the exe file inside DirHash-1.24.0-x64.zip and no issues were found: https://www.virustotal.com/gui/file/d02ecc173f4427c407fa140750021bbfb34124b5af7f3f418b8b8beae543acf8?nocache=1
> 
> Also, the exe file inside the zip is digitally signed using a valid EV code signing certificate from GlobalSign.
> 
> Could it be that the check is failing because it is a zip file and not an exe file?
> 
> Thank you for your help.

This must have been a false positive. It passed the Defender scan. Thanks for your patience and understanding.

2023-06-27 05:34 UTC, stephengillie approved these changes

2023-06-27 05:35 UTC, merged