ElectronicArts.EAapp version 12.218.0.5475
microsoft/winget-pkgs pull request #110615
Opened 2023-06-24 19:31 UTC by Tiompkin

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-06-24 19:49 UTC, ItzLevvie commented
[Policy] Needs-CLA

2023-06-24 20:04 UTC, ItzLevvie commented
[Policy] Needs-Author-Feedback

2023-06-27 02:40 UTC, stephengillie commented on manifests/e/ElectronicArts/EAapp/12.218.0.5475/ElectronicArts.EAapp.locale.it-IT.yaml
> +PackageName: EA app
```suggestion
PrivacyUrl:   http://www.ea.com/legal
PackageName: EA app
PackageUrl: https://www.ea.com/ea-app
```

2023-06-27 02:41 UTC, stephengillie commented
@wingetbot waivers Add Validation-Domain

2023-06-27 15:45 UTC, Trenly requested changes

2023-06-27 15:45 UTC, Trenly commented on manifests/e/ElectronicArts/EAapp/12.218.0.5475/ElectronicArts.EAapp.installer.yaml
> +PackageIdentifier: ElectronicArts.EAapp
```suggestion
PackageIdentifier: ElectronicArts.EADesktop
```
This package already exists under the EADesktop name, this new version should be added there

2023-06-27 15:45 UTC, Trenly commented on manifests/e/ElectronicArts/EAapp/12.218.0.5475/ElectronicArts.EAapp.locale.it-IT.yaml
> +PackageIdentifier: ElectronicArts.EAapp
```suggestion
PackageIdentifier: ElectronicArts.EADesktop
```

2023-06-27 15:45 UTC, Trenly commented on manifests/e/ElectronicArts/EAapp/12.218.0.5475/ElectronicArts.EAapp.yaml
> +PackageIdentifier: ElectronicArts.EAapp
```suggestion
PackageIdentifier: ElectronicArts.EADesktop
```

2023-07-11 23:23 UTC, closed without merging