Wikivoyage by Kiwix 2.5.2 UWP
microsoft/winget-pkgs pull request #110980
Opened 2023-06-30 14:18 UTC by Jaifroid

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110980&drop=dogfoodAlpha

2023-06-30 16:57 UTC, BrandonWanHuanSheng commented on manifests/k/Kiwix/Wikivoyage/2.5.2.0/Kiwix.Wikivoyage.installer.yaml
> +  InstallerUrl: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.5.2-Wikivoyage/Wikivoyage.by.Kiwix.2.5.2-E.appx
```suggestion
https://github.com/kiwix/kiwix-js-windows/releases/download/v2.5.2-Wikivoyage/KiwixWebAppWikivoyage_2.5.2.0_AnyCPU.appxbundle
```

2023-06-30 16:58 UTC, BrandonWanHuanSheng commented on manifests/k/Kiwix/Wikivoyage/2.5.2.0/Kiwix.Wikivoyage.installer.yaml
> +  InstallerSha256: BC089FFBD809094C465287756FA95CCBEC65EAF50D8E19640D9ED842480BC523
```suggestion
  InstallerSha256: 29AD1484259A2DD22A11AA9966299846BEE8587CF007484F92C12F0D40F74132
```

2023-06-30 17:03 UTC, BrandonWanHuanSheng requested changes
It look like that file is not found on the server. https://github.com/kiwix/kiwix-js-windows/releases/download/v2.5.2-Wikivoyage/Wikivoyage.by.Kiwix.2.5.2-E.appx got 404.

2023-06-30 17:06 UTC, BrandonWanHuanSheng commented
[Policy]: Reset-Feedback

2023-06-30 17:09 UTC, BrandonWanHuanSheng commented
[Policy] feedback reset

2023-06-30 17:14 UTC, BrandonWanHuanSheng reviewed
Sorry because github is hiding the setup package

2023-06-30 17:17 UTC, BrandonWanHuanSheng approved these changes
The setup file it might be hide setup file on the package. when downloading from github.

2023-06-30 17:50 UTC, BrandonWanHuanSheng commented
I get confused when github.com hide its setup installer.

2023-06-30 19:08 UTC, Jaifroid commented
@BrandonWanHuanSheng Thank you. Is there anything I need to change? Yes, some assets are hidden until you press "Show all 15 assets". It seems the PR is just waiting for mod approval now?

2023-07-01 00:52 UTC, BrandonWanHuanSheng commented
> @BrandonWanHuanSheng Thank you. Is there anything I need to change? Yes, some assets are hidden until you press "Show all 15 assets". It seems the PR is just waiting for mod approval now?

No, need.

2023-07-02 13:43 UTC, ItzLevvie approved these changes

2023-07-02 13:44 UTC, merged