Codespace numerunix super engine wgq7rrxpwgv3qqp
microsoft/winget-pkgs pull request #111023
Opened 2023-07-01 04:12 UTC by numerunix

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-07-02 14:59 UTC, ItzLevvie requested changes
Running the command also requires you to manually install the application:
![image](https://github.com/microsoft/winget-pkgs/assets/11600822/039f63c9-25ee-4538-9160-30aeabadb5ca)

2023-07-02 14:59 UTC, ItzLevvie commented on manifests/g/GiulioSorrentino/astroni/1.0/GiulioSorrentino.astroni.installer.yaml
> +  - winrar
Perhaps another word/term should be used here?

2023-07-02 17:06 UTC, numerunix commented
Installer type is not portable, is an exe created with winrar.
-s is silent install
-s1 is silent install with progress.

2023-07-03 23:10 UTC, stephengillie commented
@wingetbot waivers Add Validation-No-Executables

2023-07-04 01:09 UTC, stephengillie approved these changes

2023-07-04 01:11 UTC, merged