New version: RustDesk.RustDesk version 1.2.0
microsoft/winget-pkgs pull request #111231
Opened 2023-07-04 01:38 UTC by sitiom

### Pull request has been created with [Komac](https://github.com/russellbanks/Komac) v1.8.0 :rocket:

2023-07-04 01:47 UTC, CoolPlayLin requested changes

2023-07-04 01:47 UTC, CoolPlayLin commented on manifests/r/RustDesk/RustDesk/1.2.0/RustDesk.RustDesk.locale.en-US.yaml
> +PrivacyUrl: https://rustdesk.com/privacy
```suggestion
PrivacyUrl: https://rustdesk.com/privacy.html
```

2023-07-04 01:48 UTC, CoolPlayLin commented
![image](https://github.com/microsoft/winget-pkgs/assets/96709586/fcffbb11-3887-488f-bd8d-81da32270c7e)

2023-07-06 03:32 UTC, sitiom commented
@stephengillie Any idea what went wrong here?

2023-07-06 17:01 UTC, stephengillie commented
Manual Validation failed with:
> ##[error] Installer https://github.com/rustdesk/rustdesk/releases/download/1.2.0/rustdesk-1.2.0-x86_64.exe
Scan request id: '2091bb05-88d9-4512-97f8-20745062349e'
Error information: BlockingDetectionFound
##[error] Result: Failed

2023-07-06 21:37 UTC, stephengillie approved these changes

2023-07-06 21:37 UTC, merged