New version: Timthreetwelve.WUView version 0.5.14
microsoft/winget-pkgs pull request #111589
Opened 2023-07-07 15:59 UTC by ottnorml

### Pull request has been created with [Komac](https://github.com/russellbanks/Komac) v1.8.2 :rocket:

2023-07-07 18:10 UTC, mdanish-kh requested changes
PackageVersion should match Control Panel (`appwiz.cpl`) / Apps&Features

After committing the suggested changes, you would also have to rename the version folder to match the new PackageVersion. The folder under `manifests/t/Timthreetwelve/WUView` should be renamed from `0.5.14` -> `0.5.14.0`

A quick and easy way to do this would be here in GitHub Web by pressing the <kbd>.</kbd> (dot) key on your keyboard that'll open up the PR in VS Code Online. Navigate to Explorer menu, find the required folder and make the appropriate rename changes.

After that, stage and commit your changes from Source Control menu on the left. (The changes are automatically pushed)

2023-07-07 18:10 UTC, mdanish-kh commented on manifests/t/Timthreetwelve/WUView/0.5.14/Timthreetwelve.WUView.installer.yaml
> +PackageVersion: 0.5.14
```suggestion
PackageVersion: 0.5.14.0
```

2023-07-07 18:10 UTC, mdanish-kh commented on manifests/t/Timthreetwelve/WUView/0.5.14/Timthreetwelve.WUView.locale.en-US.yaml
> +PackageVersion: 0.5.14
```suggestion
PackageVersion: 0.5.14.0
```

2023-07-07 18:10 UTC, mdanish-kh commented on manifests/t/Timthreetwelve/WUView/0.5.14/Timthreetwelve.WUView.yaml
> +PackageVersion: 0.5.14
```suggestion
PackageVersion: 0.5.14.0
```

2023-07-08 14:15 UTC, ottnorml commented
> PackageVersion should match Control Panel (`appwiz.cpl`) / Apps&Features
> 
> After committing the suggested changes, you would also have to rename the version folder to match the new PackageVersion. The folder under `manifests/t/Timthreetwelve/WUView` should be renamed from `0.5.14` -> `0.5.14.0`
> 
> A quick and easy way to do this would be here in GitHub Web by pressing the <kbd>.</kbd> (dot) key on your keyboard that'll open up the PR in VS Code Online. Navigate to Explorer menu, find the required folder and make the appropriate rename changes.
> 
> After that, stage and commit your changes from Source Control menu on the left. (The changes are automatically pushed)

Thanks for the suggested changes and the instructions on how to implement them. I will have a look tomorrow.

2023-07-09 16:51 UTC, mdanish-kh approved these changes

2023-07-09 16:52 UTC, merged