New package: WinsiderSS.SystemInformer version 3.0.11299.6772
microsoft/winget-pkgs pull request #111530
Opened 2023-07-07 01:02 UTC by CoolPlayLin

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-07-07 09:28 UTC, CoolPlayLin commented
I have no idea to resolve this

2023-07-07 15:06 UTC, stephengillie commented
> I have no idea to resolve this

Unfortunately, this might not be possible to fix. It would have to be reported as not malware.

2023-07-08 21:54 UTC, Trenly requested changes

2023-07-08 21:54 UTC, Trenly commented on manifests/w/WinsiderSS/SystemInformer/3.0.11299.6772/WinsiderSS.SystemInformer.installer.yaml
> +  InstallerType: exe
Install is not silent. Please add the silent install switches

2023-07-08 21:54 UTC, Trenly commented on manifests/w/WinsiderSS/SystemInformer/3.0.11299.6772/WinsiderSS.SystemInformer.installer.yaml
> +PackageVersion: 3.0.11299.6772
Package writes `3.0` to the registry, and the GitHub tag is `3.0.6772`. This should either be -
1) Updated to 3.0 -or-
2) Changed to 3.0.6772 and the `AppsAndFeaturesEntries` added with `DisplayVersion`

2023-07-08 21:54 UTC, Trenly commented on manifests/w/WinsiderSS/SystemInformer/3.0.11299.6772/WinsiderSS.SystemInformer.locale.en-US.yaml
> +Publisher: Seminars & Solutions, Inc
```suggestion
Publisher: System Informer
```

2023-07-15 14:10 UTC, CoolPlayLin commented
Please retry one time.
If it still appears this, this PR should be blocked temporarily

2023-07-17 22:29 UTC, CoolPlayLin commented
Don't assign it to me, I have no idea to fix

2023-09-08 20:48 UTC, stephengillie commented
/AzurePipelines run

2023-09-08 23:51 UTC, stephengillie commented
Automatic Validation ended with:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/87808f02-b428-4040-8c12-bd4578f5287f)

2023-09-08 23:52 UTC, stephengillie commented
Hi @CoolPlayLin,

Is there an installer switch to bypass the message box above, and complete the install automatically?

2023-09-09 00:20 UTC, CoolPlayLin commented
@stephengillie
Sorry, I haven't used this software yet. I don't how to bypass it.

CC @0xThiebaut

2023-09-16 06:59 UTC, CoolPlayLin commented
？

2023-09-16 07:01 UTC, 0xThiebaut commented
Currently OoO, will investigate/request the switch on Sept 26.

2023-09-16 07:04 UTC, CoolPlayLin commented
@stephengillie Add `Blocking-issue` temporarily

2023-09-25 08:57 UTC, 0xThiebaut commented
Blocked by https://github.com/winsiderss/systeminformer/issues/759 .

2024-02-18 01:35 UTC, CoolPlayLin commented
@stephengillie Could this be not marked as [No-Recent-Activity](https://github.com/microsoft/winget-pkgs/labels/No-Recent-Activity) ?

2024-02-18 02:05 UTC, CoolPlayLin commented
Why it added again?

2024-02-23 04:33 UTC, CoolPlayLin commented
Why it added again?

2024-03-01 08:17 UTC, CoolPlayLin commented
No adding :)

2024-03-09 02:49 UTC, CoolPlayLin commented
Stop

2024-03-16 02:23 UTC, CoolPlayLin commented
.

2024-03-23 11:22 UTC, CoolPlayLin commented
Stop

2024-03-31 22:47 UTC, closed without merging