New package: XDesktopSoft.XWidget version 1.0
microsoft/winget-pkgs pull request #111882
Opened 2023-07-12 02:42 UTC by upintheairsheep

### Pull request has been created with [Komac](https://github.com/russellbanks/Komac) v1.8.2 :rocket:

2023-07-12 09:41 UTC, CoolPlayLin requested changes

2023-07-12 09:41 UTC, CoolPlayLin commented on manifests/x/XDesktopSoft/XWidget/1.0/XDesktopSoft.XWidget.installer.yaml
> +- Architecture: x64
```suggestion
- Architecture: x64
  InstallerType: nullsoft
```

2023-07-13 20:17 UTC, stephengillie commented
/AzurePipelines run

2023-07-13 20:24 UTC, stephengillie commented on manifests/x/XDesktopSoft/XWidget/1.0/XDesktopSoft.XWidget.locale.en-US.yaml
> +PackageUrl: http://localhost
```suggestion
PackageUrl: https://www.xwidget.com/xwidget.html
```

2023-08-01 06:54 UTC, closed without merging