New package: Bluestacks.AppDataMigrationUtility version 1.0
microsoft/winget-pkgs pull request #111881
Opened 2023-07-12 02:37 UTC by upintheairsheep

### Pull request has been created with [Komac](https://github.com/russellbanks/Komac) v1.8.2 :rocket:

2023-07-12 12:56 UTC, Trenly requested changes
>  Manifest Error: Invalid field value. [InstallerType]

2023-07-19 16:45 UTC, upintheairsheep commented
Keep open; on vacation.

2023-07-23 02:15 UTC, Trenly commented
[Policy] Needs Author Feedback

2023-07-25 22:55 UTC, stephengillie commented
/AzurePipelines run

2023-07-25 22:55 UTC, stephengillie commented
https://github.com/microsoft/winget-pkgs/issues/111634

2023-07-25 23:05 UTC, stephengillie commented on manifests/b/Bluestacks/AppDataMigrationUtility/1.0/Bluestacks.AppDataMigrationUtility.locale.en-US.yaml
> +PackageUrl: http://localhost
Please either update or remove the PackageUrl.

2023-07-26 08:23 UTC, CoolPlayLin requested changes

2023-07-26 08:23 UTC, CoolPlayLin commented on manifests/b/Bluestacks/AppDataMigrationUtility/1.0/Bluestacks.AppDataMigrationUtility.locale.en-US.yaml
> +PackageUrl: http://localhost
```suggestion
PackageUrl: https://www.bluestacks.com/
```

2023-07-26 08:23 UTC, CoolPlayLin commented on manifests/b/Bluestacks/AppDataMigrationUtility/1.0/Bluestacks.AppDataMigrationUtility.locale.en-US.yaml
> +PackageUrl: http://localhost
Why the value of `PackageUrl` is localhost? I don't really understand it.

2023-08-11 18:50 UTC, upintheairsheep commented
Appears forbidden for WinGet.

2023-08-11 18:50 UTC, closed without merging