New package: Samsung.ATIV-SW.Book9 version 2.1.14.1
microsoft/winget-pkgs pull request #111898
Opened 2023-07-12 04:30 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-07-13 17:13 UTC, Trenly requested changes
![image](https://github.com/microsoft/winget-pkgs/assets/12611259/5e06286e-f222-4d6b-83ba-3c8b042da626)

2023-07-13 17:13 UTC, Trenly commented on manifests/s/Samsung/ATIV-SW/Book9/2.1.14.1/Samsung.ATIV-SW.Book9.installer.yaml
> +PackageVersion: 2.1.14.1
```suggestion
PackageVersion: 2.1.14
```

2023-07-13 17:13 UTC, Trenly commented on manifests/s/Samsung/ATIV-SW/Book9/2.1.14.1/Samsung.ATIV-SW.Book9.locale.en-US.yaml
> +PackageVersion: 2.1.14.1
```suggestion
PackageVersion: 2.1.14
```

2023-07-13 17:13 UTC, Trenly commented on manifests/s/Samsung/ATIV-SW/Book9/2.1.14.1/Samsung.ATIV-SW.Book9.yaml
> +PackageVersion: 2.1.14.1
```suggestion
PackageVersion: 2.1.14
```

2023-07-13 17:13 UTC, Trenly commented on manifests/s/Samsung/ATIV-SW/Book9/2.1.14.1/Samsung.ATIV-SW.Book9.locale.en-US.yaml
> +Publisher: Samsung
```suggestion
Publisher: Samsung Electronics CO., LTD.
```

2023-07-13 17:13 UTC, Trenly commented on manifests/s/Samsung/ATIV-SW/Book9/2.1.14.1/Samsung.ATIV-SW.Book9.locale.en-US.yaml
> +PackageName: Samsung Software
```suggestion
PackageName: SW Update
```

2023-07-13 17:13 UTC, Trenly commented on manifests/s/Samsung/ATIV-SW/Book9/2.1.14.1/Samsung.ATIV-SW.Book9.locale.en-US.yaml
> +ShortDescription: Software drivers for varius Samsung computers
```suggestion
ShortDescription: Software drivers for various Samsung computers
```

2023-07-14 16:29 UTC, Trenly commented
[Policy] Needs-Author-Feedback

2023-07-23 17:06 UTC, ItzLevvie commented
Close with reason: Stale pull request;

2023-07-23 17:06 UTC, closed without merging