New package: Samsung.PlayTouchLauncher version 1.2.0.32
microsoft/winget-pkgs pull request #112017
Opened 2023-07-13 04:12 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-07-13 13:49 UTC, Trenly requested changes

2023-07-13 13:49 UTC, Trenly commented on manifests/s/Samsung/PlayTouchLauncher/1.2.0.32/Samsung.PlayTouchLauncher.installer.yaml
> +- InstallerUrl: https://org.downloadcenter.samsung.com/downloadfile/ContentsFile.aspx?CDSite=US&CttFileID=4902668&CDCttType=SW&ModelType=C&ModelName=XE700T1A-A02US&VPath=SW/201204/20120404155905545/P
```suggestion
- InstallerUrl: https://downloadcenter.samsung.com/content/SW/201204/20120404155905545/Play_Touch_Launcher_1.2.0.32.ZIP
```

2023-07-13 13:49 UTC, Trenly commented on manifests/s/Samsung/PlayTouchLauncher/1.2.0.32/Samsung.PlayTouchLauncher.installer.yaml
> +PackageVersion: 1.2.0.32
```suggestion
PackageVersion: 1.2.0
```
This should match control panel. The version folder will need to be renamed after committing this change.

2023-07-13 13:49 UTC, Trenly commented on manifests/s/Samsung/PlayTouchLauncher/1.2.0.32/Samsung.PlayTouchLauncher.yaml
> +PackageVersion: 1.2.0.32
```suggestion
PackageVersion: 1.2.0
```
This should match control panel. The version folder will need to be renamed after committing this change.

2023-07-13 13:49 UTC, Trenly commented on manifests/s/Samsung/PlayTouchLauncher/1.2.0.32/Samsung.PlayTouchLauncher.installer.yaml
> +    SilentWithProgress: /passive
```suggestion
  NestedInstallerType: burn
  NestedInstallerFiles:
  - RelativeFilePath: setup.exe
  InstallerSha256: B87EC63825B263A29B1AA10166A65160C8A7F55FEB42E2A10A380282ECB66425
```
Installer type is burn. Using exe will cause it to throw "different install technology" error during upgrade

2023-07-13 22:57 UTC, stephengillie commented
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/f2d2847b-9cd9-4064-9ecc-cc8a17a8fe44)

2023-07-22 02:29 UTC, denelon commented
@upintheairsheep I just got back from taking some time away and was looking into the relative health of the validation pipelines and noticed a fairly large number of PRs you've been submitting recently (last few weeks). Several of them have minor inconsistencies between the package and the metadata, or they don't meet all of our policy requirements for silent installs and other small things.

I'd love to see how we could help with guidance on testing or better tooling so more of them pass on the first attempt.

2024-09-07 11:06 UTC, ItzLevvie commented
@wingetbot run

2024-09-07 11:52 UTC, ItzLevvie commented
[Policy] Blocking-Issue

2024-12-18 01:01 UTC, denelon commented
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504

2024-12-18 01:01 UTC, closed without merging