Update version: AderitoNeto.AfterLife version 1.0.0
microsoft/winget-pkgs pull request #112590
Opened 2023-07-19 15:47 UTC by vedantmgoyal2009

### Pull request has been created with [WinGet Automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) :rocket:

2023-07-19 20:03 UTC, Trenly requested changes

2023-07-19 20:03 UTC, Trenly commented on manifests/a/AderitoNeto/AfterLife/1.0.0/AderitoNeto.AfterLife.installer.yaml
> +  InstallerUrl: https://github.com/ad3rito/AfterLife/releases/download/1.0.0/AfterLife.Portable.exe
Wrong URL

2023-07-19 22:26 UTC, stephengillie commented
Automatic Validation ended with:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/c172dc54-efa9-4306-81e8-2ef9ba294c31)

2023-08-01 22:59 UTC, ItzLevvie approved these changes

2023-08-02 18:32 UTC, merged