Autogenerated/apple.boot camp drivers/b5211d2d b630 4028 b631 1719cad5afa9
microsoft/winget-pkgs pull request #113306
Opened 2023-07-27 09:04 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-08-01 22:55 UTC, upintheairsheep commented
Would like a validation screenshot.

2023-08-02 21:28 UTC, ItzLevvie requested changes

2023-08-02 21:28 UTC, ItzLevvie commented on manifests/a/Apple/BootCampDrivers/5.1.5769/Apple.BootCampDrivers.installer.yaml
> +  InstallerSha256: FD657F2DABAD7BB08BFC6F98FAD19487CAABA15FB1BF3C1C9C59C36FF25690A2
```suggestion
  InstallerSha256: 4ede2c8ef240708c850237a3e5911094ed6adae1734258e4639bc9069a814b1e
```

2023-08-02 21:31 UTC, ItzLevvie commented
[Policy] Hardware

2024-07-04 23:41 UTC, ItzLevvie commented
[Policy] Blocking-Issue

2024-07-04 23:41 UTC, ItzLevvie commented
[Policy] Hardware

2024-12-18 01:00 UTC, denelon commented
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504

2024-12-18 01:00 UTC, closed without merging