Add version: ShiningLight.OpenSSL.Light version 1.1.1v
microsoft/winget-pkgs pull request #114624
Opened 2023-08-02 17:30 UTC by szhu25

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114624&drop=dogfoodAlpha

2023-08-02 19:01 UTC, szhu25 commented
@wingetbot run

2023-08-02 23:31 UTC, ItzLevvie requested changes

2023-08-02 23:31 UTC, ItzLevvie commented on manifests/s/ShiningLight/OpenSSL/Light/1.1.1v/ShiningLight.OpenSSL.Light.installer.yaml
> +  - DisplayName: OpenSSL 3.0.8 Light (64-bit)
```suggestion
  - DisplayName: OpenSSL 1.1.1v Light (64-bit)
```

2023-08-02 23:31 UTC, ItzLevvie commented on manifests/s/ShiningLight/OpenSSL/Light/1.1.1v/ShiningLight.OpenSSL.Light.installer.yaml
> +  - DisplayName: OpenSSL 3.0.8 Light (32-bit)
```suggestion
  - DisplayName: OpenSSL 1.1.1v Light (32-bit)
```

2023-08-02 23:36 UTC, ItzLevvie approved these changes

2023-08-03 15:52 UTC, szhu25 commented
Hi @trenly, could you help me run the Azure pipeline checks for these OpenSSL updates? There are 6 PR for the 3 updated OpenSSL version (full and light).

Thank you!

2023-08-04 08:21 UTC, merged