Add version: ShiningLight.OpenSSL version 1.1.1v
microsoft/winget-pkgs pull request #114622
Opened 2023-08-02 17:30 UTC by szhu25

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114622&drop=dogfoodAlpha

2023-08-02 23:28 UTC, ItzLevvie requested changes

2023-08-02 23:28 UTC, ItzLevvie commented on manifests/s/ShiningLight/OpenSSL/1.1.1v/ShiningLight.OpenSSL.installer.yaml
> +  - DisplayName: OpenSSL 3.0.8 (32-bit)
```suggestion
  - DisplayName: OpenSSL 1.1.1v (32-bit)
```

2023-08-02 23:28 UTC, ItzLevvie commented on manifests/s/ShiningLight/OpenSSL/1.1.1v/ShiningLight.OpenSSL.installer.yaml
> +  - DisplayName: OpenSSL 3.0.8 (64-bit)
```suggestion
  - DisplayName: OpenSSL 1.1.1v (64-bit)
```

2023-08-02 23:36 UTC, ItzLevvie approved these changes

2023-08-03 22:17 UTC, stephengillie commented
/AzurePipelines run

2023-08-04 20:04 UTC, Trenly commented
@wingetbot run

2023-08-04 23:49 UTC, stephengillie commented
Hi @szhu25,

This package appears to require a dependency:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/fd003d2a-1302-47f9-a6aa-5f38f6721284)

The `x86` version requires the `x86` dependency.

2023-08-04 23:53 UTC, szhu25 commented
> Hi @szhu25,
> 
> This package appears to require a dependency:
> ![image](https://github.com/microsoft/winget-pkgs/assets/114952565/fd003d2a-1302-47f9-a6aa-5f38f6721284)
> 
> The `x86` version requires the `x86` dependency. 

Hmm that makes sense... 
I'll retest all 6 variants of the OpenSSL installer in the sandbox when I got home tonight. 
Although I thought OpenSSL have this dependency requirement for a while now, maybe they recently modified the C++ library? 

Would this still be able to submit if this dependency requirement exists?

2023-08-05 20:28 UTC, szhu25 commented
Happy Weekends @stephengillie,

I tested this manifest using Windows sandbox (via the sandbox script in this repo) and this software installed without any issues... Is it possible to restart the pipeline and check?

The developer of this software build 6 versions of OpenSSL (OpenSSL 1.1.1v, 3.0.10, 3.1.2 and its corresponding light version), so far I have not seen the no dependency error on any of my Windows Sandbox test... I do admit that I have 2015 - 2022 installed on my host machine, but I don't know if it would affect Sandbox env?

2023-08-08 00:17 UTC, stephengillie commented
/azp run

2023-08-09 23:10 UTC, stephengillie commented
The error is still present when installed in a Windows 10 VM: 
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/77fdd602-7af3-4088-b572-682f8ffc3f58)

It's from the Inno installers.

2023-09-05 01:33 UTC, closed without merging