Add version: ShiningLight.OpenSSL version 3.0.10
microsoft/winget-pkgs pull request #114618
Opened 2023-08-02 17:28 UTC by szhu25

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-08-02 23:29 UTC, ItzLevvie requested changes

2023-08-02 23:29 UTC, ItzLevvie commented on manifests/s/ShiningLight/OpenSSL/3.0.10/ShiningLight.OpenSSL.installer.yaml
> +  - DisplayName: OpenSSL 3.0.8 (64-bit)
```suggestion
  - DisplayName: OpenSSL 3.0.10 (64-bit)
```

2023-08-02 23:29 UTC, ItzLevvie commented on manifests/s/ShiningLight/OpenSSL/3.0.10/ShiningLight.OpenSSL.installer.yaml
> +  - DisplayName: OpenSSL 3.0.8 (32-bit)
```suggestion
  - DisplayName: OpenSSL 3.0.10 (32-bit)
```

2023-08-02 23:36 UTC, ItzLevvie approved these changes

2023-08-02 23:37 UTC, ItzLevvie approved these changes

2023-08-02 23:37 UTC, ItzLevvie approved these changes

2023-08-04 20:03 UTC, Trenly commented
@wingetbot run

2023-08-05 00:27 UTC, hackean-msft commented
/azp run

2023-08-08 00:17 UTC, stephengillie commented
/azp run

2023-08-09 22:58 UTC, stephengillie commented
Hi @szhu25,

2 of the installers (Inno I believe) require a dependency: 
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/26c94870-c0c7-47f3-b54e-55506109d397)

(The `x86` installer requires the `32-bit` dependency.)

2023-08-10 23:42 UTC, stephengillie commented
/azp run

2023-08-11 00:35 UTC, merged