New version: Opera.Opera version 101.0.4843.43
microsoft/winget-pkgs pull request #116146
Opened 2023-08-10 03:46 UTC by Pckgrapp

### Pull request has been created with [Komac](https://github.com/russellbanks/Komac) v1.9.1 :rocket:

2023-08-10 09:21 UTC, CoolPlayLin requested changes

2023-08-10 09:21 UTC, CoolPlayLin commented on manifests/o/Opera/Opera/101.0.4843.43/Opera.Opera.installer.yaml
> +  InstallerSha256: 917318860BC8A7ADE202F6C2F20226C0A8DA8FF8B477CC1CBE8D7703AB174008
```suggestion
  InstallerSha256: 552C0C07655B6ADD62A1203689EC282824B7577F8DD541833620E1EDFDC746A4
```

2023-08-10 09:21 UTC, CoolPlayLin commented on manifests/o/Opera/Opera/101.0.4843.43/Opera.Opera.installer.yaml
> +  InstallerSha256: 917318860BC8A7ADE202F6C2F20226C0A8DA8FF8B477CC1CBE8D7703AB174008
```suggestion
  InstallerSha256: 552C0C07655B6ADD62A1203689EC282824B7577F8DD541833620E1EDFDC746A4
```

2023-08-10 09:21 UTC, CoolPlayLin commented on manifests/o/Opera/Opera/101.0.4843.43/Opera.Opera.installer.yaml
> +  InstallerSha256: 552C0C07655B6ADD62A1203689EC282824B7577F8DD541833620E1EDFDC746A4
```suggestion
  InstallerSha256: 917318860BC8A7ADE202F6C2F20226C0A8DA8FF8B477CC1CBE8D7703AB174008
```

2023-08-10 09:21 UTC, CoolPlayLin commented on manifests/o/Opera/Opera/101.0.4843.43/Opera.Opera.installer.yaml
> +  InstallerSha256: 552C0C07655B6ADD62A1203689EC282824B7577F8DD541833620E1EDFDC746A4
```suggestion
  InstallerSha256: 917318860BC8A7ADE202F6C2F20226C0A8DA8FF8B477CC1CBE8D7703AB174008
```

2023-08-11 00:11 UTC, stephengillie approved these changes

2023-08-11 00:11 UTC, merged