New package: Google.Picasa.2 version 2
microsoft/winget-pkgs pull request #116537
Opened 2023-08-12 20:21 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-08-14 13:44 UTC, Trenly requested changes

2023-08-14 13:44 UTC, Trenly commented on manifests/g/Google/Picasa/2/2/Google.Picasa.2.installer.yaml
> +  NestedInstallerType: exe
```suggestion
  NestedInstallerType: nullsoft
```

2023-08-14 13:44 UTC, Trenly commented on manifests/g/Google/Picasa/2/2/Google.Picasa.2.locale.en-US.yaml
> +PackageVersion: 2
```suggestion
PackageVersion: 2.0
```

2023-08-14 13:44 UTC, Trenly commented on manifests/g/Google/Picasa/2/2/Google.Picasa.2.yaml
> +PackageVersion: 2
```suggestion
PackageVersion: 2.0
```

2023-08-14 13:44 UTC, Trenly commented on manifests/g/Google/Picasa/2/2/Google.Picasa.2.locale.en-US.yaml
> +Publisher: Google
```suggestion
Publisher: Google, Inc.
```

2023-08-14 13:44 UTC, Trenly commented on manifests/g/Google/Picasa/2/2/Google.Picasa.2.installer.yaml
> +PackageVersion: 2
```suggestion
PackageVersion: 2.0
```

2023-08-16 22:31 UTC, stephengillie commented
> Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 'manifests\g\Google\Picasa\2\2', expected 'manifests\g\Google\Picasa\2\2.0'

2023-08-17 00:54 UTC, stephengillie commented
Automatic Validation ended with:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/bb951f7a-6d8a-4da7-b01a-fc608156600e)

2023-08-21 18:03 UTC, stephengillie commented
Automatic Validation ended with:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/7a7f9205-6ae7-4a40-bd10-afc1bbc23b63)

2023-08-26 20:46 UTC, closed without merging