Update version: RIA.DigiDoc4 version 4.4.0.4447
microsoft/winget-pkgs pull request #117217
Opened 2023-08-18 07:20 UTC by vedantmgoyal2009

### Pull request has been created with [WinGet Automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) :rocket:

2023-08-19 01:01 UTC, CoolPlayLin requested changes

2023-08-19 01:01 UTC, CoolPlayLin commented on manifests/r/RIA/DigiDoc4/4.4.0.4447/RIA.DigiDoc4.installer.yaml
> +  InstallerSha256: 61525820CC07BA50DFE91EDB2701EF9F832A20E12D8518C46A0278F7F7BD21ED
```suggestion
```

2023-08-19 01:01 UTC, CoolPlayLin commented on manifests/r/RIA/DigiDoc4/4.4.0.4447/RIA.DigiDoc4.installer.yaml
> +  InstallerUrl: https://github.com/open-eid/DigiDoc4-Client/releases/download/v4.4.0/Digidoc4_Client-4.4.0.4447.x64.en-US.qt.msi
```suggestion
```

2023-08-19 01:01 UTC, CoolPlayLin commented on manifests/r/RIA/DigiDoc4/4.4.0.4447/RIA.DigiDoc4.installer.yaml
> +- Architecture: x64
```suggestion
```

2023-08-21 18:20 UTC, stephengillie commented
>  Manifest Error: Duplicate installer entry found.

2023-09-05 04:14 UTC, closed without merging