New package: AfreetSoftware.HamVNA version 1.1
microsoft/winget-pkgs pull request #117683
Opened 2023-08-22 13:01 UTC by CoolPlayLin

### Pull request has been created with [Komac](https://github.com/russellbanks/Komac) v1.10.1 :rocket:
- Resolve #113360
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/117683)

2023-08-23 17:50 UTC, Trenly requested changes
Nested installer is an inno installer

2023-08-23 17:50 UTC, Trenly commented on manifests/a/AfreetSoftware/HamVNA/1.1/AfreetSoftware.HamVNA.installer.yaml
> +  InstallerSha256: A7F66234A63BC51EA3C930A45B454BF1F763DC29EF6DC16788487699C45AAEBA
```suggestion
InstallerType: zip
NestedInstallerType: inno
NestedInstallerFiles:
- RelativeFilePath: HamVnaSetup.exe
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://dxatlas.com/HamVna/Files/HamVna.zip
  InstallerSha256: A7F66234A63BC51EA3C930A45B454BF1F763DC29EF6DC16788487699C45AAEBA
  Scope: machine
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  InstallerUrl: https://dxatlas.com/HamVna/Files/HamVna.zip
  InstallerSha256: A7F66234A63BC51EA3C930A45B454BF1F763DC29EF6DC16788487699C45AAEBA
  Scope: user
  InstallerSwitches:
    Custom: /CURRENTUSER
```

2023-08-24 15:37 UTC, stephengillie commented
@wingetbot waivers Add Validation-Domain

2023-08-24 19:56 UTC, stephengillie approved these changes

2023-08-24 19:56 UTC, merged