New package: iMobieInc.AnyUnlock version 2.0.1.1
microsoft/winget-pkgs pull request #118751
Opened 2023-09-02 01:20 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2023-09-05 23:45 UTC, stephengillie commented
Should this be a portable package?

2023-09-07 02:49 UTC, Trenly requested changes

2023-09-07 02:49 UTC, Trenly commented on manifests/i/iMobieInc/AnyUnlock/2.0.1.1/iMobieInc.AnyUnlock.installer.yaml
> +- InstallerUrl: https://www.imobie.com/go/download.php?product=auo&id=2
```suggestion
- InstallerUrl: https://dl.imobie.com/anyunlock-iphone-password-unlocker-en-official-setup.exe
```

2023-09-12 03:49 UTC, stephengillie commented
This package doesn't seem to modify the system. Is that expected?

2023-10-23 19:48 UTC, Trenly commented
Stale PR; Please update or close
[Policy] Needs-Author-Feedback

2023-11-07 05:02 UTC, closed without merging