New package: EUSO.eParakstītājs3.0 version 1.7.2
microsoft/winget-pkgs pull request #122908
Opened 2023-10-17 07:09 UTC by Arturslv

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2023-10-17 07:34 UTC, Arturslv commented
@microsoft-github-policy-service agree

2023-10-17 13:32 UTC, Trenly requested changes

2023-10-17 13:32 UTC, Trenly commented on manifests/e/EUSO/eParakstītājs3/0/1.7.2/EUSO.eParakstītājs3.0.locale.LV.yaml
> +ShortDescription: eParakstitajs3.0(MSI)V_1.7.2
Please provide a better description of what this software does or what this software is used for

2023-10-17 13:32 UTC, Trenly commented on manifests/e/EUSO/eParakstītājs3/0/1.7.2/EUSO.eParakstītājs3.0.locale.LV.yaml
> +License: eParaksts  2017 VAS "Latvijas Valsts radio un televīzijas centrs"
An eSignature is not a license. Please update to actual licence terms such as `Proprietary`, `MIT`, `GPL-3.0`, or similar

2023-10-18 00:25 UTC, stephengillie commented on manifests/e/EUSO/eParakstītājs3/0/1.7.2/EUSO.eParakstītājs3.0.locale.LV.yaml
> +PackageName: eParakstītājs 3.0
```suggestion
PackageName: eParakstītājs 3.0
PackageUrl: https://www.eparaksts.lv/lv/lejupielades
```

2023-10-18 00:29 UTC, stephengillie commented
@wingetbot waivers Add Validation-Domain

2023-11-02 01:49 UTC, closed without merging