New version: Oracle.JDK.21 version 21.0.1
microsoft/winget-pkgs pull request #123520
Opened 2023-10-23 16:51 UTC by Dragon1573

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2023-10-23 16:56 UTC, Dragon1573 commented on manifests/o/Oracle/JDK/21/21.0.1/Oracle.JDK.21.installer.yaml
> +ReleaseDate: 2023-09-19
```suggestion
ReleaseDate: 2023-10-17
```

2023-10-23 16:56 UTC, Dragon1573 commented on manifests/o/Oracle/JDK/21/21.0.1/Oracle.JDK.21.locale.en-US.yaml
> +ManifestType: defaultLocale
```suggestion
ReleaseNotesUrl: https://www.oracle.com/java/technologies/javase/21-0-1-relnotes.html
ManifestType: defaultLocale
```

2023-10-23 19:40 UTC, Trenly requested changes

2023-10-23 19:40 UTC, Trenly commented on manifests/o/Oracle/JDK/21/21.0.1/Oracle.JDK.21.installer.yaml
> +- DisplayName: Java(TM) SE Development Kit 21 (64-bit)
Must match control panel exactly
```suggestion
- DisplayName: Java(TM) SE Development Kit 21.0.1 (64-bit)
```

2023-10-23 19:40 UTC, Trenly commented on manifests/o/Oracle/JDK/21/21.0.1/Oracle.JDK.21.installer.yaml
> +UpgradeBehavior: uninstallPrevious
```suggestion
InstallerSwitches:
  InstallLocation: INSTALLDIR=<INSTALLPATH>
UpgradeBehavior: uninstallPrevious
```
Should carry over metadata from previous versions

2023-10-23 19:40 UTC, Trenly commented on manifests/o/Oracle/JDK/21/21.0.1/Oracle.JDK.21.installer.yaml
> +  InstallerUrl: https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.msi
Since this is a vanity URL, the previous version should be removed (can be part of this PR or a separate one)

2023-10-24 17:27 UTC, stephengillie approved these changes

2023-10-24 17:27 UTC, merged