Remove: CrystalDewWorld.CrystalDiskInfo version 8.8.9
microsoft/winget-pkgs pull request #124663
Opened 2023-11-03 12:07 UTC by coolplaylinbot

## [Automated] It returns 504 code in architecture x86

2023-11-03 20:55 UTC, stephengillie commented
Hi @CoolPlayLin,

For this PR, the error is because the host's SSL certificate expired. 
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/3865631e-e941-40de-b47f-a6d556198342)

If the HTTPS is changed down to HTTP, the links still work.

2023-11-04 01:29 UTC, CoolPlayLin requested changes
Close with reason: No need to remove

2023-11-04 01:30 UTC, CoolPlayLin requested changes

2023-11-04 01:30 UTC, CoolPlayLin commented on manifests/c/CrystalDewWorld/CrystalDiskInfo/8.8.9/CrystalDewWorld.CrystalDiskInfo.installer.yaml
Close with reason: No need to remove

2023-11-04 01:30 UTC, CoolPlayLin commented on manifests/c/CrystalDewWorld/CrystalDiskInfo/8.8.9/CrystalDewWorld.CrystalDiskInfo.locale.en-US.yaml
Close with reason: No need to remove

2023-11-04 01:30 UTC, CoolPlayLin commented on manifests/c/CrystalDewWorld/CrystalDiskInfo/8.8.9/CrystalDewWorld.CrystalDiskInfo.yaml
Close with reason: No need to remove

2023-11-18 10:05 UTC, closed without merging