New version: Kakao.KakaoTalk version 3.6.5.3663
microsoft/winget-pkgs pull request #124959
Opened 2023-11-06 10:26 UTC by MokaSoda

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2023-11-06 10:27 UTC, MokaSoda commented
@microsoft-github-policy-service agree

2023-11-06 10:56 UTC, MokaSoda commented
@microsoft-github-policy-service rerun

2023-11-06 10:59 UTC, MokaSoda commented
@microsoft-github-policy-service agree

2023-11-06 12:22 UTC, BrandonWanHuanSheng commented
@MokaSoda There is something wrong with the @microsoft-github-policy-service. Because @microsoft-github-policy-service did not add or remove the labels on some of the PR. Please do not close this pull request. There might need some fix to applied https://github.com/microsoft/winget-pkgs/tree/master/.github/workflow. It seem like there is some labels need to re-fix it. The team is already in aware.

2023-11-06 13:00 UTC, MokaSoda commented
@microsoft-github-policy-service agree

2023-11-06 13:01 UTC, MokaSoda commented
@microsoft-github-policy-service rerun

2023-11-06 15:13 UTC, BrandonWanHuanSheng commented
@mdanish-kh. What is happening here?

2023-11-06 16:32 UTC, mdanish-kh commented
The bot appears to be down today. This will need to be looked at by the maintainers.

2023-11-06 21:09 UTC, denelon commented
It looks like the bot approved merging 10 hours ago. I'm going to trigger another run to see if it's resolved.

2023-11-06 21:09 UTC, denelon commented
/azp run

2023-11-06 21:18 UTC, mdanish-kh requested changes
PackageVersion must match version displayed in Apps&Features / Control Panel

After committing the suggested changes, you would also have to rename the version folder to match the new PackageVersion. The folder under `manifests/k/Kakao/KakaoTalk` should be renamed from `3.6.5.3663` -> `3.6.6.3669`

A quick and easy way to do this would be here in GitHub Web by pressing the <kbd>.</kbd> (dot) key on your keyboard that'll open up the PR in VS Code Online. Navigate to Explorer menu, find the required folder and make the appropriate rename changes.

After that, stage and commit your changes from Source Control menu on the left. (The changes are automatically pushed)

2023-11-06 21:18 UTC, mdanish-kh commented on manifests/k/Kakao/KakaoTalk/3.6.5.3663/Kakao.KakaoTalk.installer.yaml
> +PackageVersion: 3.6.5.3663
```suggestion
PackageVersion: 3.6.6.3669
```

2023-11-06 21:18 UTC, mdanish-kh commented on manifests/k/Kakao/KakaoTalk/3.6.5.3663/Kakao.KakaoTalk.locale.en-US.yaml
> +PackageVersion: 3.6.5.3663
```suggestion
PackageVersion: 3.6.6.3669
```

2023-11-06 21:18 UTC, mdanish-kh commented on manifests/k/Kakao/KakaoTalk/3.6.5.3663/Kakao.KakaoTalk.locale.ko-KR.yaml
> +PackageVersion: 3.6.5.3663
```suggestion
PackageVersion: 3.6.6.3669
```

2023-11-06 21:18 UTC, mdanish-kh commented on manifests/k/Kakao/KakaoTalk/3.6.5.3663/Kakao.KakaoTalk.yaml
> +PackageVersion: 3.6.5.3663
```suggestion
PackageVersion: 3.6.6.3669
```

2023-11-06 22:06 UTC, BrandonWanHuanSheng commented
@MokaSoda There is some changes requested to your bot.

2023-11-07 00:20 UTC, MokaSoda commented
Okay, I'll fix this by running wingetcreate again. Thanks for solving CLA and mentioning version problem.

2023-11-07 00:20 UTC, closed without merging