New package: BenjaminLSR.HandheldCompanion version 0.18.0.6
microsoft/winget-pkgs pull request #126196
Opened 2023-11-12 12:05 UTC by Dragon1573

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2023-11-13 18:53 UTC, stephengillie commented
Hi @Dragon1573,

This package installed normally in the Automatic Validation pipeline, but the dependency had a popup in a Windows 10 VM:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/8b5ef16d-df84-4ac3-ab4a-930b766a8822)

Is there an installer switch to bypass this?

2023-11-14 02:07 UTC, BrandonWanHuanSheng commented on manifests/b/BenjaminLSR/HandheldCompanion/0.18.0.6/BenjaminLSR.HandheldCompanion.installer.yaml
> +InstallerType: inno
```suggestion
InstallerType: inno
InstallerSwitches:
   Silent: /SILENT
   Custom: /NORESTART
```

2023-11-14 02:16 UTC, BrandonWanHuanSheng requested changes
It seem there is a dependencies pop up with a msg boxes requiring a restart.
So, there is a way to bypass this one

2023-11-14 18:36 UTC, stephengillie approved these changes

2023-11-14 18:36 UTC, merged