Microsoft.SaRA version 17.01.0268.015
microsoft/winget-pkgs pull request #127741
Opened 2023-11-22 15:53 UTC by jahvari

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2023-11-22 20:05 UTC, stephengillie commented
Manual Validation ended with:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/c5b1d236-aa85-45fb-93fe-5e1a75a7e059)

2023-11-22 20:24 UTC, stephengillie commented
Hi @jahvari,

It looks like the nested installer needs an installer switch to complete silently. Do you know of the correct switches?

2023-11-27 14:26 UTC, Trenly requested changes

2023-11-27 14:26 UTC, Trenly commented on manifests/m/Microsoft/SaRA/17.01.0268.015/Microsoft.SaRA.yaml
> +PackageIdentifier: Microsoft.SaRA
```suggestion
PackageIdentifier: Microsoft.SupportAndRecoveryAssistant
```

2023-11-27 14:26 UTC, Trenly commented on manifests/m/Microsoft/SaRA/17.01.0268.015/Microsoft.SaRA.locale.en-US.yaml
> +PackageName: SaRA
```suggestion
PackageName: Microsoft Support and Recovery Assistant
```
This should match control panel

2023-11-27 14:26 UTC, Trenly commented on manifests/m/Microsoft/SaRA/17.01.0268.015/Microsoft.SaRA.locale.en-US.yaml
> +ShortDescription: SaRA is a desktop client that enables Microsoft customers to troubleshoot and diagnose their issues
```suggestion
ShortDescription: SaRA is a desktop client that enables Microsoft customers to troubleshoot and diagnose their issues
Moniker: SaRA
```

2023-11-27 14:26 UTC, Trenly commented on manifests/m/Microsoft/SaRA/17.01.0268.015/Microsoft.SaRA.locale.en-US.yaml
> +PackageVersion: 17.01.0268.015
```suggestion
PackageVersion: 17.1.268.15
```
Should match control panel exactly

2023-11-27 14:26 UTC, Trenly commented on manifests/m/Microsoft/SaRA/17.01.0268.015/Microsoft.SaRA.locale.en-US.yaml
> +Publisher: Microsoft
```suggestion
Publisher: Microsoft Corporation
```
Should match control panel exactly

2023-11-27 14:26 UTC, Trenly commented on manifests/m/Microsoft/SaRA/17.01.0268.015/Microsoft.SaRA.yaml
> +PackageVersion: 17.01.0268.015
```suggestion
PackageVersion: 17.1.268.15
```
Should match control panel exactly

2023-11-29 17:54 UTC, stephengillie approved these changes

2023-11-29 17:55 UTC, merged