New version: Microsoft.PowerBI version 2.124.1052.0
microsoft/winget-pkgs pull request #131098
Opened 2023-12-19 00:12 UTC by PckgrBot

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2023-12-19 16:07 UTC, Trenly requested changes

2023-12-19 16:07 UTC, Trenly commented on manifests/m/Microsoft/PowerBI/2.124.1052.0/Microsoft.PowerBI.installer.yaml
> +  Custom: ACCEPT_EULA=1
Does it install without this switch?

2023-12-27 21:00 UTC, stephengillie approved these changes

2023-12-27 21:00 UTC, merged

2023-12-29 17:35 UTC, Trenly commented
@stephengillie - This package had an `ACCEPT_EULA` switch?

2024-01-02 17:39 UTC, stephengillie commented
> @stephengillie - This package had an `ACCEPT_EULA` switch?

Yeah...haven't completed detecting them yet, working on that now. File clobber detection took priority.

2024-01-02 22:02 UTC, stephengillie approved these changes

2024-01-02 22:04 UTC, stephengillie approved these changes

2024-01-02 22:12 UTC, stephengillie commented
This manifest contains a term that is blocked:

>   Custom: ACCEPT_EULA=1

(Automated response - build 510.)