New package: AmeyaP.UTAU version 0.4.18
microsoft/winget-pkgs pull request #132335
Opened 2024-01-01 17:31 UTC by Exorcism0666

### Pull request has been created with [Komac](https://github.com/russellbanks/Komac) v1.11.0 :rocket:

2024-01-01 19:35 UTC, Exorcism0666 commented
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification. It has the write permission of this account's fork so that it can resolve the issue directly.

>[!important]
>Please recheck these Pull Request carefully before merging. If it is a incorrect-removing Pull Request and the URLs don't have any issue while manual checking, please close this Pull Request directly(It's best to let Exorcism0666 know).

良い一日をお過ごしください！

2024-01-02 15:15 UTC, Trenly requested changes

2024-01-02 15:15 UTC, Trenly commented on manifests/a/AmeyaP/UTAU/0.4.18/AmeyaP.UTAU.installer.yaml
> +PackageVersion: 0.4.18
```suggestion
PackageVersion: 1.1.18
```
This should match control panel. If it does not, `AppsAndFeaturesEntries` are required in the manifest

2024-01-02 15:15 UTC, Trenly commented on manifests/a/AmeyaP/UTAU/0.4.18/AmeyaP.UTAU.installer.yaml
> +  Custom: /norestart
This is causing a command line error when trying to install the program. You will need to fix the installer switches so it installs unattended

2024-01-02 15:15 UTC, Trenly commented on manifests/a/AmeyaP/UTAU/0.4.18/AmeyaP.UTAU.locale.ja-JP.yaml
> +PackageVersion: 0.4.18
```suggestion
PackageVersion: 1.1.18
```

2024-01-02 15:15 UTC, Trenly commented on manifests/a/AmeyaP/UTAU/0.4.18/AmeyaP.UTAU.yaml
> +PackageVersion: 0.4.18
```suggestion
PackageVersion: 1.1.18
```

2024-01-07 18:07 UTC, Exorcism0666 commented
:^)

2024-01-09 16:56 UTC, stephengillie commented
Automatic Validation ended with:
> 2024-01-02T16:09:03.1728223Z ##[error] Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 'manifests\a\AmeyaP\UTAU\0.4.18', expected 'manifests\a\AmeyaP\UTAU\1.1.18'

(Automated response - build 536.)

2024-01-09 17:15 UTC, stephengillie commented
Hi @Exorcism0666,

Please update the file paths to match the new version.

2024-01-19 20:13 UTC, closed without merging