New package: Crucial.StorageExecutive version 9.09.092023.03
microsoft/winget-pkgs pull request #132977
Opened 2024-01-06 18:34 UTC by Exorcism0666

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-01-06 19:35 UTC, Exorcism0666 commented
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

2024-01-07 16:32 UTC, Exorcism0666 commented
![image](https://github.com/microsoft/winget-pkgs/assets/46537034/e04d5631-2fc0-4914-a118-be77dffe1e30)

2024-01-07 17:33 UTC, Exorcism0666 commented
> ![image](https://private-user-images.githubusercontent.com/46537034/294771443-e04d5631-2fc0-4914-a118-be77dffe1e30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDkwNDcsIm5iZiI6MTcwNDY0ODc0NywicGF0aCI6Ii80NjUzNzAzNC8yOTQ3NzE0NDMtZTA0ZDU2MzEtMmZjMC00OTE0LWExMTgtYmU3N2RmZmUxZTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDE3MzIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NTBmOTFlZGI3YmU2ODk3ZDY0NTQ0ZjhkNjk2ZTE5NjgwMjI0YWYwMGZhMmZjMGJiZTdmOGM0NTIzZGNlMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SdfhwzINEkVirokQrN3f9ddvtJ88AuBqII198vTbgjI)

What do you think I should use for silent installation?

2024-01-07 19:21 UTC, Exorcism0666 commented
> ![image](https://private-user-images.githubusercontent.com/46537034/294771443-e04d5631-2fc0-4914-a118-be77dffe1e30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NTUyODgsIm5iZiI6MTcwNDY1NDk4OCwicGF0aCI6Ii80NjUzNzAzNC8yOTQ3NzE0NDMtZTA0ZDU2MzEtMmZjMC00OTE0LWExMTgtYmU3N2RmZmUxZTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDE5MTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MmRiOTBjMjMwNjc1ZmUxY2ZhYzliNTQyNGJiNjZjZjQ2ZjZjYTM5ZWJiMzJjYTM5MjU4N2M2ODliYWYwYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HLbk_Fr7y03jO27U1jfCeQbhpy6iI527lX9JQhtGM20)

@OfficialEsco what should i do ?

2024-01-07 20:21 UTC, OfficialEsco requested changes
Azure Pipeline
> Installation failed with exit code -1978335226

Manual validation
![image](https://github.com/microsoft/winget-pkgs/assets/15158490/7d4237f5-c24c-4c86-836b-83086d1a7065)

Manual testing
![image](https://github.com/microsoft/winget-pkgs/assets/15158490/0009ba51-3c0a-4311-bfcf-2ddc48a49835)

2024-01-07 20:21 UTC, OfficialEsco commented on manifests/c/Crucial/StorageExecutive/9.09.092023.03/Crucial.StorageExecutive.installer.yaml
> +  SilentWithProgress: /S --force-run
```suggestion
  Silent: --mode unattended --force-run
  SilentWithProgress: --mode unattended --unattendedmodeui minimal --force-run
```

2024-01-07 20:33 UTC, OfficialEsco requested changes
Why did you add these? >.<
I didn't do my testing with that switch so i tough it was intended

2024-01-07 20:33 UTC, OfficialEsco commented on manifests/c/Crucial/StorageExecutive/9.09.092023.03/Crucial.StorageExecutive.installer.yaml
> +  SilentWithProgress: --mode unattended --unattendedmodeui minimal --force-run
```suggestion
  Silent: --mode unattended
  SilentWithProgress: --mode unattended --unattendedmodeui minimal
```

2024-01-07 20:55 UTC, OfficialEsco approved these changes

2024-01-07 21:57 UTC, merged