New package: Freenet.Freenet version 1496
microsoft/winget-pkgs pull request #135182
Opened 2024-01-17 15:53 UTC by Exorcism0666

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-01-17 16:07 UTC, Exorcism0666 commented
![image](https://github.com/microsoft/winget-pkgs/assets/46537034/edede96f-9d1a-40bb-8d0f-75e1d20b3d20)

2024-01-17 16:07 UTC, Exorcism0666 commented
```
2024-01-17 17:02:30.486   Log opened. (Time zone: UTC+01:00)
2024-01-17 17:02:30.486   Setup version: Inno Setup version 6.2.1
2024-01-17 17:02:30.486   Original Setup EXE: C:\Users\WDAGUtilityAccount\AppData\Local\Temp\WinGet\Freenet.Freenet.1496\FreenetInstaller-1496.exe
2024-01-17 17:02:30.486   Setup command line: /SL5="$201EC,80626432,804352,C:\Users\WDAGUtilityAccount\AppData\Local\Temp\WinGet\Freenet.Freenet.1496\FreenetInstaller-1496.exe" /SILENT /NORESTART /LOG="C:\Users\WDAGUtilityAccount\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Freenet.Freenet.1496-2024-01-17-17-02-24.460.log"
2024-01-17 17:02:30.486   Windows version: 10.0.19041  (NT platform: Yes)
2024-01-17 17:02:30.486   64-bit Windows: Yes
2024-01-17 17:02:30.486   Processor architecture: x64
2024-01-17 17:02:30.486   User privileges: Administrative
2024-01-17 17:02:30.502   Administrative install mode: No
2024-01-17 17:02:30.502   Install mode root key: HKEY_CURRENT_USER
2024-01-17 17:02:30.502   64-bit install mode: No
2024-01-17 17:02:30.908   Created temporary directory: C:\Users\WDAGUtilityAccount\AppData\Local\Temp\is-MDSD1.tmp
2024-01-17 17:02:31.080   -- DLL function import --
2024-01-17 17:02:31.080   Function name: fIsPortAvailable
2024-01-17 17:02:31.080   DLL name: setup:files:FreenetInstaller_InnoSetup_library.dll
2024-01-17 17:02:31.080   Extracting temporary file: C:\Users\WDAGUtilityAccount\AppData\Local\Temp\is-MDSD1.tmp\FreenetInstaller_InnoSetup_library.dll
2024-01-17 17:02:31.080   Dest DLL name: C:\Users\WDAGUtilityAccount\AppData\Local\Temp\is-MDSD1.tmp\FreenetInstaller_InnoSetup_library.dll
2024-01-17 17:02:31.080   Importing the DLL function.
2024-01-17 17:02:31.142   Successfully imported the DLL function. Delay loaded? No
2024-01-17 17:02:31.142   -- DLL function import --
2024-01-17 17:02:31.142   Function name: fMemoryTotalPhys
2024-01-17 17:02:31.142   DLL name: setup:files:FreenetInstaller_InnoSetup_library.dll
2024-01-17 17:02:31.142   Dest DLL name: C:\Users\WDAGUtilityAccount\AppData\Local\Temp\is-MDSD1.tmp\FreenetInstaller_InnoSetup_library.dll
2024-01-17 17:02:31.142   Importing the DLL function.
2024-01-17 17:02:31.142   Successfully imported the DLL function. Delay loaded? No
2024-01-17 17:02:37.189   Failed to proceed to next wizard page; aborting.
2024-01-17 17:02:37.189   Got EAbort exception.
2024-01-17 17:02:37.189   Deinitializing Setup.
2024-01-17 17:02:37.205   Log closed.
```

2024-01-17 19:35 UTC, Exorcism0666 commented
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

2024-01-21 04:34 UTC, Trenly requested changes

2024-01-21 04:34 UTC, Trenly commented on manifests/f/Freenet/Freenet/1496/Freenet.Freenet.locale.en-US.yaml
> +ShortDescription: Freenet Setup
Please provide a better description

2024-01-21 10:52 UTC, Exorcism0666 commented
![InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20240121101012](https://github.com/microsoft/winget-pkgs/assets/46537034/ea75f4fa-d958-4811-86a4-99701f71aa10)
What should I do ?

2024-01-22 22:59 UTC, stephengillie commented
Automatic Validation ended with:
>  2024-01-21 00:10:54.657   InitializeWizard raised an exception (fatal). 2024-01-21 00:10:54.657   Exception message:                           Runtime error (at 20:226):                           Internal error: Cannot access 64-bit registry keys on this version of Windows.

(Automated response - build 628.)

2024-01-22 23:19 UTC, stephengillie commented on manifests/f/Freenet/Freenet/1496/Freenet.Freenet.installer.yaml
> +  Architecture: x86
```suggestion
  Architecture: x86
```

2024-01-26 16:40 UTC, closed without merging