Remove: GIGABYTE.AORUS-ENGINE version 2.1.2.0
microsoft/winget-pkgs pull request #136735
Opened 2024-01-27 03:25 UTC by coolplaylinbot

## [Automated] It returns code over 400 in all urls

2024-01-27 03:43 UTC, Trenly requested changes
This is the only version in the repository; Is there a new update available instead of just removing the package?

2024-01-28 04:08 UTC, CoolPlayLin commented
I don't know where I can download it

2024-01-29 19:55 UTC, stephengillie commented
URL: https://download.gigabyte.com/FileList/Utility/vga_utility_aorus_setup_v2.1.2.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 674)

2024-01-29 19:56 UTC, stephengillie approved these changes

2024-01-29 19:56 UTC, merged