Move Roku.roku_remote_tool 4.0.5.1327 to Roku.RemoteTool 4.0.5.1327
microsoft/winget-pkgs pull request #137923
Opened 2024-02-05 19:26 UTC by Trenly

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-02-05 21:20 UTC, stephengillie commented
/AzurePipelines run

2024-02-06 19:52 UTC, stephengillie commented
This package uninstalled itself during manual validation.

2024-02-06 19:58 UTC, Trenly commented
> This package uninstalled itself during manual validation.

Interesting. Using `SandboxTest.ps1` I didn't see it uninstall itself at all

2024-02-07 10:17 UTC, mdanish-kh requested changes

2024-02-07 10:17 UTC, mdanish-kh commented on manifests/r/Roku/RemoteTool/4.0.5/Roku.RemoteTool.locale.en-US.yaml
> +ShortDescription: roku_remote_tool
```suggestion
ShortDescription: The Roku Remote Tool provides developers a quick and intuitive way to create reusable scripts for ad-hoc testing of their channel.
Documentations:
- DocumentLabel: Roku platform overview
  DocumentUrl: https://developer.roku.com/docs/references/references-overview.md
```

2024-02-07 10:17 UTC, mdanish-kh commented on manifests/r/Roku/RemoteTool/4.0.5/Roku.RemoteTool.locale.en-US.yaml
> +PackageName: roku_remote_tool
```suggestion
PackageName: roku_remote_tool
PackageUrl: https://developer.roku.com/docs/features/features-overview.md
```

2024-02-07 10:17 UTC, mdanish-kh commented on manifests/r/Roku/RemoteTool/4.0.5/Roku.RemoteTool.locale.en-US.yaml
> +License: Proprietary
```suggestion
License: Apache-2.0
LicenseUrl: http://devtools.web.roku.com/RokuRemote/
```

2024-02-07 10:17 UTC, mdanish-kh commented on manifests/r/Roku/RemoteTool/4.0.5/Roku.RemoteTool.locale.en-US.yaml
> +Copyright: Copyright © 2022 Roku
```suggestion
Copyright: Copyright © 2022 Roku, Inc.
CopyrightUrl: http://devtools.web.roku.com/RokuRemote/
```

2024-02-07 10:17 UTC, mdanish-kh commented on manifests/r/Roku/RemoteTool/4.0.5/Roku.RemoteTool.locale.en-US.yaml
> +Publisher: Roku
```suggestion
Publisher: Roku
PublisherUrl: https://developer.roku.com/
PrivacyUrl: https://docs.roku.com/published/b2bprivacypolicy/en/us
PublisherSupportUrl: https://support.roku.com
```

2024-02-07 12:35 UTC, mdanish-kh commented
@wingetbot run

2024-02-07 12:36 UTC, mdanish-kh approved these changes

2024-02-07 16:31 UTC, stephengillie commented
/AzurePipelines run

2024-02-07 16:52 UTC, stephengillie commented
/AzurePipelines run

2024-02-07 17:59 UTC, mdanish-kh commented
@wingetbot run

2024-02-07 17:59 UTC, mdanish-kh approved these changes

2024-02-07 18:53 UTC, merged