New package: AlignTechnology,Inc.InvisalignOutcomeSimulator version 4.2.1.75
microsoft/winget-pkgs pull request #138186
Opened 2024-02-06 19:48 UTC by DavidHGAK

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-02-06 21:20 UTC, stephengillie commented
/AzurePipelines run

2024-02-07 01:20 UTC, stephengillie commented
/AzurePipelines run

2024-02-07 15:52 UTC, stephengillie commented
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 2024-02-06 18:19:24.728 [CLI ] ShellExecute installer failed: 2147753984

(Automated response - build 707.)

2024-02-07 16:15 UTC, stephengillie commented
Hi @DavidHGAK,

This package didn't fully install when using the silent install switch, but did when running the attended installer - it required an EULA agreement that didn't have a counterpart installer swtich:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/3b565eeb-5de1-4457-86c3-158d2b8359c1)

I'm wondering if there's a missing installer switch to accept the license. I searched but couldn't find one. I'm guessing that the error code we're seeing is the license agreement failure error. 

This presents another issue in that we've [recently had to remove](https://github.com/microsoft/winget-pkgs/issues/131328) several packages that have EULA or similar agreements in the installer. 

Let me know what you think.

2024-02-07 16:53 UTC, Trenly requested changes
It seems this application may require an interactive install

2024-02-07 16:53 UTC, Trenly commented on manifests/a/AlignTechnology,Inc/InvisalignOutcomeSimulator/4.2.1.75/AlignTechnology,Inc.InvisalignOutcomeSimulator.installer.yaml
> +PackageIdentifier: AlignTechnology,Inc.InvisalignOutcomeSimulator
```suggestion
PackageIdentifier: AlignTechnology.InvisalignOutcomeSimulator
```
After changing this, the folder and files will need to be renamed

2024-02-07 16:53 UTC, Trenly commented on manifests/a/AlignTechnology,Inc/InvisalignOutcomeSimulator/4.2.1.75/AlignTechnology,Inc.InvisalignOutcomeSimulator.locale.en-US.yaml
> +PackageIdentifier: AlignTechnology,Inc.InvisalignOutcomeSimulator
```suggestion
PackageIdentifier: AlignTechnology.InvisalignOutcomeSimulator
```
After changing this, the folder and files will need to be renamed

2024-02-07 16:53 UTC, Trenly commented on manifests/a/AlignTechnology,Inc/InvisalignOutcomeSimulator/4.2.1.75/AlignTechnology,Inc.InvisalignOutcomeSimulator.yaml
> +PackageIdentifier: AlignTechnology,Inc.InvisalignOutcomeSimulator
```suggestion
PackageIdentifier: AlignTechnology.InvisalignOutcomeSimulator
```
After changing this, the folder and files will need to be renamed

2024-02-16 01:16 UTC, closed without merging