added send to kindle
microsoft/winget-pkgs pull request #13849
Opened 2021-05-23 12:46 UTC by bearmannl

Added the Amazon SendToKindle application, which can be used to send local files (such as PDF) to your Kindle device.

2021-05-23 14:57 UTC, OfficialEsco requested changes
The error you were seeing is "Installer failed with exit code: 1223" which means Cancel by user which happens with these package installers..
The package also requires VC++2015 x86 which will be supported soon
The installer should also be nullsoft like before instead of exe :)

2021-05-23 14:57 UTC, OfficialEsco commented on manifests/a/Amazon/SendToKindle/1.1.1.250/Amazon.SendToKindle.installer.yaml
> +MinimumOSVersion: 10.0.0.0
```suggestion
MinimumOSVersion: 10.0.0.0
InstallerSuccessCodes:
  - 1223
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VC++2015Redist-x86
      MinimumVersion: 14.0.23026.0
```

2021-05-23 14:57 UTC, OfficialEsco commented on manifests/a/Amazon/SendToKindle/1.1.1.250/Amazon.SendToKindle.installer.yaml
> +    InstallerType: exe
```suggestion
    InstallerType: nullsoft
```

2021-05-23 16:03 UTC, OfficialEsco commented
@bearmannl look at my comment/suggested changes

2021-05-23 16:38 UTC, bearmannl commented
Thanks for the feedback @OfficialEsco

2021-05-23 18:58 UTC, denelon commented
https://github.com/microsoft/winget-cli/issues/163 Support for Package Dependencies

2021-05-29 20:40 UTC, bearmannl commented
re-worked installer and added version 1.1.0.252

2021-05-29 20:53 UTC, OfficialEsco commented
Hey @bearmannl isn't this already submitted under https://github.com/microsoft/winget-pkgs/tree/master/manifests/a/Amazon/Kindle ?

2021-05-29 21:16 UTC, merged