New package: Princessmortix.Cobalt version 1.0.4
microsoft/winget-pkgs pull request #138568
Opened 2024-02-09 17:04 UTC by princessmortix

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-02-09 19:20 UTC, stephengillie commented
Automatic Validation ended with:
> 2024-02-09T18:09:26.4459910Z ##[error] Manifest Error: Field usage requires verified publishers. [Icons]

(Automated response - build 720.)

2024-02-09 23:36 UTC, stephengillie commented on manifests/p/Princessmortix/Cobalt/1.0.4/Princessmortix.Cobalt.locale.en-US.yaml
> +  IconResolution: 256x256
```suggestion
```

Hi @princessmortix,

This feature depends on the `Agreements` section, which I believe hasn't quite been deployed yet. These lines might be readded after it's available.

2024-02-12 15:14 UTC, Trenly requested changes

2024-02-12 15:14 UTC, Trenly commented on manifests/p/Princessmortix/Cobalt/1.0.4/Princessmortix.Cobalt.locale.en-US.yaml
> +- downloader, cobalt, cli
```suggestion
Tags:
- downloader
- cobalt
- cli
```

2024-02-23 19:46 UTC, closed without merging