WHTA.Tamara version 2023.0.8.9
microsoft/winget-pkgs pull request #139830
Opened 2024-02-17 15:38 UTC by lars-whta

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-02-17 18:19 UTC, lars-whta commented
> **Found duplicate pull request(s)**
> 
> * **Manifest Path: manifests\w\WHTA\Tamara\2023.0.8.9**
>   
>   * [[Agreements] Add back WHTA.Tamara #139463](https://github.com/microsoft/winget-pkgs/pull/139463)

Previous PR should be closed--not sanctioned.

2024-02-17 19:26 UTC, mdanish-kh requested changes

2024-02-17 19:26 UTC, mdanish-kh commented on manifests/w/WHTA/Tamara/2023.0.8.9/WHTA.Tamara.installer.yaml
> +  Custom: -mode silent -agreeToLicense yes
```suggestion
  Custom: -agreeToLicense yes
```
Custom represents the args that are passed in addition to the Silent / SilentWithProgress args.

This means with the current manifest, the following args will be passed:

`./installer.exe -mode silent -mode silent -agreeToLicense yes`

We can remove `-mode silent` from `Custom:` to get rid of the duplication

2024-02-17 19:33 UTC, mdanish-kh commented
Looks good now, agreements will have to be reviewed by an admin

2024-02-17 19:36 UTC, mdanish-kh commented on manifests/w/WHTA/Tamara/2023.0.8.9/WHTA.Tamara.installer.yaml
> +    Publisher: Wolkesson & Hansson Teknisk Akustik AB
```suggestion
    Publisher:
    ProductCode: Tamara
```

Missed this earlier, the installer doesn't write a Publisher value to the registry / Apps&Features / Control Panel. We can use ProductCode to have better package matching

![image](https://github.com/microsoft/winget-pkgs/assets/88161975/d6f9e545-5e28-4735-bd7c-181397ea008c)

2024-02-18 22:10 UTC, denelon approved these changes

2024-02-18 22:10 UTC, merged