New version: Kubernates.kwok version 0.5.1
microsoft/winget-pkgs pull request #140115
Opened 2024-02-19 21:44 UTC by Exorcism0666

### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.1.0 :rocket:

2024-02-20 20:01 UTC, stephengillie reviewed
Hi @Exorcism0666,

This PackageIdentifier appears to have a typo, and seems very similar to another: 

- https://github.com/microsoft/winget-pkgs/pull/130692

2024-02-20 20:01 UTC, stephengillie commented on manifests/k/Kubernates/kwok/0.5.1/Kubernates.kwok.installer.yaml
> +PackageIdentifier: Kubernates.kwok
```suggestion
PackageIdentifier: Kubernetes.kwokctl
```

2024-02-20 20:01 UTC, stephengillie commented on manifests/k/Kubernates/kwok/0.5.1/Kubernates.kwok.locale.en-US.yaml
> +PackageIdentifier: Kubernates.kwok
```suggestion
PackageIdentifier: Kubernetes.kwokctl
```

2024-02-20 20:01 UTC, stephengillie commented on manifests/k/Kubernates/kwok/0.5.1/Kubernates.kwok.yaml
> +PackageIdentifier: Kubernates.kwok
```suggestion
PackageIdentifier: Kubernetes.kwokctl
```

2024-02-20 20:03 UTC, stephengillie commented
Automatic Validation ended with:
> No errors to post.

(Automated response - build 785.)

2024-02-20 20:21 UTC, Exorcism0666 commented
@stephengillie The downloads links are not same as this PR https://github.com/microsoft/winget-pkgs/pull/130692.

2024-02-21 20:02 UTC, stephengillie commented
@wingetbot run

2024-02-22 17:00 UTC, stephengillie requested changes
Hi @Exorcism0666,

This PackageIdentifier has a typo, swapping one of the `e`'s for an `a`. The name `Kubernetes` has no `a`s in it. 

Current: `Kubern`**a**`tes.kwok`
Should: `Kubern`**e**`tes.kwok`

Please update any automation with the correct spelling.

2024-02-22 17:32 UTC, closed without merging