New version: yt-dlp.yt-dlp.nightly version 2024.02.24.232815
microsoft/winget-pkgs pull request #140877
Opened 2024-02-25 01:40 UTC by Exorcism0666

### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.1.1 :rocket:

2024-02-25 01:41 UTC, Exorcism0666 commented
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

2024-02-27 02:38 UTC, stephengillie requested changes
Hi @Exorcism0666,

> 2024-02-24 17:52:38.811 [CLI ] Installer [X64,portable,Unknown,] not applicable: Machine is not compatible with X64

I believe the dependency `Gyan.FFmpeg` is 64-bit only. Should the `x86` installer be removed in these, since its dependency doesn't install correctly?

2024-02-27 02:38 UTC, stephengillie commented on manifests/y/yt-dlp/yt-dlp/nightly/2024.02.24.232815/yt-dlp.yt-dlp.nightly.installer.yaml
> +  InstallerSha256: 22283144CC512509C63702D7054B8D97B5BAF8CB98C57AE15E55DECE1E688A67
```suggestion
```

2024-02-27 17:08 UTC, stephengillie approved these changes

2024-02-27 17:08 UTC, merged