Add version: KDE.Kdenlive version 23.08.4
microsoft/winget-pkgs pull request #142105
Opened 2024-03-04 20:40 UTC by Exorcism0666

﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

* Resolves #141108

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142105)

2024-03-05 01:52 UTC, Exorcism0666 commented
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

2024-03-05 03:07 UTC, stephengillie reviewed
Hi @Exorcism0666,

The InstallerUrl has the subsequent version number in it.

2024-03-05 07:21 UTC, Exorcism0666 commented
@stephengillie This is normal, if you try to install this version, normally it will always be indicated as 23.08.4

2024-03-06 18:11 UTC, stephengillie commented
Verify:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/d21a96f6-2376-4a4f-888b-ec0e89c2311d)

2024-03-06 18:15 UTC, stephengillie requested changes
Hi @Exorcism0666,

This PackageUrl led to a very different InstallerUrl. Should it be used instead?

2024-03-06 18:54 UTC, stephengillie commented
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Specified hash doesn't match.
 Actual hash:   83C3B30DDF2298916A2FEF39CEE2CB2579764E6B99FE908EFE8CDB3CD12B8846
 Expected hash: 8712b9483669b5c01d5642681c6d9f1d191ff8b46848a29344dc873e0c92e138
 
 3/6/2024 6:30:25 PM
 
 ****************************************************************************************
 Installer Validation
 ****************************************************************************************
 

(Automated response - build 866.)

2024-03-06 18:54 UTC, stephengillie commented on manifests/k/KDE/Kdenlive/23.08.4/KDE.Kdenlive.installer.yaml
> +  InstallerSha256: 8712B9483669B5C01D5642681C6D9F1D191FF8B46848A29344DC873E0C92E138
```suggestion

```

(Automated response - build 866.)

2024-03-07 01:34 UTC, stephengillie approved these changes

2024-03-07 01:36 UTC, stephengillie commented
> Possible duplicate package entry.
> 
> Similar installer SHA256 hash found in manifest:
> 
> * `InstallerSha256: 83c3b30ddf2298916a2fef39cee2cb2579764e6b99fe908efe8cdb3cd12b8846`
>   
>   * manifests\k\KDE\Kdenlive\23.08.05

Since the installer with `23.08.5` in the name installs the version in this PR, the manifest for `23.08.5` should be removed.

2024-03-07 08:09 UTC, Exorcism0666 commented
@trenly

2024-03-07 22:32 UTC, merged