TeamSonarr.Sonarr version 3.0.6.1196
microsoft/winget-pkgs pull request #14438
Opened 2021-05-29 23:05 UTC by stummyhurt

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-05-29 23:16 UTC, OfficialEsco commented on manifests/t/TeamSonarr/Sonarr/3.0.6.1196/TeamSonarr.Sonarr.installer.yaml
> +  InstallerUrl: https://services.sonarr.tv/v1/download/main/latest?version=3&os=windows&installer=true
```suggestion
  InstallerUrl: https://download.sonarr.tv/v3/main/3.0.6.1196/Sonarr.main.3.0.6.1196.windows.exe
```

2021-06-01 21:37 UTC, denelon commented
@OfficialEsco we will hold off on merging this until you or another of our future moderators approves this PR.

2021-06-03 20:49 UTC, ItzLevvie requested changes
A change needs to be done: https://github.com/microsoft/winget-pkgs/pull/14438#discussion_r641994529

2021-06-03 20:54 UTC, ItzLevvie requested changes

2021-06-03 20:54 UTC, ItzLevvie commented on manifests/t/TeamSonarr/Sonarr/3.0.6.1196/TeamSonarr.Sonarr.installer.yaml
> +- Architecture: neutral
```suggestion
- Architecture: x86
```

2021-06-03 20:54 UTC, ItzLevvie commented on manifests/t/TeamSonarr/Sonarr/3.0.6.1196/TeamSonarr.Sonarr.installer.yaml
> +PackageVersion: 3.0.6.1196
```suggestion
PackageVersion: 3.0
```
![image](https://user-images.githubusercontent.com/11600822/120710329-f0064700-c4b5-11eb-9728-d900711b3be6.png)

2021-06-03 20:54 UTC, ItzLevvie commented on manifests/t/TeamSonarr/Sonarr/3.0.6.1196/TeamSonarr.Sonarr.locale.en-US.yaml
> +ShortDescription: Sonarr Setup
```suggestion
ShortDescription: Sonarr is a PVR for Usenet and BitTorrent users.
```

2021-06-04 14:21 UTC, OfficialEsco commented
` Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 'manifests\t\TeamSonarr\Sonarr\3.0.6.1196', expected 'manifests\t\TeamSonarr\Sonarr\3.0'`

2021-06-18 17:14 UTC, closed without merging