New version: StefanBerg.NINA Version 3.0.0.9001
microsoft/winget-pkgs pull request #145109
Opened 2024-03-18 17:35 UTC by isbeorn

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-03-19 17:25 UTC, stephengillie requested changes
Hi @isbeorn,

We've depreciated this manifest version, but most fields are identical with the newest manifest version. In most cases, simply increasing the manifest version number is enough.

2024-03-19 17:25 UTC, stephengillie commented on manifests/s/StefanBerg/NINA/3.0.0.9001/StefanBerg.NINA.installer.yaml
> +ManifestVersion: 1.2.0
```suggestion
ManifestVersion: 1.6.0
```

2024-03-19 17:25 UTC, stephengillie commented on manifests/s/StefanBerg/NINA/3.0.0.9001/StefanBerg.NINA.yaml
> +ManifestVersion: 1.2.0
```suggestion
ManifestVersion: 1.6.0
```

2024-03-19 17:25 UTC, stephengillie commented on manifests/s/StefanBerg/NINA/3.0.0.9001/StefanBerg.NINA.locale.en-US.yaml
> +ManifestVersion: 1.2.0
```suggestion
ManifestVersion: 1.6.0
```

2024-03-19 18:02 UTC, isbeorn commented
> Hi @isbeorn,
> 
> We've depreciated this manifest version, but most fields are identical with the newest manifest version. In most cases, simply increasing the manifest version number is enough.

Thank you for the feedback. I've adjusted the manifest version and re-ran the validation successfully with that

2024-03-20 03:47 UTC, stephengillie approved these changes

2024-03-20 03:47 UTC, merged