Move Google.NearbyShare 1.0.972.0 to Google.QuickShare 1.0.972.0
microsoft/winget-pkgs pull request #146155
Opened 2024-03-23 09:46 UTC by SpecterShell

2024-03-23 16:31 UTC, mdanish-kh approved these changes

2024-03-25 18:28 UTC, stephengillie requested changes

2024-03-25 18:28 UTC, stephengillie commented on manifests/g/Google/QuickShare/1.0.972.0/Google.QuickShare.installer.yaml
> +ManifestVersion: 1.4.0
```suggestion
ManifestVersion: 1.6.0
```

2024-03-25 18:28 UTC, stephengillie commented on manifests/g/Google/QuickShare/1.0.972.0/Google.QuickShare.locale.en-US.yaml
> +ManifestVersion: 1.4.0
```suggestion
ManifestVersion: 1.6.0
```

2024-03-25 18:28 UTC, stephengillie commented on manifests/g/Google/QuickShare/1.0.972.0/Google.QuickShare.locale.zh-CN.yaml
> +ManifestVersion: 1.4.0
```suggestion
ManifestVersion: 1.6.0
```

2024-03-25 18:28 UTC, stephengillie commented on manifests/g/Google/QuickShare/1.0.972.0/Google.QuickShare.yaml
> +ManifestVersion: 1.4.0
```suggestion
ManifestVersion: 1.6.0
```

2024-03-28 05:20 UTC, stephengillie approved these changes

2024-03-28 05:20 UTC, merged