New version: 7S2P.Effie.CN version 3.8.1
microsoft/winget-pkgs pull request #146166
Opened 2024-03-23 11:08 UTC by SpecterShell

Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in Run [#3873](https://github.com/SpecterShell/Dumplings/actions/runs/8401351440).

2024-03-24 19:10 UTC, OfficialEsco requested changes
Also this is the same installer as #146165?

2024-03-24 19:10 UTC, OfficialEsco commented on manifests/7/7S2P/Effie/CN/3.8.1/7S2P.Effie.CN.installer.yaml
> +  ProductCode: Effie_is1
```suggestion
  ProductCode: Effie for Windows_is1
```

2024-03-24 19:10 UTC, OfficialEsco commented on manifests/7/7S2P/Effie/CN/3.8.1/7S2P.Effie.CN.installer.yaml
> +  ProductCode: Effie_is1
```suggestion
  ProductCode: Effie for Windows_is1
```

2024-03-25 16:37 UTC, stephengillie approved these changes

2024-03-25 16:38 UTC, merged