Move Google.NearbyShare 1.0.993.0 to Google.QuickShare 1.0.993.0
microsoft/winget-pkgs pull request #146157
Opened 2024-03-23 09:46 UTC by SpecterShell

2024-03-23 16:31 UTC, mdanish-kh approved these changes

2024-03-24 16:24 UTC, mdanish-kh approved these changes

2024-03-24 16:25 UTC, mdanish-kh commented
https://github.com/microsoft/winget-pkgs/issues/142854

2024-03-25 18:29 UTC, stephengillie requested changes

2024-03-25 18:29 UTC, stephengillie commented on manifests/g/Google/QuickShare/1.0.993.0/Google.QuickShare.installer.yaml
> +ManifestVersion: 1.4.0
```suggestion
ManifestVersion: 1.6.0
```

2024-03-25 18:29 UTC, stephengillie commented on manifests/g/Google/QuickShare/1.0.993.0/Google.QuickShare.locale.en-US.yaml
> +ManifestVersion: 1.4.0
```suggestion
ManifestVersion: 1.6.0
```

2024-03-25 18:29 UTC, stephengillie commented on manifests/g/Google/QuickShare/1.0.993.0/Google.QuickShare.locale.zh-CN.yaml
> +ManifestVersion: 1.4.0
```suggestion
ManifestVersion: 1.6.0
```

2024-03-25 18:29 UTC, stephengillie commented on manifests/g/Google/QuickShare/1.0.993.0/Google.QuickShare.yaml
> +ManifestVersion: 1.4.0
```suggestion
ManifestVersion: 1.6.0
```

2024-03-28 05:20 UTC, stephengillie approved these changes

2024-03-28 05:20 UTC, merged