New version: WatchGuardTechnologies.WatchGuardSystemManager version 1…
microsoft/winget-pkgs pull request #146230
Opened 2024-03-24 12:23 UTC by 1eyeITguy

…2.10.2.U1

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/146230)

2024-03-24 19:36 UTC, OfficialEsco requested changes

2024-03-24 19:36 UTC, OfficialEsco commented on manifests/w/WatchGuardTechnologies/WatchGuardSystemManager/12.10.2.U1/WatchGuardTechnologies.WatchGuardSystemManager.installer.yaml
> +  ProductCode: WatchGuard System Manager 12.8_is1
```suggestion
  ProductCode: WatchGuard System Manager 12.10_is1
```

2024-03-25 16:03 UTC, stephengillie commented
Hi @1eyeITguy,

> This PR's version number 1… has 1 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 12.10.2, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 873)
<!--
[Policy] Validation-Defender-Error Binary-Validation-Error Error-Analysis-Timeout Error-Hash-Mismatch Error-Installer-Availability Internal-Error Internal-Error-Dynamic-Scan Internal-Error-Manifest Internal-Error-URL Manifest-AppsAndFeaturesVersion-Error Manifest-Installer-Validation-Error Manifest-Validation-Error Possible-Duplicate PullRequest-Error URL-Validation-Error Validation-Domain Validation-Executable-Error Validation-Hash-Verification-Failed Validation-Missing-Dependency Validation-Merge-Conflict Validation-No-Executables Validation-Installation-Error Validation-Shell-Execute Validation-Unattended-Failed Policy-Test-1.2 Policy-Test-2.3 Validation-Completed Validation-Forbidden-URL-Error Validation-Unapproved-URL Validation-Retry Needs-Author-Feedback Policy-Test-2.7 Manifest-Version-Error Last-Version-Remaining[30]
[Policy] Version-Parameter-Mismatch
-->

2024-03-29 14:34 UTC, 1eyeITguy commented
Thank you for the question, and sorry I missed this and have a delayed response.   Watchguard will often put out a version number, then make updated changes to the application as Update 1, Update 2, exc.  But, in Programs and Features it will still have the version number without the update.    It's confusing.   The executable is named "wsm_12_10_2_U1.exe"

![image](https://github.com/microsoft/winget-pkgs/assets/67563275/3840b8be-fcea-4bba-98ca-ebd53c2004ad)

2024-03-29 16:35 UTC, stephengillie approved these changes

2024-03-29 16:35 UTC, merged