New package: Trimble.SketchUp.Pro.2023 version 23.1.340
microsoft/winget-pkgs pull request #146649
Opened 2024-03-27 13:28 UTC by Dragon1573

## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] There's a linked issue. Resolve #146641

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2024-03-27 14:47 UTC, sanderwi-ilionx commented
https://download.sketchup.com/SketchUpStudio-2023-1-340-117.exe

2024-03-27 15:32 UTC, stephengillie requested changes
Hi @Dragon1573,

This is probably due to an IP block of data centers, to prevent automated connections. Different companies might block with different goals - some might want to reduce network spend, while others might be trying to increase their security posture.

2024-03-27 15:32 UTC, stephengillie commented on manifests/t/Trimble/SketchUp/Pro/2023/23.1.340/Trimble.SketchUp.Pro.2023.locale.en-US.yaml
> +LicenseUrl: https://www.sketchup.com/license/b/sketchup-pro
```suggestion
PublisherUrl: https://sketchup.com/
# PublisherSupportUrl: 
# PrivacyUrl: 
Author: Trimble, Inc.
PackageName: SketchUp 2023
# PackageUrl: 
License: Proprietary
# LicenseUrl: 
```

2024-03-28 00:04 UTC, Dragon1573 reviewed
Several URLs prevent data centers from visiting the site. Just remove them from the manifest to avoid complaint by Azure Pipelines.

2024-03-28 14:28 UTC, stephengillie approved these changes

2024-03-28 14:29 UTC, stephengillie commented
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/7dca74d2-ce25-497b-934c-674e4d4a3ae8)

- https://github.com/microsoft/winget-pkgs/issues/107639

2024-03-28 14:29 UTC, merged