New package: Oven-sh.Bun version 1.1.0
microsoft/winget-pkgs pull request #147222
Opened 2024-04-01 16:40 UTC by mdanish-kh

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-04-01 17:04 UTC, sitiom commented
- Related to https://github.com/oven-sh/bun/pull/9770

2024-04-01 17:11 UTC, sitiom reviewed
As suggested by @paperdave, a CPU check like this would be nice, but I guess it's not possible with Winget yet:
```powershell
if (-not (Add-Type -MemberDefinition '[DllImport("kernel32.dll")] public static extern bool IsProcessorFeaturePresent(int ProcessorFeature);'-Name 'Kernel32'-Namespace 'Win32'-PassThru)::IsProcessorFeaturePresent(40)) {
    Write-Host -Foreground Red "This CPU does not support the AVX2 instruction set. Please install 'Oven-sh.Bun.Baseline' instead."
}
```

2024-04-01 17:17 UTC, mdanish-kh commented
> As suggested by @paperdave, a CPU check like this would be nice, but I guess it's not possible with Winget yet:
> 
> ```powershell
> if (-not (Add-Type -MemberDefinition '[DllImport("kernel32.dll")] public static extern bool IsProcessorFeaturePresent(int ProcessorFeature);'-Name 'Kernel32'-Namespace 'Win32'-PassThru)::IsProcessorFeaturePresent(40)) {
>     Write-Host -Foreground Red "This CPU does not support the AVX2 instruction set. Please install 'Oven-sh.Bun.Baseline' instead."
> }
> ```

Yes, I don't think that's possible with WinGet. We can have a note printed out after installation though that says something like:

`If you face issues running the package, it might be because your CPU does not support AVX2 instruction set. In that case, try installing Over-sh.Bun.Baseline instead.`

2024-04-01 17:33 UTC, sitiom requested changes

2024-04-01 17:33 UTC, sitiom commented on manifests/o/Oven-sh/Bun/1.1.0/Oven-sh.Bun.installer.yaml
> +  InstallerSha256: 60E9291D09657AB315BCC6BC07CBF67D2E9B9B18C21BB7CF9CE2D9FA983C9719
```suggestion
  InstallerSha256: 60E9291D09657AB315BCC6BC07CBF67D2E9B9B18C21BB7CF9CE2D9FA983C9719
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
```

2024-04-01 18:30 UTC, russellbanks approved these changes

2024-04-01 19:32 UTC, merged

2024-04-02 01:25 UTC, sitiom commented on manifests/o/Oven-sh/Bun/1.1.0/Oven-sh.Bun.installer.yaml
> +  PortableCommandAlias: bun
I forgot about this too, a `bunx` alias for `bun x` (Bun automatically detects the naming):
```suggestion
  PortableCommandAlias: bun
- RelativeFilePath: bun-windows-x64\bun.exe
  PortableCommandAlias: bunx
```

2024-04-02 01:48 UTC, sitiom commented on manifests/o/Oven-sh/Bun/1.1.0/Oven-sh.Bun.installer.yaml
> +  PortableCommandAlias: bun
- https://github.com/microsoft/winget-pkgs/pull/147295