New package: Microsoft.AzureInformationProtection version 2.18.26.0
microsoft/winget-pkgs pull request #148516
Opened 2024-04-10 15:25 UTC by Exorcism0666

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---
- Resolve #148511

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148516)

2024-04-10 23:36 UTC, Trenly requested changes

2024-04-10 23:36 UTC, Trenly commented on manifests/m/Microsoft/AzureInformationProtection/2.18.26.0/Microsoft.AzureInformationProtection.installer.yaml
> +PackageIdentifier: Microsoft.AzureInformationProtection
```suggestion
PackageIdentifier: Microsoft.Azure.InformationProtection
```
This should fall under the Azure related packages

2024-04-10 23:36 UTC, Trenly commented on manifests/m/Microsoft/AzureInformationProtection/2.18.26.0/Microsoft.AzureInformationProtection.locale.en-US.yaml
> +PackageIdentifier: Microsoft.AzureInformationProtection
```suggestion
PackageIdentifier: Microsoft.Azure.InformationProtection
```

2024-04-10 23:36 UTC, Trenly commented on manifests/m/Microsoft/AzureInformationProtection/2.18.26.0/Microsoft.AzureInformationProtection.yaml
> +PackageIdentifier: Microsoft.AzureInformationProtection
```suggestion
PackageIdentifier: Microsoft.Azure.InformationProtection
```

2024-04-10 23:36 UTC, Trenly commented on manifests/m/Microsoft/AzureInformationProtection/2.18.26.0/Microsoft.AzureInformationProtection.installer.yaml
> +  InstallerType: burn
It would be good to include the product code for the burn installer

2024-04-11 01:22 UTC, Exorcism0666 commented
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

2024-04-17 09:45 UTC, closed without merging