New package: Lime3DS.Lime3DS version 2107
microsoft/winget-pkgs pull request #148636
Opened 2024-04-11 10:04 UTC by Exorcism0666

﻿Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

* Resolves #148602

2024-04-11 14:58 UTC, Trenly requested changes
![image](https://github.com/microsoft/winget-pkgs/assets/12611259/d1266e10-19eb-4ca1-ab68-ce1521503cd3)

2024-04-11 14:58 UTC, Trenly commented on manifests/l/Lime3DS/Lime3DS/2107/Lime3DS.Lime3DS.locale.en-US.yaml
> +# Author:
```suggestion
PublisherUrl: https://github.com/Lime3DS
PublisherSupportUrl: https://github.com/Lime3DS/Lime3DS/issues
# PrivacyUrl:
# Author:
```

2024-04-11 14:58 UTC, Trenly commented on manifests/l/Lime3DS/Lime3DS/2107/Lime3DS.Lime3DS.locale.en-US.yaml
> +# PackageUrl:
```suggestion
PackageUrl: https://github.com/Lime3DS/Lime3DS
```

2024-04-11 14:58 UTC, Trenly commented on manifests/l/Lime3DS/Lime3DS/2107/Lime3DS.Lime3DS.installer.yaml
> +  InstallerSha256: 9212249DA4BEEC252A96567376C118112F19250DA9149B8658C4FD5B1E74FD99
```suggestion
  InstallerSha256: 9212249DA4BEEC252A96567376C118112F19250DA9149B8658C4FD5B1E74FD99
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
```

2024-04-12 15:46 UTC, stephengillie commented
Verify: 
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/2bc4dd26-5ce6-451c-b223-f72159675b55)

2024-04-12 15:46 UTC, stephengillie approved these changes

2024-04-12 17:25 UTC, merged