Update SQLiteStudio
microsoft/winget-pkgs pull request #148858
Opened 2024-04-12 07:48 UTC by JanWerder

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-04-12 07:49 UTC, JanWerder commented
@microsoft-github-policy-service agree

2024-04-12 07:50 UTC, JanWerder commented
> @JanWerder please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

2024-04-12 18:41 UTC, stephengillie requested changes
Hi @JanWerder,

We've depreciated this manifest version, but most fields are identical to the newest manifest version. So usually, just increasing the number is enough.

2024-04-12 18:41 UTC, stephengillie commented on manifests/s/sqlitestudio/pl/SQLiteStudio/3.4.4.0/sqlitestudio.pl.SQLiteStudio.installer.yaml
> +ManifestVersion: 1.2.0
```suggestion
ManifestVersion: 1.6.0
```

2024-04-12 18:41 UTC, stephengillie commented on manifests/s/sqlitestudio/pl/SQLiteStudio/3.4.4.0/sqlitestudio.pl.SQLiteStudio.locale.en-US.yaml
> +ManifestVersion: 1.2.0
```suggestion
ManifestVersion: 1.6.0
```

2024-04-12 18:41 UTC, stephengillie commented on manifests/s/sqlitestudio/pl/SQLiteStudio/3.4.4.0/sqlitestudio.pl.SQLiteStudio.yaml
> +ManifestVersion: 1.2.0
```suggestion
ManifestVersion: 1.6.0
```

2024-04-12 20:01 UTC, JanWerder commented
> Hi @JanWerder,
> 
> We've depreciated this manifest version, but most fields are identical to the newest manifest version. So usually, just increasing the number is enough.

Thanks! I'll try that

2024-04-13 02:21 UTC, stephengillie approved these changes

2024-04-13 02:21 UTC, merged