SpikeHD.swerve version 1.1.1
microsoft/winget-pkgs pull request #150730
Opened 2024-04-24 00:23 UTC by SpikeHD

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-04-24 00:24 UTC, SpikeHD commented
@microsoft-github-policy-service agree

2024-04-24 16:21 UTC, stephengillie commented
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\SpikeHD.swerve__DefaultSource\swerve.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\swerve.exe returned exit code: -1073741515

(Automated response - build 877.)

2024-04-24 16:41 UTC, SpikeHD commented
@stephengillie Is there any way to see more of the logs? I'd like to know why it's crashing, because that seems like a wack error code that doesn't come up anywhere when I Google it.

Also this is an application that runs indefinitely (ie until the user stops the process with Ctrl+C), in case that has anything to do with it. Verification that it works could be done with the `-h` or `-v` flags.

2024-04-24 16:47 UTC, stephengillie commented
Hi @SpikeHD,

Yeah, it's a bit of a quest. 
- Under the Details tab, click on `WinGetSvc-Validation`
- Click `View more details on Azure Pipelines`
- Under `Related`, find `4 published; 1 consumed` (The numbers might vary.)
- Find `InstallationVerificationLogs` and goto the right edge of that line. Click the 3 vertical dots.
- Click Download artifacts
- Unzip, and the contents will be the run logs. 

I wrote scripts which do this, filter for "error", "exception" and "fail", then post the results with GItHub's API.

2024-04-24 16:54 UTC, SpikeHD commented
@stephengillie Thanks! Unfortunately it was... not as helpful as I would have liked:
```
"ErrorStream": "",
"OutputStream": "",
```

As you can probably imagine, I've tested this on my own Windows 64-bit machine and it's never failed with empty logs and a exit code akin to my student loan debt, so I'm unsure where to proceed from here 😄.

2024-04-24 16:58 UTC, stephengillie commented
Manual Validation ended with:
> 
> 2024-04-24 09:58:23.278 [FAIL] Installer failed security check. Url: https://github.com/SpikeHD/swerve/releases/download/v1.1.1/swerve-x86_64-pc-windows-msvc.exe Result: 0x80004005

(Automated response - build 877.)

2024-04-24 16:58 UTC, stephengillie commented
Hi @SpikeHD,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 877.)
<!--
[Policy] Needs-Attention
[Policy] Validation-Defender-Error
-->

2024-04-24 20:20 UTC, stephengillie commented
@wingetbot run

2024-04-25 16:15 UTC, stephengillie commented
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\SpikeHD.swerve__DefaultSource\swerve.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\swerve.exe returned exit code: -1073741515

(Automated response - build 877.)

2024-04-25 16:26 UTC, stephengillie requested changes
Manual Validation ended with: 
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/14e7fa7c-f5bf-4afb-89c6-3cea78f50e91)

2024-04-25 16:26 UTC, stephengillie commented on manifests/s/SpikeHD/swerve/1.1.1/SpikeHD.swerve.installer.yaml
> +- silent
```suggestion
- silent
Dependencies:
  PackageDependencies:
     - PackageIdentifier: Microsoft.VCRedist.2015+.x64
```

2024-04-25 20:35 UTC, SpikeHD commented
Changed this to target 1.2.0, which should remove the need for VCRUNTIME140 to be installed.

2024-04-26 14:52 UTC, stephengillie commented
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\SpikeHD.swerve__DefaultSource\swerve.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\swerve.exe returned exit code: -1073741515

(Automated response - build 877.)

2024-04-26 14:54 UTC, stephengillie commented
Manual Validation ended with:
> 
> 2024-04-26 07:54:48.849 [FAIL] Installer failed security check. Url: https://github.com/SpikeHD/swerve/releases/download/v1.2.0/swerve-x86_64-pc-windows-msvc.exe Result: 0x80004005

(Automated response - build 877.)

2024-04-26 14:55 UTC, stephengillie commented
Hi @SpikeHD,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 877.)
<!--
[Policy] Needs-Attention
[Policy] Validation-Defender-Error
-->

2024-04-26 15:20 UTC, stephengillie commented
@wingetbot run

2024-04-29 16:31 UTC, SpikeHD commented
Again?? What are those error codes :sob:

2024-04-29 16:53 UTC, stephengillie requested changes
Manual Validation ended with: 
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/629b972d-7b9d-486d-a54d-ce98d141c0ea)

2024-04-29 16:53 UTC, stephengillie commented on manifests/s/SpikeHD/swerve/1.2.0/SpikeHD.swerve.installer.yaml
> +Installers:
```suggestion
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
```

2024-05-02 13:57 UTC, stephengillie approved these changes

2024-05-02 13:57 UTC, merged