New package: yuyuanweb.jianqiebanzhushou version 0.6
microsoft/winget-pkgs pull request #151152
Opened 2024-04-26 08:53 UTC by CoolPlayLin

### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 :rocket:

2024-04-26 10:22 UTC, CoolPlayLin commented
https://github.com/microsoft/winget-pkgs/labels/Validation-Domain should be dropped

2024-04-26 15:52 UTC, stephengillie requested changes
Hi @CoolPlayLin,

Should the `PackageVersion` match the Registry, or should it be added as a `DisplayVersion`?

2024-04-26 15:52 UTC, stephengillie commented on manifests/y/yuyuanweb/jianqiebanzhushou/0.6/yuyuanweb.jianqiebanzhushou.installer.yaml
> +PackageVersion: "0.6"
```suggestion
PackageVersion: 0.0.6
```
Please update file path to match this change.

2024-04-26 15:52 UTC, stephengillie commented on manifests/y/yuyuanweb/jianqiebanzhushou/0.6/yuyuanweb.jianqiebanzhushou.locale.zh-CN.yaml
> +PackageVersion: "0.6"
```suggestion
PackageVersion: 0.0.6
```
Please update file path to match this change.

2024-04-26 15:52 UTC, stephengillie commented on manifests/y/yuyuanweb/jianqiebanzhushou/0.6/yuyuanweb.jianqiebanzhushou.yaml
> +PackageVersion: "0.6"
```suggestion
PackageVersion: 0.0.6
```
Please update file path to match this change.

2024-04-27 01:52 UTC, CoolPlayLin commented
https://github.com/microsoft/winget-pkgs/labels/Validation-Domain should be dropped

2024-04-29 16:49 UTC, stephengillie commented
Verify: 
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/934d8f96-c983-43dc-a943-04f34f03db91)

2024-04-29 16:49 UTC, stephengillie approved these changes

2024-04-29 16:49 UTC, merged