New package: Inkdrop.Inkdrop version 5.8.1
microsoft/winget-pkgs pull request #154144
Opened 2024-05-18 11:08 UTC by CoolPlayLin

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-05-18 11:11 UTC, CoolPlayLin commented
Hi @craftzdog
I've made this Pull Request to add inkdrop into windows package manager! Maybe this pull request needs the approval from you, its author

2024-05-18 13:34 UTC, craftzdog requested changes
Thanks, @CoolPlayLin! I will approve it when `PublisherUrl` is updated

2024-05-18 13:34 UTC, craftzdog commented on manifests/i/Inkdrop/Inkdrop/5.8.1/Inkdrop.Inkdrop.locale.en-US.yaml
> +PublisherUrl: https://www.craftz.dog/
could you  change it to `https://www.inkdrop.app/`?

2024-05-18 13:56 UTC, CoolPlayLin commented
@craftzdog I've applied your suggestion. I shall put portable inkdrop into `Inkdrop.Inkdrop.Portable`

2024-05-18 14:01 UTC, CoolPlayLin commented
https://github.com/microsoft/winget-pkgs/labels/Validation-Domain should be wavied

2024-05-18 14:03 UTC, craftzdog approved these changes
LGTM

2024-05-18 14:10 UTC, CoolPlayLin commented
- Portable version is in #154151

2024-05-18 14:30 UTC, Trenly requested changes

2024-05-18 14:30 UTC, Trenly commented on manifests/i/Inkdrop/Inkdrop/5.8.1/Inkdrop.Inkdrop.locale.en-US.yaml
> +Publisher: Inkdrop
```suggestion
Publisher: Takuya Matsuyama
```
This should match what is written to control panel
![image](https://github.com/microsoft/winget-pkgs/assets/12611259/54923244-38d0-4e89-b969-ca674b86109e)

2024-05-18 14:30 UTC, Trenly commented on manifests/i/Inkdrop/Inkdrop/5.8.1/Inkdrop.Inkdrop.installer.yaml
> +  InstallerSha256: DCA28559B2D8151592980AA52957462526124AEC44411A205BE076ECC1F658A1
```suggestion
  InstallerSha256: DCA28559B2D8151592980AA52957462526124AEC44411A205BE076ECC1F658A1
  ProductCode: inkdrop
```

2024-05-18 14:37 UTC, Trenly approved these changes

2024-05-18 23:55 UTC, CoolPlayLin commented
https://github.com/microsoft/winget-pkgs/labels/Validation-Domain should be dropped
![image](https://github.com/microsoft/winget-pkgs/assets/96709586/24bcd245-dfdc-480f-8b9b-5da0d167b73e)

2024-05-20 01:13 UTC, craftzdog commented
Configured the proper domain for the binary distribution: `dist.inkdrop.app`

2024-05-20 17:17 UTC, stephengillie commented
> [ Validation-Domain](https://github.com/microsoft/winget-pkgs/labels/Validation-Domain) should be dropped ![image](https://private-user-images.githubusercontent.com/96709586/331837630-24bcd245-dfdc-480f-8b9b-5da0d167b73e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjU1MDcsIm5iZiI6MTcxNjIyNTIwNywicGF0aCI6Ii85NjcwOTU4Ni8zMzE4Mzc2MzAtMjRiY2QyNDUtZGZkYy00ODBmLThiOWItNWRhMGQxNjdiNzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE3MTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZDA0YTUxNGI1ZTc1NWFiNmE5NjgxY2M2OWU0ODU2OTM1YTRlZWY2ZTI3NGE5YThlOGJhMTBjYTk4Y2FmMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7rrBhA7CwaF9_1vgIZvqyehcbDxUs5xIXomJtP-gwMg)

Why should that label be dropped? The `PackageUrl` doesn't lead to the `InstallerUrl`. The image doesn't hold any data that would support this point - the existence of installer links doesn't guarantee that the `PackageUrl` will lead to them.

It appears that the developer hasn't released this version yet. It's possible that this might be a counterfeit upgrade, put out by another team to trick users into installing it.

2024-05-25 02:36 UTC, CoolPlayLin commented
Hi @stephengillie



> Configured the proper domain for the binary distribution: `dist.inkdrop.app`

Issue has been resolved

2024-05-28 20:00 UTC, stephengillie commented
I'm having difficulty getting this package to install correctly. 
- Normal install - ends with a setup error message, despite package manager reporting install complete. Shortcuts don't do anything.
- Retry with `VCRedist` - ends in normal install. Clicking shortcuts gives "This shortcut target has been removed." 

This might be a nested package, as one of the only `EXE`s it adds to the filesystem is `Setup.exe`, and after running this, Inkdrop appears to be installed.

2024-06-06 00:08 UTC, closed without merging