New package: Aakash.Swiss version 1.0.0
microsoft/winget-pkgs pull request #155220
Opened 2024-05-26 10:38 UTC by aakasheoran

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-05-26 10:46 UTC, aakasheoran commented
> @aakasheoran please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

2024-05-26 18:20 UTC, Trenly requested changes

2024-05-26 18:20 UTC, Trenly commented on manifests/a/Aakash/Swiss/1.0.0/Aakash.Swiss.installer.yaml
> +  InstallerSha256: B085F6AD8380F079C6015C5D353F5DFD72E85601744EC7F88D56B3E6A6F02329
```suggestion
  InstallerSha256: B085F6AD8380F079C6015C5D353F5DFD72E85601744EC7F88D56B3E6A6F02329
  Dependencies:
    PackageDependencies:
      - PackageIdentifier: Microsoft.VCRedist.2015+.x64
```

![image](https://github.com/microsoft/winget-pkgs/assets/12611259/fc439f1a-af98-4ff7-8a7d-4fdee3a9dfe6)

2024-05-28 16:28 UTC, stephengillie commented
This package doesn't respond to most commands, but the [source](https://github.com/aakasheoran/swiss/blob/main/src/main.rs) reveals `-v` gives version data, and `cat` is the main command to interact.

2024-05-28 16:29 UTC, stephengillie approved these changes

2024-05-28 16:29 UTC, merged

2024-05-28 18:12 UTC, aakasheoran commented
@stephengillie I will be updating the cli in future versions to provide more descriptive usage info and support for help command.
May you let me know what commands you're referring to here: `This package doesn't respond to most commands`?
It would be helpful for me and the users of the cli tool as well.

2024-05-28 18:45 UTC, stephengillie commented
Hi @aakasheoran,

CLI applications frequently have a `/?` or `--help` or similar command, which displays other commands that can be used.

2024-05-29 01:05 UTC, aakasheoran commented
Yeah @stephengillie thanks, I will be adding it in future updates.