New version: LightBurnSoftware.LightBurn version 1.6.0
microsoft/winget-pkgs pull request #155297
Opened 2024-05-27 12:27 UTC by J3n50m4t

### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 :rocket:

2024-05-27 12:30 UTC, J3n50m4t commented
@microsoft-github-policy-service agree

2024-05-28 10:00 UTC, J3n50m4t commented
Unsure what to do. 
/SUPPRESSMSGBOXES in the verysilent? 
Install works on my machine with with local manifest without interaction (with progress) - exactly as 1.4.0 was.

2024-05-29 23:15 UTC, stephengillie requested changes
Hi @J3n50m4t,

Our `x86` validations are performed on 32-bit OSes. This application appears to be 64-bit only.

2024-05-29 23:15 UTC, stephengillie commented on manifests/l/LightBurnSoftware/LightBurn/1.6.0/LightBurnSoftware.LightBurn.installer.yaml
> +  InstallerSha256: 27FC656AE07394CBD5E5217C04BE516AB7F4646F052FBE14C87D9B6A595CE4B1
```suggestion
```

2024-06-03 20:21 UTC, stephengillie approved these changes

2024-06-03 20:21 UTC, merged