New package: Opsfolio.Surveilr version 0.9.0
microsoft/winget-pkgs pull request #155614
Opened 2024-05-29 17:29 UTC by Lilit0x

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-05-29 17:47 UTC, stephengillie commented
Hi @Lilit0x,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 881.)
<!--
[Policy] Needs-Attention
[Policy] Validation-Defender-Error
-->

2024-05-29 17:47 UTC, stephengillie commented
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-29 15:20:10.767 [FAIL] Installer failed security check. Url: https://github.com/opsfolio/releases.opsfolio.com/releases/download/0.9.0/surveilr.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 881.)

2024-05-29 17:54 UTC, Lilit0x commented
@microsoft-github-policy-service agree [company="{Opsfolio}"]

2024-05-29 17:55 UTC, Lilit0x commented
@microsoft-github-policy-service agree company="Opsfolio"

2024-05-29 22:50 UTC, stephengillie commented
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-29 12:53:01.666 [FAIL] Installer failed security check. Url: https://github.com/opsfolio/releases.opsfolio.com/releases/download/0.9.0/surveilr.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. `n`n<!-- [Policy] Needs-Attention`n[Policy] Validation-Defender-Error -->

(Automated response - build 881.)

2024-05-31 16:16 UTC, stephengillie commented
@wingetbot run

2024-07-15 18:01 UTC, stephengillie commented
Automatic Validation ended with:
> ADO Build not found.

(Automated response - build 886.)

2024-07-15 18:01 UTC, stephengillie commented
/azp run

2024-07-16 15:36 UTC, stephengillie commented
/azp run

2024-07-17 03:10 UTC, stephengillie commented
Automatic Validation ended with:


(Automated response - build 886.)

2024-07-17 03:18 UTC, stephengillie requested changes
Hi @Lilit0x,

![image](https://github.com/user-attachments/assets/8adb8305-dfd3-4d15-accb-81d07a46cbba)

This appaers to be version `0.9.1`. (The package manager adds the Registry entry for portable applications.)

2024-07-17 03:18 UTC, stephengillie commented on manifests/o/Opsfolio/Surveilr/0.9.0/Opsfolio.Surveilr.installer.yaml
> +PackageVersion: 0.9.0
```suggestion
PackageVersion: 0.9.1
```
Please update file path to match this change.

2024-07-17 03:18 UTC, stephengillie commented on manifests/o/Opsfolio/Surveilr/0.9.0/Opsfolio.Surveilr.locale.en-US.yaml
> +PackageVersion: 0.9.0
```suggestion
PackageVersion: 0.9.1
```
Please update file path to match this change.

2024-07-17 03:18 UTC, stephengillie commented on manifests/o/Opsfolio/Surveilr/0.9.0/Opsfolio.Surveilr.yaml
> +PackageVersion: 0.9.0
```suggestion
PackageVersion: 0.9.1
```
Please update file path to match this change.

2024-07-25 08:31 UTC, closed without merging