AudibleInc.AudibleSync version 1.8.8
microsoft/winget-pkgs pull request #15604
Opened 2021-06-01 19:46 UTC by BattlemasterLoL

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-06-02 00:58 UTC, jedieaston requested changes

2021-06-02 00:58 UTC, jedieaston commented on manifests/a/AudibleInc/AudibleSync/1.8.8/AudibleInc.AudibleSync.installer.yaml
> +  InstallerSha256: BA1228FB9E37D142700EF63A6CBB838B97E3745057E39B4D6B9086364D3167E9
```suggestion
  InstallerSha256: BA1228FB9E37D142700EF63A6CBB838B97E3745057E39B4D6B9086364D3167E9
  InstallerSwitches: 
      Silent: " "
      SilentWithProgress: " "
```
To stop the warning for `winget validate`.

2021-06-03 16:11 UTC, msftrubengu commented
/azp run

2021-06-03 20:58 UTC, ItzLevvie requested changes

2021-06-03 20:58 UTC, ItzLevvie commented on manifests/a/AudibleInc/AudibleSync/1.8.8/AudibleInc.AudibleSync.installer.yaml
> +PackageIdentifier: AudibleInc.AudibleSync
```suggestion
PackageIdentifier: Audible.AudibleSync
```

2021-06-03 20:58 UTC, ItzLevvie commented on manifests/a/AudibleInc/AudibleSync/1.8.8/AudibleInc.AudibleSync.yaml
> +PackageIdentifier: AudibleInc.AudibleSync
```suggestion
PackageIdentifier: Audible.AudibleSync
```

2021-06-03 20:58 UTC, ItzLevvie commented on manifests/a/AudibleInc/AudibleSync/1.8.8/AudibleInc.AudibleSync.locale.en-US.yaml
> +PackageIdentifier: AudibleInc.AudibleSync
```suggestion
PackageIdentifier: Audible.AudibleSync
```

2021-06-03 20:58 UTC, ItzLevvie commented on manifests/a/AudibleInc/AudibleSync/1.8.8/AudibleInc.AudibleSync.locale.en-US.yaml
> +ShortDescription: AudibleSync
```suggestion
ShortDescription: The AudibleSync app is a Windows 10 app for your computer that allows for quick and easy downloading of your titles.
```

2021-06-03 23:32 UTC, ItzLevvie requested changes
You also have to use the GitHub client to change the folder name and the file names.

2021-06-04 14:50 UTC, closed without merging