New package: Audiveris.Audiveris version 5.3.1
microsoft/winget-pkgs pull request #156131
Opened 2024-06-01 13:47 UTC by Exorcism0666

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-06-02 01:31 UTC, Exorcism0666 commented
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

2024-06-03 23:26 UTC, stephengillie commented
Automatic Validation ended with:


(Automated response - build 882.)

2024-06-04 00:08 UTC, Trenly requested changes

2024-06-04 00:08 UTC, Trenly commented on manifests/a/Audiveris/Audiveris/5.3.1/Audiveris.Audiveris.locale.en-US.yaml
> +Publisher: Audiveris
```suggestion
Publisher: Audiveris Team
```
This should match control panel

2024-06-04 00:08 UTC, Trenly commented
> Is there an installer switch to bypass this message?

It doesn't look like there is
https://github.com/Audiveris/audiveris/blob/2dedb99bc16b521e9e9c85e6be6ae8a9bb22c578/dev/installer-windows/Installer.nsi#L96

[Policy] Interactive Only

2024-06-10 22:02 UTC, stephengillie commented
Automatic Validation ended with:
> No errors to post.

(Automated response - build 884.)

2024-06-10 22:03 UTC, stephengillie commented
> Automatic Validation ended with: Edit: ![image](https://private-user-images.githubusercontent.com/114952565/336255782-35a2f73e-083f-4eb4-b108-c7119477f0dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNTcyNjcsIm5iZiI6MTcxODA1Njk2NywicGF0aCI6Ii8xMTQ5NTI1NjUvMzM2MjU1NzgyLTM1YTJmNzNlLTA4M2YtNGViNC1iMTA4LWM3MTE5NDc3ZjBkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQyMjAyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTNkYzAzZTliMzE0ZmNkZTdiYzE3ZDQ2Mjk4ZTdkOTg4NzU3NTdiNGUxYmE5NjhmYjdkNTE4ZmNkMGFjYmM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1zoaecT0OxjUOgXvxwcZxnzKR1J8mdHhUarogAb6LF0)
> 
> Hi @Exorcism0666,
> 
> Is there an installer switch to bypass this message?

This is unchanged.

2024-06-19 03:24 UTC, closed without merging