New package: ElementTechnologie.openElement version 1.57.9
microsoft/winget-pkgs pull request #156187
Opened 2024-06-02 06:32 UTC by Exorcism0666

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-06-03 01:26 UTC, Exorcism0666 commented
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

2024-06-03 16:14 UTC, stephengillie commented
HI @Exorcism0666,

This appears to be a nested installer - running the application opens an installer window: 
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/99847026-ae0f-4b3d-9e46-2e3fe0eac419)

2024-06-03 21:22 UTC, Exorcism0666 commented
@Dragon1573 a little help wouldn't go amiss :)

2024-06-04 03:59 UTC, Dragon1573 commented
@Exorcism0666 - _Komac_ also regard this package as a portable executable.

Try manually run the installer file with `/?` switch, the following dialog shows.

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/03019a46-0c38-45e6-9657-a0dd766afdee)

2024-06-04 06:23 UTC, SpecterShell commented
Advanced Installer

2024-06-04 08:44 UTC, Dragon1573 requested changes
Suggestions were tested in `amd64` Windows Sandbox instance.

2024-06-04 08:44 UTC, Dragon1573 commented on manifests/e/ElementTechnologie/openElement/1.57.9/ElementTechnologie.openElement.installer.yaml
> +InstallerType: portable
```suggestion
InstallerType: exe
```

This is an installer wizard created by _Advanced Installer_. It's not a portable executable.

2024-06-04 08:44 UTC, Dragon1573 commented on manifests/e/ElementTechnologie/openElement/1.57.9/ElementTechnologie.openElement.installer.yaml
> +  InstallerSha256: 22F33F86128B59D3911702150EDA6438C2275065C765EE550491A601FF568AE6
```suggestion
  InstallerSha256: 22F33F86128B59D3911702150EDA6438C2275065C765EE550491A601FF568AE6
  InstallerLocale: en-US
  InstallerSwitches:
    Custom: /exelang 1033 /exenoui /qn
    InstallLocation: '/extract:<INSTALLPATH>'
    Log: /exelog <LOGPATH>
```

- This package contains both English (language ID `1033`) and French (language ID `1036`) profile.
- `InstallerSwitches` can be found by adding `/?` switch to the installer file.

2024-06-09 12:05 UTC, Dragon1573 approved these changes
Verified in _Windows Sandbox_.

More tests should be performed by moderators.

2024-06-10 22:59 UTC, stephengillie commented
Verify: 
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/ad91f5d7-7e18-46f8-96a7-6f86db355b77)
- I might have lost Internet (hotspot hiccup) during the install process - would that result in this error? Is it a local page that's downloaded durng install? Because it persists despite having a solid network connection.

![image](https://github.com/microsoft/winget-pkgs/assets/114952565/1b3352c0-23ad-4883-98e8-0f6b971289d7)

2024-06-11 14:14 UTC, Dragon1573 commented
This can be reproduced on my _Windows Sandbox_ instance.

For some well-known reason, I'm behind a proxy. Even though my proxy is enabled and valid, I cant' load that page either.

On the screen it says "Internet connection is not required", so I think this situation is acceptable.

2024-06-11 17:58 UTC, stephengillie approved these changes

2024-06-11 17:58 UTC, merged