Burnaware.BurnAwareFree version 14.4.0.0
microsoft/winget-pkgs pull request #15660
Opened 2021-06-01 22:33 UTC by igorskyflyer

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-06-02 00:40 UTC, jedieaston requested changes
One quick thing, good job otherwise.

2021-06-02 00:40 UTC, jedieaston commented on manifests/b/Burnaware/BurnAwareFree/14.4.0.0/Burnaware.BurnAwareFree.locale.en-US.yaml
> +PackageName: BurnAware Free
```suggestion
PackageName: BurnAware Free 14.4 

```

To match the ARP table. Otherwise, LGTM!

2021-06-02 01:42 UTC, jedieaston commented
This probably won't work, but....

/azp run

2021-06-03 00:20 UTC, denelon commented
/azp run

2021-06-03 00:21 UTC, denelon commented
@jedieaston we're building a PR scanner to kick builds off when something like this happens. Different retry logic per failure type. I'm only 23 hours behind on my GitHub inbox now 🥇.

Thanks for all of your help and support!

2021-06-03 00:49 UTC, jedieaston commented
@denelon No problem, happy to help!

2021-06-03 20:48 UTC, ItzLevvie approved these changes

2021-06-03 20:48 UTC, merged