Logitech.SetPoint version 6.70.55
microsoft/winget-pkgs pull request #15688
Opened 2021-06-02 01:48 UTC by GearFlame

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-06-02 03:21 UTC, ranm-msft commented
/azp run

2021-06-03 16:10 UTC, msftrubengu commented
/azp run

2021-06-03 21:02 UTC, ItzLevvie requested changes

2021-06-03 21:02 UTC, ItzLevvie commented on manifests/l/Logitech/SetPoint/6.70.55/Logitech.SetPoint.locale.en-US.yaml
> +License: Copyright C 2005-2019 Logitech. All Rights Reserved
```suggestion
License: Copyright (c) 2005-2019 Logitech. All Rights Reserved.
```

2021-06-03 21:02 UTC, ItzLevvie commented on manifests/l/Logitech/SetPoint/6.70.55/Logitech.SetPoint.locale.en-US.yaml
> +PackageName: SetPoint
```suggestion
PackageName: Logitech SetPoint
```

2021-06-03 21:02 UTC, ItzLevvie commented on manifests/l/Logitech/SetPoint/6.70.55/Logitech.SetPoint.locale.en-US.yaml
> +ShortDescription: SetPoint lets you customize your mouse, keyboard, touchpad and number pad settings in Windows.
```suggestion
ShortDescription: Logitech SetPoint lets you customize your mouse, keyboard, touchpad and number pad settings in Windows.
```

2021-06-03 21:02 UTC, ItzLevvie requested changes

2021-06-03 21:02 UTC, ItzLevvie commented on manifests/l/Logitech/SetPoint/6.70.55/Logitech.SetPoint.locale.en-US.yaml
> +Publisher: Logitech Inc.
```suggestion
Publisher: Logitech
```

2021-06-04 17:23 UTC, OfficialEsco approved these changes

2021-06-04 17:23 UTC, merged