Msodbcsql18 manifest
microsoft/winget-pkgs pull request #156805
Opened 2024-06-06 18:25 UTC by v-ancha

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-06-06 20:22 UTC, Trenly requested changes

2024-06-06 20:22 UTC, Trenly commented on manifests/m/Microsoft/msodbcsql/18.3.3.1/Microsoft.msodbcsql.locale.en-US.yaml
> +License: Copyright (c) Microsoft Corporation
A copyright isn't a license; Please update this with actual license terms such as Proprietary, MIT, GPL-2.0, or other terms as appropriate

2024-06-06 20:22 UTC, Trenly commented on manifests/m/Microsoft/msodbcsql/18.3.3.1/Microsoft.msodbcsql.installer.yaml
> +      Silent: /quiet IACCEPTMSODBCSQLLICENSETERMS=YES
Because this is an agreement being passed without user knowledge, you will need to include the `Agreements` field in the manifest's Locale files

2024-06-06 20:22 UTC, Trenly commented on manifests/m/Microsoft/msodbcsql/18.3.3.1/Microsoft.msodbcsql.installer.yaml
> +PackageIdentifier: Microsoft.msodbcsql
Please include the YAML schema headers in each manifest file.

Example:
```YAML
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
```

2024-06-06 20:24 UTC, Trenly commented
Looks like the https://github.com/microsoft/winget-pkgs/labels/Validation-Shell-Execute is due to missing dependencies:
> MSI (s) (A8:9C) [15:21:20:626]: Product: Microsoft ODBC Driver 18 for SQL Server -- Error 1723. Please install the Visual C++ 2017 Redistributable from https://aka.ms/vs/15/release/vc_redist.x64.exe before running this installer. Action IsPendingRebootKey, entry: IsPendingReboot, library: C:\Windows\Installer\MSIBF68.tmp

2024-06-07 17:18 UTC, v-ancha commented
@Trenly Is having the vcredist as a dependency supported yet?

2024-06-13 02:20 UTC, stephengillie commented
Automatic Validation ended with:

> 2024-06-12 16:29:24.587 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.40.33807.0
> 2024-06-12 15:49:14.027 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x86 with version 14.38.33135.0

(Automated response - build 885.)

2024-06-13 03:04 UTC, Trenly commented
> Automatic Validation ended with:
> 
> > 2024-06-12 16:29:24.587 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.40.33807.0
> > 2024-06-12 15:49:14.027 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x86 with version 14.38.33135.0
> 
> (Automated response - build 885.)

* https://github.com/microsoft/winget-pkgs/issues/152555

2024-06-13 21:07 UTC, stephengillie commented
Automatic Validation ended with:

> 2024-06-13 12:51:29.872 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.40.33807.0
> 2024-06-13 12:51:41.323 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x86 with version 14.38.33135.0

(Automated response - build 885.)

2024-06-18 18:13 UTC, v-ancha commented
@Trenly @stephengillie These install fine on a clean machine for both the dependencies and the actual intended package itself using winget. Is there something else to check to see why validation isn't being passed?

2024-06-18 18:39 UTC, Trenly commented
The issue is that VCRedist only has `Scope: machine` installers, so when the pipelines attempt to validate that this submission can install with the `Scope: user` you specified they detect that there are no VCRedist installers that can satisfy the requirement

2024-06-19 23:52 UTC, stephengillie commented
Automatic Validation ended with:

> 2024-06-18 16:55:04.050 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.40.33807.0
> 2024-06-18 16:54:41.979 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x86 with version 14.38.33135.0

(Automated response - build 886.)

2024-06-24 17:50 UTC, v-ancha commented
The package and its dependencies install and validate properly in testing on a clean machine using winget. Seems like an issue in the validation pipeline as linked in comments above is what we need to wait on.

2024-07-05 15:28 UTC, stephengillie commented
Hi @v-ancha,

Sorry for the delayed reply. I believe that these might be far enough along in the pipeline for me to manually complete.

2024-07-05 15:36 UTC, stephengillie commented
@wingetbot waivers Add Validation-Installation-Error

2024-07-05 17:16 UTC, stephengillie commented
Verify:
(Stitched image, please excuse the duplicated buttons and tabs.)
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/43509be2-782b-4eaa-8682-0b8b19eb26d2)
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/d4e96e0b-de57-4672-be33-5390d11f9cac)

2024-07-05 17:31 UTC, stephengillie approved these changes

2024-07-05 17:31 UTC, merged