New package: yuk7.ArchWSL version 24.4.28.0
microsoft/winget-pkgs pull request #157014
Opened 2024-06-07 18:15 UTC by vikingnope

### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 :rocket:

2024-06-07 21:59 UTC, stephengillie commented
Automatic Validation ended with:


(Automated response - build 884.)

2024-06-07 22:24 UTC, stephengillie requested changes
Hi @vikingnope,

Manual Validation ended with:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/c382e680-cfd0-4f77-995d-ec5c3d2c2ed9)

I'm not sure why the application isn't picking up the dependency, but I believe this dependency has another way to be installed. 

Edit: The error code is WSL-specific:
```PowerShell
PS C:\ManVal> winget error 0x8007019E
0x8007019e
The Windows Subsystem for Linux has not been enabled.
```

2024-06-07 22:25 UTC, stephengillie commented on manifests/y/yuk7/ArchWSL/24.4.28.0/yuk7.ArchWSL.installer.yaml
> +  - PackageIdentifier: Microsoft.WSL
```suggestion
  WindowsFeatures:
  - Microsoft-Windows-Subsystem-Linux
```
I forgot to hit "Start a revew".

2024-06-11 00:20 UTC, stephengillie commented
@wingetbot run

2024-06-11 23:20 UTC, stephengillie commented
@wingetbot run

2024-06-12 00:08 UTC, stephengillie commented
Manual Validation ended with:
> 
> 2024-06-11 17:06:55.964 [CORE] Enabling Windows Feature [Microsoft-Windows-Subsystem-Linux] 
> 2024-06-11 17:06:55.964 [CLI ] Starting: 'C:\Windows\System32\Dism.exe' with arguments '/Online /Enable-Feature /NoRestart /FeatureName:Microsoft-Windows-Subsystem-Linux' 
> 2024-06-11 17:07:21.836 [CORE] Failed to enable Windows Feature [Microsoft-Windows-Subsystem-Linux] with exit code: 14081 
> 2024-06-11 17:07:21.837 [CLI ] Terminating context: 0x8a150110 at C:\__w\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DependenciesFlow.cpp:d4  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean  

Automated error analysis suggests  may mean 

(Automated response - build 884.)

2024-07-05 15:29 UTC, stephengillie commented
Apologies - we're working through some ephemeral capacity issues for the validation pipeilne.

2024-07-05 15:29 UTC, stephengillie commented
/azp run

2024-07-05 15:37 UTC, vikingnope commented
No problem, just wanted to make sure it wasn't an issue from my end

2024-07-09 16:50 UTC, hackean-msft commented
/azp run

2024-07-10 20:54 UTC, stephengillie commented
/azp run

2024-07-13 00:11 UTC, stephengillie commented
/azp run

2024-07-15 19:16 UTC, stephengillie commented
Manual Validation ended with:
> 12:02:37 PM: 
> 2024-07-15 12:02:37.326 [CORE] Failed to enable Windows Feature [Microsoft-Windows-Subsystem-Linux] with exit code: 14081

Automated error analysis suggests 14081 may mean The referenced assembly could not be found. Is a dependency missing?

(Automated response - build 886.)

2024-07-15 19:24 UTC, vikingnope commented
> Manual Validation ended with:
> 
> > 12:02:37 PM:
> > 2024-07-15 12:02:37.326 [CORE] Failed to enable Windows Feature [Microsoft-Windows-Subsystem-Linux] with exit code: 14081
> 
> Automated error analysis suggests 14081 may mean The referenced assembly could not be found. Is a dependency missing?
> 
> (Automated response - build 886.)

Doesn't seem to be

![image](https://github.com/user-attachments/assets/cde8eac4-e4af-4a09-9ca0-74488f476e6e)

2024-07-19 16:22 UTC, vikingnope commented
> This might be due to both the validation pipeline VMs, and my VMs, both having an issue enabling WSL.

Ah yes I think so

2024-08-01 00:49 UTC, hackean-msft commented
/azp run

2024-08-01 15:50 UTC, vikingnope commented
Are we able to merge this @stephengillie?

2024-08-01 16:13 UTC, stephengillie commented
> Are we able to merge this @stephengillie?

I don't have enough information at this time to give a valid answer. I do not know when this situation will change.

2024-08-06 01:20 UTC, stephengillie commented
/azp run

2024-08-06 13:20 UTC, stephengillie commented
/azp run

2024-08-07 18:20 UTC, stephengillie commented
/azp run

2024-08-08 18:20 UTC, stephengillie commented
/azp run

2024-08-15 00:15 UTC, stephengillie commented
Manually enabling WSL gives:
![Uploading image.png…]()

2024-08-15 07:41 UTC, vikingnope commented
> Manually enabling WSL gives: ![image](https://private-user-images.githubusercontent.com/114952565/358042343-14af7628-9dad-4f7f-80e5-4cc6d0590da7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDc5NjUsIm5iZiI6MTcyMzcwNzY2NSwicGF0aCI6Ii8xMTQ5NTI1NjUvMzU4MDQyMzQzLTE0YWY3NjI4LTlkYWQtNGY3Zi04MGU1LTRjYzZkMDU5MGRhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNzQxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTE1ZjU1NWEwMGJiZGU2ZGQxZWE5MGU4OTVhZmQ1Zjc1YTlhY2I0MjI3ZDFkYmM5ODhiZmIwNzlmZmRiNzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1fDo3Kv-HnQCCv1Lam-s_sjAXsNxDOZrADaePAnHIqQ)


Is this on a VM or an actual windows build?

2024-08-15 19:07 UTC, stephengillie commented
> Is this on a VM or an actual windows build?

VM downloaded from Hyper-V Quick Create. Unforunately, we don't currently have any bare metal testing systems.

2024-08-15 20:26 UTC, vikingnope commented
> > Is this on a VM or an actual windows build?
> 
> VM downloaded from Hyper-V Quick Create. Unforunately, we don't currently have any bare metal testing systems.

I am 99.9% sure that that is the issue because I am pretty sure you cannot have WSL running on a hypervisor since there is no pass through of virtualization from the CPU directly on hypervisors. (or at least that how I think it works), so for now maybe mark this as blocked?

2024-09-07 11:06 UTC, ItzLevvie commented
@wingetbot run

2024-09-07 13:05 UTC, ItzLevvie commented
[Policy] Blocking-Issue

2024-09-13 10:50 UTC, closed without merging