Fix: Discord.Discord version 1.0.9144
microsoft/winget-pkgs pull request #157519
Opened 2024-06-12 06:09 UTC by seangibbz

Checklist for Pull Requests
- [Y] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [N] Is there a linked Issue?
	- https://github.com/microsoft/winget-pkgs/issues/137934
	- https://github.com/microsoft/winget-pkgs/issues/137157
	- https://github.com/microsoft/winget-pkgs/issues/136960

Manifests
- [Y] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [Y] This PR only modifies one (1) manifest
- [Y] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [Y] Have you tested your manifest locally with `winget install --manifest <path>`?
- [Y] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-06-12 15:01 UTC, stephengillie requested changes
The `\hc\en-us` usually indicates that the developer is using the ZenDesk Help Center, and unfortunately they've blocked our automated scans.

2024-06-12 15:01 UTC, stephengillie commented on manifests/d/Discord/Discord/1.0.9144/Discord.Discord.locale.en-US.yaml
> +CopyrightUrl: https://support.discord.com/hc/articles/4410331.0.9341.0.9655
```suggestion
# CopyrightUrl: 
```

2024-06-12 15:01 UTC, stephengillie commented on manifests/d/Discord/Discord/1.0.9144/Discord.Discord.locale.en-US.yaml
> +  DocumentUrl: https://support.discord.com/hc/en-us
```suggestion
  # DocumentUrl: 
```

2024-06-13 18:18 UTC, stephengillie requested changes
https://github.com/microsoft/winget-pkgs/pull/157519#pullrequestreview-2113319944

2024-06-13 18:18 UTC, stephengillie commented on manifests/d/Discord/Discord/1.0.9144/Discord.Discord.locale.pt-BR.yaml
> +  DocumentUrl: https://support.discord.com/hc/en-us
```suggestion
 # DocumentUrl: 
```

2024-06-13 18:18 UTC, stephengillie commented on manifests/d/Discord/Discord/1.0.9144/Discord.Discord.locale.zh-CN.yaml
> +CopyrightUrl: https://support.discord.com/hc/articles/4410331.0.9341.0.9655
```suggestion
# CopyrightUrl:
```

2024-06-14 17:10 UTC, stephengillie commented
> [#157519 (review)](https://github.com/microsoft/winget-pkgs/pull/157519#pullrequestreview-2113319944)

2024-06-15 06:02 UTC, seangibbz reviewed
hc urls removed

2024-06-17 22:52 UTC, stephengillie approved these changes

2024-06-17 22:52 UTC, merged