SimpleLedger.ElectronCashSLP version 3.6.6
microsoft/winget-pkgs pull request #15889
Opened 2021-06-02 22:04 UTC by mcastiglia

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-06-02 22:40 UTC, OfficialEsco requested changes
Wait is SLP a different version?
`Publisher: Electron Cash LLC` ❌
`PackageName: Electron Cash SLP` ✔
You can add `Author: Simple Ledger`
`Architecture` seems to be `neutral` in this version

2021-06-02 23:27 UTC, mcastiglia commented
SLP is a completely different version that was forked from the main project due to the wait to include support for SLP tokens. Yes, it includes the base code, but it has been forked for a while and is maintained by (mostly) different people.
It's also released on a different site (https://simpleledger.cash) than the vanilla version (https://electroncash.org). They also have separate support channels.
I can still change this if you prefer, but I just wanted to tell you about the differences.

2021-06-03 09:46 UTC, OfficialEsco requested changes
![image](https://user-images.githubusercontent.com/15158490/120624829-5e6cea00-c461-11eb-8d7e-82b6cea9dbcb.png)

2021-06-03 11:56 UTC, OfficialEsco approved these changes

2021-06-03 11:57 UTC, merged