Fix DevToys 2.0.1
microsoft/winget-pkgs pull request #159613
Opened 2024-06-24 15:32 UTC by stephengillie

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?
https://github.com/DevToys-app/DevToys/issues/1257

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

2024-06-25 03:16 UTC, aisgbnok approved these changes
Matches ARP

```
DisplayName    : DevToys Preview version 2.0-preview.1
DisplayVersion : 2.0-preview.1
Publisher      : DevToys
ProductCode    : DevToys Preview_is1
Scope          : User
```

2024-06-25 04:06 UTC, Trenly requested changes
Publisher field in manifest does not match ARP

2024-06-25 15:32 UTC, stephengillie commented on manifests/d/DevToys-app/DevToys/2.0-preview.1/DevToys-app.DevToys.locale.en-US.yaml
>  Publisher: DevToys-app
Thank you for the clear disambiguation of ARP.

2024-06-26 04:01 UTC, Trenly approved these changes

2024-06-26 04:02 UTC, merged