Added GitHub CLI version 1.11.0.
microsoft/winget-pkgs pull request #16031
Opened 2021-06-03 18:20 UTC by jedieaston

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

2021-06-03 18:55 UTC, ItzLevvie requested changes

2021-06-03 18:55 UTC, ItzLevvie commented on manifests/g/GitHub/cli/1.11.0/GitHub.cli.locale.en-US.yaml
> +Publisher: Github, Inc.
```suggestion
Publisher: GitHub, Inc.
```
![image](https://user-images.githubusercontent.com/11600822/120697338-7fefc500-c4a5-11eb-9b30-1463f92f63cc.png)

2021-06-03 18:55 UTC, ItzLevvie commented on manifests/g/GitHub/cli/1.11.0/GitHub.cli.locale.en-US.yaml
> +Author: Github, Inc.
```suggestion
Author: GitHub, Inc.
```

2021-06-03 20:28 UTC, jedieaston commented
Thanks!

2021-06-04 16:30 UTC, OfficialEsco approved these changes

2021-06-04 16:31 UTC, merged