New package: Jingque.Fanyiniao version 2.2.0
microsoft/winget-pkgs pull request #160616
Opened 2024-06-29 00:39 UTC by SpecterShell

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-06-29 04:20 UTC, stephengillie commented
Automatic Validation ended with:

> Installation failed with exit code -1978335141
> 2024-06-29 00:51:16.708 [CLI ] Unable to locate nested installer at: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Jingque.Fanyiniao.2.2.0\extracted\翻译鸟.exe

Automated error analysis suggests -1978335141 may mean Unable to locate nested installer. Does the `RelativeFilePath` have the previous version number in it?

(Automated response - build 886.)

2024-07-04 11:37 UTC, SpecterShell commented
> Automatic Validation ended with:
> 
> > Installation failed with exit code -1978335141
> > 2024-06-29 00:51:16.708 [CLI ] Unable to locate nested installer at: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Jingque.Fanyiniao.2.2.0\extracted\翻译鸟.exe
> 
> Automated error analysis suggests -1978335141 may mean Unable to locate nested installer. Does the `RelativeFilePath` have the previous version number in it?
> 
> (Automated response - build 886.)

The `RelativeFilePath` is correct. Is it an encoding issue that the filename in the zip file is not properly interpreted?

2024-07-04 23:31 UTC, ItzLevvie approved these changes

2024-07-05 18:16 UTC, stephengillie requested changes
Hi @SpecterShell,

Manual Validation also ended with:
> 
> > Installation failed with exit code -1978335141
> > 2024-06-29 00:51:16.708 [CLI ] Unable to locate nested installer at: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Jingque.Fanyiniao.2.2.0\extracted\翻译鸟.exe

The name appears to misencode into `τ┐╗Φ»æΘ╕ƒ`. 

Verify:
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/09319ce8-0762-4a05-ab97-c6df1110afb0)

But when replacing the characters with their misencoding, the package manager is able to find the nested installer file. This isn't the best solution - how should this PR proceed?

2024-07-05 18:16 UTC, stephengillie commented on manifests/j/Jingque/Fanyiniao/2.2.0/Jingque.Fanyiniao.installer.yaml
> +  - RelativeFilePath: 翻译鸟.exe
```suggestion
  - RelativeFilePath: τ┐╗Φ»æΘ╕ƒ.exe
```

2024-07-06 10:13 UTC, SpecterShell commented
> Hi @SpecterShell,
> 
> Manual Validation also ended with:
> 
> > > Installation failed with exit code -1978335141
> > > 2024-06-29 00:51:16.708 [CLI ] Unable to locate nested installer at: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Jingque.Fanyiniao.2.2.0\extracted\翻译鸟.exe
> 
> The name appears to misencode into `τ┐╗Φ»æΘ╕ƒ`.
> 
> Verify: ![image](https://private-user-images.githubusercontent.com/114952565/346198209-09319ce8-0762-4a05-ab97-c6df1110afb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNjA5OTQsIm5iZiI6MTcyMDI2MDY5NCwicGF0aCI6Ii8xMTQ5NTI1NjUvMzQ2MTk4MjA5LTA5MzE5Y2U4LTA3NjItNGEwNS1hYjk3LWM2ZGYxMTEwYWZiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxMDExMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTZlMDYzOTJjN2IyYzlhZGRhN2I0ZjE1MzdiMzhjYzJmMzExNDJjY2QyYWMyOWQzYjJlOGExMGY4YzVjMDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iy7WzFWb7Tu0WKDsukWTd_m8AlZGBU8FGkr2QiIsM5c)
> 
> But when replacing the characters with their misencoding, the package manager is able to find the nested installer file. This isn't the best solution - how should this PR proceed?

This might be a filename encoding issue of the zip archive. I would prefer to close the PR as it may result in errors on devices with different administrative locales.

2024-07-06 10:13 UTC, closed without merging