New package: Alteri.Avalon.Client version 2024.3.1
microsoft/winget-pkgs pull request #161194
Opened 2024-07-02 22:50 UTC by pythion

2024-07-02 23:38 UTC, pythion commented
@microsoft-github-policy-service agree

2024-07-03 02:21 UTC, stephengillie commented
/azp run

2024-07-03 22:48 UTC, hackean-msft commented
/azp run

2024-07-10 20:57 UTC, stephengillie commented
/azp run

2024-07-11 21:03 UTC, stephengillie commented
/azp run

2024-07-13 00:18 UTC, stephengillie commented
Hi @pythion,

Could you add a `PackageUrl`?

2024-07-15 18:13 UTC, stephengillie requested changes
Hi @pythion,

The `PackageUrl` should be a website eventually leading to the `InstallerUrl`.

2024-07-15 18:13 UTC, stephengillie commented on manifests/a/Alteri/Avalon/Client/2024.3.1/Alteri.Avalon.Client.locale.en-US.yaml
> +PackageUrl: https://alteri.verymad.net/avaloninstall.php
```suggestion
PackageUrl: https://alteri.verymad.net/
```

2024-07-22 17:11 UTC, stephengillie requested changes
Hi @pythion,

This package seems to have a dependency:
![image](https://github.com/user-attachments/assets/40a2f35f-5f5e-4cda-89e5-d85963105383)

2024-07-22 17:11 UTC, stephengillie commented on manifests/a/Alteri/Avalon/Client/2024.3.1/Alteri.Avalon.Client.installer.yaml
> +Installers:
```suggestion
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
Installers:
```

2024-07-31 23:24 UTC, hackean-msft commented
/azp run

2024-08-09 11:58 UTC, closed without merging