New version: Amazon.WorkspacesClient version 5.21.0
microsoft/winget-pkgs pull request #161417
Opened 2024-07-03 22:07 UTC by PckgrBot

### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.3.0 :rocket:

2024-07-05 11:41 UTC, ItzLevvie approved these changes

2024-07-06 12:49 UTC, hackean-msft commented
/azp run

2024-07-09 19:59 UTC, stephengillie requested changes
7/6/2024 12:55:33 PM
Installer Verification Analysis Context Information: 
Specified hash doesn't match.
Actual hash:   493D9AAD3F793239C0B2110180A6BA1E2C59C5D852B4521AD5A8D7C26DED0DCA
Expected hash: 7394fb18f796e44ca4bd94bf25980d1ce25606a39d68478227127b705f2e7631

2024-07-09 20:00 UTC, stephengillie commented on manifests/a/Amazon/WorkspacesClient/5.21.0/Amazon.WorkspacesClient.installer.yaml
> +  InstallerSha256: 7394FB18F796E44CA4BD94BF25980D1CE25606A39D68478227127B705F2E7631
```suggestion
  InstallerSha256: 493D9AAD3F793239C0B2110180A6BA1E2C59C5D852B4521AD5A8D7C26DED0DCA
```
Apologies for the noisy review.

2024-07-10 05:58 UTC, closed without merging