Update AngusJohnson.ResourceHacker.installer.yaml
microsoft/winget-pkgs pull request #161845
Opened 2024-07-08 01:41 UTC by SreakMan

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-07-08 22:13 UTC, ItzLevvie commented
@wingetbot run

2024-07-08 22:19 UTC, ItzLevvie requested changes

2024-07-08 22:19 UTC, ItzLevvie commented on manifests/a/AngusJohnson/ResourceHacker/5.2.6/AngusJohnson.ResourceHacker.installer.yaml
> +- DisplayName: Resource Hacker Version 5.2.6
```suggestion
- DisplayName: Resource Hacker version 5.2.6
```

2024-07-08 22:19 UTC, ItzLevvie commented on manifests/a/AngusJohnson/ResourceHacker/5.2.6/AngusJohnson.ResourceHacker.installer.yaml
> +- DisplayName: Resource Hacker Version 5.2.6
to be more consistent with Control Panel.

2024-07-09 10:53 UTC, hackean-msft commented
/azp run

2024-07-09 17:34 UTC, ItzLevvie approved these changes

2024-07-10 14:42 UTC, stephengillie commented
- https://github.com/microsoft/winget-pkgs/issues/142854

2024-07-10 14:42 UTC, merged