Updating FL Studio to 24.1.1.4239
microsoft/winget-pkgs pull request #162576
Opened 2024-07-11 17:23 UTC by HevyMusic

Deletion of 24.1.0.4225, adding of 24.1.1.4239. Updating the ProductCode

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162576)

2024-07-11 20:20 UTC, stephengillie commented
Automatic Validation ended with:
> 

(Automated response - build 886.)

2024-07-11 20:52 UTC, stephengillie requested changes
> 7/11/2024 5:30:50 PM
Installer Verification Analysis Context Information: 
Specified hash doesn't match.
Actual hash:   B170B56785735EEAC067417CF8DE98A2D17CDE78C915D16EDD9FDBF97F85AF77
Expected hash: 905bcedd2a15127e5fa6fc176b540fcddc00b947ca07784956d1bff6e4de9fb0

2024-07-11 20:52 UTC, stephengillie commented on manifests/i/ImageLine/FLStudio/24.1.1.4239/ImageLine.FLStudio.installer.yaml
> +  InstallerSha256: 905BCEDD2A15127E5FA6FC176B540FCDDC00B947CA07784956D1BFF6E4DE9FB0
```suggestion
  InstallerSha256: B170B56785735EEAC067417CF8DE98A2D17CDE78C915D16EDD9FDBF97F85AF77
```

2024-07-11 20:57 UTC, HevyMusic commented
Oups sorry, I got the email that the hash was incorrect, fixed it directly and pushed again.

2024-07-15 19:13 UTC, stephengillie commented
This package installs and launches normally on a Windows 10 VM.
<!--
[Policy] Manually-Validated
-->

2024-07-15 19:13 UTC, stephengillie commented
This package installs and launches normally on a Windows 10 VM.
<!--
[Policy] Manually-Validated
-->

2024-07-15 19:45 UTC, stephengillie approved these changes

2024-07-16 15:08 UTC, stephengillie commented
I can't find the PR where these files were submitted, but unfortunately this manifest has already been added.

2024-07-16 15:08 UTC, stephengillie commented
Close with reason: Merge Conflicts;

2024-07-16 15:08 UTC, closed without merging