DashoGames.PiozaGameLauncher version 0.4.0
microsoft/winget-pkgs pull request #162929
Opened 2024-07-14 14:33 UTC by Shieldowskyy

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-07-14 14:37 UTC, Shieldowskyy commented
@microsoft-github-policy-service agree company="DashoGames"

2024-07-14 19:32 UTC, Trenly requested changes

2024-07-14 19:32 UTC, Trenly commented on manifests/d/DashoGames/PiozaGameLauncher/0.4.0/DashoGames.PiozaGameLauncher.installer.yaml
> +InstallerType: exe
```suggestion
InstallerType: inno
```

2024-07-14 19:32 UTC, Trenly commented on manifests/d/DashoGames/PiozaGameLauncher/0.4.0/DashoGames.PiozaGameLauncher.installer.yaml
> +    SilentWithProgress: /SILENT
```suggestion
```
These should be the default for Inno based installers

2024-07-14 19:32 UTC, Trenly commented on manifests/d/DashoGames/PiozaGameLauncher/0.4.0/DashoGames.PiozaGameLauncher.installer.yaml
> +InstallerLocale: pl-PL
```suggestion
```
The installer is not specific to the `pl-PL` locale. If this is included, users of other locales may not be able to install the software

2024-07-14 19:32 UTC, Trenly commented on manifests/d/DashoGames/PiozaGameLauncher/0.4.0/DashoGames.PiozaGameLauncher.locale.en-US.yaml
> +PackageName: Pioza Game Launcher
```suggestion
PackageName: PiozaGameLauncher
```
This should match Control Panel

2024-07-15 16:10 UTC, stephengillie commented
Manual Validation ended with:
> 
> 2024-07-15 09:10:30.315 [FAIL] Installer failed security check. Url: https://github.com/Shieldowskyy/PiozaGameLauncher/releases/download/v.0.4.0/PiozaGL.exe Result: 0x80004005

(Automated response - build 886.)

2024-07-15 16:20 UTC, stephengillie commented
/azp run

2024-07-16 15:47 UTC, stephengillie commented
/azp run

2024-07-17 03:04 UTC, stephengillie requested changes
Hi @Shieldowskyy,

It appears that this package has a couple of dependencies:
![image](https://github.com/user-attachments/assets/e62b9065-53af-42c9-9e18-664f8f0990aa)
![image](https://github.com/user-attachments/assets/ea222c02-8654-4115-a6e5-95206119fec6)

2024-07-17 03:06 UTC, stephengillie commented
Verify with above dependencies:
![image](https://github.com/user-attachments/assets/c416c830-f2f2-47a2-bc1c-569f34d4cee9)
- https://github.com/microsoft/winget-pkgs/issues/107639
- https://github.com/microsoft/winget-pkgs/issues/12906

![image](https://github.com/user-attachments/assets/3870dd01-5134-40b2-84ec-9c9d4b843546)

2024-07-25 08:31 UTC, closed without merging