New version: undergroundwires.privacy.sexy version 0.13.5
microsoft/winget-pkgs pull request #163052
Opened 2024-07-15 08:02 UTC by averyterrel

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-07-15 08:04 UTC, averyterrel commented
@microsoft-github-policy-service agree

2024-07-15 14:20 UTC, stephengillie commented
Automatic Validation ended with:
> No errors to post.

(Automated response - build 886.)

2024-07-15 18:21 UTC, stephengillie requested changes
Hi @averyterrel,

Our `x86` validations are performed on 32-bit OSes. 

![image](https://github.com/user-attachments/assets/07f490ff-5eb6-41d6-b8f0-28af654f51c8)

2024-07-15 18:21 UTC, stephengillie commented on manifests/u/undergroundwires/privacy/sexy/0.13.5/undergroundwires.privacy.sexy.installer.yaml
> +- Architecture: x86
```suggestion
- Architecture: x64
```

2024-07-16 16:03 UTC, stephengillie commented
The [Policy 2.7](https://learn.microsoft.com/en-us/windows/package-manager/package/windows-package-manager-policies#27-adult-content) check here is due to the "extreme marketing" used in the name and description.

2024-07-16 16:18 UTC, stephengillie approved these changes

2024-07-16 16:20 UTC, merged