FreeSoftwareFoundation.LameXP-AudioEncoderFront-End version 4.1.8.1
microsoft/winget-pkgs pull request #16326
Opened 2021-06-05 13:01 UTC by max-stockhausen

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-06-05 17:11 UTC, ItzLevvie commented on manifests/f/FreeSoftwareFoundation/LameXP-AudioEncoderFront-End/4.1.8.1/FreeSoftwareFoundation.LameXP-AudioEncoderFront-End.installer.yaml
> +  InstallerUrl: https://downloads.sourceforge.net/project/lamexp/LameXP.2019-12-18.Release-Static.Build-2240.exe?ts=gAAAAABgu28WYlvGRxhpwwLCHinlgBfFLOHqO5gx1fbF_aB9PeV6rSar51qI83RILBz9u7F0UAjWUGw9tor
```suggestion
  InstallerUrl: https://sourceforge.net/projects/lamexp/files/LameXP.2019-12-18.Release-Static.Build-2240.exe/download
```

2021-06-05 17:13 UTC, ItzLevvie commented on manifests/f/FreeSoftwareFoundation/LameXP-AudioEncoderFront-End/4.1.8.1/FreeSoftwareFoundation.LameXP-AudioEncoderFront-End.locale.en-US.yaml
> +PackageVersion: 4.1.8.1
```suggestion
PackageVersion: 4.18 Final-1 [Build #2240]
```

2021-06-05 17:13 UTC, ItzLevvie commented on manifests/f/FreeSoftwareFoundation/LameXP-AudioEncoderFront-End/4.1.8.1/FreeSoftwareFoundation.LameXP-AudioEncoderFront-End.yaml
> +PackageVersion: 4.1.8.1
```suggestion
PackageVersion: 4.18 Final-1 [Build #2240]
```

2021-06-05 17:13 UTC, ItzLevvie commented on manifests/f/FreeSoftwareFoundation/LameXP-AudioEncoderFront-End/4.1.8.1/FreeSoftwareFoundation.LameXP-AudioEncoderFront-End.installer.yaml
> +PackageVersion: 4.1.8.1
```suggestion
PackageVersion: 4.18 Final-1 [Build #2240]
```

2021-06-05 17:13 UTC, ItzLevvie commented on manifests/f/FreeSoftwareFoundation/LameXP-AudioEncoderFront-End/4.1.8.1/FreeSoftwareFoundation.LameXP-AudioEncoderFront-End.locale.en-US.yaml
> +Publisher: Free Software Foundation
```suggestion
Publisher: LoRd_MuldeR <mulder2@gmx.de>
```

2021-06-05 17:14 UTC, ItzLevvie commented on manifests/f/FreeSoftwareFoundation/LameXP-AudioEncoderFront-End/4.1.8.1/FreeSoftwareFoundation.LameXP-AudioEncoderFront-End.locale.en-US.yaml
> +PackageName: LameXP - Audio Encoder Front-End
```suggestion
PackageName: LameXP
```

2021-06-05 17:15 UTC, ItzLevvie requested changes
Other than the changes I've made, everything else looks good to me:
![image](https://user-images.githubusercontent.com/11600822/120899908-ed2c6300-c629-11eb-8a85-b666b79ae517.png)

2021-06-06 15:19 UTC, max-stockhausen commented
Can I accept all those changes at once?

2021-06-06 15:49 UTC, ItzLevvie requested changes
You'll have to do it individually; there should be a button called "Commit suggestion" or something along the lines, or otherwise, you can use the GitHub Desktop client on Windows to modify the files manually and push the changes to your branch which will then update the PR with those changes.

2021-06-10 14:12 UTC, max-stockhausen commented
Because I cant commit to this Branch I created a new request: #16957

2021-06-10 14:12 UTC, closed without merging