Duplicati.Duplicati version 2.0.6.1
microsoft/winget-pkgs pull request #16339
Opened 2021-06-05 16:42 UTC by tiziodcaio

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-06-05 16:45 UTC, tiziodcaio commented
If I reinstall it, it gaves me an error (1603)... should I add?

2021-06-05 17:38 UTC, ItzLevvie commented on manifests/d/Duplicati/Duplicati/2.0.6.1/Duplicati.Duplicati.locale.en-US.yaml
>  PackageName: Duplicati
```suggestion
PackageName: Duplicati 2
```
![image](https://user-images.githubusercontent.com/11600822/120900553-261a0700-c62d-11eb-868a-2d99b8ec3d06.png)

2021-06-05 17:38 UTC, ItzLevvie requested changes
Other than the changes I've made, everything else looks good to me:
![image](https://user-images.githubusercontent.com/11600822/120900559-3631e680-c62d-11eb-852a-9026a782eee2.png)

2021-06-06 15:46 UTC, ItzLevvie approved these changes

2021-06-06 15:47 UTC, merged