New package: Octol1ttle.ElyPrismLauncher version 8.4
microsoft/winget-pkgs pull request #163430
Opened 2024-07-17 17:38 UTC by znarfm

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-07-17 17:42 UTC, znarfm commented
@microsoft-github-policy-service agree

2024-07-17 20:22 UTC, stephengillie commented
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Programs\PrismLauncher\prismlauncher.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Programs\PrismLauncher\prismlauncher_filelink.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Programs\PrismLauncher\prismlauncher_updater.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 886.)

2024-07-18 00:29 UTC, stephengillie requested changes
Hi @znarfm,

This package appears to have a dependency. 

![image](https://github.com/user-attachments/assets/21924200-cc56-4039-aa98-fb26d364c9c9)

2024-07-18 00:29 UTC, stephengillie commented on manifests/o/Octol1ttle/ElyPrismLauncher/8.4/Octol1ttle.ElyPrismLauncher.installer.yaml
> +Installers:
```suggestion
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
```

2024-07-18 00:37 UTC, stephengillie commented
Verify with above dependencies:
![image](https://github.com/user-attachments/assets/525346b5-fe22-40b7-900c-6ddff4162333)
![image](https://github.com/user-attachments/assets/9606c627-7009-4290-b215-ca0ca09315ec)

Just to ask - we already have a package named `PrismLauncher.PrismLauncher` which is also at version `8.4` - could this be the same package?

2024-07-18 02:22 UTC, znarfm commented
> could this be the same package?

This package is actually a fork of Prism Launcher. It includes additional features not available to the original package, such as the ability to log in with an Ely.by account.

2024-07-18 15:58 UTC, stephengillie approved these changes

2024-07-19 09:29 UTC, mdanish-kh commented
[Policy] Needs-Manual-Merge

2024-07-19 14:00 UTC, stephengillie commented
- https://github.com/microsoft/winget-pkgs/issues/142854

2024-07-19 14:00 UTC, merged