Update SIW to version 11.4.2.20210602
microsoft/winget-pkgs pull request #16358
Opened 2021-06-05 19:52 UTC by gtopala

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-06-06 15:59 UTC, ItzLevvie requested changes
I'm getting an error on my device:
![image](https://user-images.githubusercontent.com/11600822/120931210-85891d00-c6e8-11eb-947c-53588bbae97b.png)

2021-06-06 16:31 UTC, gtopala commented
I don’t know why you cannot download https://siw64.com/download/siwtrial-setup.exe
The link works from a browser of from wget

***@***.***D75ACF.2254C570]

Thank you,
Gabriel Topala

From: ItzLevvie ***@***.***>
Sent: Sunday, June 6, 2021 11:59 AM
To: microsoft/winget-pkgs ***@***.***>
Cc: Gabriel Topala ***@***.***>; Author ***@***.***>
Subject: Re: [microsoft/winget-pkgs] Update SIW to version 11.4.2.20210602 (#16358)


@ItzLevvie requested changes on this pull request.

I'm getting an error on my device:
[image]<https://user-images.githubusercontent.com/11600822/120931210-85891d00-c6e8-11eb-947c-53588bbae97b.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/microsoft/winget-pkgs/pull/16358#pullrequestreview-676880142>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AADULJSQDFENIDOPNMX5MP3TROLODANCNFSM46E532QQ>.

2021-06-07 16:23 UTC, ItzLevvie commented on manifests/t/TopalaSoftwareSolutions/SIW/2021.06.02.2/TopalaSoftwareSolutions.SIW.yaml
> +PackageName: System Information for Windows
```suggestion
PackageName: SIW 2021 Trial
```
![image](https://user-images.githubusercontent.com/11600822/121055106-dfefaf80-c7b4-11eb-8cff-559152593496.png)

2021-06-07 16:23 UTC, ItzLevvie commented on manifests/t/TopalaSoftwareSolutions/SIW/2021.06.02.2/TopalaSoftwareSolutions.SIW.yaml
> +PackageVersion: 2021.06.02.2
```suggestion
PackageVersion: 2021.06.02b
```
![image](https://user-images.githubusercontent.com/11600822/121055106-dfefaf80-c7b4-11eb-8cff-559152593496.png)

2021-06-07 16:23 UTC, ItzLevvie commented on manifests/t/TopalaSoftwareSolutions/SIW/2021.06.02.2/TopalaSoftwareSolutions.SIW.yaml
> +- Architecture: neutral
```suggestion
- Architecture: x86
```

2021-06-07 16:23 UTC, ItzLevvie requested changes
Other than the changes I've made, everything else looks good to me:
![image](https://user-images.githubusercontent.com/11600822/121055240-001f6e80-c7b5-11eb-984e-0d7998a9ae24.png)

2021-06-08 20:48 UTC, closed without merging