clickbitsGmbH.clockodo version 6.0.10
microsoft/winget-pkgs pull request #16541
Opened 2021-06-07 12:47 UTC by Keller0Junge

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-06-07 16:36 UTC, ItzLevvie commented on manifests/c/clickbitsGmbH/clockodo/6.0.10/clickbitsGmbH.clockodo.yaml
> +PackageIdentifier: clickbitsGmbH.clockodo
```suggestion
PackageIdentifier: clickbits.clockodo
```

2021-06-07 16:36 UTC, ItzLevvie commented on manifests/c/clickbitsGmbH/clockodo/6.0.10/clickbitsGmbH.clockodo.locale.de-DE.yaml
> +PackageIdentifier: clickbitsGmbH.clockodo
```suggestion
PackageIdentifier: clickbits.clockodo
```

2021-06-07 16:36 UTC, ItzLevvie commented on manifests/c/clickbitsGmbH/clockodo/6.0.10/clickbitsGmbH.clockodo.installer.yaml
> +PackageIdentifier: clickbitsGmbH.clockodo
```suggestion
PackageIdentifier: clickbits.clockodo
```

2021-06-07 16:36 UTC, ItzLevvie requested changes
Other than the changes I've made, everything else looks good to me:
![image](https://user-images.githubusercontent.com/11600822/121057081-ccdddf00-c7b6-11eb-8d9a-f2a36ae3dace.png)

Just make sure to rename the folder names using the GitHub Desktop client on Windows.

2021-06-08 06:58 UTC, closed without merging

2021-06-08 07:12 UTC, Keller0Junge commented
@ItzLevvie i had some trouble to change the path. I am pretty new in Git. It was much easier for me to creat a new request with these changes (number 16623). Iwill try to learn an understand how to change my request and path in time but for now it should be fine with a new request.