New package Microsoft.FSLogix
microsoft/winget-pkgs pull request #165828
Opened 2024-08-02 12:54 UTC by FaserF

Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-08-02 16:20 UTC, stephengillie commented
Automatic Validation ended with:


(Automated response - build 887.)

2024-08-04 14:46 UTC, FaserF commented
I need help here, this looks to me like a bug within winget itself. It downloads the zip file as an exe file (for whatever reason), and then tries to open the zip file as an exe file which results in an error, that this app is not compatible with this device. 
![image](https://github.com/user-attachments/assets/ce3deeb9-6af2-42ea-ac14-ea30bc5dcd23)

But the installer URL clearly is a ZIP file: 
InstallerUrl: https://download.microsoft.com/download/e/c/4/ec4b55b3-d2f3-4610-aebd-56478eb0d582/FSLogix_Apps_2.9.8884.27471.zip

Downloading it manually works completly fine.

2024-08-05 19:42 UTC, stephengillie commented
Automatic Validation ended with:


(Automated response - build 887.)

2024-08-05 19:42 UTC, stephengillie commented
Automatic Validation ended with:


(Automated response - build 887.)

2024-08-06 11:18 UTC, FaserF commented
@stephengillie maybe this now is the issue for this error? I have now removed the 32bit installation option, thanks as always for your great input!

https://github.com/microsoft/winget-pkgs/pull/165828#issuecomment-2268245325

2024-08-06 15:49 UTC, stephengillie commented
Automatic Validation ended with:


(Automated response - build 887.)

2024-08-06 16:06 UTC, stephengillie commented
Manual Validation ended with:
![image](https://github.com/user-attachments/assets/8501dd56-a64a-44db-a796-b7ac14bb522d)

I'm not sure why this worked on the 64-bit pipeline VM, but isn't working on my VM. At first glance, it appears to be the inexplicable situation of a 64-bit application using an installer that does not work on 64-bit OSes.

2024-08-06 16:38 UTC, FaserF commented
Still for me this looks like a winget bug. There is no "FSLogix_Apps_2.9.8884.27471.exe", it is a zip file containing another exe called  "FSLogixAppsSetup.exe".
I dont understand why winget downloads the zip file but renames it to an .exe file. Then you get this error message, since windows trys to open a zip file as an exe file, which of course cannot be read. 
See https://github.com/microsoft/winget-pkgs/pull/165828#issuecomment-2268245325

2024-08-07 01:33 UTC, stephengillie requested changes
> I dont understand why winget downloads the zip file but renames it to an .exe file.

Thank you - this reminded me of an uncommon situation. The package manager is doing what it's told - download the file and then "process as EXE". Since it is a ZIP file, we want to change this to "process as ZIP".

2024-08-07 01:33 UTC, stephengillie commented on manifests/m/Microsoft/FSLogix/2.9.8884.27471/Microsoft.FSLogix.installer.yaml
> +InstallerType: exe
```suggestion
InstallerType: zip
```

2024-08-07 01:38 UTC, stephengillie commented on manifests/m/Microsoft/FSLogix/2.9.8884.27471/Microsoft.FSLogix.installer.yaml
> +InstallerType: exe
I forgot to mention that `zip` requires the `NestedInstaller` to be described:

```
    NestedInstallerType: exe
    NestedInstallerFiles: 
      - RelativeFilePath: FSLogixAppsSetup.exe
```

2024-08-07 15:50 UTC, stephengillie commented
Verify:
![image](https://github.com/user-attachments/assets/f5f22056-7cd2-49ce-962d-80935319ac9e)

I tried one other application, and it gave an error:
![image](https://github.com/user-attachments/assets/7e43258c-f6ac-4ef8-8a13-631748e7d9e8)
Guessing ``frxshell.exe` isn't meant to be run directly.

2024-08-07 15:51 UTC, stephengillie approved these changes

2024-08-07 15:51 UTC, merged