New version: OSGeo.QGIS version 3.38.1 (3.38.1-1)
microsoft/winget-pkgs pull request #166343
Opened 2024-08-06 11:12 UTC by spectopo

Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#7139](https://github.com/SpecterShell/Dumplings/actions/runs/10265329701).

<details>

<summary>Log</summary>

````
Updated: 3.38.0-1 → 3.38.1-1
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

2024-08-06 13:20 UTC, stephengillie commented
URL: https://qgis.org/downloads/QGIS-OSGeo4W-3.38.1-1.msi 
Status Code: 200

(Automated message - build 887)

2024-08-06 16:10 UTC, stephengillie requested changes
Hi @spectopo,

It appears that the documentation site is blocking our automated scans.

2024-08-06 16:10 UTC, stephengillie commented on manifests/o/OSGeo/QGIS/3.38.1/OSGeo.QGIS.locale.en-US.yaml
> +  DocumentUrl: https://www.qgis.org/en/docs/
```suggestion
#  DocumentUrl: 
```

2024-08-06 16:10 UTC, stephengillie commented on manifests/o/OSGeo/QGIS/3.38.1/OSGeo.QGIS.locale.zh-CN.yaml
> +  DocumentUrl: https://www.qgis.org/zh-Hans/docs/
```suggestion
#  DocumentUrl: 
```

2024-08-09 19:20 UTC, stephengillie commented
/azp run

2024-08-12 22:20 UTC, stephengillie commented
/azp run

2024-08-13 20:20 UTC, stephengillie commented
/azp run

2024-08-13 22:03 UTC, ItzLevvie approved these changes

2024-08-14 19:20 UTC, stephengillie commented
/azp run

2024-08-15 16:20 UTC, stephengillie commented
/azp run

2024-08-16 23:34 UTC, stephengillie approved these changes

2024-08-17 00:17 UTC, stephengillie commented
This package installs and launches normally on a Windows 10 VM.
<!--
[Policy] Manually-Validated
-->

2024-08-17 00:17 UTC, stephengillie commented
This package installs and launches normally on a Windows 10 VM.
<!--
[Policy] Manually-Validated
-->

2024-08-19 15:34 UTC, merged