New package: Zen-Team.Zen-Browser version 1.0.0-a.28
microsoft/winget-pkgs pull request #168940
Opened 2024-08-24 04:55 UTC by sitiom

### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.4.1 :rocket:

2024-08-24 22:31 UTC, UnownPlain commented
This package already exists (#168542). You should update the existing one.

2024-08-25 01:34 UTC, sitiom commented
My bad. To be fair, Komac, @wingetbot, and a quick search of "Zen Browser" did not yield any results 😅

2024-08-25 01:40 UTC, sitiom commented on manifests/z/Zen-Team/Zen-Browser/1.0.0-a.28/Zen-Team.Zen-Browser.locale.en-US.yaml
> +Publisher: Mozilla
- https://github.com/zen-browser/desktop/issues/483

2024-08-25 02:03 UTC, UnownPlain commented
It looks like this package installs the generic version while the optimized version is a separate package (#168942). I think it makes more sense to have this be the optimized version and the generic version be in a separate package since most systems should support the faster optimized version.

See: https://docs.zen-browser.app/guides/generic-optimized

The optimized version is supported in all systems with an Intel 4th Gen+ CPU and all Ryzen CPUs.

2024-08-25 02:24 UTC, sitiom commented
> It looks like this package installs the generic version while the optimized version is a separate package (#168942). I think it makes more sense to have this be the optimized version and the generic version be in a separate package since most systems should support the faster optimized version.
> 
> See: [docs.zen-browser.app/guides/generic-optimized](https://docs.zen-browser.app/guides/generic-optimized)
> 
> The optimized version is supported in all systems with an Intel 4th Gen+ CPU and all Ryzen CPUs.

I'm following the AUR here ([`zen-browser-bin`](https://aur.archlinux.org/packages/zen-browser-bin) and [`zen-browser-optimized-bin`](https://aur.archlinux.org/packages/zen-browser-optimized-bin)), which makes sense since the "optimized" is the "specific build" and the main package is expected to work for all. I still even have a laptop that doesn't support the "optimized" build. @mauro-balades Any thoughts here?

2024-08-26 18:25 UTC, stephengillie requested changes

2024-08-26 19:42 UTC, stephengillie commented
Verify:
![image](https://github.com/user-attachments/assets/e73301de-6718-4a43-b269-9d128bf5d702)
![image](https://github.com/user-attachments/assets/99879f82-f9de-4575-b32b-b5f6bb4a903b)

2024-08-26 19:42 UTC, stephengillie approved these changes

2024-08-26 19:43 UTC, merged