New version: Zen-Team.Zen-Browser version 1.0.0-a.31
microsoft/winget-pkgs pull request #169939
Opened 2024-08-28 02:43 UTC by sitiom

### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.5.0 :rocket:

2024-08-28 02:50 UTC, UnownPlain requested changes

2024-08-28 02:50 UTC, UnownPlain commented on manifests/z/Zen-Team/Zen-Browser/1.0.0-a.31/Zen-Team.Zen-Browser.installer.yaml
> +InstallerType: exe
The package won't install correctly if this isn't set to `nullsoft`
```suggestion
InstallerType: nullsoft
```

2024-08-28 04:33 UTC, sitiom commented
Works:
![image](https://github.com/user-attachments/assets/e968bf3e-6ae5-40c0-8b94-813a17c1e1a8)

2024-08-28 17:22 UTC, stephengillie commented
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-28 01:05:09.028 [FAIL] Installer failed security check. Url: https://github.com/zen-browser/desktop/releases/download/1.0.0-a.31/zen.installer-generic.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. <!-- [Policy] Needs-Attention`n[Policy] Validation-Defender-Error -->

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 891.)

2024-08-28 22:20 UTC, stephengillie commented
/azp run

2024-08-29 00:51 UTC, stephengillie approved these changes

2024-08-29 00:52 UTC, merged