New package: BlueMystical.EDHM version 2.2.42
microsoft/winget-pkgs pull request #172233
Opened 2024-09-07 15:21 UTC by solomoncyj

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-09-07 23:48 UTC, russellbanks requested changes

2024-09-07 23:48 UTC, russellbanks commented on manifests/b/BlueMystical/EDHM/2.2.42/BlueMystical.EDHM.installer.yaml
> +- Architecture: x64
```suggestion
- Architecture: x86
```

![image](https://github.com/user-attachments/assets/3b8c8a51-a094-4212-9ba6-c27b2b1ee307)

https://learn.microsoft.com/windows/win32/msi/template-summary#remarks:
> If the platform specification is missing in the **Template Summary** property value, the installer assumes the Intel architecture.

2024-09-09 17:01 UTC, stephengillie commented
Verify:
![image](https://github.com/user-attachments/assets/85fe3ed4-040e-49ce-8ab9-702f932bf5e6)
![image](https://github.com/user-attachments/assets/90fe68ef-7271-4198-b5e9-3e5ce25c79cb)

2024-09-09 17:02 UTC, stephengillie approved these changes

2024-09-09 17:02 UTC, merged