New Version: Sigil-Ebook.PageEdit version 2.3.1
microsoft/winget-pkgs pull request #172238
Opened 2024-09-07 17:10 UTC by dougmassay

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-09-09 17:44 UTC, stephengillie commented
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Programs\PageEdit\PageEdit.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Programs\PageEdit\QtWebEngineProcess.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 895.)

2024-09-09 17:54 UTC, dougmassay commented
See the previous version's PR: #168593

There's a weird catch-22 where the local scope install can't find the Microsoft.VCRedist.2015+.x64 dependency, but there is no Microsoft.VCRedist.2015+.x64 package available for the local scope. This same scenario was approved last time. It tests fine locally since Microsoft.VCRedist.2015+.x64 is installed by default on the Minimum OS version this manifest supports. Thanks for your time and efforts!

2024-09-09 18:31 UTC, stephengillie requested changes
Hi @dougmassay,

It seems that both scopes need the dependency:
![image](https://github.com/user-attachments/assets/8b090140-f9a8-4c2e-8394-f30fa7c3552f)

2024-09-09 18:31 UTC, stephengillie commented on manifests/s/Sigil-Ebook/PageEdit/2.3.1/Sigil-Ebook.PageEdit.installer.yaml
> +  InstallerSha256: 332B562614B2EF81D7E6D3B6F73D4CC4D1D1E304015CDE9F3D52F705344AE5AC
```suggestion
  InstallerSha256: 332B562614B2EF81D7E6D3B6F73D4CC4D1D1E304015CDE9F3D52F705344AE5AC
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
```

2024-09-09 18:40 UTC, dougmassay commented
We've been down this road again and again. Yes, both scopes need the dependency, but the validation process fails miserably if the dependency is specified for the user scope installation the manifest (because no user scope package exists for Microsoft.VCRedist.2015+.x64). 

Hence the catch-22 I mentioned.

2024-09-09 18:47 UTC, dougmassay commented
I will, however, try your suggested change.

2024-09-09 22:02 UTC, dougmassay commented
Someone needs to explain how we're supposed properly manifest a user scope install that has a Microsoft.VCRedist.2015+.x64 dependency, because I'm tired of guessing.

2024-09-10 15:38 UTC, stephengillie commented
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-09-10 06:39:54.191 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.40.33810.0

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

(Automated response - build 895.)

2024-09-10 16:18 UTC, stephengillie approved these changes

2024-09-10 18:16 UTC, ItzLevvie commented
[Policy] Needs-Manual-Merge

2024-09-10 18:17 UTC, ItzLevvie approved these changes

2024-09-10 19:56 UTC, merged