New version: DuckStudio.FufuDevTools version 2024.09.08.2000
microsoft/winget-pkgs pull request #173678
Opened 2024-09-15 19:47 UTC by fjwxzde

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-09-15 19:48 UTC, fjwxzde commented
@microsoft-github-policy-service agree company="DuckStudio"

2024-09-16 05:28 UTC, fjwxzde commented
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.

I am not sure why this error occurred, but I was able to install and use it successfully during my testing.

Terminal logs:
- [install.log](https://github.com/user-attachments/files/17008791/install.log)
- [install-Administrator.log](https://github.com/user-attachments/files/17008792/install-Administrator.log)

Winget logs:

> I don't know which log is related to the installation, I only executed four commands and got these logs.

- [WinGet-DuckStudio.FufuDevTools.2024.09.08.2000-2024-09-16-13-00-46.068.log](https://github.com/user-attachments/files/17008796/WinGet-DuckStudio.FufuDevTools.2024.09.08.2000-2024-09-16-13-00-46.068.log)
- [WinGet-2024-09-16-12-57-46.837.log](https://github.com/user-attachments/files/17008809/WinGet-2024-09-16-12-57-46.837.log)
- [WinGet-2024-09-16-12-59-56.495.log](https://github.com/user-attachments/files/17008816/WinGet-2024-09-16-12-59-56.495.log)
- [WinGet-2024-09-16-13-00-20.074.log](https://github.com/user-attachments/files/17008839/WinGet-2024-09-16-13-00-20.074.log)
- [WinGetCOM-2024-09-16-13-00-58.076.log](https://github.com/user-attachments/files/17008843/WinGetCOM-2024-09-16-13-00-58.076.log)

Usage verification:

```powershell
> ffdev
Usage: ffdev <工具> <命令> [<参数>...]
> ffdev --version
✓ Version 2024.09.08.2000
> ffdev -v
✓ Version 2024.09.08.2000
> ffdev 账号切换 --edit
> # Successful
```

2024-09-16 18:36 UTC, stephengillie commented
Automatic Validation ended with:


(Automated response - build 895.)

2024-09-16 18:39 UTC, stephengillie commented
Hi @fjwxzde,

This manifest removes the DisplayVersion from the AppsAndFeaturesEntries, which is present in previous manifest versions. This entry should be added to this version, to maintain version matching, and prevent the 'upgrade always available' situation with this package.

(Automated response - build 895.)
<!--
[Policy] Needs-Author-Feedback
-->

2024-09-16 22:35 UTC, Luna-Grace approved these changes

2024-09-16 22:36 UTC, Luna-Grace commented
@DuckDuckStudio

2024-09-16 22:39 UTC, DuckDuckStudio approved these changes
Looks good.

2024-09-16 22:41 UTC, DuckDuckStudio requested changes

2024-09-16 22:41 UTC, DuckDuckStudio commented on manifests/d/DuckStudio/FufuDevTools/2024.09.08.2000/DuckStudio.FufuDevTools.installer.yaml
> +- DisplayVersion: 2024.08.01.0000
```suggestion
- DisplayVersion: 2024.09.08.2000
```

I didn't notice this just now.

2024-09-17 00:19 UTC, Luna-Grace approved these changes

2024-09-17 00:52 UTC, DuckDuckStudio approved these changes

2024-09-17 01:44 UTC, fjwxzde commented
Hi @stephengillie ,
There seems to be a problem with the pipeline.
The error label was removed, but the pipeline was not restarted.

2024-09-17 01:44 UTC, fjwxzde commented
> Azure Pipelines could not run because the pipeline triggers exclude this branch/path.

Hi @stephengillie ,
There seems to be a problem with the pipeline.
The error label was removed, but the pipeline was not restarted.

2024-09-17 02:05 UTC, fjwxzde commented
> Azure Pipelines could not run because the pipeline triggers exclude this branch/path.

Hi stephengillie ,
~~There seems to be a problem with the pipeline.~~
~~The error label was removed, but the pipeline was not restarted.~~

![image](https://github.com/user-attachments/assets/37c2e7eb-c1a7-4794-affd-36b4f71d2afe)

This was not the case when I sended this comment.
But I kone it now.

2024-09-17 14:43 UTC, stephengillie commented
Automatic Validation ended with:


(Automated response - build 895.)

2024-09-17 14:44 UTC, stephengillie approved these changes

2024-09-17 14:54 UTC, DuckDuckStudio commented
@stephengillie 
![image](https://github.com/user-attachments/assets/80f39d7b-b20e-4691-a2f2-fe89611a93b5)

2024-09-17 15:43 UTC, merged