New package: incredimo.textra version v2024.09.18.164358
microsoft/winget-pkgs pull request #174144
Opened 2024-09-18 18:30 UTC by incredimo

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-09-18 18:31 UTC, incredimo commented
@microsoft-github-policy-service agree

2024-09-19 16:20 UTC, stephengillie commented
Automatic Validation ended with:
> ADO Build not found.

(Automated response - build 895.)

2024-09-19 16:32 UTC, stephengillie commented
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\incredimo.textra__DefaultSource\textra.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\textra.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 896.)

2024-09-19 16:35 UTC, stephengillie commented
Manual Validation ended with:
> 
> 2024-09-19 09:35:06.747 [FAIL] Installer failed security check. Url: https://github.com/u-tra/textra/releases/download/v
> 2024.09.18.164358/textra.exe Result: 0x80004005

(Automated response - build 896.)

2024-09-21 01:34 UTC, stephengillie commented
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\incredimo.textra__DefaultSource\textra.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\textra.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 896.)

2024-09-21 01:51 UTC, stephengillie commented
Manual Validation ended with:
> 
> 2024-09-20 18:51:28.856 [FAIL] Installer failed security check. Url: https://github.com/u-tra/textra/releases/download/v
> 2024.09.18.164358/textra.exe Result: 0x80004005

(Automated response - build 896.)

2024-09-23 15:25 UTC, stephengillie requested changes
> Automatic Validation ended with:
> 
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\incredimo.textra__DefaultSource\textra.exe returned exit code: -1073741515
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\textra.exe returned exit code: -1073741515
> 
> Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).
> 
> (Automated response - build 896.)

Manual Validation ended with: 
![image](https://github.com/user-attachments/assets/e32e22e2-55cf-4dfb-8793-c20d63fcd7c4)

2024-09-23 15:25 UTC, stephengillie commented on manifests/i/incredimo/textra/v2024.09.18.164358/incredimo.textra.installer.yaml
> +Installers:
```suggestion
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
```

2024-10-01 20:13 UTC, closed without merging