New package: Soniczac7.DownloadManager version 5.1.0.0
microsoft/winget-pkgs pull request #174488
Opened 2024-09-20 13:21 UTC by Soniczac7

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-09-20 13:23 UTC, Soniczac7 commented
@microsoft-github-policy-service agree

2024-09-23 17:07 UTC, stephengillie commented
Automatic Validation ended with:


(Automated response - build 896.)

2024-09-23 18:22 UTC, stephengillie requested changes
Manual Validation ended with:
![image](https://github.com/user-attachments/assets/eda0de3d-33de-4680-99ef-7cd1d22d75c9)
![image](https://github.com/user-attachments/assets/027c65c2-8ef3-4924-b5be-2af6da9dec89)

2024-09-23 18:22 UTC, stephengillie commented on manifests/s/Soniczac7/DownloadManager/5.1.0.0/Soniczac7.DownloadManager.installer.yaml
> +Installers:
```suggestion
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
Installers:
```

2024-09-24 15:45 UTC, stephengillie commented
Automatic Validation ended with:

> MSI (s) (6C:B8) [11:50:16:999]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (6C:B8) [11:50:16:999]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (6C:B8) [11:50:16:999]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (6C:B8) [11:50:16:999]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (6C:B8) [11:50:16:999]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> MSI (s) (6C:B8) [11:50:18:561]: Executing op: ComponentRegister(ComponentId={8C08EE04-B7BF-5CFB-9D47-C0E09E7A33C2},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.33\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
> MSI (s) (6C:B8) [11:50:20:296]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,)
> Property(S): ErrorDialog = ErrorDlg
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (6C:C8) [11:50:24:061]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (6C:C8) [11:50:24:061]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (6C:C8) [11:50:24:061]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (6C:C8) [11:50:24:061]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (6C:C8) [11:50:24:061]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> MSI (s) (6C:C0) [11:50:24:889]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (6C:C0) [11:50:24:889]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (6C:C0) [11:50:24:889]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (6C:C0) [11:50:24:889]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (6C:C0) [11:50:24:889]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> MSI (s) (6C:84) [11:50:26:452]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (6C:84) [11:50:26:452]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (6C:84) [11:50:26:452]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (6C:84) [11:50:26:452]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (6C:84) [11:50:26:452]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.

(Automated response - build 896.)

2024-09-24 19:00 UTC, Soniczac7 commented
Hi @stephengillie,
It was an issue with the installer, I have patched the issue and updated the release and it should work as expected now.

2024-09-25 00:05 UTC, stephengillie commented
Verify:
![image](https://github.com/user-attachments/assets/9c74d92c-2b56-477a-a774-32d578ba0569)
![image](https://github.com/user-attachments/assets/8d485f08-120a-46a8-8292-d1f8b508c2b2)
The installer doesn't write a version number to the Registry.

2024-09-25 00:05 UTC, stephengillie approved these changes

2024-09-25 00:05 UTC, merged

2024-09-25 00:20 UTC, Soniczac7 commented
For this version it is intended however will be changed to have the version number available in the next release.

2024-09-25 14:27 UTC, stephengillie commented
The main concern is around version matching. The package manager offers upgrades by matching data in the Registry against a downloaded copy of the manifests in this repo. If other manifests for this `PackageIdentifier` have this data and this manifest does not, I'm not sure of the outcome, but I'm guessing this version alone might have an unexpected situation. But that issue can be solved in the future, and this manifest should stay, at least for now.