New version: WHONET.WHONET version 24.9.25
microsoft/winget-pkgs pull request #175160
Opened 2024-09-25 20:08 UTC by AClark-WHONET

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-09-25 21:12 UTC, stephengillie requested changes
HI @AClark-WHONET,

Automatic Validation ended with:

> ##[error] (Line: 34, Col: 73, Idx: 1900) - (Line: 34, Col: 73, Idx: 1900): While scanning a plain scalar value, found invalid mapping.

I'm not a YAML expert, but I believe the colon might need to be escaped.

2024-09-25 21:12 UTC, stephengillie commented on manifests/w/WHONET/WHONET/24.9.25/WHONET.WHONET.locale.en-US.yaml
> +ReleaseNotes: Corrects a problem handling breakpoints for serovar groups: ECO, HIN, NME.
```suggestion
ReleaseNotes: Corrects a problem handling breakpoints for serovar groups\: ECO, HIN, NME.
```

2024-09-25 23:24 UTC, AClark-WHONET commented
> HI @AClark-WHONET,
> 
> Automatic Validation ended with:
> 
> > ##[error] (Line: 34, Col: 73, Idx: 1900) - (Line: 34, Col: 73, Idx: 1900): While scanning a plain scalar value, found invalid mapping.
> 
> I'm not a YAML expert, but I believe the colon might need to be escaped.

Thanks Stephen.

2024-09-26 02:40 UTC, stephengillie requested changes
Apparently I was wrong about escaping, and an Internet search brings several recommendations to quote the string contents.

2024-09-26 02:40 UTC, stephengillie commented on manifests/w/WHONET/WHONET/24.9.25/WHONET.WHONET.locale.en-US.yaml
> +ReleaseNotes: Corrects a problem handling breakpoints for serovar groups\: ECO, HIN, NME.
```suggestion
ReleaseNotes: "Corrects a problem handling breakpoints for serovar groups: ECO, HIN, NME."
```

2024-09-26 02:45 UTC, AClark-WHONET commented on manifests/w/WHONET/WHONET/24.9.25/WHONET.WHONET.locale.en-US.yaml
> +ReleaseNotes: Corrects a problem handling breakpoints for serovar groups\: ECO, HIN, NME.
Thanks again!

2024-09-26 15:28 UTC, stephengillie approved these changes

2024-09-26 15:28 UTC, merged