New version: Adobe.AdobeConnect version 24.4.149
microsoft/winget-pkgs pull request #175544
Opened 2024-09-27 22:50 UTC by PckgrBot

### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.5.0 :rocket:

2024-09-27 23:20 UTC, stephengillie commented
URL: https://download.adobe.com/pub/connect/updaters/meeting/11_0/ConnectApp11_2024_9_149_32.msi 
Status Code: 200

(Automated message - build 896)

2024-09-29 09:59 UTC, ItzLevvie approved these changes

2024-10-01 19:49 UTC, stephengillie requested changes
> Url validation error
> 
> * manifests\a\Adobe\AdobeConnect\24.4.149
>   
>   * https://helpx.adobe.com/adobe-connect/connect-support.html
>     
>     * Error Message: An error occurred while sending the request. Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
>   * https://helpx.adobe.com/adobe-connect/adobe-connect-copyright-trademarks-third-party.html
>     
>     * Error Message: An error occurred while sending the request. Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

2024-10-01 19:49 UTC, stephengillie commented on manifests/a/Adobe/AdobeConnect/24.4.149/Adobe.AdobeConnect.locale.en-US.yaml
> +CopyrightUrl: https://helpx.adobe.com/adobe-connect/adobe-connect-copyright-trademarks-third-party.html
```suggestion
# PublisherSupportUrl: 
PrivacyUrl: https://www.adobe.com/privacy/policy.html
Author: Adobe
PackageName: Adobe Connect
PackageUrl: https://www.adobe.com/products/adobeconnect.html
License: Proprietary, Freeware
# Copyright: 
# CopyrightUrl: 
```

2024-10-02 17:19 UTC, ItzLevvie approved these changes

2024-10-03 20:39 UTC, ItzLevvie approved these changes

2024-10-05 14:34 UTC, ItzLevvie approved these changes

2024-10-08 20:43 UTC, ItzLevvie approved these changes

2024-10-09 06:30 UTC, ItzLevvie approved these changes

2024-10-10 23:12 UTC, ItzLevvie approved these changes

2024-10-14 17:20 UTC, ItzLevvie approved these changes

2024-10-14 20:21 UTC, closed without merging