VoodooSoftLLC.VoodooShield version 6.55
microsoft/winget-pkgs pull request #17562
Opened 2021-06-15 07:12 UTC by sanikdah

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-06-17 11:06 UTC, ItzLevvie requested changes

2021-06-17 11:06 UTC, ItzLevvie commented on manifests/v/VoodooSoftLLC/VoodooShield/6.55/VoodooSoftLLC.VoodooShield.installer.yaml
> +  InstallerUrl: https://files03.tchspt.com/temp/InstallVoodooShield.exe
```suggestion
  InstallerUrl: https://voodooshield.com/Download/InstallVoodooShield.exe
```

2021-06-17 11:06 UTC, ItzLevvie commented on manifests/v/VoodooSoftLLC/VoodooShield/6.55/VoodooSoftLLC.VoodooShield.installer.yaml
> +PackageIdentifier: VoodooSoftLLC.VoodooShield
```suggestion
PackageIdentifier: VoodooSoft.VoodooShield
```

2021-06-17 11:06 UTC, ItzLevvie commented on manifests/v/VoodooSoftLLC/VoodooShield/6.55/VoodooSoftLLC.VoodooShield.locale.en-US.yaml
> +PackageIdentifier: VoodooSoftLLC.VoodooShield
```suggestion
PackageIdentifier: VoodooSoft.VoodooShield
```

2021-06-17 11:06 UTC, ItzLevvie commented on manifests/v/VoodooSoftLLC/VoodooShield/6.55/VoodooSoftLLC.VoodooShield.yaml
> +PackageIdentifier: VoodooSoftLLC.VoodooShield
```suggestion
PackageIdentifier: VoodooSoft.VoodooShield
```

2021-06-18 09:26 UTC, OfficialEsco approved these changes

2021-06-18 09:26 UTC, merged