TeamRadarr.Radarr version 3.2.2.5080
microsoft/winget-pkgs pull request #17762
Opened 2021-06-16 22:18 UTC by mikeparkie

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-06-17 12:06 UTC, OfficialEsco requested changes

2021-06-17 12:06 UTC, OfficialEsco commented on manifests/t/TeamRadarr/Radarr/3.2.2.5080/TeamRadarr.Radarr.installer.yaml
> +- Architecture: x64
```suggestion
- Architecture: x86
```

2021-06-17 12:06 UTC, OfficialEsco commented on manifests/t/TeamRadarr/Radarr/3.2.2.5080/TeamRadarr.Radarr.installer.yaml
> +PackageVersion: 3.2.2.5080
```suggestion
PackageVersion: 3.2.2
```
This also shows as 3.2.2 🤦‍♂️
![image](https://user-images.githubusercontent.com/15158490/122393086-cc8ed200-cf74-11eb-870f-42973f56b338.png)

2021-06-17 12:06 UTC, OfficialEsco commented on manifests/t/TeamRadarr/Radarr/3.2.2.5080/TeamRadarr.Radarr.locale.en-US.yaml
> +PackageVersion: 3.2.2.5080
```suggestion
PackageVersion: 3.2.2
```
![image](https://user-images.githubusercontent.com/15158490/122393121-d7496700-cf74-11eb-8083-7022f2526b58.png)

2021-06-17 12:06 UTC, OfficialEsco commented on manifests/t/TeamRadarr/Radarr/3.2.2.5080/TeamRadarr.Radarr.locale.en-US.yaml
> +Publisher: Team.Radarr
```suggestion
Publisher: Team Radarr
```

2021-06-17 12:06 UTC, OfficialEsco commented on manifests/t/TeamRadarr/Radarr/3.2.2.5080/TeamRadarr.Radarr.yaml
> +PackageVersion: 3.2.2.5080
```suggestion
PackageVersion: 3.2.2
```

2021-06-17 15:11 UTC, mikeparkie commented
@OfficialEsco yep, understood now, I know that for next time. I'll re-raise if the devs update the packages.

2021-06-17 15:14 UTC, OfficialEsco commented
> @OfficialEsco yep, understood now, I know that for next time. I'll re-raise if the devs update the packages.

Does it matter that much tho? How often does it update under a version like 3.2.2?

2021-06-17 15:17 UTC, mikeparkie commented
Actually, that's a good point and thinking about it they all have auto updaters, so the short version isn't to bad. I'll accept those suggestions now 👍

2021-06-17 15:24 UTC, OfficialEsco commented
I would recommend you to do these changes in GitHub Desktop as you need to change the folder name

2021-06-17 20:53 UTC, OfficialEsco requested changes
Ohhnoo so close 🤦‍♂️

2021-06-17 20:53 UTC, OfficialEsco commented on manifests/t/TeamRadarr/Radarr/3.2.2/TeamRadarr.Radarr.locale.en-US.yaml
> +Publisher: TeamRadarr
```suggestion
Publisher: Team Radarr
```

2021-06-18 06:39 UTC, OfficialEsco approved these changes
🎉

2021-06-18 06:39 UTC, merged