Abyss.AbyssOverlay version 1.2.2
microsoft/winget-pkgs pull request #18016
Opened 2021-06-18 18:15 UTC by TakenMC

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-06-18 21:48 UTC, OfficialEsco requested changes

2021-06-18 21:48 UTC, OfficialEsco commented on manifests/a/Abyss/AbyssOverlay/1.2.2/Abyss.AbyssOverlay.installer.yaml
> +  InstallerSha256: 471D8FDCF6903A72C5FDFB76F49923BD2DEA3166D4CD462F76560B4D65D227C5
```suggestion
- Architecture: neutral
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/Chit132/abyss-overlay/releases/download/v1.2.2/Abyss.Overlay.Setup.v1.2.2.exe
  InstallerSha256: 471D8FDCF6903A72C5FDFB76F49923BD2DEA3166D4CD462F76560B4D65D227C5
  InstallerSwitches:
    Custom: /NORESTART /CURRENTUSER
- Architecture: neutral
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://github.com/Chit132/abyss-overlay/releases/download/v1.2.2/Abyss.Overlay.Setup.v1.2.2.exe
  InstallerSha256: 471D8FDCF6903A72C5FDFB76F49923BD2DEA3166D4CD462F76560B4D65D227C5
  InstallerSwitches:
    Custom: /NORESTART /ALLUSERS
```

For compatability.

2021-06-18 21:48 UTC, OfficialEsco commented on manifests/a/Abyss/AbyssOverlay/1.2.2/Abyss.AbyssOverlay.locale.en-US.yaml
> +Publisher: Abyss
```suggestion
Publisher: Chit
Author: Abyss
```
Needs to match what control panel sees

2021-06-26 04:50 UTC, TakenMC commented
Sorry I forgot
I approve the changes and you can merge it

2021-06-26 07:42 UTC, OfficialEsco requested changes
You need to commit the changes.

2021-06-26 21:20 UTC, TakenMC commented
There updated

2021-06-26 23:35 UTC, OfficialEsco approved these changes

2021-06-26 23:35 UTC, merged