New package: Mostaqem.Mostaqem version 2.1.0
microsoft/winget-pkgs pull request #180396
Opened 2024-10-09 17:04 UTC by MezoPeeta

### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.6.0 :rocket:

2024-10-09 17:06 UTC, MezoPeeta commented
@microsoft-github-policy-service agree

2024-10-09 19:13 UTC, stephengillie commented
Automatic Validation ended with:

> Caught exception while trying to kill child processes: System.AggregateException: Not all processes in process tree could be terminated. (Access is denied.)
>  ---> System.ComponentModel.Win32Exception (5): Access is denied.
> Executable C:\Program Files\Mostaqem\mostaqem.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 896.)

2024-10-09 19:20 UTC, stephengillie requested changes
Hi @MezoPeeta, 

It appears that this package has a dependency on `VCRedist`: 
![image](https://github.com/user-attachments/assets/0d6fff44-cab7-472b-9493-e2efc11340d8)

2024-10-09 19:20 UTC, stephengillie commented on manifests/m/Mostaqem/Mostaqem/2.1.0/Mostaqem.Mostaqem.installer.yaml
> +Installers:
```suggestion
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
```

2024-10-10 02:24 UTC, stephengillie commented
Verify:
![image](https://github.com/user-attachments/assets/8398b3d3-273c-42c6-88b5-f0dd23fc7fa0)
I couldn't find how to have the application display its version.
![image](https://github.com/user-attachments/assets/bc427c85-11ec-4683-8f2e-510943710257)

2024-10-10 02:24 UTC, stephengillie approved these changes

2024-10-10 02:24 UTC, merged