Changing VMware.WorkstationPro version 16.1.1
microsoft/winget-pkgs pull request #18334
Opened 2021-06-21 02:57 UTC by ImJoakim

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-06-21 09:49 UTC, KaranKad requested changes

2021-06-21 09:49 UTC, KaranKad commented on manifests/v/VMware/WorkstationPro/16.1.1/VMware.WorkstationPro.locale.en-US.yaml
> +Moniker: vmware-workstation
```suggestion
Moniker: vmware-workstation-pro
```

2021-06-21 16:30 UTC, KaranKad commented
Looks like validation has been stopped for a while.
Also winget isn't working 
![image](https://user-images.githubusercontent.com/71691514/122796500-1876a980-d2dc-11eb-8536-8d47d3ad47e5.png)

2021-06-21 17:25 UTC, denelon commented
@KaranKad this was due to an upgrade of the pipelines, and a rebuild of the PreIndexed package. We're looking at a way to eliminate the temporary outage caused when this happens. It was part of publishing the duplicate hash check feature. We've got one more PR to merge on the back end, and then we will enable the feature. You should see "Possible-Duplicate" tag added to PRs when we detect a duplicate "InstallerSha256" one this is fully implemented.

2021-06-21 20:05 UTC, ImJoakim commented
@denelon Any reason why some of my PRs are stuck on the Installer check? Some of them went through, but these appear to be stuck. I tried rerunning them myself by closing and opening the PR, but it still gets stuck.

#18327 
#18332 
#18334
#18425
#18421

2021-06-23 14:05 UTC, ImJoakim commented
Seems like the 5 PRs that I mentioned above are still stuck, I'll try to close them and open new ones.

2021-06-23 14:05 UTC, closed without merging