New version: Telerik.Fiddler.Classic version 5.0.20245.10105
microsoft/winget-pkgs pull request #184750
Opened 2024-10-21 12:18 UTC by spectopo

Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#8964](https://github.com/SpecterShell/Dumplings/actions/runs/11439809592).

<details>

<summary>Log</summary>

````
Updated: 5.0.20244.10953 → 5.0.20245.10105
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

2024-10-21 16:20 UTC, stephengillie commented
URL: https://downloads.getfiddler.com/fiddler-classic/FiddlerSetup.5.0.20245.10105-latest.exe 
Status Code: 200

(Automated message - build 897)

2024-10-21 21:02 UTC, ItzLevvie approved these changes

2024-10-22 00:06 UTC, stephengillie requested changes
> Url validation error
> 
> * manifests\t\Telerik\Fiddler\Classic\5.0.20245.10105
>   
>   * https://www.telerik.com/support/whats-new/fiddler/release-history/fiddler-v5.0.20245
>     
>     * Http status code: NotFound

I get:
![image](https://github.com/user-attachments/assets/a76c0673-7f7b-45f4-8ca2-bc51d27c20ee)

2024-10-22 00:06 UTC, stephengillie commented on manifests/t/Telerik/Fiddler/Classic/5.0.20245.10105/Telerik.Fiddler.Classic.locale.en-US.yaml
> +ReleaseNotesUrl: https://www.telerik.com/support/whats-new/fiddler/release-history/fiddler-v5.0.20245
```suggestion
# ReleaseNotesUrl: 
```

2024-10-22 15:59 UTC, stephengillie approved these changes

2024-10-22 22:20 UTC, ItzLevvie approved these changes

2024-10-23 16:27 UTC, merged