New version: prefix-dev.pixi version 0.34.0
microsoft/winget-pkgs pull request #184932
Opened 2024-10-22 07:17 UTC by ruben-arts

### Pull request has been created with [WinGet Releaser v2](https://github.com/vedantmgoyal2009/winget-releaser) :rocket:

2024-10-22 15:21 UTC, stephengillie commented
Automatic Validation ended with:
> 

(Automated response - build 897.)

2024-10-30 08:29 UTC, traversaro commented
> Hello @ruben-arts,
> 
> This pull request has been automatically marked as stale because it has been marked as requiring author feedback but has not had any recent activity. It will be closed if no further activity occurs **within 3 days of this comment**.
> 
> Template: msftbot/noRecentActivity

fyi @ruben-arts, I do not have experience with winget, but do you think something could be done for this? Thanks!

2024-10-30 15:58 UTC, ItzLevvie commented
@wingetbot run

2024-10-30 16:11 UTC, ruben-arts commented
Apparently you triggered a rerun @traversaro, so hopefully it will go in soon. I don't see why it would not succeed and those errors make no sense. 

Thanks for the ping though, these winget PR's almost always fail and then resolve themself so I got blind for their emails.

2024-11-04 18:35 UTC, ItzLevvie commented
@wingetbot run

2024-11-05 00:10 UTC, stephengillie requested changes
Automatic Validation ended with:
> Actual hash:   60170A28BDB2560F62819EE3165A8A3A7F2ABD3BAEFBB7DEA5E2CD6DD608E49C
Expected hash: 3411d707b9e93d5f2726fec5f6d6d1f7a9715d049febc67d0d909bac2e6fcc03

2024-11-05 00:10 UTC, stephengillie commented on manifests/p/prefix-dev/pixi/0.34.0/prefix-dev.pixi.installer.yaml
> +  InstallerSha256: 3411D707B9E93D5F2726FEC5F6D6D1F7A9715D049FEBC67D0D909BAC2E6FCC03
```suggestion
  InstallerSha256: 60170A28BDB2560F62819EE3165A8A3A7F2ABD3BAEFBB7DEA5E2CD6DD608E49C
```

2024-11-12 16:06 UTC, closed without merging