New version: c0re100.qBittorrent-Enhanced-Edition version 5.0.0.10
microsoft/winget-pkgs pull request #185659
Opened 2024-10-25 03:10 UTC by c0re100

### Pull request has been created with [WinGet Releaser v2](https://github.com/vedantmgoyal2009/winget-releaser) :rocket:

2024-10-25 13:21 UTC, stephengillie commented
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-10-24 20:25:26.527 [CLI ] ShellExecute installer failed: 1654

Automated error analysis suggests -1978335226 may mean Running ShellExecute failed

Automated error analysis suggests 1654 may mean `ERROR_INSTALL_REJECTED` - The app that you are trying to run is not supported on this version of Windows. Does this manifest have `Architecture: x86`? It might need to be `x64`.

(Automated response - build 897.)

2024-10-26 09:32 UTC, vedantmgoyal9 commented on manifests/c/c0re100/qBittorrent-Enhanced-Edition/5.0.0.10/c0re100.qBittorrent-Enhanced-Edition.installer.yaml
> +- Architecture: x86
```suggestion
```

2024-10-26 09:32 UTC, vedantmgoyal9 commented on manifests/c/c0re100/qBittorrent-Enhanced-Edition/5.0.0.10/c0re100.qBittorrent-Enhanced-Edition.installer.yaml
> +  InstallerUrl: https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-5.0.0.10/qbittorrent_enhanced_5.0.0.10_x64_setup.exe
```suggestion```

2024-10-26 09:49 UTC, sitiom requested changes

2024-10-26 09:49 UTC, sitiom commented on manifests/c/c0re100/qBittorrent-Enhanced-Edition/5.0.0.10/c0re100.qBittorrent-Enhanced-Edition.installer.yaml
> +  InstallerSha256: 618E392F70AE56055D95556E027AA891B63F81899D364C83ADB95854FD86F6A8
```suggestion
```

2024-10-29 01:15 UTC, stephengillie approved these changes

2024-10-29 01:15 UTC, merged