Submitting NTop version 0.3.20
microsoft/winget-pkgs pull request #185978
Opened 2024-10-27 06:51 UTC by gsass1

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ x Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-10-27 06:54 UTC, gsass1 commented
@microsoft-github-policy-service agree

2024-10-29 15:50 UTC, stephengillie commented
@wingetbot run

2024-10-31 03:50 UTC, stephengillie commented
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\gsass1.NTop__DefaultSource\ntop.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ntop.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 897.)

2024-10-31 20:21 UTC, stephengillie requested changes
Hi @gsass1,

This package appears to have a dependency on `Microsoft.VCRedist.2015+.x64`:
![image](https://github.com/user-attachments/assets/3109ca08-b598-4c46-ae49-1c0b2342572b)

2024-10-31 20:21 UTC, stephengillie commented on manifests/g/gsass1/NTop/0.3.20/gsass1.NTop.installer.yaml
> +Installers:
```suggestion
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
```

2024-11-04 22:16 UTC, stephengillie approved these changes

2024-11-04 22:16 UTC, merged