Add SigmaNight.BasiliskLLM version 0.1a8
microsoft/winget-pkgs pull request #186062
Opened 2024-10-27 21:31 UTC by clementb49

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-10-27 21:41 UTC, clementb49 commented
@microsoft-github-policy-service agree

2024-10-29 15:55 UTC, stephengillie commented
@wingetbot run

2024-10-31 03:51 UTC, stephengillie commented
Automatic Validation ended with:

> Executable C:\Program Files\basilisk_llm\basilisk.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Programs\basilisk_llm\basilisk.exe returned exit code: -1073741515
> Executable C:\Users\Validator\AppData\Local\Programs\basilisk_llm\basilisk.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 897.)

2024-10-31 20:27 UTC, stephengillie requested changes
Hi @clementb49,

This package appears to have a dependency on `Microsoft.VCRedist.2015+.x64`:
![image](https://github.com/user-attachments/assets/6fa09d74-d58b-4c87-9fd7-dcb2b2476ccc)

2024-10-31 20:27 UTC, stephengillie commented on manifests/s/SigmaNight/basiliskLLM/0.1a8/SigmaNight.basiliskLLM.installer.yaml
> +  InstallerSha256: 373B54D72F2C12897647A3E3EA57BEEC43B232F4941161D47E677BB601228B16
```suggestion
  InstallerSha256: 373B54D72F2C12897647A3E3EA57BEEC43B232F4941161D47E677BB601228B16
  Dependencies:
    PackageDependencies:
      - PackageIdentifier: Microsoft.VCRedist.2015+.x64
```

2024-10-31 20:27 UTC, stephengillie commented on manifests/s/SigmaNight/basiliskLLM/0.1a8/SigmaNight.basiliskLLM.installer.yaml
> +  InstallerSha256: 373B54D72F2C12897647A3E3EA57BEEC43B232F4941161D47E677BB601228B16
```suggestion
  InstallerSha256: 373B54D72F2C12897647A3E3EA57BEEC43B232F4941161D47E677BB601228B16
  Dependencies:
    PackageDependencies:
      - PackageIdentifier: Microsoft.VCRedist.2015+.x64
```

2024-10-31 20:27 UTC, stephengillie commented on manifests/s/SigmaNight/basiliskLLM/0.1a8/SigmaNight.basiliskLLM.installer.yaml
> +  InstallerSha256: FD45B800ECC207C689AA569CF9592C0B402798670A4131F428CAA5ABB49DC760
```suggestion
  InstallerSha256: FD45B800ECC207C689AA569CF9592C0B402798670A4131F428CAA5ABB49DC760
  Dependencies:
    PackageDependencies:
      - PackageIdentifier: Microsoft.VCRedist.2015+.x86
```

2024-10-31 20:27 UTC, stephengillie commented on manifests/s/SigmaNight/basiliskLLM/0.1a8/SigmaNight.basiliskLLM.installer.yaml
> +  InstallerSha256: FD45B800ECC207C689AA569CF9592C0B402798670A4131F428CAA5ABB49DC760
```suggestion
  InstallerSha256: FD45B800ECC207C689AA569CF9592C0B402798670A4131F428CAA5ABB49DC760
  Dependencies:
    PackageDependencies:
      - PackageIdentifier: Microsoft.VCRedist.2015+.x86
```

2024-11-01 13:03 UTC, clementb49 commented
Hello @stephengillie I don't understand why the validation phase isn't passing.

2024-11-01 16:28 UTC, stephengillie commented
@wingetbot waivers Add Validation-Installation-Error

2024-11-01 16:30 UTC, stephengillie approved these changes

2024-11-01 16:30 UTC, merged