Added Octopus Tentacle version 6.1.736.
microsoft/winget-pkgs pull request #18632
Opened 2021-06-23 13:11 UTC by jedieaston

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

2021-06-23 15:16 UTC, ItzLevvie requested changes

2021-06-23 15:16 UTC, ItzLevvie commented on manifests/o/OctopusDeploy/Tentacle/6.1.736/OctopusDeploy.Tentacle.locale.en-US.yaml
> +Publisher: Octopus Deploy
```suggestion
Publisher: Octopus Deploy Pty. Ltd.
```

2021-06-23 15:16 UTC, ItzLevvie commented on manifests/o/OctopusDeploy/Tentacle/6.1.736/OctopusDeploy.Tentacle.locale.en-US.yaml
> +PackageName: Octopus Tentacle
```suggestion
PackageName: Octopus Deploy Tentacle
```

2021-06-24 06:33 UTC, OfficialEsco approved these changes

2021-06-24 06:33 UTC, merged