SurgeSynth.Surge version 1.9.0
microsoft/winget-pkgs pull request #18699
Opened 2021-06-23 23:29 UTC by chausner

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-06-24 16:29 UTC, ChuckFerring commented
The installer runs but I don't see that it installed anything. What is the location of the installed application?

2021-06-24 16:51 UTC, chausner commented
> The installer runs but I don't see that it installed anything. What is the location of the installed application?

It gets installed to C:\Program Files\Common Files\VST3. It is a VST3 plugin and cannot be used standalone but only through DAW software that loads the plugin.

2021-06-24 16:54 UTC, chausner commented
Any idea why the installation validation fails?

2021-06-25 18:36 UTC, OfficialEsco requested changes

2021-06-25 18:36 UTC, OfficialEsco commented on manifests/s/SurgeSynth/Surge/1.9.0/SurgeSynth.Surge.locale.en-US.yaml
> +PackageName: Surge
```suggestion
PackageName: SST Surge
```
Sadly it needs to pass validation once more because it needs to match ARP :c

2021-06-28 18:59 UTC, OfficialEsco approved these changes

2021-06-29 15:20 UTC, ItzLevvie approved these changes

2021-06-29 15:21 UTC, merged