New package: MoonshotAI.Kimi version 1.1.2
microsoft/winget-pkgs pull request #188133
Opened 2024-11-02 15:05 UTC by SpecterShell

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-11-03 14:20 UTC, ItzLevvie approved these changes

2024-11-03 23:42 UTC, ItzLevvie approved these changes

2024-11-04 11:01 UTC, ItzLevvie approved these changes

2024-11-04 15:23 UTC, stephengillie commented
Automatic Validation ended with:

> Executable C:\Program Files\Kimi智能助手\app\resources\lib\parfait_crash_handler.exe returned exit code: -1073741515
> Executable C:\Program Files\Kimi智能助手\Kimi智能助手.exe returned exit code: 2

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 897.)

2024-11-05 12:17 UTC, ItzLevvie approved these changes

2024-11-05 13:06 UTC, ItzLevvie approved these changes

2024-11-05 17:29 UTC, ItzLevvie approved these changes

2024-11-05 18:22 UTC, ItzLevvie approved these changes

2024-11-05 22:22 UTC, ItzLevvie approved these changes

2024-11-05 23:25 UTC, ItzLevvie approved these changes

2024-11-06 03:46 UTC, stephengillie requested changes
![image](https://github.com/user-attachments/assets/22febbea-9f27-41ce-aaec-6261b6070f5a)

2024-11-06 03:46 UTC, stephengillie commented on manifests/m/MoonshotAI/Kimi/1.1.2/MoonshotAI.Kimi.installer.yaml
> +Installers:
```suggestion
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
```

2024-11-06 14:34 UTC, ItzLevvie approved these changes

2024-11-06 17:27 UTC, stephengillie commented
Hi @SpecterShell,

Verify:
![image](https://github.com/user-attachments/assets/a25a2be5-9f7f-4993-b191-f4141e916e3d)
The installer appeared to run normally, but double-clicking the desktop shortcut doesn't seem to have any effect. Is this expected?

2024-11-06 21:40 UTC, ItzLevvie approved these changes

2024-11-07 13:44 UTC, ItzLevvie approved these changes

2024-11-07 14:05 UTC, SpecterShell commented
> Hi @SpecterShell,
> 
> Verify: ![image](https://private-user-images.githubusercontent.com/114952565/383663242-a25a2be5-9f7f-4993-b191-f4141e916e3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODgxNzAsIm5iZiI6MTczMDk4Nzg3MCwicGF0aCI6Ii8xMTQ5NTI1NjUvMzgzNjYzMjQyLWEyNWEyYmU1LTlmN2YtNDk5My1iMTkxLWY0MTQxZTkxNmUzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxMzU3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTY0ZGVlMTZlOTRjMGY4ZmE4OGQyY2RiZGFmNzM0OGRhYTE4YzYxYzcyN2RkYjllNDMwZjllZjk2MWI1NjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9zH-q6nPw_X9xzYW2y5TRUAy8rkIVDZNHaQw7dkglAw) The installer appeared to run normally, but double-clicking the desktop shortcut doesn't seem to have any effect. Is this expected?

Appears to be an encoding bug with Java. Both the default installation directory and the name of config file inside contain Chinese characters, so the program would crash at startup if the non-Unicode encoding was not set to Simplified Chinese.

2024-11-07 17:23 UTC, stephengillie commented
That's a rather major bug. How should this PR proceed?

2024-11-07 20:22 UTC, ItzLevvie approved these changes

2024-11-08 02:12 UTC, SpecterShell commented
> That's a rather major bug. How should this PR proceed?

Simply merging it? Users in need of this package should not be affected by that. 👻

2024-11-08 13:32 UTC, ItzLevvie approved these changes

2024-11-08 16:00 UTC, stephengillie approved these changes

2024-11-08 16:00 UTC, merged