New package: MevLyshkin.uec version 0.2.0
microsoft/winget-pkgs pull request #190138
Opened 2024-11-09 15:23 UTC by Leinnan

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-11-09 15:30 UTC, Leinnan commented
@microsoft-github-policy-service agree

2024-11-11 14:21 UTC, stephengillie commented
Automatic Validation ended with:

> Executable C:\Program Files\uec\bin\uec.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 897.)

2024-11-11 14:44 UTC, Leinnan commented
@stephengillie Okay, what should I do with it?

2024-11-11 14:46 UTC, stephengillie requested changes
Manual Validation ended with:
![image](https://github.com/user-attachments/assets/55d22ae1-f501-464f-93b6-03ef392f6bb7)

2024-11-11 14:46 UTC, stephengillie commented on manifests/m/MevLyshkin/uec/0.2.0/MevLyshkin.uec.installer.yaml
> +Installers:
```suggestion
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
```

2024-11-11 17:24 UTC, stephengillie approved these changes

2024-11-11 17:24 UTC, stephengillie commented
Verify:
![image](https://github.com/user-attachments/assets/18241aa9-ce9b-4ba7-99dc-1fe9a2f0c57d)

2024-11-11 17:24 UTC, merged