New version: KuaiFan.DooTask version 0.39.97
microsoft/winget-pkgs pull request #190458
Opened 2024-11-11 16:12 UTC by spectopo

Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#9473](https://github.com/SpecterShell/Dumplings/actions/runs/11782091117).

<details>

<summary>Log</summary>

````
Updated: 0.39.88 → 0.39.97
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

2024-11-11 20:20 UTC, stephengillie commented
Automatic Validation ended with:

> Installation failed with exit code -2145844844
> 2024-11-11 08:26:24.861 [CORE] DeliveryOptimization error: 0x80190194, extended error: 0x00000000
> 2024-11-11 08:26:24.899 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFBA3CCA465: (caller: 00007FFBA3CCAD01) Exception(1) tid(414) 80190194 Not found (404).
> 2024-11-11 08:26:25.453 [CORE] Download request failed. Returned status: 404
> 2024-11-11 08:26:25.453 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFBA3CC43D6: (caller: 00007FFBA3CC5C49) Exception(2) tid(414) 80190194 Not found (404).
> 2024-11-11 08:26:25.622 [CLI ] Failed to download, waiting a bit and retry. Url: https://github.com/kuaifan/dootask/releases/download/v0.39.97/DooTask-v0.39.97-win-x64.exe
> 2024-11-11 08:26:27.924 [CORE] DeliveryOptimization error: 0x80190194, extended error: 0x00000000
> 2024-11-11 08:26:27.924 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFBA3CCA465: (caller: 00007FFBA3CCAD01) Exception(3) tid(414) 80190194 Not found (404).
> 2024-11-11 08:26:28.021 [CORE] Download request failed. Returned status: 404
> 2024-11-11 08:26:28.021 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFBA3CC43D6: (caller: 00007FFBA3CC5C49) Exception(4) tid(414) 80190194 Not found (404).
> 2024-11-11 08:26:21.095 [CORE] DeliveryOptimization error: 0x80190194, extended error: 0x00000000
> 2024-11-11 08:26:21.130 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFBB3DFA465: (caller: 00007FFBB3DFAD01) Exception(1) tid(1998) 80190194 Not found (404).
> 2024-11-11 08:26:21.763 [CORE] Download request failed. Returned status: 404
> 2024-11-11 08:26:21.763 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFBB3DF43D6: (caller: 00007FFBB3DF5C49) Exception(2) tid(1998) 80190194 Not found (404).
> 2024-11-11 08:26:22.014 [CLI ] Failed to download, waiting a bit and retry. Url: https://github.com/kuaifan/dootask/releases/download/v0.39.97/DooTask-v0.39.97-win-x64.exe
> 2024-11-11 08:26:24.330 [CORE] DeliveryOptimization error: 0x80190194, extended error: 0x00000000
> 2024-11-11 08:26:24.330 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFBB3DFA465: (caller: 00007FFBB3DFAD01) Exception(3) tid(1998) 80190194 Not found (404).
> 2024-11-11 08:26:24.397 [CORE] Download request failed. Returned status: 404
> 2024-11-11 08:26:24.397 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFBB3DF43D6: (caller: 00007FFBB3DF5C49) Exception(4) tid(1998) 80190194 Not found (404).

Automated error analysis suggests -2145844844 may mean Not Found (404).

Automated error analysis suggests 80190194 may mean Not found (404).

(Automated response - build 897.)

2024-11-12 20:45 UTC, ItzLevvie approved these changes

2024-11-12 22:07 UTC, ItzLevvie approved these changes

2024-11-13 01:28 UTC, stephengillie requested changes
> 11/12/2024 4:09:27 AM
Installer Verification Analysis Context Information: 
Specified hash doesn't match.
Actual hash:   3FE97FD8DDE28D7F3CC6B28CBAA83D6C9C7C590775C717E52CA8494B4DEE7D82
Expected hash: 154e231f60a37fea425c1209fafb4f36ddccefa754d5b94150c3f91e09ee266e
Specified hash doesn't match.
Actual hash:   FE024A77D49A940B0537E588D4976B244E1B19C20F070C36952D81B30D3AFCAB
Expected hash: 52bbc172d920f347bba814d8151da900bf6fb1fc32a101350e0b1aa4195ded28

2024-11-13 01:28 UTC, stephengillie commented on manifests/k/KuaiFan/DooTask/0.39.97/KuaiFan.DooTask.installer.yaml
> +  InstallerSha256: 154E231F60A37FEA425C1209FAFB4F36DDCCEFA754D5B94150C3F91E09EE266E
```suggestion
  InstallerSha256: 3FE97FD8DDE28D7F3CC6B28CBAA83D6C9C7C590775C717E52CA8494B4DEE7D82
```

2024-11-13 01:28 UTC, stephengillie commented on manifests/k/KuaiFan/DooTask/0.39.97/KuaiFan.DooTask.installer.yaml
> +  InstallerSha256: 154E231F60A37FEA425C1209FAFB4F36DDCCEFA754D5B94150C3F91E09EE266E
```suggestion
  InstallerSha256: 3FE97FD8DDE28D7F3CC6B28CBAA83D6C9C7C590775C717E52CA8494B4DEE7D82
```

2024-11-13 01:28 UTC, stephengillie commented on manifests/k/KuaiFan/DooTask/0.39.97/KuaiFan.DooTask.installer.yaml
> +  InstallerSha256: 52BBC172D920F347BBA814D8151DA900BF6FB1FC32A101350E0B1AA4195DED28
```suggestion
  InstallerSha256: FE024A77D49A940B0537E588D4976B244E1B19C20F070C36952D81B30D3AFCAB
```

2024-11-13 01:28 UTC, stephengillie commented on manifests/k/KuaiFan/DooTask/0.39.97/KuaiFan.DooTask.installer.yaml
> +  InstallerSha256: 52BBC172D920F347BBA814D8151DA900BF6FB1FC32A101350E0B1AA4195DED28
```suggestion
  InstallerSha256: FE024A77D49A940B0537E588D4976B244E1B19C20F070C36952D81B30D3AFCAB
```

2024-11-13 21:18 UTC, ItzLevvie approved these changes

2024-11-13 22:26 UTC, ItzLevvie approved these changes

2024-11-14 00:32 UTC, ItzLevvie approved these changes

2024-11-14 16:09 UTC, ItzLevvie approved these changes

2024-11-14 23:45 UTC, ItzLevvie approved these changes

2024-11-15 01:14 UTC, ItzLevvie approved these changes

2024-11-15 12:23 UTC, ItzLevvie approved these changes

2024-11-15 18:29 UTC, ItzLevvie commented
@wingetbot run

2024-11-16 16:38 UTC, ItzLevvie approved these changes

2024-11-17 12:51 UTC, ItzLevvie approved these changes

2024-11-18 12:59 UTC, ItzLevvie approved these changes

2024-11-18 14:55 UTC, ItzLevvie approved these changes

2024-11-18 15:12 UTC, ItzLevvie approved these changes

2024-11-18 15:23 UTC, ItzLevvie approved these changes

2024-11-18 18:39 UTC, ItzLevvie approved these changes

2024-11-18 20:46 UTC, stephengillie approved these changes

2024-11-18 20:46 UTC, merged