New version: Stellar.StellarCLI version 22.0.0-rc.1
microsoft/winget-pkgs pull request #191259
Opened 2024-11-13 20:40 UTC by fnando

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-11-13 20:41 UTC, fnando commented
@microsoft-github-policy-service agree

2024-11-14 02:46 UTC, stephengillie commented
Automatic Validation ended with:

> Executable C:\Program Files (x86)\Stellar CLI\stellar.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 897.)

2024-11-14 03:35 UTC, stephengillie commented
HI @fnando,

Manual Validation ended with:
![image](https://github.com/user-attachments/assets/42db1267-2f71-4f81-aa93-702b00a28850)

Is there a way to bypass this prompt and complete the install silently?

2024-11-14 03:38 UTC, stephengillie requested changes
Manual Validation ended with:
![image](https://github.com/user-attachments/assets/edd9ce68-e592-46f9-b879-dc51b9f36e7c)

2024-11-14 03:38 UTC, stephengillie commented on manifests/s/Stellar/StellarCLI/22.0.0-rc.1/Stellar.StellarCLI.installer.yaml
> +Installers:
```suggestion
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
```

2024-11-14 18:10 UTC, fnando commented
@stephengillie thank you for the review. I ended up replacing NSIS with Inno Setup, which worked without any dependencies like Microsoft.VCRedist.2015+.x64 (I've tested without having any of this installed).

2024-11-14 23:07 UTC, stephengillie commented
Automatic Validation ended with:

> Executable C:\Program Files (x86)\Stellar CLI\stellar.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 897.)

2024-11-14 23:14 UTC, stephengillie commented
Manual Validation ended with:
> 
> 2024-11-14 15:14:23.438 [FAIL] Installer failed security check. Url: https://github.com/stellar/stellar-cli/releases/download/v22.0.0-rc.1/stellar-cli-installer-22.0.0-rc.1-x86_64-pc-windows-msvc.exe Result: 0x80004005

(Automated response - build 897.)

2024-11-14 23:49 UTC, leighmcculloch reviewed
Two comments.

2024-11-14 23:49 UTC, leighmcculloch commented on manifests/s/Stellar/StellarCLI/22.0.0-rc.1/Stellar.StellarCLI.locale.en-US.yaml
> +Moniker: soroban
Unclear why we need to mention soroban here. Soroban is the execution runtime that the Stellar network uses. It's not built into the Stellar-CLI, and the Stellar-CLI is primarily about interacting with the Stellar network, not the execution runtime. A while ago the CLI carried the name "soroban-cli" due to historical hang over.

2024-11-14 23:49 UTC, leighmcculloch commented on manifests/s/Stellar/StellarCLI/22.0.0-rc.1/Stellar.StellarCLI.locale.en-US.yaml
> +Publisher: Stellar
@fnando I think the publisher would be the full foundation's name.
```suggestion
Publisher: Stellar Development Foundation
```

2024-11-15 18:24 UTC, stephengillie commented
Verify:
![image](https://github.com/user-attachments/assets/2cdb84c7-d6de-4279-9749-c3801cffa9f7)

2024-11-15 18:25 UTC, stephengillie approved these changes

2024-11-15 18:25 UTC, merged

2024-11-15 23:38 UTC, fnando commented
@stephengillie this should be available by now, right?

```
 winget source update && winget search --id Stellar.StellarCLI
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
  █████████████████████████████▋  99%
Done
No package found matching input criteria.
```

2024-12-19 22:11 UTC, stephengillie commented
Hi @fnando,

Sorry for not replying earlier. It probably needed to wait for the next Publish pipeline run to complete.