New version: ToEverything.AFFiNE version 0.18.0 (0.18.0)
microsoft/winget-pkgs pull request #191423
Opened 2024-11-14 04:11 UTC by spectopo

Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#9534](https://github.com/SpecterShell/Dumplings/actions/runs/11830479666).

<details>

<summary>Log</summary>

````
Updated: 0.17.5 → 0.18.0
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

2024-11-14 16:08 UTC, ItzLevvie approved these changes

2024-11-14 23:44 UTC, ItzLevvie approved these changes

2024-11-15 01:13 UTC, ItzLevvie approved these changes

2024-11-15 12:23 UTC, ItzLevvie approved these changes

2024-11-15 20:15 UTC, stephengillie requested changes

2024-11-15 20:15 UTC, stephengillie commented on manifests/t/ToEverything/AFFiNE/0.18.0/ToEverything.AFFiNE.locale.en-US.yaml
> +  DocumentUrl: https://docs.affine.pro/docs/hello-bonjour-aloha-你好
```suggestion
#  DocumentUrl: 
```

2024-11-15 20:15 UTC, stephengillie commented on manifests/t/ToEverything/AFFiNE/0.18.0/ToEverything.AFFiNE.locale.zh-CN.yaml
> +  DocumentUrl: https://docs.affine.pro/docs/hello-bonjour-aloha-你好
```suggestion
#  DocumentUrl: 
```

2024-11-16 16:37 UTC, ItzLevvie approved these changes

2024-11-17 12:51 UTC, ItzLevvie approved these changes

2024-11-18 12:59 UTC, ItzLevvie approved these changes

2024-11-18 14:55 UTC, ItzLevvie approved these changes

2024-11-18 15:12 UTC, ItzLevvie approved these changes

2024-11-18 15:23 UTC, ItzLevvie approved these changes

2024-11-18 18:39 UTC, ItzLevvie approved these changes

2024-11-18 20:55 UTC, stephengillie approved these changes

2024-11-18 20:55 UTC, merged