New version: GiulioSorrentino.WinDateFrom version 4.6.3
microsoft/winget-pkgs pull request #192740
Opened 2024-11-21 03:32 UTC by GiulianoSpaghetti

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-11-21 07:38 UTC, ItzLevvie approved these changes

2024-11-23 20:46 UTC, ItzLevvie approved these changes

2024-11-26 01:04 UTC, stephengillie requested changes
> Manifest is invalid. (Line: 10, Col: 3, Idx: 323) - (Line: 10, Col: 4, Idx: 324): While parsing a block mapping, did not find expected key.

2024-11-26 01:04 UTC, stephengillie commented on manifests/g/GiulioSorrentino/WinDateFrom/4.6.3/GiulioSorrentino.WinDateFrom.installer.yaml
> +  9
```suggestion
```

2024-12-02 22:13 UTC, GiulianoSpaghetti commented
smart screen?

2024-12-08 23:16 UTC, ItzLevvie approved these changes

2024-12-08 23:29 UTC, ItzLevvie commented
@wingetbot run

2024-12-09 21:42 UTC, stephengillie approved these changes

2024-12-09 21:42 UTC, merged