New version: Genesys.GenesysCloud version 2.40.811
microsoft/winget-pkgs pull request #192987
Opened 2024-11-22 00:34 UTC by PckgrMiranda

### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.6.0 :rocket:

2024-11-22 13:43 UTC, ItzLevvie approved these changes

2024-11-23 05:14 UTC, Trenly requested changes

2024-11-23 05:14 UTC, Trenly commented on manifests/g/Genesys/GenesysCloud/2.40.811/Genesys.GenesysCloud.installer.yaml
> +  - DisplayVersion: 2.34.771.0
```suggestion
```

2024-11-23 05:14 UTC, Trenly commented on manifests/g/Genesys/GenesysCloud/2.40.811/Genesys.GenesysCloud.installer.yaml
> +    DisplayVersion: 2.40.811.0
```suggestion
```

2024-11-23 05:18 UTC, Trenly approved these changes

2024-11-23 06:37 UTC, Trenly commented
Hmmm . . .

2024-11-25 19:16 UTC, stephengillie approved these changes

2024-11-25 19:16 UTC, merged