New version: HHDSoftware.FreeHexEditorNeo version 7.50.02.8795
microsoft/winget-pkgs pull request #193185
Opened 2024-11-22 23:56 UTC by PckgrMiranda

### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.6.0 :rocket:

2024-11-22 23:59 UTC, PckgrMiranda commented
@PckgrTom

2024-11-23 05:08 UTC, Trenly requested changes

2024-11-23 05:08 UTC, Trenly commented on manifests/h/HHDSoftware/FreeHexEditorNeo/7.50.02.8795/HHDSoftware.FreeHexEditorNeo.locale.en-US.yaml
> +Description: Free:Freeware binary files editing tool
```suggestion
Description: Free Freeware binary files editing tool
```

2024-11-23 05:08 UTC, Trenly commented on manifests/h/HHDSoftware/FreeHexEditorNeo/7.50.02.8795/HHDSoftware.FreeHexEditorNeo.locale.en-US.yaml
> +ShortDescription: Free:Freeware binary files editing tool
```suggestion
ShortDescription: Free Freeware binary files editing tool
```

2024-11-23 05:22 UTC, Trenly requested changes

2024-11-23 05:22 UTC, Trenly commented on manifests/h/HHDSoftware/FreeHexEditorNeo/7.50.02.8795/HHDSoftware.FreeHexEditorNeo.installer.yaml
> +  InstallerSwitches: {}
@russelbanks - Is this a Komac error?

https://github.com/PckgrMiranda/winget-pkgs/blob/HHDSoftware.FreeHexEditorNeo-7.50.02.8795-99762F06F864461389F1E452320322EF/manifests/h/HHDSoftware/FreeHexEditorNeo/6.44.01.6234/HHDSoftware.FreeHexEditorNeo.installer.yaml

2024-11-23 05:22 UTC, Trenly commented on manifests/h/HHDSoftware/FreeHexEditorNeo/7.50.02.8795/HHDSoftware.FreeHexEditorNeo.installer.yaml
> +  InstallerSwitches: {}
@PckgrMiranda - Not sure why this happened, but for some reason the switches didn't copy over from the previous version

2024-11-27 13:30 UTC, ItzLevvie approved these changes

2024-11-29 14:09 UTC, ItzLevvie approved these changes

2024-11-29 14:31 UTC, ItzLevvie commented
@wingetbot run

2024-12-06 18:23 UTC, ItzLevvie commented
@wingetbot run

2024-12-15 07:17 UTC, closed without merging