New package: colmap.colmap version 3.11.0
microsoft/winget-pkgs pull request #194939
Opened 2024-11-28 16:09 UTC by jo-chemla

### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.6.0 :rocket:

2024-11-28 16:18 UTC, jo-chemla commented
Note: GUI can be launched by running batch file `%UserProfile%\AppData\Local\Microsoft\WinGet\Packages\colmap.colmap__DefaultSource\COLMAP.bat`

2024-12-06 19:35 UTC, stephengillie requested changes
This package appears to require `VCRedist`:
![image](https://github.com/user-attachments/assets/7841b9a8-cc6b-4bfa-a94c-b9c2f905d16d)

2024-12-06 19:35 UTC, stephengillie commented on manifests/c/colmap/colmap/3.11.0/colmap.colmap.installer.yaml
> +Installers:
```suggestion
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
```

2024-12-06 21:14 UTC, jo-chemla commented
Indeed that's correct

2024-12-09 18:24 UTC, stephengillie commented
Verify:
![image](https://github.com/user-attachments/assets/4d5d746c-ce8a-4882-975a-d223d16994af)
I couldn't get the application to produce any output. Is this expected?

2024-12-10 09:01 UTC, jo-chemla commented
Colmap can be run either as:
 - CLI, see [docs](https://colmap.github.io/cli.html), you can try `colmap help` to check it's well installed or the below command
 - or GUI, which indeed rely on the batch file linked. Are scripted apps prevented from being winget-pkgs, and only executables (zipped or not) and installers are allowed? `%UserProfile%\AppData\Local\Microsoft\WinGet\Packages\colmap.colmap__DefaultSource\COLMAP.bat`

```
# The project folder must contain a folder "images" with all the images.
$ DATASET_PATH=/path/to/project

$ colmap automatic_reconstructor \
    --workspace_path $DATASET_PATH \
    --image_path $DATASET_PATH/images
```

2024-12-19 04:27 UTC, Trenly commented
> * or GUI, which indeed rely on the batch file linked. Are scripted apps prevented from being winget-pkgs, and only executables (zipped or not) and installers are allowed?

This is correct; `.bat` files and other forms of scripts such as `.ps1` or `.cmd` are disallowed by policy. I'm going to see if I can get the bot to do what it's supposed to, so apologies in advance for "testing" on this PR

[Policy] Reset Labels

2024-12-19 04:27 UTC, Trenly commented
[Policy] Scripted Application

2025-01-04 00:09 UTC, closed without merging