New version: WonderIdea.FlipPDFPlus.Corporate version 7.5.17
microsoft/winget-pkgs pull request #195616
Opened 2024-12-02 07:09 UTC by spectopo

Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#9970](https://github.com/SpecterShell/Dumplings/actions/runs/12114269051).

<details>

<summary>Log</summary>

````
Updated: 7.4.1 → 7.5.17
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
The manifests for the last version 7.4.1 will be removed. Reason: No installer URL is changed compared with the last state while the version is updated
Creating a pull request
````

</details>

2024-12-02 16:22 UTC, stephengillie commented
Automatic Validation ended with:
> No errors to post.

(Automated response - build 899.)

2024-12-02 16:32 UTC, ItzLevvie approved these changes

2024-12-03 22:11 UTC, stephengillie requested changes
> 12/3/2024 2:46:32 AM
Installer Verification Analysis Context Information: 
Specified hash doesn't match.
Actual hash:   C7A543033755E40D183C1CED3AA2FDEACF1AD0F8C0825EA186380902D5E925C7
Expected hash: 9f73e27bc28f05c5738d7cc7899b787adc2624568a99079105f7404bb4d8533d

2024-12-03 22:11 UTC, stephengillie commented on manifests/w/WonderIdea/FlipPDFPlus/Corporate/7.5.17/WonderIdea.FlipPDFPlus.Corporate.installer.yaml
>    InstallerSha256: 9F73E27BC28F05C5738D7CC7899B787ADC2624568A99079105F7404BB4D8533D
```suggestion
  InstallerSha256: C7A543033755E40D183C1CED3AA2FDEACF1AD0F8C0825EA186380902D5E925C7
```

2024-12-06 06:11 UTC, closed without merging