SystweakSoftware.RightBackup version Right Backup
microsoft/winget-pkgs pull request #19611
Opened 2021-07-02 18:02 UTC by systweaksoftware

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-02 21:16 UTC, OfficialEsco requested changes
Missing Version?
@denelon how did this get past validation?

2021-07-06 16:11 UTC, denelon commented
@OfficialEsco, it passed due to a match between the folder structure and the version. I agree this does not look like a package version we want in the repository (assuming "Right Backup" is not a proper version for this package).

2021-07-06 16:16 UTC, OfficialEsco requested changes
I somehow didn't see the PackageVersion because i expected some kind of number

![image](https://user-images.githubusercontent.com/15158490/124633983-20128280-de86-11eb-9107-004bf1ec1eb8.png)
![image](https://user-images.githubusercontent.com/15158490/124634024-29035400-de86-11eb-88f9-daee4fad51a3.png)

2021-07-06 16:16 UTC, OfficialEsco commented on manifests/s/SystweakSoftware/RightBackup/Right Backup/SystweakSoftware.RightBackup.installer.yaml
> +PackageVersion: Right Backup
```suggestion
PackageVersion: 2.1.1000.6914
```

2021-07-06 16:16 UTC, OfficialEsco commented on manifests/s/SystweakSoftware/RightBackup/Right Backup/SystweakSoftware.RightBackup.locale.en-US.yaml
> +PackageVersion: Right Backup
```suggestion
PackageVersion: 2.1.1000.6914
```

2021-07-06 16:16 UTC, OfficialEsco commented on manifests/s/SystweakSoftware/RightBackup/Right Backup/SystweakSoftware.RightBackup.yaml
> +PackageVersion: Right Backup
```suggestion
PackageVersion: 2.1.1000.6914
```

2021-07-14 15:08 UTC, closed without merging