Added HeroicGamesLauncher.HeroicGamesLauncher version 1.8.1
microsoft/winget-pkgs pull request #19654
Opened 2021-07-03 07:03 UTC by quhxl

Closes #19647 

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-03 12:18 UTC, forecaster-cyber submitted a review, later dismissed

2021-07-03 23:11 UTC, OfficialEsco requested changes

2021-07-03 23:11 UTC, OfficialEsco commented on manifests/h/HeroicGamesLauncher/HeroicGamesLauncher/1.8.1/HeroicGamesLauncher.HeroicGamesLauncher.installer.yaml
> +  UpgradeBehavior: install
```suggestion
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v1.8.1/Heroic.Setup.1.8.1.exe
  InstallerSha256: 45D89FACFF2CD5804F23FCD8C4072BCFE6FF64430358866AC267EDC65F15B2C4
  InstallerSwitches:
    Custom: /CURRENTUSER
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v1.8.1/Heroic.Setup.1.8.1.exe
  InstallerSha256: 45D89FACFF2CD5804F23FCD8C4072BCFE6FF64430358866AC267EDC65F15B2C4
  InstallerSwitches:
    Custom: /ALLUSERS
  UpgradeBehavior: install
```

2021-07-03 23:11 UTC, OfficialEsco commented on manifests/h/HeroicGamesLauncher/HeroicGamesLauncher/1.8.1/HeroicGamesLauncher.HeroicGamesLauncher.locale.en-US.yaml
> +PackageName: Heroic 1.8.1
```suggestion
PackageName: Heroic
```
You can exclude the version from the PackageName since it looks for `Heroic "wildcard"`

2021-07-04 09:49 UTC, OfficialEsco approved these changes

2021-07-04 09:49 UTC, merged