Update Synology Drive Client to 3.0.1-12667
microsoft/winget-pkgs pull request #19672
Opened 2021-07-03 17:21 UTC by Keiishu

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

-----

2021-07-04 17:33 UTC, OfficialEsco requested changes
![image](https://user-images.githubusercontent.com/15158490/124394199-a308d100-dcfe-11eb-91d2-d15067d54e33.png)

2021-07-04 17:33 UTC, OfficialEsco commented on manifests/s/Synology/DriveClient/3.0.1-12667/Synology.DriveClient.locale.en-US.yaml
> +Publisher: Synology Inc.
```suggestion
PackageVersion: 7.0.1.12667
PackageLocale: en-US
Publisher: Synology
```

2021-07-04 17:33 UTC, OfficialEsco commented on manifests/s/Synology/DriveClient/3.0.1-12667/Synology.DriveClient.installer.yaml
> +PackageVersion: 3.0.1-12667
```suggestion
PackageVersion: 7.0.1.12667
```

2021-07-04 17:33 UTC, OfficialEsco commented on manifests/s/Synology/DriveClient/3.0.1-12667/Synology.DriveClient.yaml
> +PackageVersion: 3.0.1-12667
```suggestion
PackageVersion: 7.0.1.12667
```

2021-07-04 17:38 UTC, Keiishu commented
> 
> 
> ![image](https://user-images.githubusercontent.com/15158490/124394199-a308d100-dcfe-11eb-91d2-d15067d54e33.png)

Where does this come from? I only took the official Synology website as a reference, so I must say it is confusing.
The download link is for the version "3.0.1-12667", not "3.0.1-12667".
![image](https://user-images.githubusercontent.com/28761304/124394314-44902280-dcff-11eb-9f32-0f3ddf6e845a.png)

And the official company name is not referred as "Synology", but "Synology Inc.".
![image](https://user-images.githubusercontent.com/28761304/124394341-5b367980-dcff-11eb-851c-d1a59e134e7f.png)

2021-07-06 21:24 UTC, ItzLevvie approved these changes

2021-07-06 21:25 UTC, merged

2021-08-13 12:23 UTC, Dennis14e commented
Why was the version number changed from 3.0.1 to 7.0.1?
See https://www.synology.com/de-de/releaseNote/SynologyDriveClient

2021-08-13 12:24 UTC, ItzLevvie commented
cc @Dennis14e: Windows Package Manager requires the version to be from the Control Panel.

Please update your application's version number if it's incorrect.

2021-08-13 12:24 UTC, OfficialEsco commented
Ask the developers why they can't make a consistent version name.

2021-08-13 12:25 UTC, Keiishu commented
> 
> 
> Why was the version number changed from 3.0.1 to 7.0.1?
> See [synology.com/de-de/releaseNote/SynologyDriveClient](https://www.synology.com/de-de/releaseNote/SynologyDriveClient)

> 
> 
> ![image](https://user-images.githubusercontent.com/15158490/124394199-a308d100-dcfe-11eb-91d2-d15067d54e33.png)

2021-08-13 12:32 UTC, Dennis14e commented
Oh okay, that's weird from Synology.
Thanks for the clarification. @ItzLevvie @OfficialEsco @Keiishu