Submitting RaceCore24 Ignition version 1.1.7.58 yaml
microsoft/winget-pkgs pull request #19670
Opened 2021-07-03 15:24 UTC by sith-ikjetil

- [yes] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [yes] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ yes] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ yes] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ yes] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `manifests/r/RaceCore24/Ignition/1.1.7.58/` is the name of the directory containing the manifest you're submitting.

-----

2021-07-03 19:21 UTC, quhxl commented
The `Silent` switch is missing. In this case it is `/S`.

2021-07-03 21:17 UTC, ItzLevvie requested changes

2021-07-03 21:17 UTC, ItzLevvie commented on manifests/r/RaceCore24/Ignition/1.1.7.58/RaceCore24.Ignition.yaml
> +PackageName: Ignition
```suggestion
PackageName: RaceCore24 Ignition
```

2021-07-03 21:17 UTC, ItzLevvie commented on manifests/r/RaceCore24/Ignition/1.1.7.58/RaceCore24.Ignition.yaml
> +Publisher: RaceCore24
```suggestion
Publisher: RaceCore24 Simulation Technology
```

2021-07-04 12:10 UTC, OfficialEsco approved these changes

2021-07-04 12:10 UTC, merged