Add Python 3.8.1015.0
microsoft/winget-pkgs pull request #19773
Opened 2021-07-04 10:32 UTC by Croydon

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-06 16:55 UTC, ItzLevvie requested changes

2021-07-06 16:55 UTC, ItzLevvie commented on manifests/p/Python/Python/3/3.8.1015.0/Python.Python.3.locale.en-US.yaml
> +Publisher: Python
```suggestion
Publisher: Python Software Foundation
```

2021-07-06 16:55 UTC, ItzLevvie commented on manifests/p/Python/Python/3/3.8.1015.0/Python.Python.3.locale.en-US.yaml
> +PackageName: Python 3.8.10
```suggestion
PackageName: Python 3
```

2021-07-06 16:55 UTC, ItzLevvie commented on manifests/p/Python/Python/3/3.8.1015.0/Python.Python.3.locale.en-US.yaml
> +PackageVersion: 3.8.1015.0
```suggestion
PackageVersion: 3.8.10150.0
```

2021-07-06 16:55 UTC, ItzLevvie commented on manifests/p/Python/Python/3/3.8.1015.0/Python.Python.3.installer.yaml
> +PackageVersion: 3.8.1015.0
```suggestion
PackageVersion: 3.8.10150.0
```

2021-07-06 16:55 UTC, ItzLevvie commented on manifests/p/Python/Python/3/3.8.1015.0/Python.Python.3.yaml
> +PackageVersion: 3.8.1015.0
```suggestion
PackageVersion: 3.8.10150.0
```

2021-07-06 18:41 UTC, jamespik commented
/azp run

2021-07-06 20:04 UTC, ItzLevvie requested changes
You'll have to update the version folder too.

2021-07-07 12:45 UTC, Croydon commented
I just double-checked and it works locally. Both validating and installing. No clue what is going on in CI

2021-07-07 17:55 UTC, jamespik commented
/azp run

2021-07-15 16:52 UTC, Croydon commented
Bot says it worked, CI checks say it's failed. What now?

2021-07-16 01:04 UTC, ItzLevvie approved these changes

2021-07-16 14:43 UTC, ItzLevvie commented
cc @palenshus @denelon: "Azure-Pipeline-Passed" label needs to be added to this PR.

2021-07-16 15:01 UTC, denelon approved these changes

2021-07-16 15:02 UTC, merged