Microsoft.VisualStudioCode v1.46.1
microsoft/winget-pkgs pull request #1987
Opened 2020-06-18 23:13 UTC by lszomoru

Microsoft.VisualStudioCode v1.46.1

2020-06-19 15:45 UTC, Tyriar requested changes

2020-06-19 15:45 UTC, Tyriar commented on manifests/Microsoft/VisualStudioCode/1.46.1.yaml
> +Name: Ladislau Szomoru
This is the name of the application https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Ccompschema

2020-06-19 15:45 UTC, Tyriar commented on manifests/Microsoft/VisualStudioCode/1.46.1.yaml
> +Homepage: https://visualstudio.microsoft.com/downloads/
This should be our homepage: https://github.com/microsoft/winget-pkgs/blob/f81c70010bc660c5b838f0d8dc3ef66889605bbb/manifests/Microsoft/VisualStudioCode/1.44.2.yaml#L5

2020-06-21 11:58 UTC, closed without merging

2020-06-21 12:03 UTC, lszomoru commented
Will submit a new pull request after fixing fixing these bugs in our automation.