New package: ICEMortgageTechnology,Inc.Encompass version 7.0.0.2
microsoft/winget-pkgs pull request #199085
Opened 2024-12-16 05:28 UTC by PckgrMiranda

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-12-16 08:02 UTC, PckgrMiranda commented
This application did not have a silent install switch, however did have /exenoui which was used for the silent install switch.

2024-12-16 20:55 UTC, stephengillie commented
Manual Validation ended with:
![image](https://github.com/user-attachments/assets/3ce942a0-1761-4476-99ba-8ebe384b9845)

2024-12-16 23:48 UTC, PckgrTom commented on manifests/i/ICEMortgageTechnology,Inc/Encompass/7.0.0.2/ICEMortgageTechnology,Inc.Encompass.installer.yaml
> +InstallerType: exe
```suggestion
InstallerType: exe
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Adobe.Acrobat.Reader.64-bit
```

2024-12-17 00:47 UTC, PckgrTom commented on manifests/i/ICEMortgageTechnology,Inc/Encompass/7.0.0.2/ICEMortgageTechnology,Inc.Encompass.installer.yaml
> +  Silent: /exenoui
```suggestion
  Silent: /exenoui /qn /norestart
```

2024-12-19 05:03 UTC, Trenly commented
@wingetbot run

2024-12-19 05:11 UTC, Trenly requested changes
After making the changes, the manifest folder name and the version folder will need to be updated

2024-12-19 05:11 UTC, Trenly commented on manifests/i/ICEMortgageTechnology,Inc/Encompass/7.0.0.2/ICEMortgageTechnology,Inc.Encompass.locale.en-US.yaml
> +Publisher: Ellie Mae, Inc.
```suggestion
Publisher: ICE Mortgage Technology, Inc.
```
This should match control panel

2024-12-19 05:11 UTC, Trenly commented on manifests/i/ICEMortgageTechnology,Inc/Encompass/7.0.0.2/ICEMortgageTechnology,Inc.Encompass.installer.yaml
> +PackageIdentifier: ICEMortgageTechnology,Inc.Encompass
```suggestion
PackageIdentifier: ICEMortgageTechnologyInc.Encompass
```
Commas are not preferred in package identifiers

2024-12-19 05:11 UTC, Trenly commented on manifests/i/ICEMortgageTechnology,Inc/Encompass/7.0.0.2/ICEMortgageTechnology,Inc.Encompass.locale.en-US.yaml
> +PackageIdentifier: ICEMortgageTechnology,Inc.Encompass
```suggestion
PackageIdentifier: ICEMortgageTechnologyInc.Encompass
```

2024-12-19 05:11 UTC, Trenly commented on manifests/i/ICEMortgageTechnology,Inc/Encompass/7.0.0.2/ICEMortgageTechnology,Inc.Encompass.yaml
> +PackageIdentifier: ICEMortgageTechnology,Inc.Encompass
```suggestion
PackageIdentifier: ICEMortgageTechnologyInc.Encompass
```

2024-12-19 05:11 UTC, Trenly commented on manifests/i/ICEMortgageTechnology,Inc/Encompass/7.0.0.2/ICEMortgageTechnology,Inc.Encompass.locale.en-US.yaml
> +ShortDescription: Encompass360 Installer
Please provide a better description of what Encompass is, does, or what it is used for

2024-12-19 05:11 UTC, Trenly commented on manifests/i/ICEMortgageTechnology,Inc/Encompass/7.0.0.2/ICEMortgageTechnology,Inc.Encompass.installer.yaml
> +PackageVersion: 7.0.0.2
```suggestion
PackageVersion: 2.0.1.0
```
This should match what is written to control panel

2024-12-19 05:11 UTC, Trenly commented on manifests/i/ICEMortgageTechnology,Inc/Encompass/7.0.0.2/ICEMortgageTechnology,Inc.Encompass.locale.en-US.yaml
> +PackageVersion: 7.0.0.2
```suggestion
PackageVersion: 2.0.1.0
```

2024-12-19 05:11 UTC, Trenly commented on manifests/i/ICEMortgageTechnology,Inc/Encompass/7.0.0.2/ICEMortgageTechnology,Inc.Encompass.yaml
> +PackageVersion: 7.0.0.2
```suggestion
PackageVersion: 2.0.1.0
```

2024-12-20 04:51 UTC, closed without merging