New package Microsoft.DSC
microsoft/winget-pkgs pull request #199293
Opened 2024-12-17 12:27 UTC by Gijsreyn

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? #199292 

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

![image](https://github.com/user-attachments/assets/3b66c29d-ff17-43ea-870d-1398d77a5afc)

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-12-17 13:09 UTC, Dragon1573 approved these changes
Manually verified.

<details><summary>Console logs</summary>

```text
--> Installing WinGet
--> Disabling safety warning when running installers
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Enabled admin setting 'LocalManifestFiles'.
Enabled admin setting 'LocalArchiveMalwareScanOverride'.

--> Installing the Manifest 3.0.0-preview.12

Found Desired State Configuration [Microsoft.Dsc] Version 3.0.0-preview.12
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/PowerShell/DSC/releases/download/v3.0.0-preview.12/DSC-3.0.0-preview.12-x86_64-pc-windows-msvc.zip
  ██████████████████████████████  6.94 MB / 6.94 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "dsc"
Path environment variable modified; restart your shell to use the new value.
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName                 DisplayVersion   Publisher             ProductCode                  Scope
-----------                 --------------   ---------             -----------                  -----
Desired State Configuration 3.0.0-preview.12 Microsoft Corporation Microsoft.Dsc__DefaultSource User


PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> dsc.exe
Apply configuration or invoke specific DSC resources

Usage: dsc.exe [OPTIONS] <COMMAND>

Commands:
  completer  Generate a shell completion script
  config     Apply a configuration document
  resource   Invoke a specific DSC resource
  schema     Get the JSON schema for a DSC type
  help       Print this message or the help of the given subcommand(s)

Options:
  -l, --trace-level <TRACE_LEVEL>    Trace level to use [possible values: error, warn, info, debug, trace]
  -t, --trace-format <TRACE_FORMAT>  Trace format to use [possible values: default, plaintext, json]
  -h, --help                         Print help
  -V, --version                      Print version
```

</details>

2024-12-17 13:12 UTC, Gijsreyn commented
@Dragon1573 Thanks for the approve. I have two questions you might be able to answer:

* Should we still rename the `PackageName` to have preview in there?
* Why is the build still failing if it is a preview? Shouldn't it be added in the preview folder?

2024-12-17 13:15 UTC, Dragon1573 commented
Hi @Gijsreyn 👋🏼,

> [!TIP]
>
> Link this pull request to the issue using ["close keywords"](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) can prevent other contributors from creating duplicate pull requests. It can also guide bots to label the issue <https://github.com/microsoft/winget-pkgs/labels/In-PR>.

> [!IMPORTANT]
>
> "Close keywords" is only valid in **commit messages** or in [**PR details**](https://github.com/microsoft/winget-pkgs/pull/199293#issue-2744806443).

2024-12-17 13:17 UTC, Dragon1573 commented
> * Should we still rename the `PackageName` to have preview in there?

Yes, it is.

> * Why is the build still failing if it is a preview? Shouldn't it be added in the preview folder?

It seems I approve the PR by mistake. 🤣 I can't revoke it ...

Since I AM NOT one of the moderators, the PR will not be merged automatically.

2024-12-17 13:19 UTC, Gijsreyn commented
Just added the preview text to the `PackageName`. I didn't totally get you on the preview folder. Should I move it back? :)

2024-12-17 13:19 UTC, Dragon1573 requested changes
Filenames of them should be migrated to `Microsoft.Dsc.preview.*`.

2024-12-17 13:19 UTC, Dragon1573 commented on manifests/m/Microsoft/Dsc/preview/3.0.0-preview.12/Microsoft.Dsc.locale.en-US.yaml
> +PackageIdentifier: Microsoft.Dsc
```suggestion
PackageIdentifier: Microsoft.Dsc.preview
```

2024-12-17 13:19 UTC, Dragon1573 commented on manifests/m/Microsoft/Dsc/preview/3.0.0-preview.12/Microsoft.Dsc.yaml
> +PackageIdentifier: Microsoft.Dsc
```suggestion
PackageIdentifier: Microsoft.Dsc.preview
```

2024-12-17 13:34 UTC, mdanish-kh requested changes
Please remove `preview/3.0.0-preview.12` folder. Seems to be a duplicate

2024-12-17 13:37 UTC, Gijsreyn commented
> Please remove `preview/3.0.0-preview.12` folder. Seems to be a duplicate

Oops, I was messing with the git global config settings because of capitalization. Should be good now!

2024-12-17 13:44 UTC, mdanish-kh requested changes
This will fail pipelines again since the PackageIdentifier does not match the yaml file names.

PackageId -> `Microsoft.Dsc.Preview` so the `.yaml` files should include the PackageId as `Microsoft.Dsc.Preview.installer.yaml` `Microsoft.Dsc.Preview.locale.en-US.yaml` and so on

Looping in @denelon for an appropriate PackageIdentifier for this package.

`Microsoft.DSC`, `Microsoft.PowerShell.DSC` `Microsoft.DSC.Preview`?

2024-12-17 13:45 UTC, mdanish-kh commented
We should also be adding the `msix` installer as well

2024-12-17 13:50 UTC, Gijsreyn commented
@mdanish-kh Are you talking about this one: https://apps.microsoft.com/detail/9pcx3hx4hz0z?hl=en-US&gl=GB ?

2024-12-17 13:51 UTC, mdanish-kh commented
@Gijsreyn - it's the one included in the release artifacts. This one https://github.com/PowerShell/DSC/releases/download/v3.0.0-preview.12/DSC-3.0.0-preview.12-Win.msixbundle

2024-12-17 13:52 UTC, Gijsreyn commented
Ah, gotcha, I already thought it was. Do you want me to attempt to include it?

2024-12-17 13:58 UTC, Gijsreyn commented
Yes, was already on it. Should be added!

2024-12-17 14:10 UTC, mdanish-kh commented on manifests/m/Microsoft/Dsc/Preview/3.0.0-preview.12/Microsoft.Dsc.yaml
> +PackageVersion: 3.0.0-preview.12
```suggestion
PackageVersion: 3.0.12.0
```

2024-12-17 20:37 UTC, stephengillie requested changes
Hi @Gijsreyn,

Automatic Validation ended with:
>Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 
'manifests\m\Microsoft\Dsc\Preview\3.0.0-preview.12', expected 
'manifests\m\Microsoft\Dsc\Preview\3.0.12.0'

2024-12-17 20:37 UTC, stephengillie commented on manifests/m/Microsoft/Dsc/Preview/3.0.0-preview.12/Microsoft.Dsc.installer.yaml
> +PackageVersion: 3.0.12.0
Please update file path to match this line.

2024-12-17 20:37 UTC, stephengillie commented on manifests/m/Microsoft/Dsc/Preview/3.0.0-preview.12/Microsoft.Dsc.locale.en-US.yaml
> +PackageVersion: 3.0.12.0
Please update file path to match this line.

2024-12-17 20:37 UTC, stephengillie commented on manifests/m/Microsoft/Dsc/Preview/3.0.0-preview.12/Microsoft.Dsc.yaml
> +PackageVersion: 3.0.0-12.0
Please update file path to match this line.

2024-12-18 07:19 UTC, Gijsreyn commented
Hey @stephengillie! Should be good to go.

2024-12-18 18:21 UTC, denelon commented
@Gijsreyn it looks like the package was added in: 
* https://github.com/microsoft/winget-pkgs/pull/199424

2024-12-18 18:23 UTC, stephengillie commented
Close with reason: Duplicate of #199424;

2024-12-18 18:23 UTC, closed without merging

2024-12-18 18:31 UTC, Gijsreyn commented
Somebody snooping away my PRs @denelon. No worries, glad it's in. Thanks for the heads-up.

2024-12-18 18:32 UTC, denelon commented
Lol, yeah... some people just love the WinGet :D