KakaoEnterprise.KakaoWork version 1.7.0.2191
microsoft/winget-pkgs pull request #19948
Opened 2021-07-06 16:14 UTC by alexkoala

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-06 22:45 UTC, ItzLevvie requested changes

2021-07-06 22:45 UTC, ItzLevvie commented on manifests/k/KakaoEnterprise/KakaoWork/1.7.0.2191/KakaoEnterprise.KakaoWork.locale.ko-KR.yaml
> +PackageName: KakaoWork
```suggestion
PackageName: Kakao Work
```

2021-07-06 22:45 UTC, ItzLevvie commented on manifests/k/KakaoEnterprise/KakaoWork/1.7.0.2191/KakaoEnterprise.KakaoWork.locale.ko-KR.yaml
> +Publisher: Kakao Enterprise
```suggestion
Publisher: Kakao Enterprise Corp
```

2021-07-06 22:45 UTC, ItzLevvie commented on manifests/k/KakaoEnterprise/KakaoWork/1.7.0.2191/KakaoEnterprise.KakaoWork.locale.ko-KR.yaml
> +ShortDescription: KakaoWork Application
```
ShortDescription: KakaoWork Application
```
Please write a better description.

2021-07-07 01:25 UTC, alexkoala commented on manifests/k/KakaoEnterprise/KakaoWork/1.7.0.2191/KakaoEnterprise.KakaoWork.locale.ko-KR.yaml
> +ShortDescription: KakaoWork Application
@ItzLevvie fixed

2021-07-07 07:53 UTC, ItzLevvie approved these changes

2021-07-07 07:53 UTC, merged