New version: OliverBetz.ExifTool version 13.10
microsoft/winget-pkgs pull request #200906
Opened 2024-12-21 11:51 UTC by Dragon1573

## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #200346

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

## Manual validation

![Image](https://github.com/user-attachments/assets/7b228b23-137e-4d6a-9a52-544d417b6489)
![Image](https://github.com/user-attachments/assets/f4ce647f-71ee-4690-ad8d-87c9cdac2992)

-----

2024-12-21 13:16 UTC, Dragon1573 reviewed
_Komac_ generated an incorrect manifest, installer file should be "re-hash".

2024-12-21 13:16 UTC, Dragon1573 commented on manifests/o/OliverBetz/ExifTool/13.10/OliverBetz.ExifTool.installer.yaml
> +  InstallerSha256: EC1DE44FD23992F497626DE71FD4D41E122114450D52A58C7901C3E8E7EDC4D6
```suggestion
  InstallerSha256: EF2680E717A1B4C3729E931BE5C526FA1EECBA2068E77E960E74B9FD8C946036
```

2024-12-21 13:16 UTC, Dragon1573 commented on manifests/o/OliverBetz/ExifTool/13.10/OliverBetz.ExifTool.installer.yaml
> +  InstallerSha256: EC1DE44FD23992F497626DE71FD4D41E122114450D52A58C7901C3E8E7EDC4D6
```suggestion
  InstallerSha256: EF2680E717A1B4C3729E931BE5C526FA1EECBA2068E77E960E74B9FD8C946036
```

2024-12-26 21:03 UTC, mdanish-kh requested changes

2024-12-26 21:03 UTC, mdanish-kh commented on manifests/o/OliverBetz/ExifTool/13.10/OliverBetz.ExifTool.installer.yaml
> +ElevationRequirement: elevatesSelf
```suggestion
```

`Scope: user` doesn't ask for elevation.

2024-12-26 21:03 UTC, mdanish-kh commented on manifests/o/OliverBetz/ExifTool/13.10/OliverBetz.ExifTool.installer.yaml
> +  InstallerSha256: EC1DE44FD23992F497626DE71FD4D41E122114450D52A58C7901C3E8E7EDC4D6
```suggestion
  InstallerSha256: EC1DE44FD23992F497626DE71FD4D41E122114450D52A58C7901C3E8E7EDC4D6
  ElevationRequirement: elevatesSelf
```

2024-12-26 21:03 UTC, mdanish-kh commented on manifests/o/OliverBetz/ExifTool/13.10/OliverBetz.ExifTool.installer.yaml
> +  InstallerSha256: EF2680E717A1B4C3729E931BE5C526FA1EECBA2068E77E960E74B9FD8C946036
```suggestion
  InstallerSha256: EF2680E717A1B4C3729E931BE5C526FA1EECBA2068E77E960E74B9FD8C946036
  ElevationRequirement: elevatesSelf
```

2024-12-27 07:20 UTC, mdanish-kh approved these changes

2024-12-27 07:21 UTC, merged