Standardize formatting of manifests/d/Drawpile/Drawpile/2.1.17
microsoft/winget-pkgs pull request #201405
Opened 2024-12-22 17:32 UTC by Trenly

2024-12-22 20:38 UTC, ItzLevvie approved these changes

2024-12-23 18:22 UTC, stephengillie commented
URL: https://drawpile.net/files/win/drawpile-2.1.17-setup.exe 
Status Code: 200

(Automated message - build 931)

2024-12-25 19:37 UTC, stephengillie requested changes
> Url Validation Error
> * manifests\d\Drawpile\Drawpile\2.1.17
>   * https://raw.githubusercontent.com/drawpile/Drawpile/master/COPYING
>     * Http status code: NotFound

2024-12-25 19:37 UTC, stephengillie commented on manifests/d/Drawpile/Drawpile/2.1.17/Drawpile.Drawpile.locale.en-US.yaml
>  LicenseUrl: https://raw.githubusercontent.com/drawpile/Drawpile/master/COPYING
```suggestion
# LicenseUrl: https://raw.githubusercontent.com/drawpile/Drawpile/master/COPYING
```

2024-12-27 21:55 UTC, stephengillie approved these changes

2024-12-27 21:55 UTC, merged