Standardize formatting of manifests/d/Drawpile/Drawpile/2.1.20
microsoft/winget-pkgs pull request #201408
Opened 2024-12-22 17:35 UTC by Trenly

2024-12-22 20:38 UTC, ItzLevvie approved these changes

2024-12-23 18:21 UTC, stephengillie commented
URL: https://drawpile.net/files/win/drawpile-2.1.20-setup.exe 
Status Code: 200

(Automated message - build 931)

2024-12-26 19:43 UTC, stephengillie requested changes
> Url Validation Error
> * manifests\d\Drawpile\Drawpile\2.1.20
>   * https://raw.githubusercontent.com/drawpile/Drawpile/master/COPYING
>     * Http status code: NotFound

The manifest updates are displayed in a way that prevents suggesting changes.

2024-12-27 21:56 UTC, stephengillie approved these changes

2024-12-27 21:56 UTC, merged