Alibaba.adrive version 2.1.9.693
microsoft/winget-pkgs pull request #20200
Opened 2021-07-08 12:54 UTC by oxygen-dioxide

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-08 13:07 UTC, ImJoakim commented on manifests/a/Alibaba/adrive/2.1.9.693/Alibaba.adrive.installer.yaml
> +PackageVersion: 2.1.9.693
![image](https://user-images.githubusercontent.com/52826317/124926815-3e9b8980-dffe-11eb-9372-ae1e741ff821.png)

```suggestion
PackageVersion: 2.1.9

```

2021-07-08 13:08 UTC, ImJoakim commented on manifests/a/Alibaba/adrive/2.1.9.693/Alibaba.adrive.installer.yaml
> +  InstallerUrl: https://yunpan.aliyun.com/downloads/apps/desktop/aDrive.exe?spm=aliyundrive.index.0.0.2d836020dLdn8F&file=aDrive.exe
```suggestion
  InstallerUrl: https://yunpan.aliyun.com/downloads/apps/desktop/aDrive.exe
```

2021-07-08 13:08 UTC, ImJoakim commented on manifests/a/Alibaba/adrive/2.1.9.693/Alibaba.adrive.locale.en-US.yaml
> +PackageVersion: 2.1.9.693
![image](https://user-images.githubusercontent.com/52826317/124926896-5115c300-dffe-11eb-996b-5fd71606918c.png)

```suggestion
PackageVersion: 2.1.9
```

2021-07-08 13:09 UTC, ImJoakim commented on manifests/a/Alibaba/adrive/2.1.9.693/Alibaba.adrive.locale.en-US.yaml
> +Publisher: 阿里云盘
![image](https://user-images.githubusercontent.com/52826317/124926970-65f25680-dffe-11eb-8fc9-f033201b61f3.png)

```suggestion
Publisher: Alibaba Group
```

2021-07-08 13:09 UTC, ImJoakim commented on manifests/a/Alibaba/adrive/2.1.9.693/Alibaba.adrive.locale.en-US.yaml
> +PackageName: aDrive
![image](https://user-images.githubusercontent.com/52826317/124927104-8a4e3300-dffe-11eb-9173-545bf69f525b.png)

```suggestion
PackageName: 阿里云盘
```

2021-07-08 13:10 UTC, ImJoakim commented on manifests/a/Alibaba/adrive/2.1.9.693/Alibaba.adrive.yaml
> +PackageVersion: 2.1.9.693
![image](https://user-images.githubusercontent.com/52826317/124927129-920dd780-dffe-11eb-827f-5fb918222e68.png)

```suggestion
PackageVersion: 2.1.9
```

2021-07-08 13:12 UTC, ImJoakim commented
Please see my comments above 😃
You also need to change the folder name.

- https://github.com/microsoft/winget-pkgs/pull/20200#discussion_r666175932
- https://github.com/microsoft/winget-pkgs/pull/20200#discussion_r666176119
- https://github.com/microsoft/winget-pkgs/pull/20200#discussion_r666176441
- https://github.com/microsoft/winget-pkgs/pull/20200#discussion_r666176950
- https://github.com/microsoft/winget-pkgs/pull/20200#discussion_r666177587
- https://github.com/microsoft/winget-pkgs/pull/20200#discussion_r666177801

2021-07-08 13:52 UTC, ItzLevvie requested changes
https://github.com/microsoft/winget-pkgs/pull/20200#pullrequestreview-702039331

2021-07-09 08:06 UTC, ImJoakim commented
@oxygen-dioxide It's failing because the file has a capital A in alibaba. Rename the following files:

`Alibaba.adrive.installer.yaml` -> `alibaba.adrive.installer.yaml`
`Alibaba.adrive.locale.en-US.yaml` -> `alibaba.adrive.locale.en-US.yaml `
`Alibaba.adrive.yaml`  -> `alibaba.adrive.yaml `

2021-07-13 14:10 UTC, ItzLevvie approved these changes

2021-07-13 14:11 UTC, merged