Add Genshin Impact game version 2.0
microsoft/winget-pkgs pull request #20316
Opened 2021-07-09 20:38 UTC by Lucaskyy

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Wasn't entirely sure if I should use the game version or the date (20210525204658 currently) from the downloaded file, but I went with the game version which is 2.0.

2021-07-09 20:49 UTC, Lucaskyy commented
It works fine on my PC, it gives a warning because there's no silent installer (there's none sadly and I can't decompile the installer) but it works fine besides that?

2021-07-09 21:06 UTC, Lucaskyy commented
Alright, figured it out. The generator is outdated, and there's no message whatsoever telling that. Drafting this PR so I can redo this tomorrow with winget-create.

2021-07-10 07:08 UTC, vedantmgoyal2009 requested changes

2021-07-10 07:08 UTC, vedantmgoyal2009 commented on manifests/m/miHoYo/GenshinImpact/2.0.0.0.yaml
> +    InstallerSha256: DD16F5A4ADE5AE70B929C9360858AA13DF8FA72BF9BEB437DBA7B27CCE1E1407
```suggestion
    InstallerSha256: DD16F5A4ADE5AE70B929C9360858AA13DF8FA72BF9BEB437DBA7B27CCE1E1407
ManifestType: singleton
ManifestVersion: 1.0.0
```

2021-07-10 07:11 UTC, vedantmgoyal2009 requested changes

2021-07-10 07:11 UTC, vedantmgoyal2009 commented on manifests/m/miHoYo/GenshinImpact/2.0.0.0.yaml
> +Description: "Genshin Impact is an action role-playing game developed and published by miHoYo. It was released for Microsoft Windows, PlayStation 4, Android, and iOS in September 2020, for PlayStatio
```suggestion
InstallerType: EXE
LicenseUrl: https://genshin.mihoyo.com/en/company/terms
ShortDescription: "Genshin Impact is an action role-playing game developed and published by miHoYo."
```

2021-07-10 07:12 UTC, vedantmgoyal2009 requested changes
Change manifests/m/miHoYo/GenshinImpact/2.0.0.0.yaml to manifests/m/miHoYo/GenshinImpact/2.0.0.0/2.0.0.0.yaml

2021-07-10 09:21 UTC, KaranKad commented
Support for interactive installation is yet to come.

2021-07-10 09:37 UTC, Lucaskyy commented
> Support for interactive installation is yet to come.

All this currently does is it downloads the installer from Genshin Impact and then start it.
Should I close this PR, or keep it open?

2021-07-10 11:19 UTC, Lucaskyy commented
This is indeed not possible yet, closing this PR.

2021-07-10 11:19 UTC, closed without merging