New package: DBeaverCorp.DBeaverEnterpriseEdition version 24.3.0
microsoft/winget-pkgs pull request #204444
Opened 2024-12-31 10:41 UTC by rovabunw

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-12-31 17:03 UTC, stephengillie commented
Manual Validation ended with:
> 9:02:45 AM:  finished with exit code: -1978335226 9:02:46 AM: 
> 2024-12-31 09:02:45.578 [CLI ] ShellExecute installer failed: 666660 

Automated error analysis suggests -1978335226 may mean Running ShellExecute failed

(Automated response - build 933.)

2024-12-31 18:33 UTC, stephengillie commented
Manual Validation ended with:
> 10:07:34 AM:  finished with exit code: -1978335226  10:07:34 AM: 
> 2024-12-31 10:07:33.721 [CLI ] ShellExecute installer failed: 666660  

Automated error analysis suggests -1978335226 may mean Running ShellExecute failed

(Automated response - build 933.)

2024-12-31 19:05 UTC, stephengillie commented
Manual Validation ended with:
> 11:02:53 AM:  finished with exit code: -1978335226  11:02:53 AM: 
> 2024-12-31 11:02:52.580 [CLI ] ShellExecute installer failed: 666660   

Automated error analysis suggests -1978335226 may mean Running ShellExecute failed

(Automated response - build 933.)

2024-12-31 19:23 UTC, stephengillie commented
Manual Validation ended with:
> 
> 2024-12-31 11:12:52.783 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerSharedLib\SHA256.cpp(161)\WindowsPackageManager.dll!00007FFBC2BD4C2B: (caller: 00007FFBC2C23AAC) Exception(1) tid(b94) 8A150040  
> 2024-12-31 11:13:00.937 [FAIL] Installer failed security check. Url: https://github.com/PurpleI2P/i2pd/releases/download/2.55.0/setup_i2pd_v2.55.0.exe Result: 0x80004005

(Automated response - build 933.)

2024-12-31 20:31 UTC, stephengillie commented
Manual Validation ended with:
> 12:03:00 PM: 
> 2024-12-31 12:02:59.380 [CLI ] ShellExecute installer failed: 666660    

(Automated response - build 933.)

2025-01-02 02:56 UTC, Trenly requested changes

2025-01-02 02:56 UTC, Trenly commented on manifests/d/DBeaverCorp/DBeaverEnterpriseEdition/24.3.0/DBeaverCorp.DBeaverEnterpriseEdition.installer.yaml
> +  SilentWithProgress: /S /allusers
Since `/allusers` is specified, the `scope` should also be specified. However, it would be preferred to have separate installer nodes with one specifying machine scope and `/allusers` and one specifying user scope and `/currentuser`

2025-01-02 17:12 UTC, stephengillie commented
Verify:

These errors popped up during validation, and might be invalid:
![image](https://github.com/user-attachments/assets/9c686cfb-1b30-4af4-a261-ff5432f70938)
![image](https://github.com/user-attachments/assets/7f9dc093-eb98-47f1-ab82-6100d967fb03)

First run:
![image](https://github.com/user-attachments/assets/99b4311e-9c32-4b2e-82fd-256a00283950)
Then nothing happened.

Second run:
![image](https://github.com/user-attachments/assets/5d6bb8ef-88ec-462b-9af6-ddf41ad7f0c8)
![image](https://github.com/user-attachments/assets/ad258c69-a5e3-448d-b6ef-5bcc34c80a3f)
![image](https://github.com/user-attachments/assets/3fab4a61-d510-4b94-bdab-d1b02f91edf2)
The program didn't allow interaction without a license.

Registry:
![image](https://github.com/user-attachments/assets/07e3632f-ea65-423b-8d88-9496d77e1c70)

2025-01-02 17:13 UTC, stephengillie approved these changes

2025-01-02 17:13 UTC, merged