Markdown Monster 3.5.14.0
microsoft/winget-pkgs pull request #204520
Opened 2024-12-31 23:02 UTC by RickStrahl

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

2024-12-31 23:51 UTC, DuckDuckStudio requested changes
Spelling of file names:
`WestWind.MarkdownMonster` ≠ `Westwind.MarkdownMonster`

And:
![image](https://github.com/user-attachments/assets/1a634c52-abf4-4deb-9c5a-913672dc5b8b)

2025-01-01 00:10 UTC, RickStrahl commented
WestWind.MarkdownMonster ≠ Westwind.MarkdownMonster 

Where? I don't see the latter anywhere and the former matches the company.product and base company folder. (I didn't set up the original entries). I would much prefer `Westwind.MarkdownMonster` but that's not what it's been.

2025-01-01 00:11 UTC, RickStrahl commented
Is there an example of a 1.9 schema? Even the latst MS releases use old schemas (Terminal is on 1.2?)

2025-01-01 01:06 UTC, DuckDuckStudio commented
> WestWind.MarkdownMonster ≠ Westwind.MarkdownMonster
> 
> Where? I don't see the latter anywhere and the former matches the company.product and base company folder. (I didn't set up the original entries). I would much prefer `Westwind.MarkdownMonster` but that's not what it's been.

![image](https://github.com/user-attachments/assets/50bb37f8-66ac-477d-833b-ab2273021cf9)

2025-01-01 01:10 UTC, DuckDuckStudio commented
> Is there an example of a 1.9 schema? Even the latst MS releases use old schemas (Terminal is on 1.2?)
> 
> And schema validation nor local install has found none of these issues.

The manifest version 1.9 documentation: https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0
A very simple modification:
Change `yaml-language-server` in line 2 of the manifest and 1.6.0 to 1.9.0 in the last line `ManifestVersion` entry.

2025-01-01 22:54 UTC, RickStrahl commented
Updated the manifest and updated the branch but looks like the PR is not picking it up and re-running the pipeline.

2025-01-02 02:20 UTC, DuckDuckStudio commented
West *W* ind.MarkdownMonster ≠ West *w* ind.MarkdownMonster

Looks like the filename is still incorrect...
![image](https://github.com/user-attachments/assets/230172dc-71ff-4480-9190-715cf7c14e06)

2025-01-02 18:51 UTC, RickStrahl commented
I'm closing this one - something on my end got screwed up  on hte build that's picking up the wrong version. Will republish with a new version number.

My apologies.

2025-01-02 18:51 UTC, closed without merging