VladimirYakovlev.ElectronMail version 4.12.4
microsoft/winget-pkgs pull request #20471
Opened 2021-07-11 12:32 UTC by Dyaminigo

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-11 15:16 UTC, Dyaminigo commented
I don't understand what the validation error is. Installing ElectronMail with the / S flag performs a silent installation, no manual input is required. I cannot reproduce a situation where the installer would ask for some action. On my device, everything is successfully installed in a hidden (quiet) mode with the / S flag.
P.S. I am sorry for my bad english.

2021-07-14 19:48 UTC, ItzLevvie commented on manifests/v/VladimirYakovlev/ElectronMail/4.12.4/VladimirYakovlev.ElectronMail.installer.yaml
> +    Silent: /S
These switches are not needed; winget-cli makes nullsoft installers run with `/S` in the code.

2021-07-14 19:48 UTC, ItzLevvie requested changes
Please see review.

2021-07-14 19:49 UTC, ItzLevvie commented
You'll need to contact the application's developer(s) to allow the Visual C++ Redist to install silently, I'm currently stuck here:
![image](https://user-images.githubusercontent.com/11600822/125683956-9bc50a17-9940-4b4c-bb10-e9a9514807e0.png)

2021-07-17 03:33 UTC, Dyaminigo commented
Hello @ItzLevvie,
Thank you for comments about the manifest compiled by me and for the problem found in unsuccessful installer checks! I will contact the ElectronMail developer and give him information about the installer. In the meantime, I'll close this PR until the ElectronMail developer will not solve the problem with the installer.

2021-07-17 03:33 UTC, closed without merging