Update: dokan-dev.Dokany version 1.5.0.3000
microsoft/winget-pkgs pull request #20680
Opened 2021-07-12 08:08 UTC by vedantmgoyal2009

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-12 08:26 UTC, OfficialEsco requested changes
![image](https://user-images.githubusercontent.com/15158490/125255319-976b6a80-e2fb-11eb-81ee-9d5e7ebe4863.png)

2021-07-12 08:26 UTC, OfficialEsco commented on manifests/d/dokan-dev/Dokany/1.5.0.3000/dokan-dev.Dokany.locale.en-US.yaml
> +#Description:
```suggestion
Publisher: Dokany Project
PublisherUrl: http://dokan-dev.github.io/
PublisherSupportUrl: https://github.com/dokan-dev/dokany/issues
#PrivacyUrl: 
Author: Dokany Project
PackageName: Dokany Library
PackageUrl: https://dokan-dev.github.io/
License: LGPL/MIT
LicenseUrl: https://github.com/dokan-dev/dokany/blob/master/license.mit.txt
Copyright: Copyright (C) 2007 Free Software Foundation, Inc. / Copyright (C) 2015 - 2020 Adrien J. and Maxime C.
CopyrightUrl: https://github.com/dokan-dev/dokany/blob/master/license.mit.txt
ShortDescription: User mode file system library for windows with FUSE Wrapper
Description: Dokany is a fork of Dokan 0.6.0 with bug fixes, clean change history and updated to build with latest tools.
```

2021-07-12 13:24 UTC, vedantmgoyal2009 commented
![image](https://user-images.githubusercontent.com/83997633/125295089-82fe9080-e342-11eb-975f-4a80559bbe8a.png)

2021-07-12 13:27 UTC, OfficialEsco commented
`Validation-Executable-Error` does not mean there is a issue with the Manifest which is why this is assigned to a technician.

2021-07-13 01:38 UTC, palenshus commented
The issue here is that dokanctl.exe ends with exit code: 1, which the validator takes as a failure. Ideally the exe would return 0 when run with no arguments, otherwise we require a validation override.

2021-07-13 14:29 UTC, ItzLevvie requested changes

2021-07-13 14:29 UTC, ItzLevvie commented on manifests/d/dokan-dev/Dokany/1.5.0.3000/dokan-dev.Dokany.locale.en-US.yaml
> +PackageName: Dokany Library
```suggestion
PackageName: Dokan Library
```

2021-07-14 19:18 UTC, vedantmgoyal2009 commented
Please merge this PR.

2021-07-15 20:52 UTC, denelon commented
@vedantmgoyal2009 I think this one is just waiting on a moderator approval. I removed the error label.

2021-07-15 21:06 UTC, OfficialEsco approved these changes
We are looking at `Azure-Pipeline-Passed` labels, not `Needs: Attention` or `Validation-Completed`
Edit: as you can see we have no power in this PR.

2021-07-15 22:34 UTC, palenshus approved these changes

2021-07-15 22:49 UTC, denelon commented
It looks like @ItzLevvie still has changes requested on the PR.

2021-07-15 22:52 UTC, ItzLevvie approved these changes

2021-07-15 22:52 UTC, merged