Update: `CozyCloud.CozyDrive` version 3.28.0
microsoft/winget-pkgs pull request #20754
Opened 2021-07-13 11:24 UTC by vedantmgoyal2009

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-13 12:59 UTC, ItzLevvie requested changes

2021-07-13 12:59 UTC, ItzLevvie commented on manifests/c/CozyCloud/CozyDrive/3.28.0/CozyCloud.CozyDrive.locale.en-US.yaml
> +Publisher: CozyCloud
```suggestion
Publisher: Cozy Cloud
```

2021-07-13 12:59 UTC, ItzLevvie commented on manifests/c/CozyCloud/CozyDrive/3.28.0/CozyCloud.CozyDrive.locale.en-US.yaml
> +PackageName: CozyDrive
```suggestion
PackageName: Cozy Drive
```

2021-07-13 12:59 UTC, ItzLevvie commented on manifests/c/CozyCloud/CozyDrive/3.28.0/CozyCloud.CozyDrive.installer.yaml
> +  Scope: machine
```suggestion
  Scope: user
```

2021-07-13 13:01 UTC, vedantmgoyal2009 commented
Can you please tell how to decide whether to keep `Scope: machine`or `Scope: user`

2021-07-13 13:36 UTC, ItzLevvie approved these changes

2021-07-13 13:36 UTC, merged

2021-07-15 20:09 UTC, denelon commented
@vedantmgoyal2009 the scope has to do with whether the package installs for "all users" - "machine" or if it installs for only "one user" - "user". Some installers support both, while some only support one. It's a case by case basis.

2021-07-16 01:03 UTC, vedantmgoyal2009 commented
Thanks. In some package, the software is installed for only the current user but it requires `machine` otherwise Azure Pipelines would fail.

2021-07-16 15:32 UTC, denelon commented
@vedantmgoyal2009 please don't use the scope for the scenario where "machine" would be indicated due to UAC requirements. We would prefer to have other mechanisms to indicate UAC required. https://github.com/microsoft/winget-cli/issues/1284

This would be a bad experience for a user expecting the package to install for all users.