Update: `plex.plexmediaserver` version 1.23.4.4805
microsoft/winget-pkgs pull request #20762
Opened 2021-07-13 12:59 UTC by vedantmgoyal2009

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-13 13:35 UTC, ItzLevvie requested changes
Looks like this version is already in the repository.

2021-07-13 13:43 UTC, vedantmgoyal2009 commented
Oh, sorry. I have to update my fork.

2022-03-01 12:15 UTC, ItzLevvie approved these changes

2022-03-01 12:45 UTC, ItzLevvie requested changes
~~Re-run pipeline; @msftbot removed the "Azure-Pipeline-Passed" label.~~

nvm

2022-03-01 12:46 UTC, ItzLevvie approved these changes

2022-03-01 12:48 UTC, merged