Add: stnkl.EverythingToolbar version 0.7.1
microsoft/winget-pkgs pull request #20846
Opened 2021-07-14 12:17 UTC by quhxl

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-14 14:35 UTC, OfficialEsco requested changes

2021-07-14 14:35 UTC, OfficialEsco commented on manifests/s/stnkl/EverythingToolbar/0.7.1/stnkl.EverythingToolbar.installer.yaml
> +PackageVersion: 0.7.1
```suggestion
PackageVersion: 0.7.1.0
```

2021-07-14 14:35 UTC, OfficialEsco commented on manifests/s/stnkl/EverythingToolbar/0.7.1/stnkl.EverythingToolbar.locale.en-US.yaml
> +PackageVersion: 0.7.1
```suggestion
PackageVersion: 0.7.1.0
```

2021-07-14 14:35 UTC, OfficialEsco commented on manifests/s/stnkl/EverythingToolbar/0.7.1/stnkl.EverythingToolbar.yaml
> +PackageVersion: 0.7.1
```suggestion
PackageVersion: 0.7.1.0
```

2021-07-14 14:35 UTC, OfficialEsco commented on manifests/s/stnkl/EverythingToolbar/0.7.1/stnkl.EverythingToolbar.locale.en-US.yaml
> +#CopyrightUrl:
```suggestion
License: MIT License
LicenseUrl: https://raw.githubusercontent.com/stnkl/EverythingToolbar/master/LICENSE
Copyright: Copyright (c) 2021 Stephan Rumswinkel
CopyrightUrl: https://raw.githubusercontent.com/stnkl/EverythingToolbar/master/LICENSE
```

2021-07-14 16:50 UTC, quhxl commented
@OfficialEsco Do you know something about `Validation-No-Executables`?

2021-07-14 16:58 UTC, OfficialEsco commented
> @OfficialEsco Do you know something about `Validation-No-Executables`?

No idea

https://github.com/microsoft/winget-cli/blob/5898d09203409d08742d97f8eb54e249316695e8/doc/windows/package-manager/package/winget-validation.md

https://docs.microsoft.com/en-us/windows/package-manager/package/winget-validation#internal-labels

Neither does the pipeline it seems...

2021-07-15 18:49 UTC, palenshus commented
@OfficialEsco it looks like there are no install-time dependencies, but there is a runtime dependency, which we allow. You can go ahead and approve it if you're happy with the manifest, thanks!

2021-07-15 18:51 UTC, OfficialEsco approved these changes

2021-07-15 18:51 UTC, merged

2021-07-15 20:56 UTC, denelon commented
@OfficialEsco we're working on the update to the documentation, but it means we didn't find an executable for the installer to "run".

2021-07-15 21:09 UTC, OfficialEsco commented
> @OfficialEsco we're working on the update to the documentation, but it means we didn't find an executable for the installer to "run".

I was going to say that as it makes sense, but then surely these would fail

```
7/14/2021 2:58:31 PM
Installer Availability and Hash Validation
Status: Started
Installer: https://github.com/stnkl/EverythingToolbar/releases/download/0.7.1/EverythingToolbar-0.7.1.msi

7/14/2021 2:58:32 PM
Installer https://github.com/stnkl/EverythingToolbar/releases/download/0.7.1/EverythingToolbar-0.7.1.msi
Hash validation succeeded

7/14/2021 2:58:34 PM
Status: Completed
Installer: https://github.com/stnkl/EverythingToolbar/releases/download/0.7.1/EverythingToolbar-0.7.1.msi
Result: Succeeded

7/14/2021 2:58:35 PM
Static Analysis
Status: Started
Installer: https://github.com/stnkl/EverythingToolbar/releases/download/0.7.1/EverythingToolbar-0.7.1.msi

7/14/2021 2:58:50 PM
Status: Completed
Installer https://github.com/stnkl/EverythingToolbar/releases/download/0.7.1/EverythingToolbar-0.7.1.msi 
Result: Succeeded

7/14/2021 2:58:52 PM

****************************************************************************************
Installer Validation
****************************************************************************************
Status: Completed
-----------------------------------------------------
Installer https://github.com/stnkl/EverythingToolbar/releases/download/0.7.1/EverythingToolbar-0.7.1.msi
Result: Validation Succeeded
-----------------------------------------------------
Result: Succeeded
```
🤷‍♂️

2021-07-16 00:53 UTC, denelon commented
Lots of moving pieces, and active development. I'm not sure what happened exactly. I was just responding to the comment about the label. There may be some other subtle edge cases where the label gets set. It's new enough we didn't even have it in our document, so I had to do a bit of digging myself.