Metadata: ProtonTechnologies.ProtonVPN version 1.16.3
microsoft/winget-pkgs pull request #21686
Opened 2021-07-18 17:13 UTC by vedantmgoyal2009

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-18 18:17 UTC, ItzLevvie requested changes

2021-07-18 18:17 UTC, ItzLevvie commented on manifests/p/ProtonTechnologies/ProtonVPN/1.16.3/ProtonTechnologies.ProtonVPN.locale.en-US.yaml
> +- private network
```suggestion
- private-network
```

2021-07-18 18:48 UTC, ItzLevvie requested changes
Please wait for an engineer to take a look.

2021-07-21 02:45 UTC, vedantmgoyal2009 commented
Ok

2021-07-25 05:04 UTC, vedantmgoyal2009 commented
Please look this PR also.

2021-07-27 08:28 UTC, ItzLevvie requested changes
I'm seeing:
![image](https://user-images.githubusercontent.com/11600822/127122177-981c2c01-22a0-4689-93b9-0a398a5c81ca.png)

It seems to install the application using multiple MSI installers and one of them errors out because only one MSI installer can be installed at a time.

2021-07-27 22:09 UTC, ItzLevvie requested changes
I'm still seeing the same on Windows Sandbox:
![image](https://user-images.githubusercontent.com/11600822/127234033-07657756-6725-4409-89cd-4764a5be0f81.png)

2021-07-28 04:44 UTC, vedantmgoyal2009 commented
If it is failing, the manifest should be removed from the repo.

2021-07-29 10:54 UTC, closed without merging