Added Certify SSL Manager version 5.5.1.0.
microsoft/winget-pkgs pull request #22064
Opened 2021-07-22 11:12 UTC by jedieaston

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

2021-07-22 11:13 UTC, ItzLevvie approved these changes

2021-07-22 11:17 UTC, ItzLevvie requested changes

2021-07-22 11:17 UTC, ItzLevvie commented on manifests/c/CertifyTheWeb/CertifySSLManager/5.5.1.0/CertifyTheWeb.CertifySSLManager.yaml
> +Publisher: Certify The Web
```suggestion
Publisher: Webprofusion Pty Ltd
```

2021-07-22 11:17 UTC, ItzLevvie commented on manifests/c/CertifyTheWeb/CertifySSLManager/5.5.1.0/CertifyTheWeb.CertifySSLManager.yaml
> +PackageVersion: 5.5.1.0
```suggestion
PackageVersion: 5.5.1
```

2021-07-22 11:17 UTC, ItzLevvie commented on manifests/c/CertifyTheWeb/CertifySSLManager/5.5.1.0/CertifyTheWeb.CertifySSLManager.yaml
> +PackageName: Certify SSL Manager
```suggestion
PackageName: Certify The Web
```

2021-07-23 07:50 UTC, OfficialEsco approved these changes

2021-07-23 07:50 UTC, merged