CodecGuide.K LiteCodecPackStandard 16.3.5
microsoft/winget-pkgs pull request #22072
Opened 2021-07-22 11:41 UTC by OfficialEsco

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-22 11:46 UTC, ItzLevvie requested changes
Looks like a weird file was added: https://github.com/microsoft/winget-pkgs/pull/22072/files#diff-8f277251d1ce3bae4a66180ac19df83f214dddce31e04a56052bf620c1658d9d

2021-07-22 11:55 UTC, OfficialEsco commented
No idea how that got in these PR's as i've used the same branch for other PR's today (#21204)
![image](https://user-images.githubusercontent.com/15158490/126634935-3f5322be-a1b5-47a6-9499-97cfcd8e48fc.png)

My master:
![image](https://user-images.githubusercontent.com/15158490/126634971-c06123d6-b765-440a-9bf2-729016459f80.png)

Upstream master:
![image](https://user-images.githubusercontent.com/15158490/126635006-68e856b0-3417-47f2-8bcd-17e4fe92c312.png)

These branches:
![image](https://user-images.githubusercontent.com/15158490/126635125-79c0a942-0fbe-4ae9-863e-905d670215be.png)

2021-07-22 12:27 UTC, ItzLevvie approved these changes

2021-07-22 12:28 UTC, merged

2021-07-23 16:34 UTC, denelon commented
@ItzLevvie Just a heads-up. I'll be off the grid next week 7/26-7/30: Training at 🏕️ Baker.

The .validation files are used when an exception has been granted for a false positive on one of our automated policy checks. Those files should live in either the "Publisher" or "Package" directory, and not inside "Version" directories.