raimo.Smallpdf version 2.3.0.0
microsoft/winget-pkgs pull request #22132
Opened 2021-07-23 15:25 UTC by Gashans

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-23 18:42 UTC, ashpatil-msft commented
/azp run

2021-07-23 20:02 UTC, ChuckFerring commented
It appears that this is a 64bit application but the specified installer is x86.

2021-07-24 12:51 UTC, ItzLevvie requested changes

2021-07-24 12:51 UTC, ItzLevvie commented on manifests/r/raimo/Smallpdf/2.3.0.0/raimo.Smallpdf.installer.yaml
> +  Architecture: x86
```suggestion
  Architecture: x64
```

2021-07-24 12:51 UTC, ItzLevvie commented on manifests/r/raimo/Smallpdf/2.3.0.0/raimo.Smallpdf.locale.en-US.yaml
> +ShortDescription: pdf management programm
```suggestion
ShortDescription: Smallpdf is the first and only PDF software you’ll love. We have all the tools you’ll need to start, manage, and finish your work with digital documents.
```

2021-07-24 12:51 UTC, ItzLevvie commented on manifests/r/raimo/Smallpdf/2.3.0.0/raimo.Smallpdf.locale.en-US.yaml
> +License: ???
```suggestion
License: Proprietary
```

2021-07-30 13:36 UTC, ItzLevvie approved these changes
![image](https://user-images.githubusercontent.com/11600822/127660886-7af5e16c-6a98-4451-ac96-2e388e223fdf.png)

2021-07-30 13:37 UTC, merged