Added Visual Studio 2022 Community Preview 2
microsoft/winget-pkgs pull request #22305
Opened 2021-07-25 11:32 UTC by bearmannl

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-07-25 12:52 UTC, ItzLevvie requested changes

2021-07-25 12:52 UTC, ItzLevvie commented on manifests/m/Microsoft/VisualStudio/2022/Community-Preview/17.0.0 Preview 2/Microsoft.VisualStudio.2022.Community-Preview.locale.en-US.yaml
> +Moniker: vs2022-Community-preview
```suggestion
Moniker: vs2022-community-preview
```

2021-07-25 12:52 UTC, ItzLevvie commented on manifests/m/Microsoft/VisualStudio/2022/Community-Preview/17.0.0 Preview 2/Microsoft.VisualStudio.2022.Community-Preview.locale.en-US.yaml
> +PackageVersion: 17.0.0 Preview 2
```suggestion
PackageVersion: 17.0.0 Preview 2.1
```

2021-07-25 12:52 UTC, ItzLevvie commented on manifests/m/Microsoft/VisualStudio/2022/Community-Preview/17.0.0 Preview 2/Microsoft.VisualStudio.2022.Community-Preview.installer.yaml
> +PackageVersion: 17.0.0 Preview 2
```suggestion
PackageVersion: 17.0.0 Preview 2.1
```

2021-07-25 12:52 UTC, ItzLevvie commented on manifests/m/Microsoft/VisualStudio/2022/Community-Preview/17.0.0 Preview 2/Microsoft.VisualStudio.2022.Community-Preview.locale.en-US.yaml
> +ShortDescription: Visual Studio 2022 Community Preview
```suggestion
ShortDescription: Visual Studio Community 2022 Preview
```

2021-07-25 12:52 UTC, ItzLevvie commented on manifests/m/Microsoft/VisualStudio/2022/Community-Preview/17.0.0 Preview 2/Microsoft.VisualStudio.2022.Community-Preview.yaml
> +PackageVersion: 17.0.0 Preview 2
```suggestion
PackageVersion: 17.0.0 Preview 2.1
```

2021-07-25 17:34 UTC, bearmannl commented on manifests/m/Microsoft/VisualStudio/2022/Community-Preview/17.0.0 Preview 2/Microsoft.VisualStudio.2022.Community-Preview.installer.yaml
> +PackageVersion: 17.0.0 Preview 2
Good catch, thanks!

2021-07-26 07:51 UTC, ItzLevvie approved these changes

2021-07-26 08:28 UTC, ItzLevvie approved these changes

2021-07-26 08:43 UTC, merged