Submitting  Intuiter version 0.7.3.yaml
microsoft/winget-pkgs pull request #22925
Opened 2021-07-30 18:01 UTC by seonglae

- [o] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [o] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [o] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [o] Have you tested your manifest locally with `winge@mast install --manifest <path>`?
- [o] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

2021-07-30 19:51 UTC, ItzLevvie requested changes
![image](https://user-images.githubusercontent.com/11600822/127704726-a37af04e-c6a8-4985-8d2a-087d4c70be1b.png)

2021-07-30 19:51 UTC, ItzLevvie commented on manifests/s/Seonglae/Intuiter/0.7.3/Seonglae.Intuiter.yaml
> +- Architecture: x86
```suggestion
- Architecture: x64
```

2021-07-30 19:51 UTC, ItzLevvie requested changes

2021-07-30 19:51 UTC, ItzLevvie commented on manifests/s/Seonglae/Intuiter/0.7.3/Seonglae.Intuiter.yaml
> +Publisher: Seonglae
```suggestion
Publisher: Seonglae Cho
```

2021-07-31 04:34 UTC, seonglae commented
@msftbot

2021-07-31 10:20 UTC, OfficialEsco approved these changes

2021-07-31 10:21 UTC, merged