Add L'math 1.6
microsoft/winget-pkgs pull request #2366
Opened 2020-07-08 11:23 UTC by TheJiahao

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

2020-07-09 12:49 UTC, OfficialEsco requested changes
Redirect fix, also sent to smartscreen just incase

2020-07-09 12:49 UTC, OfficialEsco commented on manifests/RoniLehto/Lmath/1.6.yaml
> +    Url: https://www.lehtodigital.fi/lmath/proxy.php?download=win32
```suggestion
    Url: https://github.com/lehtoroni/lmath-issues/releases/download/r1.6/LMath_Windows_r1.6.exe
```
`https://www.lehtodigital.fi/lmath/proxy.php?download=win32` redirects to `https://github.com/lehtoroni/lmath-issues/releases/download/r1.6/LMath_Windows_r1.6.exe`

2020-07-09 13:05 UTC, TheJiahao commented
@OfficialEsco The suggestion sounds reasonable, committed. Additionally, the bot removed the labels as well.

2020-07-12 15:38 UTC, ghost approved these changes
Validation has completed

2020-07-12 15:38 UTC, merged