nimblenote.nimblenote version 2.0.2.605
microsoft/winget-pkgs pull request #23722
Opened 2021-08-04 10:55 UTC by oxygen-dioxide

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-08-04 14:51 UTC, OfficialEsco requested changes

2021-08-04 14:51 UTC, OfficialEsco commented on manifests/n/nimblenote/nimblenote/2.0.2.605/nimblenote.nimblenote.installer.yaml
> +PackageVersion: 2.0.2.605
```suggestion
PackageVersion: 2.0.2
```

2021-08-04 14:51 UTC, OfficialEsco commented on manifests/n/nimblenote/nimblenote/2.0.2.605/nimblenote.nimblenote.locale.en-US.yaml
> +ShortDescription: Simple keyboard-driven note taking
```suggestion
PackageVersion: 2.0.2
PackageLocale: en-US
Publisher:leaves under foot ltd
PackageName: nimblenote
License: Copyright © 2020 leaves under foot ltd
ShortDescription: Simple keyboard-driven note taking
Description: nimblenote is a simple keyboard-driven note taking application. Search, create, edit and delete notes all without the mouse.
```

2021-08-04 14:51 UTC, OfficialEsco commented on manifests/n/nimblenote/nimblenote/2.0.2.605/nimblenote.nimblenote.yaml
> +PackageVersion: 2.0.2.605
```suggestion
PackageVersion: 2.0.2
```

2021-08-05 04:17 UTC, vedantmgoyal2009 requested changes
You have not updated the directory name.

2021-08-05 04:17 UTC, vedantmgoyal2009 commented on manifests/n/nimblenote/nimblenote/2.0.2.605/nimblenote.nimblenote.installer.yaml
> +PackageVersion: 2.0.2
```suggestion
PackageVersion: 2.0.2.605

```

2021-08-05 04:17 UTC, vedantmgoyal2009 commented on manifests/n/nimblenote/nimblenote/2.0.2.605/nimblenote.nimblenote.locale.en-US.yaml
> +PackageVersion: 2.0.2
```suggestion
PackageVersion: 2.0.2.605

```

2021-08-05 04:17 UTC, vedantmgoyal2009 commented on manifests/n/nimblenote/nimblenote/2.0.2.605/nimblenote.nimblenote.yaml
> +PackageVersion: 2.0.2
```suggestion
PackageVersion: 2.0.2.605

```

2021-08-05 09:48 UTC, OfficialEsco requested changes

2021-08-05 09:48 UTC, OfficialEsco commented on manifests/n/nimblenote/nimblenote/2.0.2/nimblenote.nimblenote.locale.en-US.yaml
> +Publisher:leaves under foot ltd
```suggestion
Publisher: leaves under foot ltd
```
My bad
`(Line: 7, Col: 1, Idx: 223) - (Line: 7, Col: 32, Idx: 254): While parsing a block mapping, did not find expected key.`

2021-08-05 13:03 UTC, OfficialEsco approved these changes

2021-08-05 13:04 UTC, merged