Added Puppet Development Kit version 2.2.0.0.
microsoft/winget-pkgs pull request #23732
Opened 2021-08-04 12:16 UTC by jedieaston

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23732)

2021-08-04 16:08 UTC, OfficialEsco requested changes

2021-08-04 16:08 UTC, OfficialEsco commented on manifests/p/Puppet/pdk/2.2.0.0/Puppet.pdk.yaml
> +Publisher: Puppet, Inc
![image](https://user-images.githubusercontent.com/15158490/128215543-4a89da0a-3d5a-4394-83f2-a5dc2bcaa9a2.png)
```suggestion
PackageVersion: 2.2.0
PackageName: Puppet Development Kit
Publisher: Puppet Inc
```

2021-08-05 09:02 UTC, ItzLevvie approved these changes

2021-08-05 16:27 UTC, vedantmgoyal2009 approved these changes

2021-08-05 16:27 UTC, merged