SignatureSha256/FamilyName: Finebits.MetroCommander version 1.3.86.0
microsoft/winget-pkgs pull request #24157
Opened 2021-08-07 03:20 UTC by vedantmgoyal2009

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-08-09 21:16 UTC, ItzLevvie requested changes
![image](https://user-images.githubusercontent.com/11600822/128775619-512aab1c-9d46-4b19-94d1-dc5d3d00d62a.png)

2021-08-09 21:16 UTC, ItzLevvie commented on manifests/f/Finebits/MetroCommander/1.3.86.0/Finebits.MetroCommander.yaml
>    InstallerSwitches:
```suggestion
```
This isn't meant to be here.

2021-08-09 21:16 UTC, ItzLevvie commented on manifests/f/Finebits/MetroCommander/1.3.86.0/Finebits.MetroCommander.yaml
> +   SilentWithProgress: /S
```suggestion
```
This isn't meant to be here.

2021-08-10 02:44 UTC, vedantmgoyal2009 commented
Yeah, I removed it first but then added it back as I thought Pipelines were failing due to this.

2021-08-12 11:07 UTC, closed without merging