Update: Baidunetdisk 7.6.0
microsoft/winget-pkgs pull request #24197
Opened 2021-08-07 14:53 UTC by Meng5in

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-08-07 16:49 UTC, ImJoakim reviewed
You can only submit 1 manifest per PR. You are currently trying to add version `7.5.1` and version `7.6.0`. Based on your PR title, you need to remove the files for version `7.5.1`.

2021-08-08 16:26 UTC, OfficialEsco requested changes

2021-08-08 16:26 UTC, OfficialEsco commented on manifests/b/baidu/baidunetdisk/7.6.0/baidu.baidunetdisk.installer.yaml
> +    SilentWithProgress: /S
This is not needed
```suggestion
```

2021-08-08 16:26 UTC, OfficialEsco commented on manifests/b/baidu/baidunetdisk/7.6.0/baidu.baidunetdisk.locale.en-US.yaml
> +PackageName: baidunetdisk
```suggestion
PackageName: 百度网盘
```

2021-08-08 16:26 UTC, OfficialEsco commented on manifests/b/baidu/baidunetdisk/7.6.0/baidu.baidunetdisk.locale.zh-CN.yaml
> +PackageName: BaiduNetdisk
```suggestion
PackageName: 百度网盘
```

2021-08-10 12:05 UTC, OfficialEsco submitted a review, later dismissed
Also accepting this one since the zh-CN locale got the correct PackageName

2021-08-10 12:21 UTC, Meng5in reviewed
> Also accepting this one since the zh-CN locale got the correct PackageName

But I have changed the PackageName in the zh-CN locale.
I can't understand.

2021-08-10 12:26 UTC, OfficialEsco commented
> But I have changed the PackageName in the zh-CN locale.
> I can't understand.

Yes you did in the zh-CN locale, but not the en-US locale.
The Software installs as `百度网盘` on a en-US computer, which is why i suggested this change https://github.com/microsoft/winget-pkgs/pull/24197#discussion_r684798516
Atm the en-US locale PackageName is more of a English moniker for the software, but since its correct in the zh-CN locale this is "ok", however someone will probably update it to `百度网盘` in the next version.

2021-08-10 17:55 UTC, palenshus commented
/AzurePipelines run

2021-08-10 18:37 UTC, merged