Added Tencent.TencentMeeting 2.16.2.406
microsoft/winget-pkgs pull request #24289
Opened 2021-08-09 01:36 UTC by VAllens

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-08-10 12:09 UTC, OfficialEsco requested changes

2021-08-10 12:09 UTC, OfficialEsco commented on manifests/t/Tencent/TencentMeeting/2.16.2.406/Tencent.TencentMeeting.locale.en-US.yaml
> +Publisher: Tencent
```suggestion
Publisher: Tencent Technology (Shenzhen) Co. Ltd.
```

2021-08-10 12:32 UTC, VAllens commented
Hi, @OfficialEsco 
This is generated automatically using the `wingetcreate` tool.

2021-08-10 12:47 UTC, OfficialEsco commented
> Hi, @OfficialEsco
> This is generated automatically using the `wingetcreate` tool.

Either the previous manifest was wrong or the current version changed the Publisher field

2021-08-10 14:58 UTC, OfficialEsco approved these changes

2021-08-10 17:55 UTC, palenshus commented
/AzurePipelines run

2021-08-10 18:37 UTC, merged

2021-08-11 02:24 UTC, VAllens commented
> > Hi, @OfficialEsco
> > This is generated automatically using the  tool.`wingetcreate`
> 
> Either the previous manifest was wrong or the current version changed the Publisher field

Maybe, the current version has changed the publisher field.
thanks. :)