Added Simplenote version 2.15.0.
microsoft/winget-pkgs pull request #24329
Opened 2021-08-09 23:08 UTC by jedieaston

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

2021-08-10 04:46 UTC, vedantmgoyal2009 commented
#24120 #24119 #24118 #24116 #24114 #24113 #24110 #24109 #24108 #24106 Why? Is there any issue with pipelines?

2021-08-11 21:59 UTC, palenshus commented
/AzurePipelines run

2021-08-11 22:55 UTC, palenshus commented
This is failing due to a SignatureSha256 hash mismatch

2021-08-12 02:34 UTC, vedantmgoyal2009 commented
> This is failing due to a SignatureSha256 hash mismatch, winget-create will help you avoid these

I took the hash from `winget hash -f`.

2021-08-12 11:05 UTC, ItzLevvie requested changes

2021-08-12 11:05 UTC, ItzLevvie commented on manifests/a/Automattic/Simplenote/2.15.0/Automattic.Simplenote.installer.yaml
> +  SignatureSha256: 0B949D4FBC8FE97553562F2678E86A2CAA6AF8FBDA26CA954A6AE4DF785AA653
```suggestion
  SignatureSha256: E78161A416905A639955D8DFAA8AB3FE6CCF0917CBAB388214D7C4D90324B41B
```

2021-08-12 11:05 UTC, ItzLevvie commented on manifests/a/Automattic/Simplenote/2.15.0/Automattic.Simplenote.installer.yaml
> +  SignatureSha256: 01C0122D12D272C021C1E0A50B91FC8BF8CD6CF23007752C5F50EC3C2267B907
```suggestion
  SignatureSha256: 87C306F0D5C4575E8D8CF5BBA2F5361EBDFB244A7586D57729ACCF8E02D38BD5
```

2021-08-12 12:13 UTC, ItzLevvie approved these changes

2021-08-12 12:14 UTC, merged