SignatureSha256/FamilyName: Trufflesuite.Ganache version 2.5.4
microsoft/winget-pkgs pull request #25064
Opened 2021-08-15 07:59 UTC by vedantmgoyal2009

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-08-15 13:44 UTC, ItzLevvie requested changes

2021-08-15 13:44 UTC, ItzLevvie commented on manifests/t/Trufflesuite/Ganache/2.5.4/Trufflesuite.Ganache.locale.en-US.yaml
> +Publisher: Trufflesuite
```suggestion
Publisher: Truffle
```

2021-08-15 14:16 UTC, ItzLevvie requested changes
Duplicate of https://github.com/microsoft/winget-pkgs/pull/25047.

2021-08-15 22:22 UTC, ItzLevvie requested changes
https://github.com/microsoft/winget-pkgs/pull/25064#pullrequestreview-730192062

2021-08-16 05:57 UTC, ItzLevvie requested changes
Incorrect `Publisher`.

2021-08-16 07:15 UTC, vedantmgoyal2009 commented
Setting Publisher to 'Truffle' leads to validation failure.

2021-08-16 10:23 UTC, ItzLevvie commented
I don't know what the difference between this and https://github.com/microsoft/winget-pkgs/pull/25047 is, but could you please contribute over at https://github.com/OfficialEsco/winget-pkgs/tree/Trufflesuite.Ganache-2.5.4 instead?

It also looks like the `Installers:` section in file `Trufflesuite.Ganache.yaml` isn't meant to be there.

2021-08-16 10:27 UTC, ItzLevvie requested changes
https://github.com/microsoft/winget-pkgs/pull/25064#issuecomment-899398671

2021-08-17 09:54 UTC, vedantmgoyal2009 commented
After #25217 will get merged, my PR will pass the Validation Pipeline.

2021-08-18 08:26 UTC, ItzLevvie commented
Since @OfficialEsco's PR was merged, this can be closed now.

2021-08-18 08:42 UTC, ItzLevvie requested changes
https://github.com/microsoft/winget-pkgs/pull/25064#issuecomment-900922819

2021-08-18 08:50 UTC, vedantmgoyal2009 commented
Please approve. I don't think it will create any issues.

2021-08-18 09:16 UTC, OfficialEsco commented
Why?.. the only change is the location of the user scope

2021-08-19 08:41 UTC, ItzLevvie requested changes
https://github.com/microsoft/winget-pkgs/pull/25064#issuecomment-900955678

2022-03-01 12:17 UTC, ItzLevvie approved these changes

2022-03-01 15:22 UTC, merged