Iterate.MountainDuck version 4.7.1.18339
microsoft/winget-pkgs pull request #25097
Opened 2021-08-15 20:45 UTC by chausner

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-08-16 11:42 UTC, ItzLevvie requested changes
(refs/pull/25097/head): PR validation failed. Actual: 3010, Expected: 0. Please test your WinGet package inside of a virtual machine. For more infomation about error codes, please read https://docs.microsoft.com/en-us/windows/win32/msi/error-codes.

2021-08-16 22:53 UTC, chausner commented
> (refs/pull/25097/head): PR validation failed. Actual: 3010, Expected: 0. Please test your WinGet package inside of a virtual machine. For more infomation about error codes, please read https://docs.microsoft.com/en-us/windows/win32/msi/error-codes.

Exit code 3010 means success but a reboot is required. I have fixed it in the manifest.

2021-08-17 16:37 UTC, OfficialEsco reviewed
Uhhh is there no NORESTART switch for this? It just instantly rebooted without any warning which is a very bad user experience...

2021-08-17 16:40 UTC, OfficialEsco requested changes
99% sure /norestart worked

2021-08-17 16:40 UTC, OfficialEsco commented on manifests/i/Iterate/MountainDuck/4.7.1.18339/Iterate.MountainDuck.installer.yaml
> +  InstallerSha256: 24DED835D1A36C259A9B25A7B500074C68D88B65B41A2FA0AD56E58CE7D51496
```suggestion
  InstallerSha256: 24DED835D1A36C259A9B25A7B500074C68D88B65B41A2FA0AD56E58CE7D51496
  InstallerSwitches:
    Custom: /norestart
```

2021-08-17 17:21 UTC, chausner commented
> 99% sure /norestart worked

Ah great, thanks!

2021-08-17 18:45 UTC, OfficialEsco approved these changes

2021-08-17 18:46 UTC, merged