bytedance.bytedance-devtool version 3.1.3
microsoft/winget-pkgs pull request #25147
Opened 2021-08-16 12:37 UTC by oxygen-dioxide

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-08-16 13:49 UTC, ItzLevvie requested changes

2021-08-16 13:49 UTC, ItzLevvie commented on manifests/b/bytedance/bytedance-devtool/3.1.3/bytedance.bytedance-devtool.installer.yaml
> +  InstallerSha256: 6D119D20CBE19DE9CA99770270E5960C66EAB0C1A99507B41FFC5218825DD0C1
```suggestion
  InstallerSha256: 6D119D20CBE19DE9CA99770270E5960C66EAB0C1A99507B41FFC5218825DD0C1
  ProductCode: 0d6cc698-a1aa-5593-a60b-0310adcebfe2
```

2021-08-17 16:32 UTC, OfficialEsco approved these changes

2021-08-19 17:49 UTC, ryfu-msft commented
/azp run

2021-08-19 18:35 UTC, merged