GNURadio.GNURadio version 3.8.2.0
microsoft/winget-pkgs pull request #25454
Opened 2021-08-19 12:42 UTC by oxygen-dioxide

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-08-19 15:33 UTC, ImJoakim commented on manifests/g/GNURadio/GNURadio/3.8.2.0/GNURadio.GNURadio.installer.yaml
> +PackageVersion: 3.8.2.0
![image](https://user-images.githubusercontent.com/52826317/130097721-17aacc3e-90f5-4c28-b67a-2f1ef4e938a4.png)

```suggestion
PackageVersion: 3.8.2.1
```

2021-08-19 15:33 UTC, ImJoakim commented on manifests/g/GNURadio/GNURadio/3.8.2.0/GNURadio.GNURadio.locale.en-US.yaml
> +PackageVersion: 3.8.2.0
![image](https://user-images.githubusercontent.com/52826317/130097721-17aacc3e-90f5-4c28-b67a-2f1ef4e938a4.png)

```suggestion
PackageVersion: 3.8.2.1
```

2021-08-19 15:33 UTC, ImJoakim commented on manifests/g/GNURadio/GNURadio/3.8.2.0/GNURadio.GNURadio.yaml
> +PackageVersion: 3.8.2.0
![image](https://user-images.githubusercontent.com/52826317/130097721-17aacc3e-90f5-4c28-b67a-2f1ef4e938a4.png)

```suggestion
PackageVersion: 3.8.2.1
```

2021-08-19 15:34 UTC, ImJoakim commented on manifests/g/GNURadio/GNURadio/3.8.2.0/GNURadio.GNURadio.locale.en-US.yaml
> +ShortDescription: GNURadio.GNURadio
```suggestion
ShortDescription: GNU Radio is a free & open-source software development toolkit that provides signal processing blocks to implement software radios.
```

2021-08-19 15:34 UTC, ImJoakim commented on manifests/g/GNURadio/GNURadio/3.8.2.0/GNURadio.GNURadio.locale.en-US.yaml
> +Publisher: GNURadio
![image](https://user-images.githubusercontent.com/52826317/130097946-de13db92-083c-44b5-a270-25af8e101ce9.png)

```suggestion
Publisher: GCN Development
```

2021-08-19 15:36 UTC, ImJoakim commented
Please see my comments above. You also need to change the version folder:

`manifests/g/GNURadio/GNURadio/3.8.2.0/` -> `manifests/g/GNURadio/GNURadio/3.8.2.1/`

https://github.com/microsoft/winget-pkgs/pull/25454#discussion_r692236951
https://github.com/microsoft/winget-pkgs/pull/25454#discussion_r692237094
https://github.com/microsoft/winget-pkgs/pull/25454#discussion_r692237196
https://github.com/microsoft/winget-pkgs/pull/25454#discussion_r692237724
https://github.com/microsoft/winget-pkgs/pull/25454#discussion_r692238121

2021-08-19 15:36 UTC, ImJoakim requested changes
Please see my comments above. You also need to change the version folder:

`manifests/g/GNURadio/GNURadio/3.8.2.0/` -> `manifests/g/GNURadio/GNURadio/3.8.2.1/`

https://github.com/microsoft/winget-pkgs/pull/25454#discussion_r692236951
https://github.com/microsoft/winget-pkgs/pull/25454#discussion_r692237094
https://github.com/microsoft/winget-pkgs/pull/25454#discussion_r692237196
https://github.com/microsoft/winget-pkgs/pull/25454#discussion_r692237724
https://github.com/microsoft/winget-pkgs/pull/25454#discussion_r692238121

2021-08-20 09:19 UTC, ItzLevvie approved these changes

2021-08-20 10:01 UTC, merged