New: Tencent.WeSing version 2.21.170.63
microsoft/winget-pkgs pull request #25558
Opened 2021-08-20 17:24 UTC by SpecterShell

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-08-20 20:18 UTC, OfficialEsco approved these changes, later dismissed

2021-08-21 00:53 UTC, ryfu-msft commented
Hey @SpecterShell ,
I followed the publisherURL and found the installerURL to be https://c.y.qq.com/r/7qZ5
Just want to the link to match what's shown on the publisher's official site. Thanks!

2021-08-21 09:07 UTC, SpecterShell commented
Using [https://c.y.qq.com/r/7qZ5](https://c.y.qq.com/r/7qZ5) directly just redirects to the homepage. Use the destination URL instead.
![image](https://user-images.githubusercontent.com/56779163/130316837-9902d762-d136-45b9-ab4d-9ff2e11aa92b.png)

2021-08-21 19:59 UTC, ItzLevvie requested changes

2021-08-21 19:59 UTC, ItzLevvie commented on manifests/t/Tencent/WeSing/2.21.170.63/Tencent.WeSing.locale.en-US.yaml
> +Moniker: WeSing
```suggestion
Moniker: wesing
```

2021-08-22 11:26 UTC, ItzLevvie approved these changes

2021-08-23 22:10 UTC, merged