vradarserver.vrs version 2.4.4
microsoft/winget-pkgs pull request #26885
Opened 2021-09-03 11:55 UTC by Boxersteavee

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-09-03 13:07 UTC, Boxersteavee commented
What happened there.... It worked fine for me during testing

2021-09-03 16:41 UTC, ItzLevvie requested changes

2021-09-03 16:41 UTC, ItzLevvie commented on manifests/v/vradarserver/vrs/2.4.4/vradarserver.vrs.locale.en-US.yaml
> +- dump1090 dump
```suggestion
- virtual-radar
- virtual-radar-server
- dump1090
- dump
```

2021-09-03 16:41 UTC, ItzLevvie commented on manifests/v/vradarserver/vrs/2.4.4/vradarserver.vrs.locale.en-US.yaml
> +PackageName: vrs
```suggestion
PackageName: Virtual Radar
```

2021-09-03 16:41 UTC, ItzLevvie commented on manifests/v/vradarserver/vrs/2.4.4/vradarserver.vrs.installer.yaml
> +  InstallerSha256: 02CB721766B8D2ADEBEB773A168FBAC12619EC275F4C696BF80CB1AFC273E071
```suggestion
  InstallerSha256: 02CB721766B8D2ADEBEB773A168FBAC12619EC275F4C696BF80CB1AFC273E071
  ProductCode: Virtual Radar_is1
```

2021-09-03 16:41 UTC, ItzLevvie commented on manifests/v/vradarserver/vrs/2.4.4/vradarserver.vrs.installer.yaml
> +  InstallerUrl: http://www.virtualradarserver.co.uk/Files/VirtualRadarSetup.exe
```suggestion
  InstallerUrl: https://www.virtualradarserver.co.uk/Files/VirtualRadarSetup.exe
```

2021-09-03 16:41 UTC, ItzLevvie commented on manifests/v/vradarserver/vrs/2.4.4/vradarserver.vrs.locale.en-US.yaml
> +Description: '"Virtual Radar Server is an open-source .NET application that runs a local web server"'
```suggestion
ShortDescription: Virtual Radar Server is an open-source .NET application that runs a local web server.
Description: Virtual Radar Server is an open-source .NET application that runs a local web server.
```

2021-09-03 20:10 UTC, ItzLevvie approved these changes

2021-09-04 10:47 UTC, Boxersteavee commented
I have no idea what's going on here, it worked fine for me during testing.

2021-09-04 10:55 UTC, ItzLevvie commented
> I have no idea what's going on here, it worked fine for me during testing.

Wait for an engineer to take a look. The error may also be related to the architecture specified in the manifest (i.e. the installer could be x64 but you listed x86)

2021-09-08 18:05 UTC, ChuckFerring commented
The application has a runtime dependency on .Net Framework 3.5.

2021-09-11 23:03 UTC, Boxersteavee commented
> > I have no idea what's going on here, it worked fine for me during testing.
> 
> Wait for an engineer to take a look. The error may also be related to the architecture specified in the manifest (i.e. the installer could be x64 but you listed x86)

Website said x86 (altho x64 is available and I was planning on adding that after)

2021-09-11 23:04 UTC, Boxersteavee commented
> The application has a runtime dependency on .Net Framework 3.5.

So what do I do then? (sorry for not replying recently I have been super busy IRL)

2022-12-04 22:55 UTC, closed without merging