New version: Microsoft.dotnetruntime.3-x64 3.1.19.30416
microsoft/winget-pkgs pull request #27721
Opened 2021-09-15 14:15 UTC by lychichem

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-09-15 14:40 UTC, KaranKad requested changes

2021-09-15 14:40 UTC, KaranKad commented on manifests/m/Microsoft/dotnetRuntime/3-x64/3.1.19.30416/Microsoft.dotnetRuntime.3-x64.installer.yaml
> +  InstallerType: exe
```suggestion
  InstallerType: burn
```

2021-09-15 14:40 UTC, KaranKad commented on manifests/m/Microsoft/dotnetRuntime/3-x64/3.1.19.30416/Microsoft.dotnetRuntime.3-x64.installer.yaml
> +    SilentWithProgress: /passive
```suggestion
```

2021-09-16 16:59 UTC, ItzLevvie approved these changes

2021-09-16 16:59 UTC, merged