MicrosoftCorporation.WindowsPCHealthCheck version 3.0.2109.14001
microsoft/winget-pkgs pull request #28276
Opened 2021-09-22 14:18 UTC by m4ttyj

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-09-22 14:29 UTC, jedieaston requested changes
wingetcreate tries to put Microsoft software in "MicrosoftCorporation", but we use "Microsoft" instead. Once you apply these changes, you'll also have to move it to the Microsoft folder. 

Thanks!

2021-09-22 14:29 UTC, jedieaston commented on manifests/m/MicrosoftCorporation/WindowsPCHealthCheck/3.0.2109.14001/MicrosoftCorporation.WindowsPCHealthCheck.installer.yaml
> +PackageIdentifier: MicrosoftCorporation.WindowsPCHealthCheck
```suggestion
PackageIdentifier: Microsoft.WindowsPCHealthCheck

```

2021-09-22 14:29 UTC, jedieaston commented on manifests/m/MicrosoftCorporation/WindowsPCHealthCheck/3.0.2109.14001/MicrosoftCorporation.WindowsPCHealthCheck.locale.en-US.yaml
> +PackageIdentifier: MicrosoftCorporation.WindowsPCHealthCheck
```suggestion
PackageIdentifier: Microsoft.WindowsPCHealthCheck

```

2021-09-22 14:29 UTC, jedieaston commented on manifests/m/MicrosoftCorporation/WindowsPCHealthCheck/3.0.2109.14001/MicrosoftCorporation.WindowsPCHealthCheck.yaml
> +PackageIdentifier: MicrosoftCorporation.WindowsPCHealthCheck
```suggestion
PackageIdentifier: Microsoft.WindowsPCHealthCheck

```

2021-09-22 14:35 UTC, jedieaston requested changes
Hot tip to change the folder name: Press "." on your keyboard when you have GitHub open to this PR in your browser, and a web version of VSCode will launch. 

Once it loads, find the files you added, and drag the WIndowsPCHealthCheck folder to Microsoft. Then use the source control button on the left to commit (it's automatically pushed).

![image](https://user-images.githubusercontent.com/21368066/134364126-9a95a8fc-55c1-4fee-9b8b-146545e2d24d.png)

2021-09-23 22:50 UTC, Rolling2405 commented
@m4ttyj  I already have a pull request with this manifest [https://github.com/microsoft/winget-pkgs/pull/28359](url)

2021-09-24 05:34 UTC, Rolling2405 commented
#28359

2021-09-24 10:23 UTC, closed without merging