Update XnView MP to 0.99.1
microsoft/winget-pkgs pull request #28491
Opened 2021-09-24 07:56 UTC by auanasgheps

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-09-24 09:34 UTC, OfficialEsco reviewed
Works in Sandbox
@ItzLevvie or @ImJoakim can one of you please test the x86?

2021-09-24 09:35 UTC, OfficialEsco requested changes

2021-09-24 09:35 UTC, OfficialEsco commented on manifests/x/XnSoft/XnViewMP/0.99.1/XnSoft.XnViewMP.locale.en-US.yaml
> +- image viewer
Someone gonna suggest this sooner or later 👀
```suggestion
- image-viewer
```

2021-09-24 09:42 UTC, ImJoakim commented
> Works in x64 Sandbox
> @ItzLevvie or @ImJoakim can one of you please test the x86?

Seems to work fine.

![ra2vthl7wrno](https://user-images.githubusercontent.com/52826317/134654087-d1ecf8e4-4a49-4df3-9d85-fe9ba89acea8.png)

2021-09-24 09:45 UTC, auanasgheps commented
Thank you guys for showing test results, you were faster than me.

2021-09-24 10:11 UTC, OfficialEsco approved these changes
![image](https://user-images.githubusercontent.com/15158490/134658247-90c63d75-56a8-48b4-8dfc-c3fc5fed8c8e.png)

2021-09-27 07:19 UTC, auanasgheps commented
So we're good to go, right?

2021-09-28 16:08 UTC, arjun-msft commented
/azp run

2021-09-28 20:34 UTC, merged