Moved: Tencent.EDULite version 2.2.1.38
microsoft/winget-pkgs pull request #28770
Opened 2021-09-26 15:15 UTC by SpecterShell

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-09-26 15:23 UTC, BajajAditya123 commented
uhmm.....
why are you creating so much of pr
create but do not break the repo

2021-09-26 15:38 UTC, ItzLevvie requested changes

2021-09-26 15:38 UTC, ItzLevvie commented on manifests/t/Tencent/EDULite/1.0/Tencent.TXEDULite.installer.yaml
> +PackageIdentifier: Tencent.TXEDULite
```suggestion
PackageIdentifier: Tencent.EDULite
```

2021-09-26 15:38 UTC, ItzLevvie commented on manifests/t/Tencent/EDULite/1.0/Tencent.TXEDULite.locale.en-US.yaml
> +PackageIdentifier: Tencent.TXEDULite
```suggestion
PackageIdentifier: Tencent.EDULite
```

2021-09-26 15:38 UTC, ItzLevvie commented on manifests/t/Tencent/EDULite/1.0/Tencent.TXEDULite.locale.zh-CN.yaml
> +PackageIdentifier: Tencent.TXEDULite
```suggestion
PackageIdentifier: Tencent.EDULite
```

2021-09-26 15:38 UTC, ItzLevvie commented on manifests/t/Tencent/EDULite/1.0/Tencent.TXEDULite.yaml
> +PackageIdentifier: Tencent.TXEDULite
```suggestion
PackageIdentifier: Tencent.EDULite
```

2021-09-26 15:40 UTC, ItzLevvie requested changes
Make sure to rename the files from `Tencent.TXEDULite` to `Tencent.EDULite`

2021-09-26 15:41 UTC, ItzLevvie requested changes
https://github.com/microsoft/winget-pkgs/pull/28770#pullrequestreview-763708714

2021-09-26 15:50 UTC, ItzLevvie approved these changes

2021-09-27 16:58 UTC, ghost approved these changes

2021-09-27 16:58 UTC, merged