GSmartControl.GSmartControl version 1.1.3
microsoft/winget-pkgs pull request #29136
Opened 2021-10-01 09:02 UTC by OyePradumya

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-10-01 09:42 UTC, ItzLevvie requested changes

2021-10-01 09:42 UTC, ItzLevvie commented on manifests/g/GSmartControl/GSmartControl/1.1.3/GSmartControl.GSmartControl.installer.yaml
> +  InstallerUrl: https://nchc.dl.sourceforge.net/project/gsmartcontrol/1.1.3/gsmartcontrol-1.1.3-win64.exe
```suggestion
  InstallerUrl: https://sourceforge.net/projects/gsmartcontrol/files/1.1.3/gsmartcontrol-1.1.3-win64.exe/download
```

2021-10-01 09:43 UTC, ItzLevvie requested changes

2021-10-01 09:43 UTC, ItzLevvie commented on manifests/g/GSmartControl/GSmartControl/1.1.3/GSmartControl.GSmartControl.installer.yaml
> +  InstallerSha256: F33064B67B7399BEA4D106862AFE3A6F36EDF7200A7B6B1BE68A39FED4E39E6D
```suggestion
  InstallerSha256: F33064B67B7399BEA4D106862AFE3A6F36EDF7200A7B6B1BE68A39FED4E39E6D
  Scope: machine
```

2021-10-01 10:33 UTC, ItzLevvie requested changes
missing https://github.com/microsoft/winget-pkgs/pull/29136/files#r720103526

2021-10-02 13:40 UTC, ItzLevvie submitted a review, later dismissed

2021-10-02 14:16 UTC, ItzLevvie requested changes

2021-10-02 14:16 UTC, ItzLevvie commented on manifests/g/GSmartControl/GSmartControl/1.1.3/GSmartControl.GSmartControl.installer.yaml
> +  Scope: machine
```suggestion
```
You added this two times.

2021-10-02 14:17 UTC, OyePradumya commented
You just suggest whatever you want. I will commit every damn suggestion.. but let it merged. @ItzLevvie

2021-10-02 14:17 UTC, ItzLevvie approved these changes

2021-10-03 13:53 UTC, OyePradumya commented
@msftbot Merge this.

2021-10-03 13:54 UTC, ItzLevvie commented
> @msftbot Merge this.

You will need to wait for an administrator to take a look at this PR.

2021-10-04 21:35 UTC, merged