New version: Files-Community.Files version 2.0.13.0
microsoft/winget-pkgs pull request #29281
Opened 2021-10-04 03:08 UTC by vedantmgoyal2009

Auto-updated by vedantmgoyal2009/winget-pkgs-automation

2021-10-09 15:57 UTC, vedantmgoyal2009 commented
@itzlevvie can you tell where the error is? I can't find any.

2021-10-10 11:24 UTC, ItzLevvie requested changes
This issue is caused by a dependency not available in the validation pipelines.

from the latest version of WinGet:
![image](https://user-images.githubusercontent.com/11600822/136693362-15de672c-b98c-461d-b63d-cf95cae5b4e9.png)

from an older version of WinGet:
![image](https://user-images.githubusercontent.com/11600822/136693464-2b48a958-1a7c-45cf-bad8-2c3cb4886ff3.png)

2021-10-10 16:18 UTC, ItzLevvie approved these changes

2021-10-10 16:21 UTC, ghost approved these changes

2021-10-10 16:22 UTC, merged