IP Messenger v5.1.0
microsoft/winget-pkgs pull request #29487
Opened 2021-10-05 15:43 UTC by shirouzu

- [✓] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [✓] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [✓] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [✓] Have you tested your manifest locally with `winget install --manifest <path>`?
- [✓] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?
-----
IP Messenger v5.1.0 released.

2021-10-05 19:45 UTC, ItzLevvie requested changes

2021-10-05 19:45 UTC, ItzLevvie commented on manifests/f/FastCopy/IPMsg/5.1.0/FastCopy.IPMsg.yaml
> +PackageName: IP Messenger
```suggestion
PackageName: IP Messenger for Win
```

2021-10-05 19:45 UTC, ItzLevvie commented on manifests/f/FastCopy/IPMsg/5.1.0/FastCopy.IPMsg.yaml
> +Publisher: FastCopy Lab, LLC.
```suggestion
Publisher: H.Shirouzu & FastCopy Lab, LLC.
```

2021-10-05 19:45 UTC, ItzLevvie commented on manifests/f/FastCopy/IPMsg/5.1.0/FastCopy.IPMsg.yaml
> +Publisher: FastCopy Lab, LLC.
Windows Package Manager requires `Publisher` to match Control Panel.

2021-10-05 19:45 UTC, ItzLevvie commented on manifests/f/FastCopy/IPMsg/5.1.0/FastCopy.IPMsg.yaml
> +PackageName: IP Messenger
Windows Package Manager requires `PackageName` to match Control Panel.

2021-10-06 01:27 UTC, shirouzu reviewed
reflect suggestions.

2021-10-06 08:59 UTC, ItzLevvie approved these changes

2021-10-06 08:59 UTC, ghost approved these changes

2021-10-06 09:00 UTC, merged