Malwarebytes.Malwarebytes version 4.4.6.232
microsoft/winget-pkgs pull request #30069
Opened 2021-10-11 19:18 UTC by GarethTheNerd

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/30069)

2021-10-12 10:25 UTC, ItzLevvie requested changes

2021-10-12 10:29 UTC, ItzLevvie requested changes
You'll have to update the version folder as well, otherwise, the package will not pass pipelines.

2021-10-12 10:30 UTC, OfficialEsco requested changes

2021-10-13 09:03 UTC, ItzLevvie requested changes
https://github.com/microsoft/winget-pkgs/pull/30069#discussion_r726985616

You can set the PR in DRAFT mode until you've made changes to the package.

2021-11-06 14:25 UTC, closed without merging