New version: stnkl.EverythingToolbar version 0.7.3
microsoft/winget-pkgs pull request #33334
Opened 2021-10-31 12:29 UTC by vedantmgoyal2009

### Installation timed out.

Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation)

2021-10-31 12:36 UTC, ItzLevvie approved these changes

2021-10-31 13:06 UTC, ItzLevvie requested changes
Please close and reopen the PR to rerun the pipelines.

2021-11-05 17:31 UTC, arjun-msft commented
/azp run

2021-11-05 17:34 UTC, vedantmgoyal2009 commented
@arjun-msft can you please merge https://github.com/microsoft/winget-pkgs/pulls?q=is%3Aopen+is%3Apr+author%3Avedantmgoyal2009+label%3AModerator-Approved 🙏

2021-11-08 20:10 UTC, merged