UniversityofLjubljana.Orange version 3.30.2
microsoft/winget-pkgs pull request #33949
Opened 2021-11-04 08:47 UTC by Amoenus

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-11-04 09:38 UTC, Amoenus commented
Locally it took some time but was installed silently.

2021-11-04 11:03 UTC, ItzLevvie requested changes

2021-11-04 11:03 UTC, ItzLevvie commented on manifests/u/UniversityofLjubljana/Orange/3.30.2/UniversityofLjubljana.Orange.installer.yaml
> +  Architecture: x86
```suggestion
  Architecture: x64
```

2021-11-04 11:03 UTC, ItzLevvie commented on manifests/u/UniversityofLjubljana/Orange/3.30.2/UniversityofLjubljana.Orange.installer.yaml
> +  Architecture: x86
```suggestion
  Architecture: x64
```

2021-11-04 11:03 UTC, ItzLevvie commented on manifests/u/UniversityofLjubljana/Orange/3.30.2/UniversityofLjubljana.Orange.locale.en-US.yaml
> +- data mining
```suggestion
- machine-learning
- data-mining
```

2021-11-05 00:27 UTC, ItzLevvie approved these changes

2021-11-05 00:28 UTC, merged