New version: Microsoft.Edge version 95.0.1020.44
microsoft/winget-pkgs pull request #33993
Opened 2021-11-04 20:16 UTC by vedantmgoyal2009

### ARP entries are correct.

Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation)

2021-11-04 20:18 UTC, ItzLevvie requested changes

2021-11-04 20:18 UTC, ItzLevvie commented on manifests/m/Microsoft/Edge/95.0.1020.44/Microsoft.Edge.installer.yaml
> +- Architecture: x86
```suggestion
- Architecture: arm64
```

2021-11-04 20:18 UTC, ItzLevvie commented on manifests/m/Microsoft/Edge/95.0.1020.44/Microsoft.Edge.installer.yaml
> +- Architecture: arm64
```suggestion
- Architecture: x64
```

2021-11-04 20:18 UTC, ItzLevvie commented on manifests/m/Microsoft/Edge/95.0.1020.44/Microsoft.Edge.installer.yaml
> +- Architecture: x64
```suggestion
- Architecture: x86
```

2021-11-04 21:03 UTC, jedieaston requested changes
The version number for this is wrong; these MSIs install 95.0.1040.40, which we already have.

95.0.1040.44 has only been released for arm64 so far.

![image](https://user-images.githubusercontent.com/21368066/140419720-fdbff045-4d1f-4ab9-925b-031b61819a34.png)

2021-11-05 05:50 UTC, Trenly commented
Still have to fix the version numbers, but I updated the installer architectures to match

2021-11-05 06:00 UTC, vedantmgoyal2009 commented
When a new version of MS Edge will be available, I could remove x64 and x86 installer links and then it could be merged. If it will be merged now, my automation would break.

2021-11-05 11:31 UTC, ItzLevvie requested changes
> If this will be merged now, my automation would break.

2021-11-06 19:23 UTC, closed without merging