New version: Microsoft.Teams.Preview version 1.4.00.29469
microsoft/winget-pkgs pull request #34185
Opened 2021-11-06 20:23 UTC by vedantmgoyal2009

\n\nAuto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation)

2021-11-06 23:04 UTC, jedieaston requested changes

2021-11-06 23:04 UTC, jedieaston commented on manifests/m/Microsoft/Teams/Preview/1.4.00.29469/Microsoft.Teams.Preview.installer.yaml
> +  InstallerUrl: https://statics.teams.cdn.office.net/production-windows-x64/1.4.00.29469/Teams_windows_x64.exe
This is not a preview URL..?

2021-11-07 02:43 UTC, vedantmgoyal2009 commented
There are many versions of Teams that are there in both **Stable** and **Preview** channels.

![image](https://user-images.githubusercontent.com/83997633/140630211-db9c1e22-b989-46a2-afc7-a25b17fb2e7f.png)

The installer URLs: 

![image](https://user-images.githubusercontent.com/83997633/140630368-1d33b703-9c03-4304-8592-6d1d77a1158a.png)


According to the APIs mentioned by @itzlevvie at https://github.com/vedantmgoyal2009/winget-pkgs-automation/issues/157#issuecomment-962494234:

> **Preview**: https://teams.microsoft.com/desktopclient/installer/windows/x64?ring=ring3_6 https://teams.microsoft.com/desktopclient/installer/windows/x32?ring=ring3_6 https://teams.microsoft.com/desktopclient/installer/windows/arm64?ring=ring3_6
> 
> _To get MSI installers, replace `.exe` with `.msi`._
> 
> **Production**: https://teams.microsoft.com/desktopclient/installer/windows/x64?ring=general https://teams.microsoft.com/desktopclient/installer/windows/x32?ring=general https://teams.microsoft.com/desktopclient/installer/windows/arm64?ring=general
> 
> _To get MSI installers, replace `.exe` with `.msi`._

They both return the same version, so my automation updated them to the same version.

2021-11-07 03:33 UTC, jedieaston approved these changes

2021-11-07 03:33 UTC, merged