MKProj.Minerva version 1.1.1
microsoft/winget-pkgs pull request #34466
Opened 2021-11-09 18:26 UTC by Mustafif

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-11-09 18:48 UTC, ItzLevvie requested changes

2021-11-09 18:48 UTC, ItzLevvie commented on manifests/m/MKProj/Minerva/1.1.1/MKProj.Minerva.locale.en-US.yaml
> +PackageName: Minerva
```suggestion
PackageName: minerva
```

2021-11-09 18:48 UTC, ItzLevvie commented on manifests/m/MKProj/Minerva/1.1.1/MKProj.Minerva.locale.en-US.yaml
> +Publisher: MKProj
```suggestion
Publisher: Mustafif
```

2021-11-09 19:55 UTC, Mustafif reviewed
All good

2021-11-09 20:09 UTC, ItzLevvie requested changes
Missing these changes: https://github.com/microsoft/winget-pkgs/pull/34466#pullrequestreview-801699268

It must match Control Panel.

2021-11-10 10:25 UTC, ItzLevvie requested changes
https://github.com/microsoft/winget-pkgs/pull/34466#pullrequestreview-801812306

2021-11-10 12:41 UTC, closed without merging