Added NSwagStudio version 13.14.1.0.
microsoft/winget-pkgs pull request #34738
Opened 2021-11-12 18:02 UTC by jedieaston

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

2021-11-13 04:37 UTC, KaranKad requested changes

2021-11-13 04:37 UTC, KaranKad commented on manifests/r/RicoSuter/NSwagStudio/13.14.1.0/RicoSuter.NSwagStudio.yaml
> +PackageVersion: 13.14.1.0
```suggestion
PackageVersion: 13.14.3.0
```

2021-11-13 04:37 UTC, KaranKad commented on manifests/r/RicoSuter/NSwagStudio/13.14.1.0/RicoSuter.NSwagStudio.locale.en-US.yaml
> +PackageVersion: 13.14.1.0
```suggestion
PackageVersion: 13.14.3.0
```

2021-11-13 04:37 UTC, KaranKad commented on manifests/r/RicoSuter/NSwagStudio/13.14.1.0/RicoSuter.NSwagStudio.installer.yaml
> +PackageVersion: 13.14.1.0
```suggestion
PackageVersion: 13.14.3.0
```

2021-11-14 11:48 UTC, ItzLevvie approved these changes

2021-11-14 12:02 UTC, merged