Twitch.TwitchStudio version 0.104.7
microsoft/winget-pkgs pull request #34777
Opened 2021-11-13 17:14 UTC by sanyer

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-11-13 22:53 UTC, jedieaston requested changes
Don't forget to change the folder name too.

2021-11-13 22:53 UTC, jedieaston commented on manifests/t/Twitch/TwitchStudio/0.104.7/Twitch.TwitchStudio.installer.yaml
> +PackageVersion: 0.104.7
```suggestion
PackageVersion: 8.0.0
```

2021-11-13 22:53 UTC, jedieaston commented on manifests/t/Twitch/TwitchStudio/0.104.7/Twitch.TwitchStudio.locale.en-US.yaml
> +PackageVersion: 0.104.7
```suggestion
PackageVersion: 8.0.0
```

2021-11-13 22:53 UTC, jedieaston commented on manifests/t/Twitch/TwitchStudio/0.104.7/Twitch.TwitchStudio.yaml
> +PackageVersion: 0.104.7
```suggestion
PackageVersion: 8.0.0
```

2021-11-13 22:56 UTC, jedieaston requested changes

2021-11-13 22:56 UTC, jedieaston commented on manifests/t/Twitch/TwitchStudio/0.104.7/Twitch.TwitchStudio.installer.yaml
> +  InstallerSha256: ECF53920563C32BC433CAA4ED9E317691B509D0505435731BE29346B78A1E905
```suggestion
  InstallerSha256: ECF53920563C32BC433CAA4ED9E317691B509D0505435731BE29346B78A1E905
  ProductCode: {DEE70742-F4E9-44CA-B2B9-EE95DCF372B0}
```

2021-11-14 17:17 UTC, jedieaston commented
Hot tip to change the folder name: Press "." on your keyboard when you have GitHub open to this PR in your browser, and a web version of VSCode will launch.
 
 Once it loads, find the files you added, and rename the folder. Then use the source control button on the left to commit (it's automatically pushed).
 
 <img alt="image" width="268" src="https://user-images.githubusercontent.com/21368066/136942061-26715615-b675-4868-ae65-0ecfe1da6b0e.png">

2021-11-14 17:28 UTC, sanyer commented
oh, that's sick new addition! Thanks for the tip :-D

btw, what can you say about the fact that version `8.0.0` is not a version of the Twitch apps, but instead is their wrapper's (or something)?
The real version is available only for Twitch Studio, though.

2021-11-14 17:33 UTC, jedieaston commented
> btw, what can you say about the fact that version 8.0.0 is not a version of the Twitch apps, but instead is their wrapper's (or something)?

I'm not sure why that is (ISVs be crazy :D) but we probably need to use that version number since it's the one in the ARP table so winget can detect it. There will be mitigations for this in schema v1.1 (no eta yet on that though).

2021-11-14 17:34 UTC, jedieaston requested changes

2021-11-14 17:34 UTC, jedieaston commented on manifests/t/Twitch/TwitchStudio/8.0.0/Twitch.TwitchStudio.installer.yaml
> +PackageVersion: 0.104.7
```suggestion
PackageVersion: 8.0.0
```

2021-11-14 17:48 UTC, sanyer commented
> > btw, what can you say about the fact that version 8.0.0 is not a version of the Twitch apps, but instead is their wrapper's (or something)?
> 
> I'm not sure why that is (ISVs be crazy :D) but we probably need to use that version number since it's the one in the ARP table so winget can detect it. There will be mitigations for this in schema v1.1 (no eta yet on that though).

so, v1.1 is not live yet? Links are available at `aka.ms`.

2021-11-14 17:50 UTC, jedieaston commented
Schema 1.1 is finalized, but it hasn’t been implemented in the client (the one to many ARP relationship hasn’t been, anyway).

2021-11-14 17:51 UTC, sanyer commented
.

> Schema 1.1 is finalized, but it hasn’t been implemented in the client (the one to many ARP relationship hasn’t been, anyway).

oh, ok, got it.
Is there a documentation for the changes?

2021-11-14 18:10 UTC, jedieaston approved these changes

2021-11-14 18:12 UTC, jedieaston commented
>  Is there a documentation for the changes?

Not yet. The best I know of is this issue: https://github.com/microsoft/winget-cli/issues/1243.

2021-11-14 18:43 UTC, merged