New version: zokugun.MrCode version 1.62.3+21323
microsoft/winget-pkgs pull request #35400
Opened 2021-11-19 22:32 UTC by vedantmgoyal2009

### Installation timed out.\r\n\r\n#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation) in workflow run [498](https://github.com/vedantmgoyal2009/winget-pkgs-automation/actions/runs/1482923177)

2021-11-19 23:29 UTC, OfficialEsco requested changes

2021-11-19 23:29 UTC, OfficialEsco commented on manifests/z/zokugun/MrCode/1.62.3+21323/zokugun.MrCode.installer.yaml
> +PackageVersion: 1.62.3+21323
```suggestion
PackageVersion: 1.62.3.21323
```

2022-03-01 11:32 UTC, ItzLevvie approved these changes

2022-03-01 12:18 UTC, ghost approved these changes

2022-03-01 12:20 UTC, merged