Cyber.Cat.ADBAppControl version 1.7.1
microsoft/winget-pkgs pull request #36281
Opened 2021-11-28 04:13 UTC by Mav3r1x

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-11-28 14:44 UTC, ItzLevvie requested changes

2021-11-28 14:44 UTC, ItzLevvie commented on manifests/c/Cyber/Cat/ADBAppControl/1.7.1/Cyber.Cat.ADBAppControl.locale.en-US.yaml
> +PackageIdentifier: Cyber.Cat.ADBAppControl
```suggestion
PackageIdentifier: CyberCat.ADBAppControl
```

2021-11-28 14:44 UTC, ItzLevvie commented on manifests/c/Cyber/Cat/ADBAppControl/1.7.1/Cyber.Cat.ADBAppControl.installer.yaml
> +PackageIdentifier: Cyber.Cat.ADBAppControl
```suggestion
PackageIdentifier: CyberCat.ADBAppControl
```

2021-11-28 14:44 UTC, ItzLevvie commented on manifests/c/Cyber/Cat/ADBAppControl/1.7.1/Cyber.Cat.ADBAppControl.yaml
> +PackageIdentifier: Cyber.Cat.ADBAppControl
```suggestion
PackageIdentifier: CyberCat.ADBAppControl
```

2021-12-01 03:26 UTC, Mav3r1x reviewed
Naming scheme corrections.

2021-12-01 10:34 UTC, ItzLevvie approved these changes

2021-12-01 10:35 UTC, merged