Microsoft.dotnetUninstallTool version 1.5.255402
microsoft/winget-pkgs pull request #36291
Opened 2021-11-28 10:36 UTC by dgellow

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-11-28 10:38 UTC, dgellow commented
Manifest for the .Net SDK uninstall tool from https://github.com/dotnet/cli-lab.

It's the first time I ever create a winget manifest, it's very likely I missed a few things. I used the wingetcreate tool, and tried the manifest locally to install the msi.

2021-11-28 15:59 UTC, ItzLevvie requested changes

2021-11-28 15:59 UTC, ItzLevvie commented on manifests/m/Microsoft/dotnetUninstallTool/1.5.255402/Microsoft.dotnetUninstallTool.locale.en-US.yaml
> +PackageName: Microsoft .Net SDK Uninstall Tool
```suggestion
PackageName: Microsoft .NET Core SDK Uninstall Tool
```

2021-11-28 15:59 UTC, ItzLevvie commented on manifests/m/Microsoft/dotnetUninstallTool/1.5.255402/Microsoft.dotnetUninstallTool.locale.en-US.yaml
> +PackageVersion: 1.5.255402
```suggestion
PackageVersion: 4.80.595
```

2021-11-28 15:59 UTC, ItzLevvie commented on manifests/m/Microsoft/dotnetUninstallTool/1.5.255402/Microsoft.dotnetUninstallTool.yaml
> +PackageVersion: 1.5.255402
```suggestion
PackageVersion: 4.80.595
```

2021-11-28 15:59 UTC, ItzLevvie commented on manifests/m/Microsoft/dotnetUninstallTool/1.5.255402/Microsoft.dotnetUninstallTool.installer.yaml
> +PackageVersion: 1.5.255402
```suggestion
PackageVersion: 4.80.595
```

2021-11-28 17:31 UTC, dgellow commented
@ItzLevvie Where does the version number 4.80.595 come from? I used 1.5.255402 because that's the version mentioned in the release page: https://github.com/dotnet/cli-lab/releases.

2021-11-28 17:50 UTC, ItzLevvie requested changes
> https://github.com/microsoft/winget-pkgs/pull/36291#issuecomment-981122490

`PackageVersion` must match Control Panel.

2021-11-29 07:12 UTC, dgellow commented
Should I also change the directory name then? It is currently `manifests/m/Microsoft/dotnetUninstallTool/1.5.255402`. Should I rename it to `m/Microsoft/dotnetUninstallTool/4.80.595`? I have to say, I do not understand why there are two different version numbers, that should maybe be clarified with `dotnet-core-uninstall` authors.

2021-11-29 11:12 UTC, ItzLevvie requested changes
Should I also change the directory name then? It is currently manifests/m/Microsoft/dotnetUninstallTool/1.5.255402. Should I rename it to m/Microsoft/dotnetUninstallTool/4.80.595?

Yes

2021-11-29 14:33 UTC, ItzLevvie approved these changes

2021-11-30 22:01 UTC, merged