New version: Igoravl.TfsCmdlets version 2.1.4+2594.1
microsoft/winget-pkgs pull request #36478
Opened 2021-11-30 16:38 UTC by vedantmgoyal2009

### Installation timed out.

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation) in workflow run [743](https://github.com/vedantmgoyal2009/winget-pkgs-automation/actions/runs/1521879612)

2021-11-30 22:51 UTC, OfficialEsco requested changes

2021-11-30 22:51 UTC, OfficialEsco commented on manifests/i/Igoravl/TfsCmdlets/2.1.4+2594.1/Igoravl.TfsCmdlets.installer.yaml
> +PackageVersion: 2.1.4+2594.1
```suggestion
PackageVersion: 2.1.4.2594
```

2021-12-01 14:27 UTC, OfficialEsco requested changes
```
Status: Completed
##[error] Result: Failed
##[error] Manifest is invalid. (Line: 10, Col: 1, Idx: 302) - (Line: 10, Col: 2, Idx: 303): While parsing a block mapping, did not find expected key.
##[error]Manifest Schema Validation Failed

****************************************************************************************
Manifest Schema Validation
****************************************************************************************
Status: Completed
##[error] Result: Failed
##[error] One or more errors occurred. (Manifest is invalid.) Manifest is invalid. (Line: 10, Col: 1, Idx: 302) - (Line: 10, Col: 2, Idx: 303): While parsing a block mapping, did not find expected key.
Finishing
```

2021-12-01 14:36 UTC, vedantmgoyal2009 commented
The error is occurring in release notes probably. Can you tell how to fix? I have tried removing certain characters which I think were causing error.

2021-12-01 14:49 UTC, OfficialEsco commented
Well, it does say its on line 10, which is broken in the Installer Yaml.

its missing InstallModes on line 10.

2021-12-01 15:27 UTC, OfficialEsco requested changes

2021-12-01 15:27 UTC, OfficialEsco commented on manifests/i/Igoravl/TfsCmdlets/2.1.4.2594/Igoravl.TfsCmdlets.locale.en-US.yaml
> +- Error calling Invoke-TfsRestApi for alternate hosts under Windows PowerShell (Desktop)- There was a bug in the implementation of Invoke-TfsRestApi that caused it to fail when using alternate hosts
```suggestion
  Version 2.1.4 (30/Nov/2021)

  This release fixes a couple issues in Get-TfsIdentity and Invoke-TfsRestApi.

  Fixes

  - Error when using Get-TfsIdentity with Azure DevOps Services- Get-TfsIdentity is a cmdlet that helps to deal with legacy APIs, such as the Azure DevOps Security API. To fetch an identiy, it connected to a configuration server (the "root" of an Azure DevOps installation) and called the required API. However, connecting to a configuration server is not supported when using Azure DevOps Services. Now, when used with Azure DevOps Services, Get-TfsIdentity will use the collection (organization) scope for the API, whereas calls to the on-prem server still target the configuration server.

  - Error calling Invoke-TfsRestApi for alternate hosts under Windows PowerShell (Desktop)- There was a bug in the implementation of Invoke-TfsRestApi that caused it to fail when using alternate hosts in Windows PowerShell. This has been fixed.
```

2021-12-01 16:44 UTC, OfficialEsco approved these changes

2021-12-01 16:50 UTC, merged