CaffeineInc.Caffeine version 1.7.0.443
microsoft/winget-pkgs pull request #36708
Opened 2021-12-02 07:36 UTC by Amoenus

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-12-02 08:55 UTC, Amoenus commented
Re-installed from scratch and it works flawlessly for me.
![image](https://user-images.githubusercontent.com/5391396/144389525-f2753f87-02ee-432c-86be-9ebf127a5272.png)

2021-12-02 12:06 UTC, ItzLevvie requested changes

2021-12-02 12:06 UTC, ItzLevvie commented on manifests/c/CaffeineInc/Caffeine/1.7.0.443/CaffeineInc.Caffeine.installer.yaml
> +- Architecture: x86
```suggestion
- Architecture: x64
```

2021-12-02 12:06 UTC, ItzLevvie commented on manifests/c/CaffeineInc/Caffeine/1.7.0.443/CaffeineInc.Caffeine.locale.en-US.yaml
> +ShortDescription: Caffeine
```suggestion
ShortDescription: Caffeine is a social broadcasting platform that delivers live, interactive content at the intersection of gaming, sports, and entertainment.
```

2021-12-03 12:18 UTC, ItzLevvie approved these changes

2021-12-03 12:18 UTC, merged