Geeks3D.MSIKombustor4 version 4.1.15.0
microsoft/winget-pkgs pull request #36709
Opened 2021-12-02 08:28 UTC by Amoenus

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-12-02 11:25 UTC, KaranKad requested changes

2021-12-02 11:25 UTC, KaranKad commented on manifests/g/Geeks3D/MSIKombustor4/4.1.15.0/Geeks3D.MSIKombustor4.locale.en-US.yaml
> +PackageIdentifier: Geeks3D.MSIKombustor4
```suggestion
PackageIdentifier: Geeks3D.MSIKombustor.4
```

2021-12-02 11:25 UTC, KaranKad commented on manifests/g/Geeks3D/MSIKombustor4/4.1.15.0/Geeks3D.MSIKombustor4.installer.yaml
> +PackageIdentifier: Geeks3D.MSIKombustor4
```suggestion
PackageIdentifier: Geeks3D.MSIKombustor.4
```

2021-12-02 11:25 UTC, KaranKad commented on manifests/g/Geeks3D/MSIKombustor4/4.1.15.0/Geeks3D.MSIKombustor4.yaml
> +PackageIdentifier: Geeks3D.MSIKombustor4
```suggestion
PackageIdentifier: Geeks3D.MSIKombustor.4
```

2021-12-02 11:29 UTC, ItzLevvie requested changes
Like https://github.com/microsoft/winget-pkgs/pull/26659, it would be preferable if the download came from https://www.geeks3d.com/furmark/kombustor/downloads/.

![image](https://user-images.githubusercontent.com/11600822/144413839-a2dafad1-7f62-404d-8d5c-8d5eda3b5812.png)
![image](https://user-images.githubusercontent.com/11600822/144413895-7e74c041-5339-4b87-a048-536ea7b7022e.png)

2021-12-02 11:29 UTC, KaranKad commented
Edit folder structure using github.dev

2021-12-02 11:33 UTC, KaranKad commented
@ItzLevvie Their download link redirects to that link
![image](https://user-images.githubusercontent.com/71691514/144414247-e4e3f86f-d5f1-4506-a234-31b9fd3299f9.png)

2021-12-02 13:57 UTC, OfficialEsco commented
Just checked their other softwares, MSIKombustor is the only download link that redirect to another site
Every other software that is on their servers just loop back around like FurMark
https://github.com/microsoft/winget-pkgs/pull/26659#issuecomment-912943352

2021-12-03 07:13 UTC, Amoenus commented
@KaranKad @ItzLevvie are we positive we want to use Geeks3D.MSIKombustor.4?
It seems a bit odd-looking to me. I was going back and forth between Geeks3D.MSIKombustor and Geeks3D.MSIKombustor4

I went for the second option because of an installer:
![image](https://user-images.githubusercontent.com/5391396/144560289-4f0d90c5-a2c8-471d-8aa4-9c3c0bffbf8f.png)

It always mentions MSI Kombustor 4 even in the default install path
I usually rely on the `winget list` as a tie-breaker or a hint on how to determine new identifier. Sadly this package gives worst case scenario with just a guid and unknown version...
![image](https://user-images.githubusercontent.com/5391396/144560741-8180875c-7e43-4ec8-aaf5-a362e878a71b.png)

2021-12-03 07:23 UTC, OfficialEsco commented
Example of this splitting: https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Corsair/iCUE

2021-12-03 07:29 UTC, Amoenus commented
This is a similar issue I am having with picking the right identifier for LEGOEducation.WeDo
![image](https://user-images.githubusercontent.com/5391396/144562215-dc39933e-8399-43f3-860d-0b534907c827.png)

![image](https://user-images.githubusercontent.com/5391396/144562427-01b79ca8-0f35-40bf-b277-4259c8cee9da.png)

This one is even weirder as it is `WeDo 2.0` version `1.9.x`

2021-12-03 13:44 UTC, ItzLevvie requested changes

2021-12-03 13:44 UTC, ItzLevvie commented on manifests/g/Geeks3D/MSIKombustor4/4.1.15.0/Geeks3D.MSIKombustor4.locale.en-US.yaml
> +PackageName: MSI Kombustor 4
```suggestion
PackageName: MSI Kombustor
```

2021-12-03 13:44 UTC, ItzLevvie commented on manifests/g/Geeks3D/MSIKombustor4/4.1.15.0/Geeks3D.MSIKombustor4.locale.en-US.yaml
> +PackageName: MSI Kombustor 4
> It seems a bit odd-looking to me. I was going back and forth between Geeks3D.MSIKombustor and Geeks3D.MSIKombustor4

Knowing what we do with other installers, I would probably vouch for the former.

If Control Panel showed `MSI Kombustor 4 version 4.1.15.0` then we could probably go for `Geeks3D.MSIKombustor.4` with `MSI Kombustor 4` as PackageName.

At the moment, Control Panel shows `MSI Kombustor 4.1.15.0` so if we remove the version, it'll be `MSI Kombustor`

If you want to add older versions of MSI Kombustor, then you could split it up into `Geeks3D.MSIKombustor.4`; `Geeks3D.MSIKombustor.3`, etc.

2021-12-03 13:48 UTC, ItzLevvie commented
> This one is even weirder as it is WeDo 2.0 version 1.9.x

I think for that `LEGOEducation.WeDo` would be fine.

2021-12-03 17:52 UTC, Amoenus commented on manifests/g/Geeks3D/MSIKombustor4/4.1.15.0/Geeks3D.MSIKombustor4.installer.yaml
> +PackageIdentifier: Geeks3D.MSIKombustor4
Will go with Geeks3D.MSIKombustor

2021-12-03 17:53 UTC, Amoenus commented on manifests/g/Geeks3D/MSIKombustor4/4.1.15.0/Geeks3D.MSIKombustor4.yaml
> +PackageIdentifier: Geeks3D.MSIKombustor4
Will go with Geeks3D.MSIKombustor

2021-12-03 17:53 UTC, Amoenus commented on manifests/g/Geeks3D/MSIKombustor4/4.1.15.0/Geeks3D.MSIKombustor4.locale.en-US.yaml
> +PackageIdentifier: Geeks3D.MSIKombustor4
Will go with Geeks3D.MSIKombustor

2021-12-04 11:29 UTC, ItzLevvie approved these changes

2021-12-07 22:51 UTC, merged