New version: CrystalRich.LockHunter version 3.4.3
microsoft/winget-pkgs pull request #36795
Opened 2021-12-03 08:37 UTC by DinCahill

﻿- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

2021-12-03 13:20 UTC, ItzLevvie requested changes

2021-12-03 13:20 UTC, ItzLevvie commented on manifests/c/CrystalRich/LockHunter/3.4.3/CrystalRich.LockHunter.locale.en-US.yaml
> +PackageVersion: 3.4.3
```suggestion
PackageVersion: 3.4.3.146
```

2021-12-03 13:20 UTC, ItzLevvie commented on manifests/c/CrystalRich/LockHunter/3.4.3/CrystalRich.LockHunter.installer.yaml
> +PackageVersion: 3.4.3
```suggestion
PackageVersion: 3.4.3.146
```

2021-12-03 13:20 UTC, ItzLevvie commented on manifests/c/CrystalRich/LockHunter/3.4.3/CrystalRich.LockHunter.yaml
> +PackageVersion: 3.4.3
```suggestion
PackageVersion: 3.4.3.146
```

2021-12-03 13:20 UTC, ItzLevvie commented on manifests/c/CrystalRich/LockHunter/3.4.3/CrystalRich.LockHunter.yaml
> +PackageVersion: 3.4.3
This must match Control Panel.

2021-12-03 13:20 UTC, ItzLevvie commented on manifests/c/CrystalRich/LockHunter/3.4.3/CrystalRich.LockHunter.locale.en-US.yaml
> +PackageVersion: 3.4.3
This must match Control Panel.

2021-12-03 13:20 UTC, ItzLevvie commented on manifests/c/CrystalRich/LockHunter/3.4.3/CrystalRich.LockHunter.installer.yaml
> +PackageVersion: 3.4.3
This must match Control Panel.

2021-12-04 10:35 UTC, OfficialEsco approved these changes

2021-12-04 10:35 UTC, merged