SoftwareFreedomConservancy.QEMU.GuestAgent version 102.7.0
microsoft/winget-pkgs pull request #37032
Opened 2021-12-06 16:24 UTC by kevinoid

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2021-12-07 17:22 UTC, ItzLevvie requested changes

2021-12-07 17:22 UTC, ItzLevvie commented on manifests/s/SoftwareFreedomConservancy/QEMU/GuestAgent/102.7.0/SoftwareFreedomConservancy.QEMU.GuestAgent.locale.en-US.yaml
> +PackageName: QEMU Guest Agent
```suggestion
PackageName: QEMU guest agent
```

2021-12-07 17:22 UTC, ItzLevvie commented on manifests/s/SoftwareFreedomConservancy/QEMU/GuestAgent/102.7.0/SoftwareFreedomConservancy.QEMU.GuestAgent.locale.en-US.yaml
> +PackageName: QEMU Guest Agent
This must match Control Panel for consistency.

2021-12-07 17:27 UTC, ItzLevvie submitted a review, later dismissed

2021-12-07 23:03 UTC, jamespik commented
Why is this app added as a nested folder of the QEMU app? By policy, this should be a side by side application under the SoftwareFreedomConservancy publisher?

2021-12-08 01:21 UTC, kevinoid commented
Thanks @jamespik.  I must have overlooked that policy.  Where is it documented?  Is that the case even though it is part of the same project/source tree?

2021-12-08 15:36 UTC, kevinoid commented
Updated PackageIdentifier to SoftwareFreedomConservancy.QEMUGuestAgent.  I still have the [same reservations about using "SoftwareFreedomConservancy."](https://github.com/microsoft/winget-pkgs/pull/37032#issuecomment-986940656) but am using it for consistency.

After looking at other packages, it's clear that third-level naming is typically used for editions/variants rather than components (although I don't see any documentation for these conventions).  Sorry for my earlier confusion.

2021-12-08 20:47 UTC, ItzLevvie approved these changes

2021-12-11 00:37 UTC, merged