Memurai Developer v2.0.5
microsoft/winget-pkgs pull request #37095
Opened 2021-12-07 09:24 UTC by MemuraiUser

Pull request was created by azure pipeline

2021-12-07 10:35 UTC, ItzLevvie requested changes
This manifest is not v1.0.0 or v1.1.0 compliant and is written weirdly.

2021-12-07 17:00 UTC, ItzLevvie requested changes

2021-12-07 17:00 UTC, ItzLevvie commented on manifests/m/Memurai/MemuraiDeveloper/2.0.5/Memurai.MemuraiDeveloper.yaml
> +PackageName: MemuraiDeveloper
```suggestion
PackageName: Memurai Developer
```

2021-12-07 17:00 UTC, ItzLevvie commented on manifests/m/Memurai/MemuraiDeveloper/2.0.5/Memurai.MemuraiDeveloper.yaml
> +Publisher: Memurai
```suggestion
Publisher: Janea Systems
```

2021-12-07 17:00 UTC, ItzLevvie commented on manifests/m/Memurai/MemuraiDeveloper/2.0.5/Memurai.MemuraiDeveloper.yaml
> +    InstallerSha256: d88ee77a2fc5063e979639084b1797bcce7cbfc40fee2617866f4ebda74e280b
```suggestion
    InstallerSha256: d88ee77a2fc5063e979639084b1797bcce7cbfc40fee2617866f4ebda74e280b
    ProductCode: "{70E00C1E-673F-4FCB-A20C-ECBD5A8FE747}"
```

2021-12-07 17:00 UTC, ItzLevvie commented on manifests/m/Memurai/MemuraiDeveloper/2.0.5/Memurai.MemuraiDeveloper.yaml
> +Publisher: Memurai
This must match Control Panel.

2021-12-07 17:00 UTC, ItzLevvie commented on manifests/m/Memurai/MemuraiDeveloper/2.0.5/Memurai.MemuraiDeveloper.yaml
> +PackageName: MemuraiDeveloper
This must match Control Panel.

2021-12-07 17:00 UTC, ItzLevvie commented on manifests/m/Memurai/MemuraiDeveloper/2.0.5/Memurai.MemuraiDeveloper.yaml
> +    InstallerSha256: d88ee77a2fc5063e979639084b1797bcce7cbfc40fee2617866f4ebda74e280b
This must match Windows Registry.

2021-12-07 23:42 UTC, MemuraiUser commented on manifests/m/Memurai/MemuraiDeveloper/2.0.5/Memurai.MemuraiDeveloper.yaml
> +    InstallerSha256: d88ee77a2fc5063e979639084b1797bcce7cbfc40fee2617866f4ebda74e280b
Added ProductCode as suggested.

2021-12-07 23:42 UTC, MemuraiUser commented on manifests/m/Memurai/MemuraiDeveloper/2.0.5/Memurai.MemuraiDeveloper.yaml
> +Publisher: Memurai
Done

2021-12-07 23:42 UTC, MemuraiUser commented on manifests/m/Memurai/MemuraiDeveloper/2.0.5/Memurai.MemuraiDeveloper.yaml
> +PackageName: MemuraiDeveloper
Done

2021-12-08 14:24 UTC, ItzLevvie approved these changes

2021-12-08 14:25 UTC, merged