New version: Microsoft.Edge.Beta version 97.0.1072.34
microsoft/winget-pkgs pull request #37637
Opened 2021-12-13 21:16 UTC by vedantmgoyal2009

### ARP entries are correct.

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation) in workflow run [1049](https://github.com/vedantmgoyal2009/winget-pkgs-automation/actions/runs/1574905673)

2021-12-13 23:05 UTC, ItzLevvie requested changes

2021-12-13 23:05 UTC, ItzLevvie commented on manifests/m/Microsoft/Edge/Beta/97.0.1072.34/Microsoft.Edge.Beta.installer.yaml
> +- Architecture: x64
```suggestion
- Architecture: x86
```

2021-12-13 23:05 UTC, ItzLevvie commented on manifests/m/Microsoft/Edge/Beta/97.0.1072.34/Microsoft.Edge.Beta.installer.yaml
> +- Architecture: x86
```suggestion
- Architecture: x64
```

2021-12-13 23:33 UTC, ChuckFerring commented
/azp run

2021-12-14 13:11 UTC, ItzLevvie approved these changes

2021-12-14 14:01 UTC, ghost approved these changes

2021-12-14 14:03 UTC, merged