New version: valinet.ExplorerPatcher.Prerelease version 22000.348.40.11_94db02b
microsoft/winget-pkgs pull request #37714
Opened 2021-12-14 14:17 UTC by vedantmgoyal2009

### Installation timed out.

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation) in workflow run [1066](https://github.com/vedantmgoyal2009/winget-pkgs-automation/actions/runs/1578206886)

2021-12-14 14:21 UTC, ItzLevvie requested changes

2021-12-14 14:21 UTC, ItzLevvie commented on manifests/v/valinet/ExplorerPatcher/Prerelease/22000.348.40.11_94db02b/valinet.ExplorerPatcher.Prerelease.installer.yaml
> +PackageVersion: 22000.348.40.11_94db02b
```suggestion
PackageVersion: 22000.348.40.11
```

2021-12-14 14:21 UTC, ItzLevvie commented on manifests/v/valinet/ExplorerPatcher/Prerelease/22000.348.40.11_94db02b/valinet.ExplorerPatcher.Prerelease.locale.en-US.yaml
> +PackageVersion: 22000.348.40.11_94db02b
```suggestion
PackageVersion: 22000.348.40.11
```

2021-12-14 14:21 UTC, ItzLevvie commented on manifests/v/valinet/ExplorerPatcher/Prerelease/22000.348.40.11_94db02b/valinet.ExplorerPatcher.Prerelease.yaml
> +PackageVersion: 22000.348.40.11_94db02b
```suggestion
PackageVersion: 22000.348.40.11
```

2021-12-14 14:32 UTC, OfficialEsco commented
Duplicate of https://github.com/microsoft/winget-pkgs/pull/37704

2021-12-14 14:35 UTC, Trenly commented
@vedantmgoyal Can you check on what needs to be added for the versionMethod?

2022-03-01 11:46 UTC, ItzLevvie approved these changes

2022-03-01 12:35 UTC, merged