New version: Mirantis.Lens.Alpha version 5.3.3-latest.20211214.2
microsoft/winget-pkgs pull request #37767
Opened 2021-12-14 21:15 UTC by vedantmgoyal2009

### ARP entries are correct.

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation) in workflow run [1073](https://github.com/vedantmgoyal2009/winget-pkgs-automation/actions/runs/1579899015)

2021-12-14 23:22 UTC, OfficialEsco reviewed
According to GitHub Releases this is another Release not Pre-Release

2021-12-14 23:37 UTC, ItzLevvie requested changes
https://github.com/microsoft/winget-pkgs/pull/37767#pullrequestreview-832146287

2021-12-16 11:09 UTC, ItzLevvie requested changes

2021-12-16 11:09 UTC, ItzLevvie commented on manifests/m/Mirantis/Lens/5.3.3-latest.20211214.2/Mirantis.Lens.locale.en-US.yaml
> +PackageName: Lens (Alpha)
```suggestion
PackageName: Lens
```

2021-12-16 11:17 UTC, ItzLevvie approved these changes

2021-12-16 11:52 UTC, merged