New version: Mu.Mu version 1.1.0-beta.7
microsoft/winget-pkgs pull request #38611
Opened 2021-12-22 12:27 UTC by vedantmgoyal2009

### Installation timed out.

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation) in workflow run [1255](https://github.com/vedantmgoyal2009/winget-pkgs-automation/actions/runs/1611246595)

2021-12-22 20:20 UTC, ItzLevvie requested changes

2021-12-22 20:20 UTC, ItzLevvie commented on manifests/m/Mu/Mu/1.1.0-beta.7/Mu.Mu.locale.en-US.yaml
> +PackageVersion: 1.1.0-beta.7
```suggestion
PackageVersion: 1.1.0
```

2021-12-22 20:20 UTC, ItzLevvie commented on manifests/m/Mu/Mu/1.1.0-beta.7/Mu.Mu.installer.yaml
> +PackageVersion: 1.1.0-beta.7
```suggestion
PackageVersion: 1.1.0
```

2021-12-22 20:20 UTC, ItzLevvie commented on manifests/m/Mu/Mu/1.1.0-beta.7/Mu.Mu.yaml
> +PackageVersion: 1.1.0-beta.7
```suggestion
PackageVersion: 1.1.0
```

2021-12-22 20:20 UTC, ItzLevvie commented on manifests/m/Mu/Mu/1.1.0-beta.7/Mu.Mu.installer.yaml
> +  InstallerSha256: 775E9D963F0AE02DC98D0394FCB57BE85E202C0CD90EAD5B2DAE31294D8BA5E7
```suggestion
  InstallerSha256: 775E9D963F0AE02DC98D0394FCB57BE85E202C0CD90EAD5B2DAE31294D8BA5E7
  ProductCode: "{2858D67E-5485-419C-A099-19EABD12F748}"
```

2021-12-23 04:15 UTC, OfficialEsco approved these changes
VSCode online made it way harder to rename the folder than it needed to.. (Folders disappeared)

2021-12-23 04:51 UTC, merged