CambridgeUniversityPress.CambridgeReader version 1.0
microsoft/winget-pkgs pull request #40066
Opened 2022-01-06 14:08 UTC by solomoncyj

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-01-07 09:02 UTC, OfficialEsco submitted a review, later dismissed

2022-01-07 14:14 UTC, solomoncyj commented
@ItzLevvie

2022-01-07 14:21 UTC, ItzLevvie commented
> @ItzLevvie

Wait for the WinGet engineers who were assigned to this PR to take a look.

2022-01-07 14:22 UTC, solomoncyj commented
> > @ItzLevvie
> 
> Wait for the WinGet engineers who were assigned to this PR to take a look.

i need you to approve the pr

2022-01-07 19:44 UTC, ItzLevvie requested changes

2022-01-07 19:44 UTC, ItzLevvie commented on manifests/c/CambridgeUniversityPress/CambridgeReader/1.0/CambridgeUniversityPress.CambridgeReader.installer.yaml
> +- Architecture: x86
```suggestion
- Architecture: x64
```

2022-01-09 01:42 UTC, ItzLevvie approved these changes

2022-01-09 01:43 UTC, merged