CapricornConsultingGmbH.Vigoon version (2.4.2559.0)
microsoft/winget-pkgs pull request #40665
Opened 2022-01-13 08:25 UTC by cctimoerdbruegger

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-01-13 21:43 UTC, msftrubengu commented
@wingetbot waivers add Validation-Domain

2022-01-14 11:08 UTC, ItzLevvie requested changes

2022-01-14 11:08 UTC, ItzLevvie commented on manifests/c/CapricornConsultingGmbH/Vigoon/(2.4.2559.0)/CapricornConsultingGmbH.Vigoon.locale.en-US.yaml
> +PackageVersion: (2.4.2559.0)
```suggestion
PackageVersion: 1.0.0
```

2022-01-14 11:08 UTC, ItzLevvie commented on manifests/c/CapricornConsultingGmbH/Vigoon/(2.4.2559.0)/CapricornConsultingGmbH.Vigoon.yaml
> +PackageVersion: (2.4.2559.0)
```suggestion
PackageVersion: 1.0.0
```

2022-01-14 11:08 UTC, ItzLevvie commented on manifests/c/CapricornConsultingGmbH/Vigoon/(2.4.2559.0)/CapricornConsultingGmbH.Vigoon.installer.yaml
> +PackageVersion: (2.4.2559.0)
```suggestion
PackageVersion: 1.0.0
```

2022-01-14 11:08 UTC, ItzLevvie commented on manifests/c/CapricornConsultingGmbH/Vigoon/(2.4.2559.0)/CapricornConsultingGmbH.Vigoon.installer.yaml
> +PackageVersion: (2.4.2559.0)
This must match Control Panel.

2022-01-14 11:08 UTC, ItzLevvie commented on manifests/c/CapricornConsultingGmbH/Vigoon/(2.4.2559.0)/CapricornConsultingGmbH.Vigoon.locale.en-US.yaml
> +PackageVersion: (2.4.2559.0)
This must match Control Panel.

2022-01-14 11:08 UTC, ItzLevvie commented on manifests/c/CapricornConsultingGmbH/Vigoon/(2.4.2559.0)/CapricornConsultingGmbH.Vigoon.yaml
> +PackageVersion: (2.4.2559.0)
This must match Control Panel.

2022-01-14 11:08 UTC, ItzLevvie commented on manifests/c/CapricornConsultingGmbH/Vigoon/(2.4.2559.0)/CapricornConsultingGmbH.Vigoon.locale.en-US.yaml
> +ShortDescription: Vigoon App Platform - Version 2.4.2559.0
```
ShortDescription: Vigoon App Platform - Version 2.4.2559.0
```
Please write a better description for what this application is about.

2022-01-14 13:27 UTC, ItzLevvie requested changes
Make sure to update the version folder as well: https://github.com/microsoft/winget-pkgs/pull/40665#pullrequestreview-852795092; otherwise the application upgrade will end up in a upgrade loop.

You'll also need to update the description for the application.

2022-01-17 09:33 UTC, cctimoerdbruegger commented
> Make sure to update the version folder as well: [#40665 (review)](https://github.com/microsoft/winget-pkgs/pull/40665#pullrequestreview-852795092); otherwise the application upgrade will end up in a upgrade loop.
> 
> You'll also need to update the description for the application.

How should i update the version folder? The package identify is not recognized by wingetcreate update comment. So i am not allowed to push an updated manifest. I can only make a new manifest pull request then?

2022-01-17 10:39 UTC, ItzLevvie approved these changes

2022-01-17 10:40 UTC, merged