SteelSeries.SteelSeriesEngine version 3.22.1
microsoft/winget-pkgs pull request #40868
Opened 2022-01-14 20:35 UTC by spitfire

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-01-14 22:36 UTC, OfficialEsco requested changes
Huh, this software have been forgotten..

2022-01-14 22:36 UTC, OfficialEsco commented on manifests/s/SteelSeries/SteelSeriesEngine/3.22.1/SteelSeries.SteelSeriesEngine.locale.en-US.yaml
> +PackageName: SteelSeriesEngine
```suggestion
Publisher: SteelSeries ApS
PackageName: SteelSeries Engine
```

2022-01-14 22:36 UTC, OfficialEsco commented on manifests/s/SteelSeries/SteelSeriesEngine/3.22.1/SteelSeries.SteelSeriesEngine.locale.en-US.yaml
> +Moniker: SteelSeriesEngine
```suggestion
License: Proprietary
Copyright: Copyright (c) SteelSeries ApS
ShortDescription: SteelSeries Engine is a configuration program for all compatible SteelSeries gear, allowing the user to adjust a wide range of customization options for their SteelSeries product(s).
Moniker: steelseries-engine
```

2022-01-21 12:06 UTC, spitfire commented
> Huh, this software have been forgotten..

I don't think this will get any more updates, since they moved on to a bigger suite of tools containing this. Not everyone likes to install whole bunch of stuff though.

2022-01-21 12:10 UTC, OfficialEsco approved these changes
Well, atleast now it can be exported and imported to the people who use the software :)

2022-01-21 12:39 UTC, merged