New version: FengHe.Migi version 2.15.1-670
microsoft/winget-pkgs pull request #40941
Opened 2022-01-15 02:12 UTC by vedantmgoyal2009

### Installation timed out.

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation) in workflow run [1815](https://github.com/vedantmgoyal2009/winget-pkgs-automation/actions/runs/1700369881)

2022-01-15 10:22 UTC, OfficialEsco requested changes

2022-01-15 10:22 UTC, OfficialEsco commented on manifests/f/FengHe/Migi/2.15.1-670/FengHe.Migi.installer.yaml
> +  InstallerUrl: https://download.kirakuapp.com/FN_PC/Focus%20Note%20Setup%202.15.1-670.exe
Still the wrong urls

2022-01-15 16:14 UTC, vedantmgoyal2009 commented
I will look at the issue, please don't close the PR.

2022-01-17 11:35 UTC, ItzLevvie requested changes
https://github.com/microsoft/winget-pkgs/pull/40941#issuecomment-1013708855

2022-01-19 04:09 UTC, vedantmgoyal2009 commented
Fixed the issue in automation.

2022-03-01 15:34 UTC, ItzLevvie approved these changes

2022-03-01 16:05 UTC, merged