New Package: WaterbugStudios.Mazerator v0.0.1
microsoft/winget-pkgs pull request #40997
Opened 2022-01-15 17:39 UTC by Trenly

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
  - Closes #40971 
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-01-15 17:46 UTC, Trenly commented
@OfficialEsco  I can't quite figure out how to get past this. Any ideas? 
![image](https://user-images.githubusercontent.com/12611259/149632185-b1b9d364-af3a-4769-bfa1-8980f696ddc4.png)

2022-01-15 17:48 UTC, OfficialEsco requested changes
*cough* yes.

2022-01-15 17:48 UTC, OfficialEsco commented on manifests/w/WaterbugStudios/Mazerator/0.0.1/WaterbugStudios.Mazerator.installer.yaml
> +  InstallerType: nullsoft
```suggestion
  InstallerType: inno
```

2022-01-15 17:48 UTC, OfficialEsco commented on manifests/w/WaterbugStudios/Mazerator/0.0.1/WaterbugStudios.Mazerator.installer.yaml
> +  InstallerType: nullsoft
```suggestion
  InstallerType: inno
```

2022-01-15 17:50 UTC, Trenly commented
> _cough_ yes.

🤦

2022-01-15 17:53 UTC, Trenly commented
> https://github.com/microsoft/winget-pkgs/pull/40997/commits/d792f0cf6ddcab00b4cf93e4df55401c8d3e692e

Oof, its been a long day

2022-01-15 17:54 UTC, OfficialEsco approved these changes
> Edit: Didn't work

> Oof, its been a long day


I can see that... 🤔😁
```
Enter a pull request number: #40997

Manifest validation succeeded.
Found Mazerator [WaterbugStudios.Mazerator] Version 0.0.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.tuxfamily.org/mazerator/Mazerator/v0.0.1/mazerator-0.0.1-x64.exe
  ██████████████████████████████  48.9 MB / 48.9 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Name        : Mazerator version 0.0.1
Publisher   : Waterbug Studios
Version     : 0.0.1
ProductCode : {A2086546-A47B-486A-9449-DC433173B399}_is1
Uninstall   : winget uninstall "{A2086546-A47B-486A-9449-DC433173B399}_is1"

Press any key to continue . . .
```

2022-01-21 04:21 UTC, JohnMcPMS commented
@wingetbot waivers Add Validation-Domain

2022-01-21 04:56 UTC, merged