Microsoft.PIX version 22.1.24.1
microsoft/winget-pkgs pull request #42434
Opened 2022-01-25 20:44 UTC by Devaniti

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-01-25 20:46 UTC, ItzLevvie requested changes

2022-01-25 20:46 UTC, ItzLevvie commented on manifests/m/Microsoft/PIX/22.1.24.1/Microsoft.PIX.installer.yaml
> +  InstallerSha256: B73B97D223B7DC0BDD16A8D2F5B8DDC1BC7AE855EC420C028FAE3E6B4BCF636F
```suggestion
  InstallerSha256: B73B97D223B7DC0BDD16A8D2F5B8DDC1BC7AE855EC420C028FAE3E6B4BCF636F
  Scope: machine
```
`C:\Program Files\Microsoft PIX\2201.24`

2022-01-25 20:57 UTC, ItzLevvie approved these changes

2022-01-26 22:14 UTC, Trenly commented
#42616

2022-01-27 15:55 UTC, ItzLevvie requested changes
Please close and re-open the PR to re-run the pipelines.

2022-01-28 08:39 UTC, merged