New version: JetBrains.CLion.EAP version 221.3427.90
microsoft/winget-pkgs pull request #43583
Opened 2022-01-27 20:19 UTC by vedantmgoyal2009

### Installation timed out.

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation) in workflow run [2119](https://github.com/vedantmgoyal2009/winget-pkgs-automation/actions/runs/1758230133)

2022-01-27 21:42 UTC, ItzLevvie requested changes

2022-01-27 21:42 UTC, ItzLevvie commented on manifests/j/JetBrains/CLion/EAP/221.3427.90/JetBrains.CLion.EAP.installer.yaml
> +  ProductCode: CLion 213.5605.4
```suggestion
  ProductCode: CLion 221.3427.90
```

2022-01-28 01:20 UTC, ItzLevvie2 approved these changes

2022-01-28 01:20 UTC, ItzLevvie approved these changes

2022-01-28 01:20 UTC, merged