PaulWoolcock.SyncOutlookandGooglecalendars.alpha version 2.9.2-alpha
microsoft/winget-pkgs pull request #44009
Opened 2022-01-30 15:30 UTC by SM-26

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-01-30 15:33 UTC, SM-26 commented
This PR is based on https://github.com/microsoft/winget-pkgs/pull/41396
(which is based on #40602)
This one includes the Alpha tag. and (should) be the last PR regarding this app

2022-01-30 22:28 UTC, ItzLevvie requested changes

2022-01-30 22:28 UTC, ItzLevvie commented on manifests/p/PaulWoolcock/SyncOutlookandGooglecalendars/alpha/2.9.2-alpha/PaulWoolcock.SyncOutlookandGooglecalendars.alpha.locale.en-US.yaml
> +PackageName: Outlook Google Calendar Sync
```suggestion
PackageName: Outlook Google Calendar Sync (Alpha)
```

2022-01-31 10:27 UTC, SM-26 reviewed
Added the Alpha tag in the packageName

2022-02-01 09:40 UTC, OfficialEsco approved these changes

2022-02-01 16:01 UTC, ghost approved these changes

2022-02-01 16:02 UTC, merged