TroyeGuo.KoodoReader version 1.4.0.811
microsoft/winget-pkgs pull request #44424
Opened 2022-02-03 18:51 UTC by superusercode

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-02-03 20:04 UTC, superusercode commented
This worked fine for me locally.

2022-02-03 22:19 UTC, Trenly commented
This is what I get on the sandbox environment
![image](https://user-images.githubusercontent.com/12611259/152438741-bcda90eb-e501-4353-b847-787c21bea2bd.png)

2022-02-03 22:30 UTC, Trenly requested changes

2022-02-03 22:30 UTC, Trenly commented on manifests/t/TroyeGuo/KoodoReader/1.4.0.811/TroyeGuo.KoodoReader.installer.yaml
> +PackageVersion: 1.4.0.811
```suggestion
PackageVersion: 1.4.0
```
This must match the version shown in control panel. Don't forget to update the version folder name when this changes

2022-02-03 22:30 UTC, Trenly commented on manifests/t/TroyeGuo/KoodoReader/1.4.0.811/TroyeGuo.KoodoReader.locale.en-US.yaml
> +PackageVersion: 1.4.0.811
```suggestion
PackageVersion: 1.4.0
```

2022-02-03 22:30 UTC, Trenly commented on manifests/t/TroyeGuo/KoodoReader/1.4.0.811/TroyeGuo.KoodoReader.yaml
> +PackageVersion: 1.4.0.811
```suggestion
PackageVersion: 1.4.0
```

2022-02-03 22:30 UTC, Trenly commented on manifests/t/TroyeGuo/KoodoReader/1.4.0.811/TroyeGuo.KoodoReader.installer.yaml
> +  InstallerSha256: 797149FFD50C7CBD31DBC077D1CB0726F715AA5CD812EB6FC32713139C973A92
```suggestion
  InstallerSha256: 797149FFD50C7CBD31DBC077D1CB0726F715AA5CD812EB6FC32713139C973A92
  Scope: machine
  ElevationRequirement: elevationRequired #This should fix the unattended error
```

2022-02-03 22:30 UTC, Trenly commented on manifests/t/TroyeGuo/KoodoReader/1.4.0.811/TroyeGuo.KoodoReader.installer.yaml
> +ManifestVersion: 1.0.0
```suggestion
ManifestVersion: 1.1.0 # For the elevation requirement key
```

2022-02-03 22:30 UTC, Trenly commented on manifests/t/TroyeGuo/KoodoReader/1.4.0.811/TroyeGuo.KoodoReader.locale.en-US.yaml
> +ManifestVersion: 1.0.0
```suggestion
ManifestVersion: 1.1.0
```

2022-02-03 22:30 UTC, Trenly commented on manifests/t/TroyeGuo/KoodoReader/1.4.0.811/TroyeGuo.KoodoReader.yaml
> +ManifestVersion: 1.0.0
```suggestion
ManifestVersion: 1.1.0
```

2022-02-03 22:30 UTC, Trenly commented on manifests/t/TroyeGuo/KoodoReader/1.4.0.811/TroyeGuo.KoodoReader.locale.en-US.yaml
> +Publisher: Troye Guo
```suggestion
Publisher:  App by Troye
```
This must match the entry in control panel

2022-02-03 22:30 UTC, Trenly commented on manifests/t/TroyeGuo/KoodoReader/1.4.0.811/TroyeGuo.KoodoReader.locale.en-US.yaml
> +License: AGPL-3.0 License
```suggestion
License: AGPL-3.0 License
LicenseUrl: https://github.com/troyeguo/koodo-reader/blob/master/LICENSE
```

2022-02-04 01:19 UTC, superusercode commented
> This is what I get on the sandbox environment ![image](https://user-images.githubusercontent.com/12611259/152438741-bcda90eb-e501-4353-b847-787c21bea2bd.png)

I think this must be a successful install code? I can't find equivalents documented in the scoop and chocolatey versions of this application.

2022-02-04 01:21 UTC, superusercode commented
Scratch that, looking up that error code seems to be related to incorrect memory use by the program. Not sure if this is on the VM or the installer itself.

2022-02-04 01:31 UTC, Trenly commented
> Scratch that, looking up that error code seems to be related to incorrect memory use by the program. Not sure if this is on the VM or the installer itself.

When I install as admin, works just fine. Without admin, I get that error code, which is why I put the suggestions

2022-02-04 02:55 UTC, superusercode commented
Is it still failing to the same error code?

2022-02-04 03:00 UTC, Trenly commented
> Is it still failing to the same error code?

I can’t tell. Seems to work for me. You could try switching the architecture to x64 and see if that works?

2022-02-05 12:59 UTC, OfficialEsco approved these changes

2022-02-05 14:06 UTC, merged