New version: KRTirtho.Spotube version 1.2.0
microsoft/winget-pkgs pull request #45318
Opened 2022-02-08 06:12 UTC by KRTirtho

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-02-08 06:40 UTC, KaranKad submitted a review, later dismissed

2022-02-09 17:00 UTC, OfficialEsco requested changes

2022-02-09 17:00 UTC, OfficialEsco commented on manifests/k/KRTirtho/Spotube/1.2.0/KRTirtho.Spotube.installer.yaml
> +- Architecture: x86
```suggestion
- Architecture: x64
```

2022-02-09 17:00 UTC, OfficialEsco commented on manifests/k/KRTirtho/Spotube/1.2.0/KRTirtho.Spotube.installer.yaml
> +- Architecture: x86
```suggestion
- Architecture: x64
```

2022-02-09 22:30 UTC, KaranKad approved these changes

2022-02-09 22:30 UTC, merged