New version: Kitware.CMake version 3.23.0-rc1
microsoft/winget-pkgs pull request #45416
Opened 2022-02-08 17:34 UTC by vedantmgoyal2009

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation) in workflow run [2365](https://github.com/vedantmgoyal2009/winget-pkgs-automation/actions/runs/1813702686)

2022-02-08 18:03 UTC, KaranKad requested changes
This is a release client version but with no way do differentiate it from stable release, so it might be better to not add it.

2022-02-08 19:21 UTC, vedantmgoyal2009 commented
I don't know much about release management, but according to this, I think we can add it because "this release goes into production". 
![image](https://user-images.githubusercontent.com/83997633/153060045-9c38a0f7-b4fa-4d56-a657-49e9ceff0d1d.png)

2022-02-08 19:33 UTC, KaranKad requested changes

2022-02-08 19:33 UTC, KaranKad commented on manifests/k/Kitware/CMake/3.23.0-rc1/Kitware.CMake.yaml
> +PackageVersion: 3.23.0-rc1
```suggestion
PackageVersion: 3.23.0
```

2022-02-08 19:33 UTC, KaranKad commented on manifests/k/Kitware/CMake/3.23.0-rc1/Kitware.CMake.locale.en-US.yaml
> +PackageVersion: 3.23.0-rc1
```suggestion
PackageVersion: 3.23.0
```

2022-02-08 19:33 UTC, KaranKad commented on manifests/k/Kitware/CMake/3.23.0-rc1/Kitware.CMake.installer.yaml
> +PackageVersion: 3.23.0-rc1
```suggestion
PackageVersion: 3.23.0
```

2022-02-08 19:34 UTC, KaranKad commented on manifests/k/Kitware/CMake/3.23.0-rc1/Kitware.CMake.yaml
> +PackageVersion: 3.23.0-rc1
![image](https://user-images.githubusercontent.com/71691514/153062023-2c26d437-f9a7-4ac9-8e79-3e7dbee73728.png)

2022-02-08 22:48 UTC, ItzLevvie approved these changes

2022-02-09 01:14 UTC, merged

2022-02-28 22:18 UTC, Carbenium commented
@vedantmgoyal2009 @KaranKad @ItzLevvie Please consider not adding RCs (Release Candidates) to winget without an explicit opt-in. The default should be stable releases only.
The citation given by @vedantmgoyal2009 (from https://en.wikipedia.org/wiki/Software_release_life_cycle) is not really applicable. Yes, it might be true that the last RC before stable is promoted to the stable version, but that does not mean that RC1 (the first RC) is actually going stable (as seen with 3.23.0-rc2).