New version: RandomEngy.VidCoder version 7.11
microsoft/winget-pkgs pull request #46537
Opened 2022-02-16 03:33 UTC by vedantmgoyal2009

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation) in workflow run [2535](https://github.com/vedantmgoyal2009/winget-pkgs-automation/actions/runs/1850711258)

2022-02-16 16:41 UTC, quhxl commented
![image](https://user-images.githubusercontent.com/69106310/154313318-4c9ccd9e-00ee-4b59-bf9f-43cced609824.png)

2022-02-17 00:44 UTC, ItzLevvie requested changes
https://github.com/microsoft/winget-pkgs/pull/46537#issuecomment-1041861524

2022-02-28 11:29 UTC, vedantmgoyal2009 commented
Held due to dependency issue.

2022-03-01 11:45 UTC, ItzLevvie approved these changes

2022-03-01 12:33 UTC, merged