Remove: Jackett.Jackett version 0.16.1684
microsoft/winget-pkgs pull request #48201
Opened 2022-02-23 19:17 UTC by vedantmgoyal2009

## Removing old versions to reduce clutter

2022-02-23 19:19 UTC, ItzLevvie approved these changes

2022-02-24 00:27 UTC, jedieaston approved these changes, later dismissed

2022-02-24 00:55 UTC, ItzLevvie requested changes
This PR includes two package removals.

2022-02-24 15:42 UTC, KaranKad approved these changes

2022-02-24 15:43 UTC, merged