New version: BraveSoftware.BraveBrowser version 98.1.36.106
microsoft/winget-pkgs pull request #49167
Opened 2022-02-25 12:39 UTC by vedantmgoyal2009

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [18](https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/1898606660)

2022-02-25 14:01 UTC, ItzLevvie requested changes

2022-02-25 14:01 UTC, ItzLevvie commented on manifests/b/BraveSoftware/BraveBrowser/98.1.36.106/BraveSoftware.BraveBrowser.installer.yaml
> +PackageVersion: 98.1.36.106
```suggestion
PackageVersion: 99.1.36.106
```

2022-02-25 14:01 UTC, ItzLevvie commented on manifests/b/BraveSoftware/BraveBrowser/98.1.36.106/BraveSoftware.BraveBrowser.locale.en-US.yaml
> +PackageVersion: 98.1.36.106
```suggestion
PackageVersion: 99.1.36.106
```

2022-02-25 14:01 UTC, ItzLevvie commented on manifests/b/BraveSoftware/BraveBrowser/98.1.36.106/BraveSoftware.BraveBrowser.yaml
> +PackageVersion: 98.1.36.106
```suggestion
PackageVersion: 99.1.36.106
```

2022-02-25 14:01 UTC, ItzLevvie commented on manifests/b/BraveSoftware/BraveBrowser/98.1.36.106/BraveSoftware.BraveBrowser.yaml
> +PackageVersion: 98.1.36.106
![image](https://user-images.githubusercontent.com/11600822/155727979-084c691a-ef0e-442a-b6ce-1bc98002b5fb.png)

2022-02-25 14:01 UTC, ItzLevvie commented on manifests/b/BraveSoftware/BraveBrowser/98.1.36.106/BraveSoftware.BraveBrowser.locale.en-US.yaml
> +PackageVersion: 98.1.36.106
![image](https://user-images.githubusercontent.com/11600822/155727974-eeea381c-edd9-4e53-bb7b-a3fa0ca74fd6.png)

2022-02-25 14:01 UTC, ItzLevvie commented on manifests/b/BraveSoftware/BraveBrowser/98.1.36.106/BraveSoftware.BraveBrowser.installer.yaml
> +PackageVersion: 98.1.36.106
![image](https://user-images.githubusercontent.com/11600822/155727970-eecf1dea-7d1e-44b5-acb6-3515b1d0ea6a.png)

2022-02-26 09:17 UTC, OfficialEsco approved these changes

2022-02-26 09:44 UTC, merged