Xanthus58.VanillaRenewed version 2.2
microsoft/winget-pkgs pull request #49505
Opened 2022-02-28 10:01 UTC by Xanthus58

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-02-28 12:23 UTC, ItzLevvie submitted a review, later dismissed
Installs to `C:\Users\WDAGUtilityAccount\Desktop\%appdata%\.minecraft\resourcepacks\Vanilla Renewed`

2022-02-28 15:53 UTC, Xanthus58 commented
ahh right right forgot about the hash 2 secconds <3

2022-02-28 16:42 UTC, Xanthus58 commented
Should "Validation-No-Executables" be concerning? I had it working on my end, just confused on how it passed the pipeline but has errors

2022-02-28 17:31 UTC, KaranKad commented
`Validation-No-Executables` means it couldn't find any `.exe` after this application is installed, but it makes sense since this is a minecraft resource pack.

2022-02-28 17:33 UTC, Xanthus58 commented
> `Validation-No-Executables` means it couldn't find any `.exe` after this application is installed, but it makes sense since this is a minecraft resource pack.

Ahhhhh i see thank you <3

2022-03-01 12:20 UTC, ItzLevvie requested changes

2022-03-01 12:20 UTC, ItzLevvie commented on manifests/x/Xanthus58/VanillaRenewed/2.2/Xanthus58.VanillaRenewed.installer.yaml
> +  InstallerSha256: 053b6361f2e4c5e2b5aaba205d36504425078a82d4a78852537884efa43c777e
```suggestion
  InstallerSha256: 053b6361f2e4c5e2b5aaba205d36504425078a82d4a78852537884efa43c777e
  Scope: user
```

2022-03-01 12:44 UTC, ItzLevvie approved these changes

2022-03-01 18:37 UTC, msftrubengu commented
@wingetbot waivers add Validation-No-Executables

2022-03-01 19:08 UTC, merged