New version: JetBrains.DataGrip.EarlyAccess version 221.4906.1
microsoft/winget-pkgs pull request #49747
Opened 2022-03-01 17:36 UTC by vedantmgoyal2009

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [110](https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/1917651796)

2022-03-01 18:23 UTC, msftrubengu commented
/azp run

2022-03-02 13:48 UTC, ItzLevvie requested changes

2022-03-02 13:48 UTC, ItzLevvie commented on manifests/j/JetBrains/DataGrip/EarlyAccess/221.4906.1/JetBrains.DataGrip.EarlyAccess.installer.yaml
> +  ProductCode: DataGrip 213.5744.9
```suggestion
  ProductCode: DataGrip 221.4906.1
```

2022-03-02 14:20 UTC, ItzLevvie approved these changes

2022-03-02 14:58 UTC, ghost approved these changes

2022-03-02 14:58 UTC, merged