Symflower.SymflowerCLI version 20890
microsoft/winget-pkgs pull request #50135
Opened 2022-03-04 15:21 UTC by bauersimon

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-03-04 15:40 UTC, ItzLevvie requested changes

2022-03-04 15:40 UTC, ItzLevvie commented on manifests/s/Symflower/SymflowerCLI/20890/Symflower.SymflowerCLI.locale.en-US.yaml
> +LicenseURL: https://symflower.com/en/license/
```suggestion
LicenseUrl: https://symflower.com/en/license/
```

2022-03-04 16:01 UTC, ItzLevvie requested changes

2022-03-04 16:01 UTC, ItzLevvie requested changes

2022-03-04 16:01 UTC, ItzLevvie commented on manifests/s/Symflower/SymflowerCLI/20890/Symflower.SymflowerCLI.installer.yaml
> +  Architecture: x86
```suggestion
  Architecture: x64
```
Installer is `x86_64` which is meant to be run on x64 devices.

2022-03-04 16:30 UTC, bauersimon commented on manifests/s/Symflower/SymflowerCLI/20890/Symflower.SymflowerCLI.locale.en-US.yaml
> +PackageVersion: 20890
I also renamed the folder to 1.0.20890 then.

2022-03-06 00:49 UTC, Trenly requested changes

2022-03-06 00:49 UTC, Trenly commented on manifests/s/Symflower/SymflowerCLI/1.0.20917/Symflower.SymflowerCLI.installer.yaml
> +    ProductCode: "{8E68DE64-6D60-42CE-88C4-290CECBAFA6F}"
```suggestion
    ProductCode: '{B41C1F22-E777-4C3D-ACDC-944B9CA8482E}'
```

2022-03-07 12:14 UTC, ItzLevvie approved these changes

2022-03-07 12:15 UTC, merged