New version: uvncbvba.UltraVnc version 1.3.8.0
microsoft/winget-pkgs pull request #50166
Opened 2022-03-05 00:20 UTC by OfficialEsco

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

2022-03-05 10:26 UTC, ItzLevvie approved these changes

2022-03-07 22:54 UTC, ItzLevvie commented
@wingetbot run

2022-03-07 22:54 UTC, ItzLevvie requested changes
Please close and re-open the PR to re-run the pipelines.

2022-03-08 16:36 UTC, OfficialEsco commented
```
3/8/2022 7:03:56 AM
Status: Completed
##[error] Installer https://www.uvnc.eu/download/1380/UltraVnc_1380_x86.msi Scan information: 'Error information: BlockingDetectionFound'
##[error] Result: Failed

3/8/2022 7:04:02 AM
Status: Completed
##[error] Installer https://www.uvnc.eu/download/1380/UltraVnc_1380_X64.msi Scan information: 'Error information: BlockingDetectionFound'
##[error] Result: Failed
```

Guess we're not getting this one then

2022-03-08 21:10 UTC, closed without merging