Add ChilliBits.Spice version 0.7.2
microsoft/winget-pkgs pull request #51098
Opened 2022-03-10 13:55 UTC by marcauberer

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-03-10 19:06 UTC, Trenly requested changes

2022-03-10 19:06 UTC, Trenly commented on manifests/c/ChilliBits/Spice/0.7.2/ChilliBits.Spice.installer.yaml
> +  ProductCode: "{A70BEF44-08F4-405B-A361-349257A8C2FD}"
```suggestion
  ProductCode: '{F4BF91AF-86F5-47CA-830A-7EC7767AD9E1}'
```

2022-03-10 19:06 UTC, Trenly commented on manifests/c/ChilliBits/Spice/0.7.2/ChilliBits.Spice.installer.yaml
> +InstallerType: msi
```suggestion
InstallerType: wix
```

2022-03-10 19:49 UTC, Trenly commented
* #42616

Close and reopen this PR to rerun the pipelines

2022-03-11 00:59 UTC, ItzLevvie approved these changes

2022-03-11 01:00 UTC, merged