Remove Old: JanDeDobbeleer.OhMyPosh version 7.38.0
microsoft/winget-pkgs pull request #54164
Opened 2022-03-14 11:31 UTC by vedantmgoyal2009

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [403](https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/1980212142)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/54164)

2022-03-14 12:01 UTC, ItzLevvie requested changes

2022-03-14 12:01 UTC, ItzLevvie commented on manifests/r/r12f/Rnp/0.1.143.main/r12f.Rnp.installer.yaml
> +PackageVersion: 0.1.143.main
```suggestion
PackageVersion: 0.1.143.0
```

2022-03-14 19:45 UTC, ItzLevvie submitted a review, later dismissed

2022-03-16 07:15 UTC, r12f commented
I created a new PR with winget-create here, not sure if it will work better: https://github.com/microsoft/winget-pkgs/pull/54559.

2022-03-16 10:55 UTC, ItzLevvie submitted a review, later dismissed

2022-03-19 13:55 UTC, ItzLevvie approved these changes

2022-03-19 14:57 UTC, merged