New Package: rcmaehl.MSEdgeRedirect version 0.6.4.0
microsoft/winget-pkgs pull request #54267
Opened 2022-03-14 12:55 UTC by gnpaone

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-03-14 14:05 UTC, ItzLevvie requested changes

2022-03-14 14:05 UTC, ItzLevvie commented on manifests/r/rcmaehl/MSEdgeRedirect/0.6.4.0/rcmaehl.MSEdgeRedirect.locale.en-US.yaml
> +Publisher: rcmaehl
```suggestion
Publisher: Robert Maehl Software
```
This must match Control Panel.

2022-03-14 14:36 UTC, gnpaone commented on manifests/r/rcmaehl/MSEdgeRedirect/0.6.4.0/rcmaehl.MSEdgeRedirect.locale.en-US.yaml
> +Publisher: rcmaehl
Sure 😊, will change that

2022-03-14 14:47 UTC, ItzLevvie approved these changes

2022-03-17 07:35 UTC, gnpaone commented
`Azurepipelines` didn't run due to First time contributors thing, anything to do for that?

2022-03-17 10:27 UTC, ItzLevvie commented
> `Azurepipelines` didn't run due to First time contributors thing, anything to do for that?

A PSA has been posted: https://github.com/microsoft/winget-pkgs/issues/54601

2022-03-18 23:39 UTC, msftrubengu commented
/azp run

2022-03-19 00:17 UTC, merged

2022-03-22 09:48 UTC, iMonZ commented
Thank you so much! Finally, I can try this tool, and it works wonderful.
Just one thing, it would be great to rename the settings.exe file to something like MSEdgeRedirectSettings.exe because it's confusing when I search for settings and find this.

2022-03-22 16:30 UTC, rcmaehl commented
> Thank you so much! Finally, I can try this tool, and it works wonderful. Just one thing, it would be great to rename the settings.exe file to something like MSEdgeRedirectSettings.exe because it's confusing when I search for settings and find this.

Good point, will change