Slonopotamus.Stevedore version 0.3.3
microsoft/winget-pkgs pull request #54370
Opened 2022-03-14 20:38 UTC by slonopotamus

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-03-14 20:59 UTC, slonopotamus commented
I was unable to verify "Does your manifest conform to the 1.0 schema?" because there are no instructions on how I do that. On one hand, manifest was produced using `wingetcreate new`, so it is very likely valid. On the other hand, it contains `ManifestVersion: 1.1.0`. Does 1.1.0 version conform to 1.0 schema? I have no idea.

Another issue: I've tested `winget install --manifest <path>` and it does install the package successfully. But it causes immediate reboot. I came across https://github.com/microsoft/winget-cli/issues/229 but that doesn't help very much. Stevedore MSI is **not forcing** a reboot. It only [**schedules** a reboot](https://github.com/slonopotamus/stevedore/blob/0.3.3/wix/main.wxs#L296). If you install Stevedore MSI manually, you're presented with a "would you like to reboot" dialog. If you install Stevedore via [Chocolatey package](https://community.chocolatey.org/packages/stevedore), it returns 3010 exit code and Chocolatey warns user that reboot is required. So, I am not sure what and why transforms **scheduled** reboot into a **forced** reboot. But I believe this is something that users are unhappy about in https://github.com/microsoft/winget-cli/issues/229 and what needs to be fixed on WinGet side.

2022-03-15 14:36 UTC, ItzLevvie requested changes
Since validation is done on VMs I don't know if would go through because I'm stuck here:
```
WixQuietExec:  Get-LocalGroup : Group docker-users was not found.
WixQuietExec:  At line:1 char:2
WixQuietExec:  + (Get-LocalGroup -Name docker-users) -or (New-LocalGroup -Name docker- ...
WixQuietExec:  +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WixQuietExec:      + CategoryInfo          : ObjectNotFound: (docker-users:String) , GroupNotFoundException
WixQuietExec:      + FullyQualifiedErrorId : GroupNotFound,Microsoft.PowerShell.Commands.GetLocalGroupCommand
WixQuietExec:   
WixQuietExec:  True
```

and the installer stalls

2022-03-15 15:36 UTC, OfficialEsco requested changes

2022-03-15 15:36 UTC, OfficialEsco commented on manifests/s/Slonopotamus/Stevedore/0.3.3/Slonopotamus.Stevedore.installer.yaml
> +Installers:
```suggestion
InstallerSwitches:
  Custom: /norestart
  Upgrade: /norestart
Installers:
```

2022-03-17 07:47 UTC, OfficialEsco submitted a review, later dismissed

2022-03-18 23:56 UTC, msftrubengu commented
/azp run

2022-03-19 00:40 UTC, OfficialEsco commented
<details>
<summary>Click for Log</summary>
<br>

```
=== Logging started: 3/18/2022  17:02:20 ===
Action start 17:02:20: INSTALL.
Action start 17:02:20: FindRelatedProducts.
Action ended 17:02:20: FindRelatedProducts. Return value 1.
Action start 17:02:20: LaunchConditions.
Action ended 17:02:20: LaunchConditions. Return value 1.
Action start 17:02:20: ValidateProductID.
Action ended 17:02:20: ValidateProductID. Return value 1.
Action start 17:02:20: CostInitialize.
Action ended 17:02:20: CostInitialize. Return value 1.
Action start 17:02:20: FileCost.
Action ended 17:02:20: FileCost. Return value 1.
Action start 17:02:20: CostFinalize.
Action ended 17:02:20: CostFinalize. Return value 1.
Action start 17:02:20: SetARPINSTALLLOCATION.
Action ended 17:02:20: SetARPINSTALLLOCATION. Return value 1.
Action start 17:02:20: MigrateFeatureStates.
Action ended 17:02:20: MigrateFeatureStates. Return value 0.
Action start 17:02:20: InstallValidate.
Action ended 17:02:20: InstallValidate. Return value 1.
Action start 17:02:20: InstallInitialize.
Action ended 17:02:20: InstallInitialize. Return value 1.
Action start 17:02:20: RemoveExistingProducts.
Action ended 17:02:20: RemoveExistingProducts. Return value 1.
Action start 17:02:20: ProcessComponents.
Action ended 17:02:23: ProcessComponents. Return value 1.
Action start 17:02:23: UnpublishFeatures.
Action ended 17:02:23: UnpublishFeatures. Return value 1.
Action start 17:02:23: StopServices.
Action ended 17:02:23: StopServices. Return value 1.
Action start 17:02:23: DeleteServices.
Action ended 17:02:23: DeleteServices. Return value 1.
Action start 17:02:23: RemoveRegistryValues.
Action ended 17:02:23: RemoveRegistryValues. Return value 1.
Action start 17:02:23: RemoveShortcuts.
Action ended 17:02:23: RemoveShortcuts. Return value 1.
Action start 17:02:23: RemoveEnvironmentStrings.
Action ended 17:02:23: RemoveEnvironmentStrings. Return value 1.
Action start 17:02:23: RemoveFiles.
Action ended 17:02:23: RemoveFiles. Return value 0.
Action start 17:02:23: SetCreateDockerGroup.
Action ended 17:02:23: SetCreateDockerGroup. Return value 1.
Action start 17:02:23: CreateDockerGroup.
Action ended 17:02:23: CreateDockerGroup. Return value 1.
Action start 17:02:23: SetInstallContainersFeature.
Action ended 17:02:23: SetInstallContainersFeature. Return value 1.
Action start 17:02:23: InstallContainersFeature.
Action ended 17:02:23: InstallContainersFeature. Return value 1.
Action start 17:02:23: SetInstallHyperVFeature.
Action ended 17:02:23: SetInstallHyperVFeature. Return value 1.
Action start 17:02:23: InstallHyperVFeature.
Action ended 17:02:23: InstallHyperVFeature. Return value 1.
Action start 17:02:23: SetInstallWSL2Feature.
Action ended 17:02:23: SetInstallWSL2Feature. Return value 1.
Action start 17:02:23: InstallWSL2Feature.
Action ended 17:02:23: InstallWSL2Feature. Return value 1.
Action start 17:02:23: ConfigureUsers.
Action start 17:02:26: CreateUserRollback.
Action ended 17:02:26: CreateUserRollback. Return value 1.
Action start 17:02:26: CreateUser.
Action ended 17:02:26: CreateUser. Return value 1.
Action ended 17:02:26: ConfigureUsers. Return value 1.
Action start 17:02:26: InstallFiles.
Action ended 17:02:26: InstallFiles. Return value 1.
Action start 17:02:26: CreateShortcuts.
Action ended 17:02:26: CreateShortcuts. Return value 1.
Action start 17:02:26: WriteRegistryValues.
Action ended 17:02:26: WriteRegistryValues. Return value 1.
Action start 17:02:26: WriteEnvironmentStrings.
Action ended 17:02:26: WriteEnvironmentStrings. Return value 1.
Action start 17:02:26: InstallServices.
Action ended 17:02:26: InstallServices. Return value 1.
Action start 17:02:26: SchedServiceConfig.
Action start 17:02:26: RollbackServiceConfig.
Action ended 17:02:26: RollbackServiceConfig. Return value 1.
Action start 17:02:26: ExecServiceConfig.
Action ended 17:02:26: ExecServiceConfig. Return value 1.
Action ended 17:02:26: SchedServiceConfig. Return value 1.
Action start 17:02:26: StartServices.
Action ended 17:02:26: StartServices. Return value 1.
Action start 17:02:26: RegisterUser.
Action ended 17:02:26: RegisterUser. Return value 1.
Action start 17:02:26: RegisterProduct.
Action ended 17:02:26: RegisterProduct. Return value 1.
Action start 17:02:26: PublishFeatures.
Action ended 17:02:26: PublishFeatures. Return value 1.
Action start 17:02:26: PublishProduct.
Action ended 17:02:26: PublishProduct. Return value 1.
Action start 17:02:26: InstallFinalize.
WixQuietExec:  Get-LocalGroup : Group docker-users was not found.
WixQuietExec:  At line:1 char:2
WixQuietExec:  + (Get-LocalGroup -Name docker-users) -or (New-LocalGroup -Name docker- ...
WixQuietExec:  +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WixQuietExec:      + CategoryInfo          : ObjectNotFound: (docker-users:String) , GroupNotFoundException
WixQuietExec:      + FullyQualifiedErrorId : GroupNotFound,Microsoft.PowerShell.Commands.GetLocalGroupCommand
WixQuietExec:   
WixQuietExec:  True
WixQuietExec:  WARNING: Restart is suppressed because NoRestart is specified.
WixQuietExec:  
WixQuietExec:  
WixQuietExec:  Path          : 
WixQuietExec:  Online        : True
WixQuietExec:  RestartNeeded : True
WixQuietExec:  
WixQuietExec:  
WixQuietExec:  
WixQuietExec:  WARNING: Restart is suppressed because NoRestart is specified.
WixQuietExec:  
WixQuietExec:  
WixQuietExec:  Path          : 
WixQuietExec:  Online        : True
WixQuietExec:  RestartNeeded : True
WixQuietExec:  
WixQuietExec:  
WixQuietExec:  
WixQuietExec:  WARNING: Restart is suppressed because NoRestart is specified.
WixQuietExec:  
WixQuietExec:  
WixQuietExec:  Path          : 
WixQuietExec:  Online        : True
WixQuietExec:  RestartNeeded : True
WixQuietExec:  
WixQuietExec:  
WixQuietExec:  
Action ended 17:03:18: InstallFinalize. Return value 1.
Action start 17:03:18: ScheduleReboot.
Action ended 17:03:18: ScheduleReboot. Return value 1.
Action ended 17:03:18: INSTALL. Return value 1.
Property(S): DiskPrompt = Stevedore Installation
Property(S): UpgradeCode = {9A68EC9C-B494-4CDD-B081-F074FE91BF0B}
Property(S): InstallContainersFeature = "C:\Windows\sysnative\WindowsPowerShell\v1.0\powershell.exe" -Command "Enable-WindowsOptionalFeature -Online -FeatureName Containers -All -NoRestart"
Property(S): InstallHyperVFeature = "C:\Windows\sysnative\WindowsPowerShell\v1.0\powershell.exe" -Command "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All -NoRestart"
Property(S): InstallWSL2Feature = "C:\Windows\sysnative\WindowsPowerShell\v1.0\powershell.exe" -Command "Enable-WindowsOptionalFeature -Online -FeatureName 'Microsoft-Windows-Subsystem-Linux;VirtualMachinePlatform' -All -NoRestart"
Property(S): INSTALLDIR = C:\Program Files\Stevedore\
Property(S): bin = C:\Program Files\Stevedore\bin\
Property(S): cli_plugins = C:\Program Files\Docker\cli-plugins\
Property(S): WixUIRMOption = UseRM
Property(S): ALLUSERS = 1
Property(S): CreateDockerGroup = "C:\Windows\sysnative\WindowsPowerShell\v1.0\powershell.exe" -Command "(Get-LocalGroup -Name docker-users) -or (New-LocalGroup -Name docker-users -Description 'Users of Docker Desktop')"
Property(S): ARPINSTALLLOCATION = C:\Program Files\Stevedore\
Property(S): CreateUser = **********
Property(S): CreateUserRollback = **********
Property(S): ExecServiceConfig = SchedServiceConfigstevedore1restartrestartnone160
Property(S): RollbackServiceConfig = SchedServiceConfig
Property(S): ProgramFiles64Folder = C:\Program Files\
Property(S): Docker = C:\Program Files\Docker\
Property(S): TARGETDIR = D:\
Property(S): ProgramMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\
Property(S): DesktopFolder = C:\Users\Public\Desktop\
Property(S): SourceDir = C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\
Property(S): VersionNT = 603
Property(S): SERVICENAME = stevedore
Property(S): DISABLEADVTSHORTCUTS = 1
Property(S): POWERSHELLEXE = C:\Windows\sysnative\WindowsPowerShell\v1.0\powershell.exe
Property(S): ARPPRODUCTICON = stevedore.ico [...]

2022-03-20 16:08 UTC, ItzLevvie approved these changes

2022-03-20 17:08 UTC, merged