Add Golang.Go version 1.18
microsoft/winget-pkgs pull request #54491
Opened 2022-03-15 17:30 UTC by marcauberer

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-03-15 19:44 UTC, ItzLevvie requested changes

2022-03-15 19:44 UTC, ItzLevvie commented on manifests/g/GoLang/Go/1.18.0/GoLang.Go.installer.yaml
> +  ProductCode: '{E5DC7A79-C9A0-4472-8159-9F331CAB8E81}'
```suggestion
  ProductCode: '{F307E329-805A-4C79-BAEC-7FB35F3FE64B}'
```
winget-create or YamlCreate.ps1 is recommended to make new packages or new versions.

Both of these will update the ProductCode for you. ProductCode is unique for each release of the Go installer and cannot be the same.

2022-03-15 19:44 UTC, ItzLevvie commented on manifests/g/GoLang/Go/1.18.0/GoLang.Go.installer.yaml
> +  ProductCode: '{F03216DF-2EBC-46AA-B28C-F46B336F786C}'
```suggestion
  ProductCode: '{96064C04-3021-4953-A847-E05D1F5BABF3}'
```
winget-create or YamlCreate.ps1 is recommended to make new packages or new versions.

Both of these will update the ProductCode for you. ProductCode is unique for each release of the Go installer and cannot be the same.

2022-03-15 20:36 UTC, ItzLevvie approved these changes

2022-03-17 17:40 UTC, marcauberer commented
I assume this is a pipeline bug. Seems like the pipeline is unhealthy at the moment, as the badge above suggests ...
So I am waiting for the pipeline to re-run the check

2022-03-19 01:59 UTC, msftrubengu commented
/azp run

2022-03-19 02:33 UTC, merged