Update: VMware.WorkstationPro version 16.2.3.21887
microsoft/winget-pkgs pull request #54834
Opened 2022-03-18 16:12 UTC by virtualex-itv

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-03-18 16:56 UTC, ItzLevvie requested changes

2022-03-18 16:56 UTC, ItzLevvie commented on manifests/v/VMware/WorkstationPro/16.2.3.21887/VMware.WorkstationPro.installer.yaml
> +PackageVersion: 16.2.3.21887
```suggestion
PackageVersion: 16.2.3
```
This must match Control Panel.

2022-03-18 16:56 UTC, ItzLevvie commented on manifests/v/VMware/WorkstationPro/16.2.3.21887/VMware.WorkstationPro.locale.en-US.yaml
> +PackageVersion: 16.2.3.21887
```suggestion
PackageVersion: 16.2.3
```
This must match Control Panel.

2022-03-18 16:56 UTC, ItzLevvie commented on manifests/v/VMware/WorkstationPro/16.2.3.21887/VMware.WorkstationPro.yaml
> +PackageVersion: 16.2.3.21887
```suggestion
PackageVersion: 16.2.3
```
This must match Control Panel.

2022-03-18 16:56 UTC, ItzLevvie commented on manifests/v/VMware/WorkstationPro/16.2.3.21887/VMware.WorkstationPro.installer.yaml
> +PackageVersion: 16.2.3.21887
You will also need to update the version folder from `16.2.3.21887` to `16.2.3`

2022-03-18 16:56 UTC, ItzLevvie commented on manifests/v/VMware/WorkstationPro/16.2.3.21887/VMware.WorkstationPro.locale.en-US.yaml
> +PackageVersion: 16.2.3.21887
You will also need to update the version folder from `16.2.3.21887` to `16.2.3`

2022-03-18 16:56 UTC, ItzLevvie commented on manifests/v/VMware/WorkstationPro/16.2.3.21887/VMware.WorkstationPro.yaml
> +PackageVersion: 16.2.3.21887
You will also need to update the version folder from `16.2.3.21887` to `16.2.3`

2022-03-18 16:57 UTC, ItzLevvie requested changes

2022-03-18 16:57 UTC, ItzLevvie commented on manifests/v/VMware/WorkstationPro/16.2.3.21887/VMware.WorkstationPro.installer.yaml
> +  ProductCode: '{13421077-BD32-4B28-96EA-354654CB7E0C}'
```suggestion
  ProductCode: '{9D6C87F1-2E07-4B8D-99D8-D00248F62D55}'
```

2022-03-19 07:00 UTC, denelon commented
/azp run

2022-03-19 13:58 UTC, ItzLevvie approved these changes

2022-03-20 20:42 UTC, virtualex-itv commented
Not sure why this fails validation. URL is correct.

2022-03-25 01:19 UTC, virtualex-itv commented
can someone please look at this and advise why it's failing.  this should be working.  thanks.

2022-03-27 16:46 UTC, denelon commented
Our "on-call" will take a look at this on Monday.

2022-03-30 19:30 UTC, virtualex-itv commented
@denelon - any updates?

2022-03-30 23:27 UTC, yao-msft commented
The internal installer scan service reported there may be potentially unwanted behavior detected in the installer. We have reached out to the team for investigation.

2022-04-01 15:03 UTC, ItzLevvie commented
@wingetbot run

2022-04-03 14:00 UTC, ItzLevvie commented
@wingetbot run

2022-04-03 22:29 UTC, virtualex-itv commented
someone needs to take a look at this manually to determine what the issue is.  The URL used in the package is indeed valid and is the direct link from VMware.  This is the same URL also used in the chocolatey package as well and there are no issues with that package.  Please advise.

2022-04-04 17:32 UTC, OfficialEsco commented
The issue is not the link, its that some wild AV Vendor have flagged it as PUP..

2022-04-15 17:58 UTC, ItzLevvie commented
@wingetbot run

If it errors out you will need to comment again so it doesn't automatically close the PR in 14 days.

This issue happens because there's an (or multiple) anti-virus software that has marked VMware's installers as a Potentially Unwanted Program (PUP) or Potentially Unwanted Application (PUA).

It's been an issue for previous VMware installers, and is a false positive. You can check out https://github.com/microsoft/winget-pkgs/pull/34577#event-5598809516 so you'll have to play the waiting game here.

2022-04-15 18:02 UTC, ItzLevvie commented
@wingetbot run

2022-04-16 14:26 UTC, ItzLevvie commented
@wingetbot run

2022-04-17 00:23 UTC, ItzLevvie commented
@wingetbot run

2022-04-18 14:28 UTC, ItzLevvie commented
@wingetbot run

2022-04-20 10:52 UTC, ItzLevvie commented
@wingetbot run

2022-04-25 14:30 UTC, ItzLevvie commented
@wingetbot run

2022-04-25 14:31 UTC, ItzLevvie commented
> this may need manual approval.

This won't be possible as the policies require apps to pass anti-virus tests.

2022-05-02 17:02 UTC, ItzLevvie commented
@wingetbot run

2022-05-02 22:22 UTC, virtualex-itv commented
please manually approve, there is nothing wrong with the package.  it has been tested as per documentation

2022-05-02 23:06 UTC, denelon commented
We are still getting a blocking detection in our automated scan.

2022-05-03 21:51 UTC, virtualex-itv commented
> We are still getting a blocking detection in our automated scan.

re-running the same failing automated scans is not going to correct/resolve the issue.  what can be done to address this manually?  I manage the same package on chocolatey and have zero issues with the URL or any blocking as the file is being pulled directing from the manufacturer site.

2022-05-03 22:06 UTC, denelon commented
The detection needs to be changed to a false positive, or the binary needs to have the detected code removed.

The automated scans are taking in the latest definitions for each run.

You can report a false positive at https://www.microsoft.com/wdsi/filesubmission

2022-05-12 16:26 UTC, ItzLevvie commented
@wingetbot run

2022-05-19 21:02 UTC, ItzLevvie commented
@wingetbot run

2022-05-22 14:01 UTC, ItzLevvie commented
@wingetbot run

2022-06-03 18:01 UTC, merged