New version: JetBrains.IntelliJIDEA.Community.EAP version 221.5080.9
microsoft/winget-pkgs pull request #54842
Opened 2022-03-18 18:19 UTC by vedantmgoyal2009

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [468](https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2005706454)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/54842)

2022-03-18 21:55 UTC, ItzLevvie requested changes

2022-03-18 21:55 UTC, ItzLevvie commented on manifests/j/JetBrains/IntelliJIDEA/Community/EAP/221.5080.9/JetBrains.IntelliJIDEA.Community.EAP.installer.yaml
> +  ProductCode: IntelliJ IDEA Community Edition 221.4906.8
```suggestion
  ProductCode: IntelliJ IDEA Community Edition 221.5080.9
```

2022-03-19 07:02 UTC, denelon commented
/azp run

2022-03-19 12:12 UTC, ImJoakim approved these changes

2022-03-19 14:51 UTC, merged