CiderCollective.Cider.Nightly version 1.3.1481
microsoft/winget-pkgs pull request #54995
Opened 2022-03-19 11:35 UTC by yazninja

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-03-19 13:53 UTC, ItzLevvie approved these changes

2022-03-19 13:53 UTC, ItzLevvie commented on manifests/c/CiderCollective/Cider/Nightly/1.3.1481/CiderCollective.Cider.Nightly.installer.yaml
> +  Architecture: x86
```suggestion
  Architecture: x64
```

2022-03-19 19:18 UTC, Trenly requested changes
I think Levvie meant to request changes
![image](https://user-images.githubusercontent.com/12611259/159135363-bf973778-3bb6-4b70-b0f2-08f222c984ca.png)

2022-03-20 04:20 UTC, yazninja commented
My bad it went back to x32

2022-03-20 04:20 UTC, closed without merging