MEGALimited.MEGAcmd version 1.5.0.0
microsoft/winget-pkgs pull request #55683
Opened 2022-03-25 08:56 UTC by MatyiFKBT

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-03-25 13:12 UTC, ItzLevvie requested changes

2022-03-25 13:12 UTC, ItzLevvie commented on manifests/m/MEGALimited/MEGAcmd/1.5.0.0/MEGALimited.MEGAcmd.locale.en-US.yaml
> +ShortDescription: MEGAcmd
```suggestion
ShortDescription: MEGAcmd provides non UI access to MEGA services. It intends to offer all the functionality with your MEGA account via commands.
```

2022-03-25 13:12 UTC, ItzLevvie commented on manifests/m/MEGALimited/MEGAcmd/1.5.0.0/MEGALimited.MEGAcmd.locale.en-US.yaml
> +PackageIdentifier: MEGALimited.MEGAcmd
```suggestion
PackageIdentifier: MEGA.MEGAcmd
```

2022-03-25 13:12 UTC, ItzLevvie commented on manifests/m/MEGALimited/MEGAcmd/1.5.0.0/MEGALimited.MEGAcmd.installer.yaml
> +PackageIdentifier: MEGALimited.MEGAcmd
```suggestion
PackageIdentifier: MEGA.MEGAcmd
```

2022-03-25 13:12 UTC, ItzLevvie commented on manifests/m/MEGALimited/MEGAcmd/1.5.0.0/MEGALimited.MEGAcmd.yaml
> +PackageIdentifier: MEGALimited.MEGAcmd
```suggestion
PackageIdentifier: MEGA.MEGAcmd
```

2022-03-25 13:12 UTC, ItzLevvie commented on manifests/m/MEGALimited/MEGAcmd/1.5.0.0/MEGALimited.MEGAcmd.yaml
> +PackageIdentifier: MEGALimited.MEGAcmd
You will also need to update the folder from `MEGALimited` to `MEGA`.

2022-03-25 13:12 UTC, ItzLevvie commented on manifests/m/MEGALimited/MEGAcmd/1.5.0.0/MEGALimited.MEGAcmd.locale.en-US.yaml
> +PackageIdentifier: MEGALimited.MEGAcmd
You will also need to update the folder from `MEGALimited` to `MEGA`.

2022-03-25 13:12 UTC, ItzLevvie commented on manifests/m/MEGALimited/MEGAcmd/1.5.0.0/MEGALimited.MEGAcmd.locale.en-US.yaml
> +Publisher: MEGA Limited
```suggestion
Publisher: Mega Limited
```
This must match Control Panel.

2022-03-25 13:12 UTC, ItzLevvie commented on manifests/m/MEGALimited/MEGAcmd/1.5.0.0/MEGALimited.MEGAcmd.installer.yaml
> +PackageIdentifier: MEGALimited.MEGAcmd
You will also need to update the folder from `MEGALimited` to `MEGA`.

2022-04-01 15:24 UTC, ItzLevvie commented
@wingetbot run

2022-04-03 14:00 UTC, ItzLevvie commented
@wingetbot run

2022-04-03 14:43 UTC, MatyiFKBT commented
@ItzLevvie is validation failing because I missed one of the edits?

2022-04-03 14:47 UTC, ItzLevvie requested changes
> @ItzLevvie is validation failing because I missed one of the edits?

No.

It's flagged by anti-virus software.

2022-04-05 23:41 UTC, ItzLevvie commented
@wingetbot run

2022-04-06 13:02 UTC, ItzLevvie commented
@wingetbot run

2022-04-07 19:15 UTC, ItzLevvie commented
@wingetbot run

2022-04-09 14:07 UTC, ItzLevvie commented
@wingetbot run

2022-04-10 16:09 UTC, ItzLevvie commented
@wingetbot run

2022-04-11 12:03 UTC, closed without merging