HERE.OLPCLI version 10.5.106
microsoft/winget-pkgs pull request #56376
Opened 2022-03-31 13:15 UTC by ksen0byte

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/56376)

2022-03-31 13:35 UTC, ItzLevvie requested changes

2022-03-31 13:35 UTC, ItzLevvie commented on manifests/h/HERE/OLPCLI/0.0.0/HERE.OLPCLI.installer.yaml
> +PackageVersion: 0.0.0
```suggestion
PackageVersion: 10.5.106
```
This must match Control Panel.

2022-03-31 13:35 UTC, ItzLevvie commented on manifests/h/HERE/OLPCLI/0.0.0/HERE.OLPCLI.locale.en-US.yaml
> +PackageVersion: 0.0.0
```suggestion
PackageVersion: 10.5.106
```
This must match Control Panel.

2022-03-31 13:35 UTC, ItzLevvie commented on manifests/h/HERE/OLPCLI/0.0.0/HERE.OLPCLI.yaml
> +PackageVersion: 0.0.0
```suggestion
PackageVersion: 10.5.106
```
This must match Control Panel.

2022-03-31 13:38 UTC, ItzLevvie requested changes
You will also need to update the version folder from `0.0.0` to `10.5.106` using Visual Studio Online by pressing the `.`  (dot) on your keyboard on this PR.

2022-03-31 13:49 UTC, ItzLevvie approved these changes

2022-04-01 18:18 UTC, ItzLevvie commented
Wait for an engineer to take a look.

2022-04-02 03:44 UTC, Trenly requested changes

2022-04-02 03:44 UTC, Trenly commented on manifests/h/HERE/OLPCLI/10.5.106/HERE.OLPCLI.locale.en-US.yaml
> +License: Copyright (C) 2017-2022 HERE Global B.V. and its affiliate(s).
A copyright is not a license. Please move this to the `Copyright` field and provide a valid license

2022-04-04 17:40 UTC, ryfu-msft commented
@wingetbot waivers Add Validation-Executable-Error

2022-04-04 18:14 UTC, merged