New version: wethat.onenotetaggingkit version 4.0.8132
microsoft/winget-pkgs pull request #57124
Opened 2022-04-07 23:20 UTC by vedantmgoyal2009

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [936](https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2112033463)

2022-04-08 08:56 UTC, OfficialEsco requested changes
Duplicate of https://github.com/microsoft/winget-pkgs/pull/57099

2022-04-08 08:56 UTC, OfficialEsco commented on manifests/w/wethat/onenotetaggingkit/4.0.8132/wethat.onenotetaggingkit.installer.yaml
> +PackageVersion: 4.0.8132
```suggestion
PackageVersion: 4.0.8132.30888
```

2022-04-10 16:11 UTC, ItzLevvie requested changes

2022-04-10 16:11 UTC, ItzLevvie commented on manifests/w/wethat/onenotetaggingkit/4.0.8132/wethat.onenotetaggingkit.locale.en-US.yaml
> +PackageVersion: 4.0.8132
```suggestion
PackageVersion: 4.0.8132.30888
```

2022-04-10 16:11 UTC, ItzLevvie commented on manifests/w/wethat/onenotetaggingkit/4.0.8132/wethat.onenotetaggingkit.yaml
> +PackageVersion: 4.0.8132
```suggestion
PackageVersion: 4.0.8132.30888
```

2022-04-12 14:01 UTC, ItzLevvie approved these changes

2022-04-12 19:32 UTC, closed without merging