New version: wethat.onenotetaggingkit version 4.0.30319
microsoft/winget-pkgs pull request #57276
Opened 2022-04-09 20:20 UTC by vedantmgoyal2009

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [979](https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2141737883)

2022-04-10 16:10 UTC, ItzLevvie requested changes

2022-04-10 16:10 UTC, ItzLevvie commented on manifests/w/wethat/onenotetaggingkit/4.0.30319/wethat.onenotetaggingkit.locale.en-US.yaml
> +PackageVersion: 4.0.30319
```suggestion
PackageVersion: 4.0.8134.39795
```

2022-04-10 16:10 UTC, ItzLevvie commented on manifests/w/wethat/onenotetaggingkit/4.0.30319/wethat.onenotetaggingkit.installer.yaml
> +PackageVersion: 4.0.30319
```suggestion
PackageVersion: 4.0.8134.39795
```

2022-04-10 16:10 UTC, ItzLevvie commented on manifests/w/wethat/onenotetaggingkit/4.0.30319/wethat.onenotetaggingkit.yaml
> +PackageVersion: 4.0.30319
```suggestion
PackageVersion: 4.0.8134.39795
```

2022-04-10 16:10 UTC, ItzLevvie commented on manifests/w/wethat/onenotetaggingkit/4.0.30319/wethat.onenotetaggingkit.locale.en-US.yaml
> +PackageVersion: 4.0.30319
to match ARP.

2022-04-10 16:10 UTC, ItzLevvie commented on manifests/w/wethat/onenotetaggingkit/4.0.30319/wethat.onenotetaggingkit.installer.yaml
> +PackageVersion: 4.0.30319
to match ARP.

2022-04-10 16:10 UTC, ItzLevvie commented on manifests/w/wethat/onenotetaggingkit/4.0.30319/wethat.onenotetaggingkit.yaml
> +PackageVersion: 4.0.30319
to match ARP.

2022-04-11 12:20 UTC, OfficialEsco approved these changes

2022-04-11 12:50 UTC, ghost approved these changes

2022-04-11 12:51 UTC, merged