SyncTERM.SyncTERM version 1.1
microsoft/winget-pkgs pull request #57469
Opened 2022-04-12 15:27 UTC by markandpreston123

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-04-12 15:45 UTC, Trenly requested changes
`idk` is not a valid license

Please update it with the information from their SourceForge page
![image](https://user-images.githubusercontent.com/12611259/163001628-545c9a57-83a4-45bd-8211-1b446e14d348.png)

2022-04-12 15:45 UTC, Trenly commented on manifests/s/SyncTERM/SyncTERM/1.1/SyncTERM.SyncTERM.locale.en-US.yaml
> +License: idk
```suggestion
License: GPLv2
```

2022-04-12 17:50 UTC, ItzLevvie requested changes

2022-04-12 17:50 UTC, ItzLevvie commented on manifests/s/SyncTERM/SyncTERM/1.1/SyncTERM.SyncTERM.locale.en-US.yaml
> +License: GPLv2
```suggestion
License: GPL-2.0
```
to match SPDX.

2022-04-12 17:50 UTC, ItzLevvie commented on manifests/s/SyncTERM/SyncTERM/1.1/SyncTERM.SyncTERM.installer.yaml
> +  InstallerUrl: https://netix.dl.sourceforge.net/project/syncterm/syncterm/syncterm-1.1/SyncTERM-1.1-setup.exe
```suggestion
  InstallerUrl: https://sourceforge.net/projects/syncterm/files/syncterm/syncterm-1.1/SyncTERM-1.1-setup.exe/download
```

2022-04-15 20:18 UTC, lechacon commented
The URL from sourceforge looks good. We can add the waiver for Unapproved-URL, but I'll wait as the URI may change as per @ItzLevvie 's suggestion.

2022-04-24 15:59 UTC, closed without merging