New version: DigiDNA.iMazing version 2.14.7
microsoft/winget-pkgs pull request #57488
Opened 2022-04-12 18:45 UTC by vedantmgoyal2009

#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [1044](https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2156882145)

2022-04-12 19:03 UTC, ItzLevvie commented
@wingetbot run

2022-04-12 19:11 UTC, ItzLevvie commented
@wingetbot run

2022-04-12 19:19 UTC, ItzLevvie requested changes

2022-04-12 19:19 UTC, ItzLevvie commented on manifests/d/DigiDNA/iMazing/2.14.7/DigiDNA.iMazing.locale.en-US.yaml
> +PackageVersion: 2.14.7
```suggestion
PackageVersion: 2.14.7.0
```

2022-04-12 19:19 UTC, ItzLevvie commented on manifests/d/DigiDNA/iMazing/2.14.7/DigiDNA.iMazing.locale.zh-CN.yaml
> +PackageVersion: 2.14.7
```suggestion
PackageVersion: 2.14.7.0
```

2022-04-12 19:19 UTC, ItzLevvie commented on manifests/d/DigiDNA/iMazing/2.14.7/DigiDNA.iMazing.yaml
> +PackageVersion: 2.14.7
```suggestion
PackageVersion: 2.14.7.0
```

2022-04-12 19:55 UTC, ItzLevvie approved these changes

2022-04-12 20:00 UTC, ItzLevvie commented
@wingetbot run

2022-04-12 23:45 UTC, ItzLevvie commented
@wingetbot run

2022-04-13 16:36 UTC, zachcarp commented
This is one of three that keep failing for internal failures. I'll pull the logs later today and see if I can figure out whats going wrong.

2022-04-13 23:42 UTC, zachcarp commented
@vedantmgoyal2009 This is an internal failure. An upstream team sent us an unexpected value that we attempted to parse into an enumeration which failed. We are currently working on a fix for this. We will also build measures to help avoid this in the future.

2022-04-15 17:59 UTC, ItzLevvie commented
@wingetbot run

2022-04-15 18:33 UTC, merged