Added DataGrip version 221.5591.9.
microsoft/winget-pkgs pull request #58906
Opened 2022-04-27 19:01 UTC by jedieaston

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

2022-04-27 19:54 UTC, ItzLevvie requested changes

2022-04-27 19:54 UTC, ItzLevvie commented on manifests/j/JetBrains/DataGrip/221.5591.9/JetBrains.DataGrip.installer.yaml
> +  ProductCode: DataGrip 2022.1.1
```suggestion
  ProductCode: DataGrip 2022.1.2
```

2022-04-27 20:55 UTC, jedieaston commented
I fixed it and didn't push it, sorry.

2022-04-28 02:05 UTC, ItzLevvie approved these changes

2022-04-28 04:02 UTC, merged