Version 2.37
microsoft/winget-pkgs pull request #59323
Opened 2022-05-01 17:15 UTC by NickeManarin

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-05-01 18:11 UTC, Trenly requested changes

2022-05-01 18:11 UTC, Trenly commented on manifests/n/NickeManarin/ScreenToGif/2.37.0/NickeManarin.ScreenToGif.installer.yaml
> +PackageVersion: 2.37.0
```suggestion
PackageVersion: 2.37
```
This should match control panel

2022-05-01 18:11 UTC, Trenly commented on manifests/n/NickeManarin/ScreenToGif/2.37.0/NickeManarin.ScreenToGif.locale.en-US.yaml
> +PackageVersion: 2.37.0
```suggestion
PackageVersion: 2.37
```
This should match control panel

2022-05-01 18:11 UTC, Trenly commented on manifests/n/NickeManarin/ScreenToGif/2.37.0/NickeManarin.ScreenToGif.locale.pt-BR.yaml
> +PackageVersion: 2.37.0
```suggestion
PackageVersion: 2.37
```
This should match control panel

2022-05-01 18:11 UTC, Trenly commented on manifests/n/NickeManarin/ScreenToGif/2.37.0/NickeManarin.ScreenToGif.yaml
> +PackageVersion: 2.37.0
```suggestion
PackageVersion: 2.37
```
This should match control panel

2022-05-03 02:17 UTC, ItzLevvie submitted a review, later dismissed

2022-05-03 03:48 UTC, vedantmgoyal2009 requested changes
Update version folder too.

2022-05-03 18:36 UTC, jedieaston commented
Hot tip to change the folder name: Press "." on your keyboard when you have GitHub open to this PR in your browser, and a web version of VSCode will launch.
 
 Once it loads, find the files you added, and rename the folder. Then use the source control button on the left to commit (it's automatically pushed).
 
 <img alt="image" width="268" src="https://user-images.githubusercontent.com/21368066/136942061-26715615-b675-4868-ae65-0ecfe1da6b0e.png">

2022-05-03 19:27 UTC, NickeManarin commented
@jedieaston Oh, I did but I forgot to push the changes after the commit. :(

2022-05-03 19:41 UTC, ItzLevvie2 approved these changes

2022-05-03 19:43 UTC, ItzLevvie approved these changes

2022-05-03 20:05 UTC, merged