Slik.Subversion version 1.14.2001
microsoft/winget-pkgs pull request #59580
Opened 2022-05-05 08:17 UTC by rhuijben

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-05-05 09:08 UTC, rhuijben commented
Looks like a transient failure
`Exception Message: Cannot get DNS address for host 'winget-pme.azurefd.net' (No such host is known). (type TeamFoundationServerException)`

2022-05-05 09:10 UTC, rhuijben commented
/AzurePipelines run

2022-05-05 13:19 UTC, rhuijben commented
Pushed exactly the same commit with a new timestamp, to retry validation.

2022-05-05 14:11 UTC, Trenly requested changes

2022-05-05 14:11 UTC, Trenly commented on manifests/s/Slik/Subversion/1.14.2001/Slik.Subversion.locale.en-US.yaml
> +ShortDescription: Subversion Client
Please provide a better description

2022-05-06 14:15 UTC, ItzLevvie requested changes

2022-05-06 14:15 UTC, ItzLevvie commented on manifests/s/Slik/Subversion/1.14.2001/Slik.Subversion.locale.en-US.yaml
> +PackageName: Subversion 1.14.2
```suggestion
PackageName: Slik Subversion
```
to match Control Panel.

2022-05-06 14:16 UTC, ItzLevvie requested changes

2022-05-06 14:16 UTC, ItzLevvie commented on manifests/s/Slik/Subversion/1.14.2001/Slik.Subversion.locale.en-US.yaml
> +License: Apache-2
```suggestion
License: Apache-2.0
```

2022-05-06 18:03 UTC, ItzLevvie approved these changes

2022-05-06 18:33 UTC, merged