RevoUninstaller.RevoUninstallerPro version 5.0.1
microsoft/winget-pkgs pull request #60136
Opened 2022-05-11 17:10 UTC by tim-mann

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/60136)

2022-05-11 17:41 UTC, ItzLevvie requested changes

2022-05-11 17:41 UTC, ItzLevvie commented on manifests/r/RevoUninstaller/RevoUninstallerPro/5.0.1/RevoUninstaller.RevoUninstallerPro.installer.yaml
> +ManifestVersion: 1.1.0
```suggestion
PackageIdentifier: RevoUninstaller.RevoUninstallerPro
PackageVersion: 5.0.1
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://1baf5346ec1e2437e714-1959a2065c6dc5b4e5e9f6fa5eeb4840.ssl.cf1.rackcdn.com/RevoUninProSetup.exe
  InstallerSha256: 9F7AD647D126310E850D64F871776462FE359B530CE12CF9155E4E94DE71133A
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.1.0
```

2022-05-11 17:41 UTC, ItzLevvie commented on manifests/r/RevoUninstaller/RevoUninstallerPro/5.0.1/RevoUninstaller.RevoUninstallerPro.locale.en-US.yaml
> +ManifestVersion: 1.1.0
```suggestion
PackageIdentifier: RevoUninstaller.RevoUninstallerPro
PackageVersion: 5.0.1
PackageLocale: en-US
Publisher: VS Revo Group, Ltd.
PublisherUrl: https://www.revouninstaller.com
PublisherSupportUrl: https://www.revouninstaller.com/support
PrivacyUrl: https://www.revouninstaller.com/revo-uninstaller-privacy-policy
Author: VS Revo Group, Ltd.
PackageName: Revo Uninstaller Pro
PackageUrl: https://www.revouninstaller.com/products/revo-uninstaller-pro
License: Proprietary
LicenseUrl: https://www.revouninstaller.com/revo-uninstaller-pro-eula/
Copyright: Copyright VS Revo Group
CopyrightUrl: https://www.revouninstaller.com/revo-uninstaller-pro-eula/
ShortDescription: Revo Uninstaller helps you to uninstall software and remove unwanted programs easily.
Description: Revo Uninstaller is a freeware uninstall utility. It has powerful features to uninstall programs scanning for leftover files, folders and registry entries after uninstall. With its unique 'Hunter mode' it offers you some simple, easy to use but effective and powerful approaches to manage (uninstall, stop, delete, disable from auto starting) and to get information about your installed and/or running application. Many cleaning tools included!
Moniker: revo-pro
ReleaseNotesUrl: https://www.revouninstaller.com/revo-uninstaller-pro-full-version-history/
Tags:
- revo
- revo-uninstaller-pro
- cleaner
ManifestType: defaultLocale
ManifestVersion: 1.1.0
```

2022-05-11 17:43 UTC, tim-mann commented
The installer URL is from https://www.revouninstaller.com/revo-uninstaller-pro-full-version-history/

2022-05-11 17:48 UTC, ItzLevvie submitted a review, later dismissed

2022-05-11 18:18 UTC, tim-mann commented
The installer URL is from https://www.revouninstaller.com/revo-uninstaller-pro-full-version-history/

2022-05-11 22:12 UTC, ItzLevvie requested changes

2022-05-11 22:12 UTC, ItzLevvie commented on manifests/r/RevoUninstaller/RevoUninstallerPro/5.0.1/RevoUninstaller.RevoUninstallerPro.installer.yaml
> +  InstallerLocale: en-US
```suggestion
- InstallerLocale: en-US
```

2022-05-11 22:20 UTC, ItzLevvie approved these changes

2022-05-11 22:50 UTC, tim-mann commented
The installer URL is from https://www.revouninstaller.com/revo-uninstaller-pro-full-version-history/

2022-05-11 23:01 UTC, ItzLevvie commented
An engineer will take a look at this PR.

2022-05-12 00:28 UTC, hackean-msft commented
@wingetbot waivers Add Validation-No-Executables

2022-05-12 01:53 UTC, hackean-msft commented
@wingetbot waivers Add Validation-Domain

2022-05-12 02:27 UTC, merged