New version: JetBrains.Rider.EAP version 222.2270.26
microsoft/winget-pkgs pull request #61324
Opened 2022-05-19 18:38 UTC by vedantmgoyal2009

### Result: Installation Failed
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | JetBrains Rider (EAP) | CLion 222.2270.30    |
| Version     | 222.2270.26     | 222.2270.30 |
| Publisher   | JetBrains s.r.o.   | JetBrains s.r.o.      |
| ProductCode | JetBrains Rider 221.5080.72          | CLion 222.2270.30    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [1638](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2353815677>)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/61324)

2022-05-19 19:39 UTC, ItzLevvie requested changes

2022-05-19 19:39 UTC, ItzLevvie commented on manifests/j/JetBrains/Rider/EAP/222.2270.26/JetBrains.Rider.EAP.installer.yaml
> +  ProductCode: JetBrains Rider 221.5080.72
```suggestion
  ProductCode: JetBrains Rider 222.2270.26
```

2022-05-19 19:39 UTC, ItzLevvie approved these changes

2022-05-20 01:40 UTC, jedieaston approved these changes

2022-05-22 13:25 UTC, ItzLevvie commented
@wingetbot run

2022-05-22 14:33 UTC, merged