Add Spyglass 22.5.15
microsoft/winget-pkgs pull request #61989
Opened 2022-05-25 17:13 UTC by oparaskos

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/61989)

2022-05-26 16:08 UTC, ItzLevvie requested changes

2022-05-26 16:08 UTC, ItzLevvie commented on manifests/a/a5huynh/spyglass/2022.5.15/a5huynh.spyglass.locale.en-US.yaml
> +Publisher: Andrew Huynh
```suggestion
Publisher: athlabs
```
This must match Control Panel.

2022-05-26 16:08 UTC, ItzLevvie commented on manifests/a/a5huynh/spyglass/2022.5.15/a5huynh.spyglass.installer.yaml
> +PackageVersion: 2022.5.15
```suggestion
PackageVersion: 22.5.15
```
This must match Control Panel.

2022-05-26 16:08 UTC, ItzLevvie commented on manifests/a/a5huynh/spyglass/2022.5.15/a5huynh.spyglass.locale.en-US.yaml
> +PackageVersion: 2022.5.15
```suggestion
PackageVersion: 22.5.15
```
This must match Control Panel.

2022-05-26 16:08 UTC, ItzLevvie commented on manifests/a/a5huynh/spyglass/2022.5.15/a5huynh.spyglass.yaml
> +PackageVersion: 2022.5.15
```suggestion
PackageVersion: 22.5.15
```
This must match Control Panel.

2022-05-29 12:36 UTC, KaranKad requested changes

2022-05-29 12:36 UTC, KaranKad commented on manifests/a/a5huynh/spyglass/2022.5.15/a5huynh.spyglass.yaml
> +PackageIdentifier: a5huynh.spyglass
```suggestion
PackageIdentifier: athlabs.spyglass
```

2022-05-29 12:36 UTC, KaranKad commented on manifests/a/a5huynh/spyglass/2022.5.15/a5huynh.spyglass.installer.yaml
> +PackageIdentifier: a5huynh.spyglass
```suggestion
PackageIdentifier: athlabs.spyglass
```

Also modify the file name and folder name to match it.

2022-05-29 12:36 UTC, KaranKad commented on manifests/a/a5huynh/spyglass/2022.5.15/a5huynh.spyglass.installer.yaml
> +  SilentWithProgress: /qb
```suggestion
```

Switches are unnecessary

2022-05-29 12:36 UTC, KaranKad commented on manifests/a/a5huynh/spyglass/2022.5.15/a5huynh.spyglass.locale.en-US.yaml
> +PackageIdentifier: a5huynh.spyglass
```suggestion
PackageIdentifier: athlabs.spyglass
```

2022-05-29 12:36 UTC, KaranKad commented on manifests/a/a5huynh/spyglass/2022.5.15/a5huynh.spyglass.locale.en-US.yaml
> +Description: Spyglass is very much in its early stages, but it’s in a place where it's functional and can be used to replace basic searches. Spyglass is an entirely local and configurable search engi
```suggestion
```

2022-05-29 12:36 UTC, KaranKad commented on manifests/a/a5huynh/spyglass/2022.5.15/a5huynh.spyglass.locale.en-US.yaml
> +- lenses
```suggestion
```
These tags don't make sense

2022-06-06 08:24 UTC, oparaskos commented
> Hello @oparaskos,
> This pull request has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.

Boop

2022-06-06 11:30 UTC, ItzLevvie requested changes
Needs changes: https://github.com/microsoft/winget-pkgs/pull/61989#issuecomment-1147184398

2022-06-11 21:07 UTC, closed without merging

2022-06-12 09:40 UTC, KaranKad commented
I've created a new pr at https://github.com/microsoft/winget-pkgs/pull/63378