ashisoft.dff version 8.1.0.1
microsoft/winget-pkgs pull request #62276
Opened 2022-05-29 17:40 UTC by mqdb

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-05-29 18:41 UTC, KaranKad requested changes

2022-05-29 18:41 UTC, KaranKad commented on manifests/a/ashisoft/dff/8.1.0.1/ashisoft.dff.locale.en-US.yaml
> +ShortDescription: Duplicate File Finder Setup
```suggestion
ShortDescription: Duplicate File Finder is a powerful application that uses intelligent algorithms to identify all types of duplicate files.
```
Proper description of the application.

2022-05-29 18:41 UTC, KaranKad commented on manifests/a/ashisoft/dff/8.1.0.1/ashisoft.dff.locale.en-US.yaml
> +PackageIdentifier: ashisoft.dff
```suggestion
PackageIdentifier: Ashisoft.DuplicateFileFinder
```
Edit filename and foldername as well.

2022-05-29 18:41 UTC, KaranKad commented on manifests/a/ashisoft/dff/8.1.0.1/ashisoft.dff.installer.yaml
> +PackageIdentifier: ashisoft.dff
```suggestion
PackageIdentifier: Ashisoft.DuplicateFileFinder
```
Edit filename and foldername as well.

2022-05-29 18:41 UTC, KaranKad commented on manifests/a/ashisoft/dff/8.1.0.1/ashisoft.dff.yaml
> +PackageIdentifier: ashisoft.dff
```suggestion
PackageIdentifier: Ashisoft.DuplicateFileFinder
```
Edit filename and foldername as well.

2022-06-01 00:19 UTC, ItzLevvie approved these changes, later dismissed

2022-06-01 03:45 UTC, mqdb reviewed
Is there anything else? I used the shortened version as Ashisoft had.

2022-06-01 04:08 UTC, Trenly commented
> Is there anything else? I used the shortened version as Ashisoft had.

You will need to change the name of the folders so that the manifest files are in the directory `manifests\a\Ashisoft\DuplicateFileFinder\8.1.0.1`

2022-06-01 14:49 UTC, ItzLevvie approved these changes

2022-06-08 22:27 UTC, mqdb reviewed
I'm okay with these changes.

2022-06-08 22:53 UTC, ItzLevvie requested changes
@mqdb: Looks like you need to rename the folder and file names to match the PackageIdentifier.

`ashisoft` to `Ashisoft`
`dff` to `DuplicateFileFinder`

2022-06-09 04:50 UTC, mqdb commented
> @mqdb: Looks like you need to rename the folder and file names to match the PackageIdentifier.
> 
> `ashisoft` to `Ashisoft` `dff` to `DuplicateFileFinder`

I am not sure I see a simple way to do this. Is there somewhere I would find a file manager, or is the suggestion that I just resubmit the whole thing. The latter seems like it would be easier

2022-06-09 12:11 UTC, Trenly commented
> > @mqdb: Looks like you need to rename the folder and file names to match the PackageIdentifier.
> > `ashisoft` to `Ashisoft` `dff` to `DuplicateFileFinder`
> 
> I am not sure I see a simple way to do this. Is there somewhere I would find a file manager, or is the suggestion that I just resubmit the whole thing. The latter seems like it would be easier

If you presss `.` while on this screen it will bring up an editor

2022-06-25 15:40 UTC, ItzLevvie requested changes
https://github.com/microsoft/winget-pkgs/pull/62276#issuecomment-1151042918

2022-06-27 21:54 UTC, closed without merging