warpdesign.react-explorer version 2.3.1
microsoft/winget-pkgs pull request #62896
Opened 2022-06-05 14:16 UTC by oxygen-dioxide

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-06-05 18:05 UTC, KaranKad requested changes

2022-06-05 18:05 UTC, KaranKad commented on manifests/w/warpdesign/react-explorer/2.3.1/warpdesign.react-explorer.installer.yaml
> +PackageIdentifier: warpdesign.react-explorer
```suggestion
PackageIdentifier: NicolasRamz.React-Explorer
```
I suggest using installer provided names instead of github names.

2022-06-05 18:05 UTC, KaranKad commented on manifests/w/warpdesign/react-explorer/2.3.1/warpdesign.react-explorer.locale.en-US.yaml
> +PackageIdentifier: warpdesign.react-explorer
```suggestion
PackageIdentifier: NicolasRamz.React-Explorer
```

2022-06-05 18:05 UTC, KaranKad commented on manifests/w/warpdesign/react-explorer/2.3.1/warpdesign.react-explorer.locale.en-US.yaml
> +Author: warpdesign
```suggestion
Author: Nicolas Ramz
```

2022-06-05 18:05 UTC, KaranKad commented on manifests/w/warpdesign/react-explorer/2.3.1/warpdesign.react-explorer.locale.en-US.yaml
> +ShortDescription: Plugin-based file explorer written with React
```suggestion
ShortDescription: Plugin-based file explorer written with React.
```

2022-06-05 18:05 UTC, KaranKad commented on manifests/w/warpdesign/react-explorer/2.3.1/warpdesign.react-explorer.yaml
> +PackageIdentifier: warpdesign.react-explorer
```suggestion
PackageIdentifier: NicolasRamz.React-Explorer
```

2022-06-08 12:07 UTC, ItzLevvie submitted a review, later dismissed

2022-06-09 10:33 UTC, KaranKad approved these changes

2022-06-09 10:34 UTC, merged