Added Cygwin
microsoft/winget-pkgs pull request #63513
Opened 2022-06-13 23:57 UTC by licon4812

- [ yes ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ yes ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ yes ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ yes ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ yes ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-06-14 15:52 UTC, ItzLevvie requested changes

2022-06-14 15:52 UTC, ItzLevvie commented on manifests/c/Cygwin/Cygwin/3.3.4/Cygwin.Cygwin.installer.yaml
> +PackageVersion: 3.3.4
```suggestion
PackageVersion: 3.3.5
```
Output shows that it installs 3.3.5? You will also have to update the package version folder from `3.3.4` to `3.3.5`
```
Augmented Transaction List:
   [...]
   1 install cygwin          3.3.5-1
   [...]
```

2022-06-14 15:52 UTC, ItzLevvie commented on manifests/c/Cygwin/Cygwin/3.3.4/Cygwin.Cygwin.locale.en-US.yaml
> +PackageVersion: 3.3.4
```suggestion
PackageVersion: 3.3.5
```
Output shows that it installs 3.3.5? You will also have to update the package version folder from `3.3.4` to `3.3.5`
```
Augmented Transaction List:
   [...]
   1 install cygwin          3.3.5-1
   [...]
```

2022-06-14 15:52 UTC, ItzLevvie commented on manifests/c/Cygwin/Cygwin/3.3.4/Cygwin.Cygwin.yaml
> +PackageVersion: 3.3.4
```suggestion
PackageVersion: 3.3.5
```
Output shows that it installs 3.3.5? You will also have to update the package version folder from `3.3.4` to `3.3.5`
```
Augmented Transaction List:
   [...]
   1 install cygwin          3.3.5-1
   [...]
```

2022-06-14 20:55 UTC, licon4812 commented
@ItzLevvie  since this download location changes when a new version is released would we be able to get the update process done automatically whenever they change the installer at that location?

2022-06-15 11:01 UTC, ItzLevvie approved these changes

2022-06-15 11:08 UTC, merged