Bluesound.BluOSController version 3.18.2
microsoft/winget-pkgs pull request #64506
Opened 2022-06-27 10:23 UTC by TaekeK

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-06-27 13:17 UTC, ItzLevvie requested changes

2022-06-27 13:17 UTC, ItzLevvie commented on manifests/b/Bluesound/BluOSController/3.18.2/Bluesound.BluOSController.locale.en-US.yaml
> +ShortDescription: BluOS Controller
```suggestion
ShortDescription: BluOS Controller for Windows upgrades the user experience with a high-resolution 4K interface, powerful new features, and a seamless music experience across all devices. 
```

2022-07-01 11:10 UTC, ItzLevvie commented
cc @TaekeK

2022-07-01 16:07 UTC, Trenly approved these changes
Testing that this doesn't get merged while waiting for feedback

2022-07-05 18:39 UTC, closed without merging