New version: InfiniteInstant.KoduGameLab version 1.6.12.0
microsoft/winget-pkgs pull request #65538
Opened 2022-07-09 12:32 UTC by mdanish-kh

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-07-09 14:25 UTC, Trenly requested changes
The PackageVersion must match control panel; When updating this, you will need to update the name of the version folder also. You can do this in GitHub web by pressing <kbd>.</kbd>

2022-07-09 14:25 UTC, Trenly commented on manifests/i/InfiniteInstant/KoduGameLab/1.6.12.0/InfiniteInstant.KoduGameLab.locale.en-US.yaml
> +LicenseUrl: https://github.com/scoy/KoduGameLab/blob/main/LICENSE.TXT
```suggestion
License: Proprietary
LicenseUrl: https://www.kodugamelab.com/EULA
```
License for the code is not the same as the package License

2022-07-09 14:25 UTC, Trenly commented on manifests/i/InfiniteInstant/KoduGameLab/1.6.12.0/InfiniteInstant.KoduGameLab.locale.en-US.yaml
> +PackageVersion: 1.6.12.0
```suggestion
PackageVersion: 1.6.12
```

2022-07-09 14:25 UTC, Trenly commented on manifests/i/InfiniteInstant/KoduGameLab/1.6.12.0/InfiniteInstant.KoduGameLab.installer.yaml
> +PackageVersion: 1.6.12.0
```suggestion
PackageVersion: 1.6.12
```

2022-07-09 14:25 UTC, Trenly commented on manifests/i/InfiniteInstant/KoduGameLab/1.6.12.0/InfiniteInstant.KoduGameLab.yaml
> +PackageVersion: 1.6.12.0
```suggestion
PackageVersion: 1.6.12
```

2022-07-09 14:25 UTC, Trenly commented on manifests/i/InfiniteInstant/KoduGameLab/1.6.12.0/InfiniteInstant.KoduGameLab.locale.en-US.yaml
> +PackageName: Kodu
```suggestion
PackageName: Kodu Game Lab
```
Must match control panel

2022-07-10 12:01 UTC, OfficialEsco approved these changes

2022-07-10 12:04 UTC, merged