MindsetInnovationInc.Enowork version 1.0.7
microsoft/winget-pkgs pull request #65601
Opened 2022-07-11 05:03 UTC by SIDNut

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-07-11 13:17 UTC, Trenly requested changes

2022-07-11 13:17 UTC, Trenly commented on manifests/m/MindsetInnovationInc/Enowork/1.0.7/MindsetInnovationInc.Enowork.locale.en-US.yaml
> +PackageName: Enowork
```suggestion
PackageName: Eno
```
This must match control panel

2022-07-13 11:19 UTC, ItzLevvie requested changes
See https://github.com/microsoft/winget-pkgs/pull/65601#pullrequestreview-1034320571

2022-07-18 14:24 UTC, OfficialEsco approved these changes

2022-07-18 14:24 UTC, merged