Update eduVPN to 3.2
microsoft/winget-pkgs pull request #66200
Opened 2022-07-13 14:00 UTC by rozmansi

Signed-off-by: Simon Rozman <simon@rozman.si>

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-07-13 17:46 UTC, hackean-msft commented
/azp run

2022-07-13 18:26 UTC, Trenly requested changes

2022-07-13 18:26 UTC, Trenly commented on manifests/s/SURF/eduVPNClient/3.2/SURF.eduVPNClient.installer.yaml
> +  ProductCode: '{8835FB7C-99C2-426F-9200-3D866F62A1D6}'
```suggestion
  AppsAndFeaturesEntries:
  - ProductCode: '{8835FB7C-99C2-426F-9200-3D866F62A1D6}'
    DisplayName: eduVPN Client 3.2 ARM64
    UpgradeCode: '{02EBD828-2565-4BCD-ABFF-E3F48C3F9A23}'
```

2022-07-13 18:26 UTC, Trenly commented on manifests/s/SURF/eduVPNClient/3.2/SURF.eduVPNClient.installer.yaml
> +  ProductCode: '{8835FB7C-99C2-426F-9200-3D866F62A1D6}'
```suggestion
  AppsAndFeaturesEntries: 
  - ProductCode: '{8835FB7C-99C2-426F-9200-3D866F62A1D6}'
    DisplayName: eduVPN Client 3.2 x64
    UpgradeCode: '{02EBD828-2565-4BCD-ABFF-E3F48C3F9A23}'
```

2022-07-13 18:26 UTC, Trenly commented on manifests/s/SURF/eduVPNClient/3.2/SURF.eduVPNClient.installer.yaml
> +  ProductCode: '{8835FB7C-99C2-426F-9200-3D866F62A1D6}'
```suggestion
  AppsAndFeaturesEntries: 
  - ProductCode: '{8835FB7C-99C2-426F-9200-3D866F62A1D6}'
    DisplayName: eduVPN Client 3.2 x86
    UpgradeCode: '{E3746042-5041-4E2F-83E8-0240EF3C60CA}'
```

2022-07-14 20:15 UTC, ItzLevvie approved these changes

2022-07-14 20:47 UTC, merged