New version: Bitnami.WAMP version 8.1.7-1
microsoft/winget-pkgs pull request #66325
Opened 2022-07-14 12:45 UTC by russellbanks

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

2022-07-14 12:48 UTC, ItzLevvie approved these changes

2022-07-22 23:49 UTC, OfficialEsco commented
@denelon it appears this one failed because it didn't give it enough time to install
![InstallationVerification-x64-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20220714133806](https://user-images.githubusercontent.com/15158490/180581346-73f8fced-e058-46ab-b3df-e3c8b036c393.png)

Probably the same with #66324 and #66323 if its the same installer

2022-07-25 23:24 UTC, yao-msft commented
By looking at the other 2 failures, both are stuck at launch time when "Allow network access type" window is popped for user input.
I guess this is related to `Custom: --launch_cloud 0` switch.

2022-07-31 15:10 UTC, ItzLevvie commented
@wingetbot run

2022-07-31 16:10 UTC, ItzLevvie requested changes

2022-07-31 16:10 UTC, ItzLevvie commented on manifests/b/Bitnami/WAMP/8.1.7-1/Bitnami.WAMP.installer.yaml
> +  InstallerSha256: A768518C9447DD9C9B7B9829CEB0B621CD195917A6A03DA4069682E3D29C6377
```suggestion
  InstallerSha256: A768518C9447DD9C9B7B9829CEB0B621CD195917A6A03DA4069682E3D29C6377
  AppsAndFeaturesEntries:
  - DisplayName: WAMP packaged by Bitnami
```

2022-07-31 16:13 UTC, ItzLevvie approved these changes

2022-07-31 17:52 UTC, merged