Mazerator 0.0.2
microsoft/winget-pkgs pull request #67363
Opened 2022-07-24 13:39 UTC by AwesomeKalin

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-07-25 02:20 UTC, hackean-msft commented
/azp run

2022-07-25 19:08 UTC, yao-msft commented
Hi @AwesomeKalin ,
Is it possible to use release links from https://github.com/MazeratorGame/Mazerator/releases for InstallerUrl? That will pass the Validation-Domain check.
Thanks

2022-07-27 23:55 UTC, ItzLevvie requested changes
See https://github.com/microsoft/winget-pkgs/pull/67363#issuecomment-1194500457

2022-07-29 00:56 UTC, ItzLevvie requested changes

2022-07-29 00:56 UTC, ItzLevvie commented on manifests/w/WaterbugStudios/Mazerator/0.0.2/WaterbugStudios.Mazerator.locale.en-US.yaml
> +Publisher: Waterbug Studios
```suggestion
Publisher: Waterbug Studios/Awesome Arcade
```
cc @AwesomeKalin: This must match Control Panel.

2022-07-31 13:47 UTC, ItzLevvie commented
Close with reason: Replaced by another PR;

2022-07-31 13:47 UTC, closed without merging