New Package: Schezo.Lhaplus
microsoft/winget-pkgs pull request #67638
Opened 2022-07-27 11:15 UTC by Kyure-A

- 

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-07-27 13:02 UTC, Kyure-A commented
What exactly is meant by "evidence" here?

2022-07-27 13:12 UTC, Kyure-A commented
The software is "redistributable as long as the archive file is not modified" as stated in this URL (http://www7a.biglobe.ne.jp/~schezo/ReadMe.txt).

Is the above text acceptable as "evidence"?

2022-07-27 23:59 UTC, ItzLevvie requested changes

2022-07-27 23:59 UTC, ItzLevvie commented on manifests/s/Schezo/Lhaplus/1.7.4.0/Schezo.Lhaplus.installer.yaml
> +  InstallerSha256: 142D8F2ED308EFE9E1DCB8657757D99848827C40A5199436EB36C53F2B9D40FE
```suggestion
  InstallerSha256: 142D8F2ED308EFE9E1DCB8657757D99848827C40A5199436EB36C53F2B9D40FE
  ProductCode: Lhaplus
```

2022-07-27 23:59 UTC, ItzLevvie commented on manifests/s/Schezo/Lhaplus/1.7.4.0/Schezo.Lhaplus.installer.yaml
> +  InstallerUrl: https://dforest.watch.impress.co.jp/library/l/lhaplus/10418/lpls174.exe
```suggestion
  InstallerUrl: http://www7a.biglobe.ne.jp/~schezo/lpls174.exe
```

2022-07-27 23:59 UTC, ItzLevvie commented on manifests/s/Schezo/Lhaplus/1.7.4.0/Schezo.Lhaplus.locale.en-US.yaml
> +License: http://www7a.biglobe.ne.jp/~schezo/ReadMe.txt
```suggestion
License: Proprietary
LicenseUrl: http://www7a.biglobe.ne.jp/~schezo/ReadMe.txt
PackageUrl: http://www7a.biglobe.ne.jp/~schezo/
```

2022-07-28 00:38 UTC, ItzLevvie approved these changes

2022-07-28 01:11 UTC, Kyure-A commented
why

2022-07-28 01:16 UTC, ItzLevvie commented
Wait for an engineer to take a look.

2022-07-28 01:18 UTC, Kyure-A commented
Thank you.

2022-07-28 18:23 UTC, yao-msft commented
@wingetbot waivers Add Validation-Domain

2022-07-28 18:56 UTC, merged