Add version: Cloudflare.cloudflared version 2022.6.1
microsoft/winget-pkgs pull request #67829
Opened 2022-07-28 20:03 UTC by mdanish-kh

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-07-28 23:22 UTC, ItzLevvie requested changes
cc @mdanish-kh: Looks like this is using the EXE installer instead of the MSI installer.

https://github.com/cloudflare/cloudflared/releases/download/2022.6.2/cloudflared-windows-amd64.msi

2022-07-29 00:09 UTC, mdanish-kh commented
> cc @mdanish-kh: Looks like this is using the EXE installer instead of the MSI installer.
> 
> https://github.com/cloudflare/cloudflared/releases/download/2022.6.2/cloudflared-windows-amd64.msi

:sigh: How did I overlook this

2022-07-29 00:57 UTC, ItzLevvie requested changes

2022-07-29 00:57 UTC, ItzLevvie commented on manifests/c/Cloudflare/cloudflared/2022.6.1/Cloudflare.cloudflared.installer.yaml
> +  InstallerSha256: F4BF3FF9692E2BE386B9D89509BA85F0C0D9717B341027F795F7806D9FA298DA
```suggestion
  InstallerSha256: F4BF3FF9692E2BE386B9D89509BA85F0C0D9717B341027F795F7806D9FA298DA
  ProductCode: "{35E5E858-9372-4449-BF73-1CD6F7267128}"
```
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{35E5E858-9372-4449-BF73-1CD6F7267128}`

2022-07-29 12:16 UTC, ItzLevvie approved these changes

2022-07-29 12:26 UTC, merged