New package: GoLang.Go.1.18 version 1.18.4
microsoft/winget-pkgs pull request #67898
Opened 2022-07-29 10:11 UTC by russellbanks

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

2022-07-29 10:48 UTC, jedieaston commented on manifests/g/GoLang/Go/1/18/1.18.4/GoLang.Go.1.18.locale.en-US.yaml
> +Moniker: go-1-18
Should the latest version just have the moniker `go` or `golang` or something? I think `winget install golang` should do something. If someone else disagrees, I'm all ears.

2022-07-29 10:49 UTC, jedieaston requested changes
Should the latest version just have the moniker `go` or `golang` or something? I think `winget install golang` should do something. If someone else disagrees, I'm all ears.

2022-07-29 10:56 UTC, russellbanks commented
> Should the latest version just have the moniker `go` or `golang` or something? I think `winget install golang` should do something. If someone else disagrees, I'm all ears.

Could do, but it would just mean having to change it every time there's a new channel so when Go 1.19 comes out, these packages would need updating to have the moniker of `go-1-18` again.

2022-07-29 19:26 UTC, jedieaston commented
@Trenly, @OfficialEsco, @ItzLevvie, thoughts?

2022-07-29 19:31 UTC, OfficialEsco commented
Is it that important atm? How far away is the feature to point to the latest version for a parent folder? How many people would prefer to just do `winget install golang` instead of just updating to the latest version via `winget upgrade`?

2022-07-29 19:43 UTC, jedieaston commented
Updating to the latest version won't be a thing if we split the PackageIdentifiers up by minor though, right? You'll get the latest patch but not the latest major/minor (which you could get around with `winget install golang`).

I'm guessing pointer packages are a while away, I haven't seen anything with a timeframe (although since it would probably be mostly work on the winget-pkgs service and not the CLI, the timeframe is not very public).

2022-07-29 20:58 UTC, OfficialEsco commented
From my point of view most people don't want to update to the latest major/minor version since they are working with a specific major/minor version, also we're causing more issues with installing side-by-side applications from the same package.

But if you want to keep an eye on the moniker for the versions so people can do `winget install golang`, go ahead, however i doubt  we'll get any complains about not getting the latest version by doing `winget install golang`, if we do then something that feature should be prioritized =)

2022-08-01 10:33 UTC, russellbanks commented
I think it's better to keep it as-is because this is how a lot of other packages are currently (`Groovy.2.5`, `Groovy.3`, `Groovy.4`, `RubyInstallerTeam.3.1`, etc) and as OfficialEsco has said, the feature to point to the latest version is coming

2022-08-01 12:30 UTC, jedieaston approved these changes

2022-08-01 15:58 UTC, ItzLevvie commented
@wingetbot run

2022-08-01 16:43 UTC, merged