Nilesoft.Shell version 1.7.0.0
microsoft/winget-pkgs pull request #68369
Opened 2022-08-01 18:08 UTC by moudey

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-08-02 15:46 UTC, Trenly requested changes

2022-08-02 18:32 UTC, Trenly requested changes
https://github.com/microsoft/winget-pkgs/pull/68369#discussion_r935756509

2022-08-02 23:13 UTC, ItzLevvie requested changes

2022-08-02 23:13 UTC, ItzLevvie commented on manifests/n/Nilesoft/Shell/1.7.0.0/Nilesoft.Shell.installer.yaml
> +MinimumOSVersion: 6.1
```suggestion
MinimumOSVersion: 6.1.0.0
```

2022-08-03 02:42 UTC, Trenly requested changes
We can’t approve this until you change this field to match control panel 

https://github.com/microsoft/winget-pkgs/pull/68369#discussion_r935756509

2022-08-05 00:36 UTC, ItzLevvie approved these changes

2022-08-05 00:36 UTC, merged