Jio.JioMeet version 4.22.0.30
microsoft/winget-pkgs pull request #71839
Opened 2022-08-24 10:37 UTC by Vaibhavpvinchurkar

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/71839)

2022-08-24 14:28 UTC, Trenly requested changes

2022-08-24 14:28 UTC, Trenly commented on manifests/j/Jio/JioMeet/4.22.0.30/Jio.JioMeet.locale.en-US.yaml
> +License: 'Jio '
```suggestion
License: Proprietary
```

2022-08-24 14:28 UTC, Trenly commented on manifests/j/Jio/JioMeet/4.22.0.30/Jio.JioMeet.installer.yaml
> +    SilentWithProgress: NA
```suggestion
    SilentWithProgress: /exenoui
```
Pipeline is failing because `NA` is not a valid command line argument

2022-08-24 16:32 UTC, msftrubengu commented
I believe @Trenly SilentWithProgress suggestions will let it through
![InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20220824111338](https://user-images.githubusercontent.com/36937303/186473010-cef2f0a2-5e6f-41ac-989a-9b7ef50f8286.png)

2022-08-26 15:50 UTC, ItzLevvie approved these changes

2022-08-26 15:51 UTC, ItzLevvie approved these changes

2022-09-03 12:36 UTC, ItzLevvie commented
Close with reason: Inactive PR;

2022-09-03 12:39 UTC, closed without merging