Update: JackieLiu.NotepadsApp version 1.4.5.0
microsoft/winget-pkgs pull request #72809
Opened 2022-08-27 01:03 UTC by vedantmgoyal2009

null

2022-08-27 01:36 UTC, ItzLevvie approved these changes, later dismissed

2022-08-27 17:49 UTC, ItzLevvie approved these changes

2022-08-27 20:42 UTC, ItzLevvie approved these changes

2022-08-30 07:33 UTC, OfficialEsco requested changes
Why is this deleted?

2022-08-30 13:07 UTC, ItzLevvie commented
@wingetbot run

2022-08-30 13:13 UTC, ItzLevvie approved these changes

2022-08-30 13:23 UTC, OfficialEsco requested changes
Url works

2022-08-30 13:24 UTC, merged