Update: Microsoft.WingetCreate version 0.3.0.6
microsoft/winget-pkgs pull request #73963
Opened 2022-08-27 15:53 UTC by vedantmgoyal2009

null

2022-08-27 17:05 UTC, ItzLevvie approved these changes

2022-08-27 17:13 UTC, ItzLevvie approved these changes, later dismissed

2022-08-29 14:56 UTC, Trenly requested changes
No need to delete this package; Just add the PackageFamilyName

2022-08-30 16:24 UTC, ItzLevvie approved these changes

2022-08-30 16:35 UTC, merged