Add version: JetBrains.GoLand version 222.3739.57
microsoft/winget-pkgs pull request #75491
Opened 2022-08-29 19:28 UTC by vedantmgoyal2009

### Result: Installation Failed
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | GoLand | GoLand 222.3345.48    |
| Version     | 222.3739.57     | 222.3345.48 |
| Publisher   | JetBrains s.r.o.   | JetBrains s.r.o.      |
| ProductCode |           | GoLand 222.3345.48    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://bittu.eu.org/docs/wpa-intro) in workflow run [2808](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2950322855>)

2022-08-30 16:29 UTC, ItzLevvie requested changes
PR needs to be set to DRAFT: https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JetBrains/GoLand/2022.2.2

2022-08-30 17:03 UTC, ItzLevvie approved these changes, later dismissed

2022-08-30 17:06 UTC, Trenly requested changes
Version is incorrect

2022-09-01 21:22 UTC, ItzLevvie approved these changes

2022-09-01 22:42 UTC, merged