update to latest lts build.  16.17.0
microsoft/winget-pkgs pull request #75818
Opened 2022-08-30 21:10 UTC by KevinLaMS

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-08-30 21:17 UTC, Trenly commented on manifests/o/OpenJS/NodeJS/16.17.0/OpenJS.NodeJS.locale.en-US.yaml
> +License: Copyright (c) Joyent, Inc. and other Node contributors. All rights reserved.
A copyright isn't a license

2022-08-30 23:54 UTC, ItzLevvie requested changes
Looks like Node.js LTS version 16.17.0 exists under https://github.com/microsoft/winget-pkgs/blob/master/manifests/o/OpenJS/NodeJS/LTS/16.17.0/OpenJS.NodeJS.LTS.installer.yaml#L15-L23

2022-09-04 22:34 UTC, ItzLevvie commented
Close with reason: Node.js LTS version 16.17.0 is available under OpenJS.NodeJS.LTS;

2022-09-04 22:34 UTC, closed without merging

2022-09-07 00:38 UTC, jsoref commented
Hi @KevinLaMS, @Trenly: you're going to want to delete this branch