Normalize TobySuggate.GitFiend 0.28.0
microsoft/winget-pkgs pull request #76480
Opened 2022-08-31 14:44 UTC by Trenly

2022-08-31 15:04 UTC, ItzLevvie submitted a review, later dismissed

2022-08-31 16:43 UTC, vedantmgoyal2009 requested changes
https://github.com/microsoft/winget-pkgs/pull/74544

2022-09-02 18:05 UTC, OfficialEsco approved these changes

2022-09-03 12:53 UTC, ItzLevvie commented
@wingetbot run

2022-09-03 12:58 UTC, merged