Zoom.Zoom version 5.11.10.8200
microsoft/winget-pkgs pull request #76559
Opened 2022-09-01 06:46 UTC by mivsvit

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-09-04 23:39 UTC, ItzLevvie requested changes

2022-09-04 23:39 UTC, ItzLevvie commented on manifests/z/Zoom/Zoom/5.11.10.8200/Zoom.Zoom.installer.yaml
> +PackageVersion: 5.11.10.8200
```suggestion
PackageVersion: 5.11.8200
```
This must match Control Panel.

2022-09-04 23:39 UTC, ItzLevvie commented on manifests/z/Zoom/Zoom/5.11.10.8200/Zoom.Zoom.locale.en-US.yaml
> +PackageVersion: 5.11.10.8200
```suggestion
PackageVersion: 5.11.8200
```
This must match Control Panel.

2022-09-04 23:39 UTC, ItzLevvie commented on manifests/z/Zoom/Zoom/5.11.10.8200/Zoom.Zoom.yaml
> +PackageVersion: 5.11.10.8200
```suggestion
PackageVersion: 5.11.8200
```
This must match Control Panel.

2022-09-07 21:17 UTC, mivsvit commented
Closing request and resubmitting with updated version number.

2022-09-07 21:17 UTC, closed without merging