New version: MicaForEveryone.MicaForEveryone version 1.2.0.1
microsoft/winget-pkgs pull request #77642
Opened 2022-09-02 11:31 UTC by xmine64

### Pull request has been automatically created using 🛫 [WinGet Releaser](https://bittu.eu.org/docs/wr-intro).

2022-09-02 11:36 UTC, sitiom requested changes
This manifest should be updated also support the machine scope:
![image](https://user-images.githubusercontent.com/56180050/188131291-1e99ed3f-8608-459d-868c-dad9efe57495.png)

2022-09-02 11:43 UTC, sitiom requested changes

2022-09-02 11:43 UTC, sitiom commented on manifests/m/MicaForEveryone/MicaForEveryone/1.2.0.1/MicaForEveryone.MicaForEveryone.installer.yaml
> +  InstallerSha256: CE529BE24753D6BB26C7F201F0BC5579726CEB9D230EE26902BA2091118265A9
Add machine scope:
```suggestion
UpgradeBehavior: install
ReleaseDate: 2022-09-02
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/MicaForEveryone/MicaForEveryone/releases/download/v1.2.0.1/MicaForEveryone-x64-Release-Installer.exe
  InstallerSha256: CE529BE24753D6BB26C7F201F0BC5579726CEB9D230EE26902BA2091118265A9
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/MicaForEveryone/MicaForEveryone/releases/download/v1.2.0.1/MicaForEveryone-x64-Release-Installer.exe
  InstallerSha256: CE529BE24753D6BB26C7F201F0BC5579726CEB9D230EE26902BA2091118265A9
  InstallerSwitches:
    Custom: /ALLUSERS
```

2022-09-03 12:38 UTC, ItzLevvie approved these changes

2022-09-03 12:45 UTC, merged