LingitAS.Lingdys4 version 4.5.111.0
microsoft/winget-pkgs pull request #78539
Opened 2022-09-05 08:23 UTC by Ogobor

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-09-07 14:11 UTC, Trenly requested changes

2022-09-07 14:11 UTC, Trenly commented on manifests/l/LingitAS/Lingdys4/4.5.111.0/LingitAS.Lingdys4.locale.nb-NO.yaml
> +ReleaseNotes: https://lingit.no/
A URL is not release notes.

2022-09-07 14:11 UTC, Trenly commented on manifests/l/LingitAS/Lingdys4/4.5.111.0/LingitAS.Lingdys4.locale.nb-NO.yaml
> +ReleaseNotesUrl: https://lingit.no/
Please ensure this is a direct link to the release notes, not just to the package homepage

2022-09-07 14:11 UTC, Trenly commented on manifests/l/LingitAS/Lingdys4/4.5.111.0/LingitAS.Lingdys4.locale.nb-NO.yaml
> +InstallationNotes: LingDys installed.
```suggestion
```
Not needed

2022-09-07 14:11 UTC, Trenly commented on manifests/l/LingitAS/Lingdys4/4.5.111.0/LingitAS.Lingdys4.locale.nb-NO.yaml
> +CopyrightUrl: https://lingit.no/
Please ensure this is a direct link to the copyright, not just to the package homepage

2022-09-07 14:11 UTC, Trenly commented on manifests/l/LingitAS/Lingdys4/4.5.111.0/LingitAS.Lingdys4.locale.nb-NO.yaml
> +LicenseUrl: https://lingit.no/
Please ensure this is a direct link to the license, not just to the package homepage

2022-09-07 14:11 UTC, Trenly commented on manifests/l/LingitAS/Lingdys4/4.5.111.0/LingitAS.Lingdys4.locale.nb-NO.yaml
> +License: None
A URL isn't a license; Please update this with actual license terms such as Proprietary, MIT, GPL-2.0, or other terms as appropriate

2022-09-07 14:11 UTC, Trenly commented on manifests/l/LingitAS/Lingdys4/4.5.111.0/LingitAS.Lingdys4.locale.nb-NO.yaml
> +PrivacyUrl: https://lingit.no/
Please ensure this is a direct link to the privacy policy, not just to the package homepage

2022-09-07 14:11 UTC, Trenly commented on manifests/l/LingitAS/Lingdys4/4.5.111.0/LingitAS.Lingdys4.locale.nb-NO.yaml
> +PublisherSupportUrl: https://lingit.no/
Please ensure this is a direct link to the publisher support page, not just to the package homepage

2022-09-10 00:40 UTC, ItzLevvie approved these changes

2022-09-10 00:41 UTC, merged