Minecodes.azure version 1.1.1
microsoft/winget-pkgs pull request #78763
Opened 2022-09-06 13:43 UTC by Minecodes

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-09-07 13:57 UTC, Trenly requested changes

2022-09-07 13:57 UTC, Trenly commented on manifests/m/Minecodes/azure/1.1.1/Minecodes.azure.installer.yaml
> +PackageIdentifier: Minecodes.azure
```suggestion
PackageIdentifier: Minecodes.4zur3
```
This is best to match `Publisher.PackageName`

2022-09-07 13:57 UTC, Trenly commented on manifests/m/Minecodes/azure/1.1.1/Minecodes.azure.locale.en-US.yaml
> +PackageIdentifier: Minecodes.azure
```suggestion
PackageIdentifier: Minecodes.4zur3
```
This is best to match `Publisher.PackageName`

2022-09-07 13:57 UTC, Trenly commented on manifests/m/Minecodes/azure/1.1.1/Minecodes.azure.yaml
> +PackageIdentifier: Minecodes.azure
```suggestion
PackageIdentifier: Minecodes.4zur3
```
This is best to match `Publisher.PackageName`

2022-09-10 01:12 UTC, ItzLevvie requested changes
See https://github.com/microsoft/winget-pkgs/pull/78763#pullrequestreview-1099230440

2022-09-11 23:47 UTC, ItzLevvie requested changes

2022-09-11 23:47 UTC, ItzLevvie commented on manifests/m/Minecodes/4zur3/1.1.1/Minecodes.4zur3.locale.en-US.yaml
> +PackageVersion: 1.1.1
```suggestion
PackageVersion: 1.1.1.0
```
This must match Control Panel.

You'll also need to change `manifests/m/Minecodes/4zur3/1.1.1` to `manifests/m/Minecodes/4zur3/1.1.1.0`

2022-09-11 23:47 UTC, ItzLevvie commented on manifests/m/Minecodes/4zur3/1.1.1/Minecodes.4zur3.yaml
> +PackageVersion: 1.1.1
```suggestion
PackageVersion: 1.1.1.0
```
This must match Control Panel.

You'll also need to change `manifests/m/Minecodes/4zur3/1.1.1` to `manifests/m/Minecodes/4zur3/1.1.1.0`

2022-09-11 23:47 UTC, ItzLevvie commented on manifests/m/Minecodes/4zur3/1.1.1/Minecodes.4zur3.installer.yaml
> +PackageVersion: 1.1.1
```suggestion
PackageVersion: 1.1.1.0
```
This must match Control Panel.

You'll also need to change `manifests/m/Minecodes/4zur3/1.1.1` to `manifests/m/Minecodes/4zur3/1.1.1.0`

2022-09-13 11:28 UTC, ItzLevvie approved these changes

2022-09-13 11:28 UTC, merged