MuhammedKalkan.OpenLens version 6.0.1
microsoft/winget-pkgs pull request #78765
Opened 2022-09-06 14:08 UTC by brotich

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-09-06 14:57 UTC, mdanish-kh commented on manifests/m/MuhammedKalkan/OpenLens/6.0.1/MuhammedKalkan.OpenLens.installer.yaml
> +- DisplayVersion: 6.0.1-latest.1660157736010
```suggestion
- DisplayVersion: 6.0.1-latest.1660667913150
```
This should match control panel.

2022-09-06 21:08 UTC, brotich commented
will check on this tomorrow

2022-09-10 01:16 UTC, ItzLevvie requested changes

2022-09-10 01:16 UTC, ItzLevvie commented on manifests/m/MuhammedKalkan/OpenLens/6.0.1/MuhammedKalkan.OpenLens.installer.yaml
> +- Architecture: x86
```suggestion
- Architecture: x64
```

2022-09-10 01:16 UTC, ItzLevvie commented on manifests/m/MuhammedKalkan/OpenLens/6.0.1/MuhammedKalkan.OpenLens.installer.yaml
> +- Architecture: x86
```suggestion
- Architecture: x64
```

2022-09-10 01:17 UTC, ItzLevvie approved these changes, later dismissed

2022-09-15 09:55 UTC, brotich commented
closing for now, till i figure out what the issue is

2022-09-15 09:55 UTC, closed without merging