Zola installer 0.16.1
microsoft/winget-pkgs pull request #79060
Opened 2022-09-08 11:46 UTC by leotsarev

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Blocked on 1.4 release

2022-09-08 12:23 UTC, russellbanks commented
@leotsarev singleton ManifestVersion was "deprecated" a while ago; the latest is 1.2.0. To my knowledge, there isn't a single singleton manifest left in the repository

2022-09-08 12:24 UTC, Trenly requested changes

2022-09-08 12:24 UTC, Trenly commented on manifests/z/Zola/zola/0.16.1.yaml
> +---
```suggestion
# ---
```

2022-09-08 12:24 UTC, Trenly commented on manifests/z/Zola/zola/0.16.1.yaml
> +    InstallerType: zip
Zip type is not supported yet

2022-09-08 12:24 UTC, Trenly commented on manifests/z/Zola/zola/0.16.1.yaml
> +ManifestType: singleton
Please move to Multi-manifest format

2022-09-08 13:13 UTC, leotsarev commented on manifests/z/Zola/zola/0.16.1.yaml
> +ManifestType: singleton
Thanks, fixed

2022-09-08 13:13 UTC, leotsarev commented on manifests/z/Zola/zola/0.16.1.yaml
> +---
fixed

2022-09-10 01:07 UTC, ItzLevvie submitted a review, later dismissed

2022-09-12 06:13 UTC, leotsarev commented on manifests/z/Zola/zola/0.16.1.yaml
> +    InstallerType: zip
That's why this is a draft.

2022-11-09 23:50 UTC, ItzLevvie commented
@msftbot .zip

2023-02-09 04:44 UTC, Trenly commented
@wingetbot run

2023-02-09 05:06 UTC, Trenly requested changes
Folder name `manifests/z/Zola/zola/` should be `manifests/z/Zola/Zola/`

2023-03-06 16:28 UTC, stephengillie commented
Hi @leotsarev,

The package installs normally, but requires `Microsoft.VCRedist.2015+.x64` to run:
![image](https://user-images.githubusercontent.com/114952565/223171208-d6b2794c-81c6-4faa-9a7f-fed120cd293d.png)

Pending:
* https://github.com/microsoft/winget-cli/issues/163

2023-03-07 15:24 UTC, stephengillie commented
Hi @leotsarev,

Please understand that dependencies are not currently supported. Specifying the dependency in the manifest won't have it install in the pipeline nor on user computers at this time. We are hoping to have this resolved soon. It's being tracked in this issue: 
* https://github.com/microsoft/winget-cli/issues/163

2023-03-07 15:29 UTC, leotsarev commented
Thanks @stephengillie !

I guess I have to wait yet another winget release:-)

2023-03-15 11:30 UTC, ItzLevvie commented
[Policy] Blocking-Issue

2023-07-23 17:25 UTC, ItzLevvie approved these changes

2023-07-24 15:11 UTC, stephengillie commented
/AzurePipelines run

2023-08-01 15:47 UTC, ItzLevvie commented
[Policy] Blocking-Issue

2023-09-26 07:09 UTC, armoha commented
Since packaging dependencies (https://github.com/microsoft/winget-cli/issues/163) has been supported in WinGet 1.6, can we continue to work on this issue?

2023-12-08 04:19 UTC, closed without merging