Added JetBrains ReSharper version 2022.2.3.
microsoft/winget-pkgs pull request #79665
Opened 2022-09-15 12:33 UTC by jedieaston

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-09-15 13:23 UTC, Trenly requested changes

2022-09-15 16:04 UTC, ItzLevvie approved these changes, later dismissed

2022-09-16 12:15 UTC, jedieaston commented on manifests/j/JetBrains/ReSharper/2022.2.3/JetBrains.ReSharper.installer.yaml
> +    ProductCode: '{e7699bcd-06dc-5b82-81b9-5a9c2d731c34}'
None of them are, really. The ARP entries shouldn't be present for ReSharper (matching works without them anyway).

2022-09-16 16:02 UTC, ItzLevvie approved these changes

2022-09-16 20:02 UTC, ItzLevvie approved these changes

2022-09-16 20:18 UTC, merged