Add Neovim Nightly version 0.8.0-dev-1092-g89b9eab63
microsoft/winget-pkgs pull request #79699
Opened 2022-09-16 03:48 UTC by trbrink

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Closes #79698

2022-09-16 04:19 UTC, vedantmgoyal2009 requested changes
Rename version folder also.

2022-09-16 04:19 UTC, vedantmgoyal2009 commented on manifests/n/Neovim/Neovim/Nightly/0.8.0-dev-1092-g89b9eab63/Neovim.Neovim.Nightly.installer.yaml
> +PackageVersion: 0.8.0-dev-1092-g89b9eab63
```suggestion
PackageVersion: 0.8.0
```

2022-09-16 04:19 UTC, vedantmgoyal2009 commented on manifests/n/Neovim/Neovim/Nightly/0.8.0-dev-1092-g89b9eab63/Neovim.Neovim.Nightly.yaml
> +PackageVersion: 0.8.0-dev-1092-g89b9eab63
```suggestion
PackageVersion: 0.8.0
```

2022-09-16 04:19 UTC, vedantmgoyal2009 commented on manifests/n/Neovim/Neovim/Nightly/0.8.0-dev-1092-g89b9eab63/Neovim.Neovim.Nightly.locale.en-US.yaml
> +PackageVersion: 0.8.0-dev-1092-g89b9eab63
```suggestion
PackageVersion: 0.8.0
```

2022-09-16 09:51 UTC, trbrink commented
@vedantmgoyal2009, I made the changes you request.

2022-09-18 14:31 UTC, KaranKad approved these changes

2022-09-18 14:32 UTC, merged