Added RubyMine version 2022.2.2.
microsoft/winget-pkgs pull request #80109
Opened 2022-09-19 12:54 UTC by jedieaston

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-09-19 13:03 UTC, Trenly commented on manifests/j/JetBrains/RubyMine/2022.2.2/JetBrains.RubyMine.installer.yaml
> +  ProductCode: RubyMine 2022.2.1
```suggestion
```
Installer level is overriding this anyways

2022-09-19 17:09 UTC, vedantmgoyal9 requested changes
* Duplicate of https://github.com/microsoft/winget-pkgs/pull/80077

2022-09-19 18:08 UTC, ItzLevvie approved these changes

2022-09-20 08:01 UTC, ItzLevvie commented
Close with reason: Merge conflicts;

2022-09-20 08:02 UTC, closed without merging