New version: JAMSoftware.TreeSize.Free version 4.6.1
microsoft/winget-pkgs pull request #80215
Opened 2022-09-20 14:19 UTC by Daniel-Tr

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-09-20 22:30 UTC, ItzLevvie requested changes

2022-09-20 22:30 UTC, ItzLevvie commented on manifests/j/JAMSoftware/TreeSize/Free/4.6.1/JAMSoftware.TreeSize.Free.installer.yaml
> +PackageVersion: 4.6.1
```suggestion
PackageVersion: 4.6
```
I'm still seeing `4.6` in Control Panel:
![image](https://user-images.githubusercontent.com/11600822/191376261-8f300bc6-d285-4925-a69a-f307ebc99921.png)

2022-09-20 22:30 UTC, ItzLevvie commented on manifests/j/JAMSoftware/TreeSize/Free/4.6.1/JAMSoftware.TreeSize.Free.locale.en-US.yaml
> +PackageVersion: 4.6.1
```suggestion
PackageVersion: 4.6
```
I'm still seeing `4.6` in Control Panel:
![image](https://user-images.githubusercontent.com/11600822/191376261-8f300bc6-d285-4925-a69a-f307ebc99921.png)

2022-09-20 22:30 UTC, ItzLevvie commented on manifests/j/JAMSoftware/TreeSize/Free/4.6.1/JAMSoftware.TreeSize.Free.yaml
> +PackageVersion: 4.6.1
```suggestion
PackageVersion: 4.6
```
I'm still seeing `4.6` in Control Panel:
![image](https://user-images.githubusercontent.com/11600822/191376261-8f300bc6-d285-4925-a69a-f307ebc99921.png)

2022-09-21 06:02 UTC, Daniel-Tr commented
@ItzLevvie: Package version 4.6.1 is correct - the product version set is wrong unfortunately (we missed to update it along with the file version, which is set to 4.6.1 as intended). We will publish a corrected version shortly.

2022-09-21 19:43 UTC, Daniel-Tr commented
Corrected version has been published -> Revoking this PR, creating a new one with the correct information

2022-09-21 19:43 UTC, closed without merging