Add version: VPNetwork.TorGuard version 4.8.9
microsoft/winget-pkgs pull request #80211
Opened 2022-09-20 13:25 UTC by russellbanks

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

2022-09-20 15:29 UTC, ItzLevvie approved these changes

2022-09-20 19:06 UTC, russellbanks commented
.

2022-09-30 20:47 UTC, ItzLevvie requested changes

2022-09-30 20:47 UTC, ItzLevvie commented on manifests/v/VPNetwork/TorGuard/4.8.9/VPNetwork.TorGuard.installer.yaml
> +  Publisher: VPNetwork LLC
```suggestion
  Publisher: '"VPNetwork LLC"'
```

2022-09-30 20:47 UTC, ItzLevvie commented on manifests/v/VPNetwork/TorGuard/4.8.9/VPNetwork.TorGuard.installer.yaml
> +  DisplayVersion: 4.8.9-build.144.1+g3174a6b
```suggestion
  DisplayVersion: '"4.8.9-build.144.1+g3174a6b"'
```

2022-10-01 12:35 UTC, ItzLevvie approved these changes

2022-10-01 13:16 UTC, ItzLevvie requested changes
See https://github.com/microsoft/winget-pkgs/pull/80209#pullrequestreview-1127524702

2022-10-05 18:56 UTC, ItzLevvie approved these changes

2022-10-05 19:13 UTC, merged