Updated Meld to 3.22.0
microsoft/winget-pkgs pull request #80813
Opened 2022-09-26 16:26 UTC by G-Pereira

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-09-26 16:28 UTC, G-Pereira commented
@microsoft-github-policy-service agree

2022-09-27 13:15 UTC, ItzLevvie requested changes

2022-09-27 13:15 UTC, ItzLevvie commented on manifests/m/Meld/Meld/3.22.0/Meld.Meld.locale.en-US.yaml
> +Publisher: The Meld project
```suggestion
Publisher: Kai Willadsen
```
This must match Control Panel.

2022-09-27 13:15 UTC, ItzLevvie commented on manifests/m/Meld/Meld/3.22.0/Meld.Meld.installer.yaml
> +  ProductCode: '{68E6C01E-D7C1-4BED-9FDA-A00118F7CBC4}'
```suggestion
  ProductCode: '{F305FD7B-EE65-4D75-ADB4-A6BD7D5F86B9}'
```
This must match Windows Registry.

2022-09-27 15:42 UTC, ItzLevvie approved these changes

2022-09-27 16:28 UTC, merged