MoheshwarAmarnathBiswas.YouTubeVideoDownloader version 1.2.2
microsoft/winget-pkgs pull request #80923
Opened 2022-09-28 05:27 UTC by fluentmoheshwar

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-09-28 05:30 UTC, fluentmoheshwar commented
@microsoft-github-policy-service agree

2022-09-28 05:36 UTC, fluentmoheshwar commented
> /AzurePipelines run

The workflow didn't seem to run. 😂

2022-09-29 03:16 UTC, Trenly requested changes

2022-09-29 03:16 UTC, Trenly commented on manifests/m/MoheshwarAmarnathBiswas/YouTubeVideoDownloader/1.2.2/MoheshwarAmarnathBiswas.YouTubeVideoDownloader.installer.yaml
> +    Custom: /ALLUSERS /VERYSILENT
```suggestion
    Custom: /ALLUSERS
```
Silent switches should not be part of custom

2022-09-30 12:49 UTC, Trenly approved these changes

2022-09-30 12:49 UTC, merged