Dapr.CLI version 1.9.0.1
microsoft/winget-pkgs pull request #81209
Opened 2022-09-30 12:00 UTC by shivamkm07

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-09-30 12:04 UTC, shivamkm07 commented
@ItzLevvie Updated the manifest with latest official Dapr release (https://github.com/dapr/cli/releases/tag/v1.9.0-rc.1). Please approve!
Reference: https://github.com/microsoft/winget-pkgs/pull/79840

2022-09-30 18:54 UTC, ItzLevvie requested changes

2022-09-30 18:54 UTC, ItzLevvie commented on manifests/d/Dapr/CLI/1.9.0.1/Dapr.CLI.installer.yaml
> +  ProductCode: '{C1060BAC-0409-4AC7-B336-A1DBD61A90CE}'
```suggestion
  ProductCode: '{8F585665-3A4E-4D47-8B2C-E76EC7DD1D4F}'
```
```
Enter a pull request number: https://github.com/microsoft/winget-pkgs/pull/81209

Manifest validation succeeded.
Found CLI [Dapr.CLI] Version 1.9.0.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/dapr/cli/releases/download/v1.9.0-rc.1/dapr.msi
  ██████████████████████████████  32.2 MB / 32.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Name          : CLI
Publisher     : Dapr
Version       : 1.9.0.1
ProductCode   : {8F585665-3A4E-4D47-8B2C-E76EC7DD1D4F}
Registry Path : Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{8F585665-3A4E-4D47-8B2C-E76EC7DD1D4F}
Uninstall     : winget uninstall --id "{8F585665-3A4E-4D47-8B2C-E76EC7DD1D4F}"

Press any key to continue . . .
```

2022-10-02 05:52 UTC, shivamkm07 commented
@ItzLevvie completed the requested changes. Can this be merged now?

2022-10-02 06:58 UTC, ItzLevvie approved these changes

2022-10-02 06:59 UTC, merged