MinnekDigitalStudio.Cominnek version 2.0.0-alpha.2
microsoft/winget-pkgs pull request #82106
Opened 2022-10-02 18:57 UTC by isaacismaelx14

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-10-02 20:21 UTC, isaacismaelx14 commented
@microsoft-github-policy-service agree [company="Minnek Digital Studio"]

2022-10-02 20:22 UTC, isaacismaelx14 commented
@microsoft-github-policy-service agree company="Minnek Digital Studio"

2022-10-04 16:12 UTC, ItzLevvie commented
@wingetbot run

2022-10-04 16:16 UTC, ItzLevvie requested changes

2022-10-04 16:16 UTC, ItzLevvie commented on manifests/m/MinnekDigitalStudio/Cominnek/2.0.0-alpha.2/MinnekDigitalStudio.Cominnek.locale.en-US.yaml
> +PackageName: cominnek
```suggestion
PackageName: Cominnek
```

2022-10-04 16:16 UTC, ItzLevvie commented on manifests/m/MinnekDigitalStudio/Cominnek/2.0.0-alpha.2/MinnekDigitalStudio.Cominnek.locale.en-US.yaml
> +PackageVersion: 2.0.0-alpha.2
```suggestion
PackageVersion: 2.0.0-alpha.3
```

2022-10-04 16:16 UTC, ItzLevvie commented on manifests/m/MinnekDigitalStudio/Cominnek/2.0.0-alpha.2/MinnekDigitalStudio.Cominnek.installer.yaml
> +PackageVersion: 2.0.0-alpha.2
```suggestion
PackageVersion: 2.0.0-alpha.3
```

2022-10-04 16:16 UTC, ItzLevvie commented on manifests/m/MinnekDigitalStudio/Cominnek/2.0.0-alpha.2/MinnekDigitalStudio.Cominnek.yaml
> +PackageVersion: 2.0.0-alpha.2
```suggestion
PackageVersion: 2.0.0-alpha.3
```

2022-10-04 16:16 UTC, ItzLevvie commented on manifests/m/MinnekDigitalStudio/Cominnek/2.0.0-alpha.2/MinnekDigitalStudio.Cominnek.installer.yaml
> +  InstallerUrl: https://github.com/Minnek-Digital-Studio/cominnek/releases/download/v2.0.0-alpha.2/cominnek_2.0.0-alpha.2.exe
```suggestion
  InstallerUrl: https://github.com/Minnek-Digital-Studio/cominnek/releases/download/v2.0.0-alpha.3/cominnek_2.0.0-alpha.3.exe
```

2022-10-04 16:16 UTC, ItzLevvie commented on manifests/m/MinnekDigitalStudio/Cominnek/2.0.0-alpha.2/MinnekDigitalStudio.Cominnek.installer.yaml
> +  InstallerSha256: 6695685720437228A3A852713D7CFF0DB998372FE712E3B123C82F135495E0CF
```suggestion
  InstallerSha256: A554C7EF707192F963223C2C9ACCD49B30851FAAD8065440445CEB0E29D89D04
```

2022-10-06 13:35 UTC, closed without merging