FrostWireLLC.FrostWire version 6.9.9.313
microsoft/winget-pkgs pull request #83320
Opened 2022-10-12 16:46 UTC by ptanmay143

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-10-12 16:47 UTC, ptanmay143 commented
[Package Request]: FrostWireLLC.FrostWire #83137

2022-10-12 21:26 UTC, KaranKad requested changes

2022-10-12 21:26 UTC, KaranKad commented on manifests/f/FrostWireLLC/FrostWire/6.9.9.313/FrostWireLLC.FrostWire.installer.yaml
> +PackageVersion: 6.9.9.313
```suggestion
PackageIdentifier: FrostWire.FrostWire
PackageVersion: 6.9.9.313
InstallModes:
- interactive
- silent
ReleaseDate: 2022-09-12
Scope: machine
```

2022-10-12 21:26 UTC, KaranKad commented on manifests/f/FrostWireLLC/FrostWire/6.9.9.313/FrostWireLLC.FrostWire.locale.en-US.yaml
> +PackageIdentifier: FrostWireLLC.FrostWire
```suggestion
PackageIdentifier: FrostWire.FrostWire
```

2022-10-12 21:26 UTC, KaranKad commented on manifests/f/FrostWireLLC/FrostWire/6.9.9.313/FrostWireLLC.FrostWire.locale.en-US.yaml
> +License: GPL
```suggestion
License: GPL-3.0
LicenseUrl: https://raw.githubusercontent.com/frostwire/frostwire/master/desktop/LICENSE.txt
```

2022-10-12 21:26 UTC, KaranKad commented on manifests/f/FrostWireLLC/FrostWire/6.9.9.313/FrostWireLLC.FrostWire.locale.en-US.yaml
> +ShortDescription: FrostWire - Search, Download, Play, Share.
```suggestion
ShortDescription: FrostWire is an easy to use Cloud Downloader, BitTorrent Client and Media Player.
```

2022-10-12 21:26 UTC, KaranKad commented on manifests/f/FrostWireLLC/FrostWire/6.9.9.313/FrostWireLLC.FrostWire.yaml
> +PackageIdentifier: FrostWireLLC.FrostWire
```suggestion
PackageIdentifier: FrostWire.FrostWire
```

2022-10-13 10:17 UTC, KaranKad approved these changes

2022-10-13 10:22 UTC, merged