Add Version: Inkscape 0.92.5
microsoft/winget-pkgs pull request #85033
Opened 2022-10-18 15:44 UTC by yashjawale

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-10-19 02:50 UTC, Trenly requested changes

2022-10-19 02:50 UTC, Trenly commented on manifests/i/Inkscape/Inkscape/0.92.5/Inkscape.Inkscape.installer.yaml
> +PackageVersion: 0.92.5
```suggestion
PackageVersion: 0.92.5.0
```
This should match what is written to control panel

2022-10-19 02:50 UTC, Trenly commented on manifests/i/Inkscape/Inkscape/0.92.5/Inkscape.Inkscape.locale.en-US.yaml
> +PackageVersion: 0.92.5
```suggestion
PackageVersion: 0.92.5.0
```
This should match what is written to control panel

2022-10-19 02:50 UTC, Trenly commented on manifests/i/Inkscape/Inkscape/0.92.5/Inkscape.Inkscape.yaml
> +PackageVersion: 0.92.5
```suggestion
PackageVersion: 0.92.5.0
```
This should match what is written to control panel

2022-10-20 02:41 UTC, stephengillie approved these changes

2022-10-20 02:41 UTC, merged