BlueMarbleGeographics.GlobalMapper version 24
microsoft/winget-pkgs pull request #85504
Opened 2022-10-19 19:57 UTC by TechnicaVivunt

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-10-20 03:46 UTC, Trenly requested changes
I'm a bit confused by this package. It appears that this doesn't install Global Mapper itself, but rather this appears to be the Installer for the Installer for Global Mapper?

2022-10-20 11:47 UTC, TechnicaVivunt commented
Yeah that's definitely odd; I will go ahead and switch this to .exe version of the installer instead since I know it's expected behavior.

2022-10-21 13:31 UTC, Trenly requested changes

2022-10-21 13:31 UTC, Trenly commented on manifests/b/BlueMarbleGeographics/GlobalMapper/24.00.0000/BlueMarbleGeographics.GlobalMapper.locale.en-US.yaml
> +Copyright: 'Contact: geohelp@bluemarblegeo.com'
This doesn't seem like a copyright

2022-10-21 13:31 UTC, Trenly commented on manifests/b/BlueMarbleGeographics/GlobalMapper/24.00.0000/BlueMarbleGeographics.GlobalMapper.installer.yaml
> +    Silent: /S
```suggestion
    Silent: /S
  ProductCode: '{277751E5-AA45-48BE-A78C-685205FB6196}'
  AppsAndFeaturesEntries:
    - DisplayName: Global Mapper 24.0 64-bit
      ProductCode: '{277751E5-AA45-48BE-A78C-685205FB6196}'
```

2022-10-21 13:54 UTC, Trenly approved these changes

2022-10-21 13:55 UTC, Trenly approved these changes

2022-10-21 14:39 UTC, merged