akeo.ie.Zadig version 2.7.765
microsoft/winget-pkgs pull request #86217
Opened 2022-10-25 09:40 UTC by G0rocks

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-10-27 15:47 UTC, G0rocks commented
Yeah I also got a failed validation, might look into this more later but I'm not so good with the wingetcreate multifile manifests,

2022-11-09 20:45 UTC, ItzLevvie requested changes

2022-11-09 20:45 UTC, ItzLevvie commented on manifests/a/akeo/ie/Zadig/2.7.765/akeo.ie.Zadig.installer.yaml
> +PackageVersion: 2.7.765
```suggestion
PackageVersion: 2.7.765
Commands:
- zadig
```

2022-11-09 22:25 UTC, stephengillie commented
/azp run

2022-11-09 23:12 UTC, ItzLevvie requested changes

2022-11-09 23:12 UTC, ItzLevvie commented on manifests/a/akeo/ie/Zadig/2.7.765/akeo.ie.Zadig.installer.yaml
> +PackageVersion: 2.7.765
```suggestion
PackageVersion: 2.7.765
Commands:
- zadig
```

2022-11-09 23:15 UTC, ItzLevvie commented
Close with reason: Replaced by PR 87985

2022-11-09 23:15 UTC, ItzLevvie commented
Close with reason: Replaced by PR 87985;

2022-11-09 23:15 UTC, closed without merging