Updates Sonos.Controller to PackageVersion: 70.1.34112
microsoft/winget-pkgs pull request #86261
Opened 2022-10-25 22:30 UTC by Rokory

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-10-25 22:32 UTC, Rokory commented
@microsoft-github-policy-service agree

2022-10-26 01:37 UTC, Trenly requested changes

2022-10-26 01:37 UTC, Trenly commented on manifests/s/Sonos/Controller/70.1.34112/Sonos.Controller.locale.en-US.yaml
> +License: Copyright (c) Sonos Inc.
A copyright isn't a license; Please update this with actual license terms such as Proprietary, MIT, GPL-2.0, or other terms as appropriate

2022-10-26 14:44 UTC, Rokory commented
I updated the license property.

2022-10-27 23:41 UTC, ItzLevvie approved these changes

2022-10-27 23:41 UTC, merged