Tableau.Public version 22.3.0
microsoft/winget-pkgs pull request #87104
Opened 2022-11-01 20:02 UTC by s-crypt

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-11-01 20:48 UTC, Trenly commented
```
[1F78:1F40][2022-11-01T13:14:03]e000: Error 0xffffffff: The installation failed because the installation directory is invalid.  A full path, including a drive letter, must be specified.  A UNC path, such as \\server\share, is also valid.   A path with just a drive letter, such as D:\, is not valid.
[1F78:1F40][2022-11-01T13:14:03]e000: Error 0xffffffff: Failed to initialize data in bootstrapper application.
[1F78:1F68][2022-11-01T13:14:03]i500: Shutting down, exit code: 0xffff
```

2022-11-02 05:22 UTC, s-crypt commented
Interesting. The installer is the same as the previous version but is now having errors with the new version. 
I am not sure why the default installer path is not working, as I tested it on my machine with no problems, though there is a UAC prompt. Could that be the problem?
There is currently [no documentation](https://learn.microsoft.com/en-us/windows/package-manager/package/winget-validation#pull-request-labels) for "Validation-Shell-Execute"

2022-11-09 21:40 UTC, ItzLevvie requested changes

2022-11-09 21:40 UTC, ItzLevvie commented on manifests/t/Tableau/Public/22.3.0/Tableau.Public.installer.yaml
> +PackageVersion: 22.3.0
```suggestion
PackageVersion: 22.3.1408
```

2022-11-09 21:40 UTC, ItzLevvie commented on manifests/t/Tableau/Public/22.3.0/Tableau.Public.locale.en-US.yaml
> +PackageVersion: 22.3.0
```suggestion
PackageVersion: 22.3.1408
```

2022-11-09 21:40 UTC, ItzLevvie commented on manifests/t/Tableau/Public/22.3.0/Tableau.Public.yaml
> +PackageVersion: 22.3.0
```suggestion
PackageVersion: 22.3.1408
```

2022-11-09 21:40 UTC, ItzLevvie commented on manifests/t/Tableau/Public/22.3.0/Tableau.Public.installer.yaml
> +  ProductCode: '{4e57e52e-17bd-4325-8436-082178b08a83}'
```suggestion
  ProductCode: '{36297416-d815-4cde-951f-dc0a58414a1b}'
```

2022-11-09 21:40 UTC, ItzLevvie commented on manifests/t/Tableau/Public/22.3.0/Tableau.Public.installer.yaml
> +  ProductCode: '{4e57e52e-17bd-4325-8436-082178b08a83}'
```suggestion
  ProductCode: '{36297416-d815-4cde-951f-dc0a58414a1b}'
```

2022-11-09 21:40 UTC, ItzLevvie commented on manifests/t/Tableau/Public/22.3.0/Tableau.Public.installer.yaml
> +- DisplayName: Tableau Public 2022.1 (20221.22.0331.2015)
```suggestion
- DisplayName: Tableau Public 2022.3 (20223.22.1005.1835)
```

2022-11-09 21:40 UTC, ItzLevvie commented on manifests/t/Tableau/Public/22.3.0/Tableau.Public.installer.yaml
> +- Architecture: x86
```suggestion
- Architecture: x64
```

2022-11-09 22:14 UTC, stephengillie commented
/azp run

2022-11-09 22:59 UTC, closed without merging