New package: Gyan.CodexFFmpeg version 5.1.2
microsoft/winget-pkgs pull request #87327
Opened 2022-11-03 09:03 UTC by SpecterShell

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-11-04 02:50 UTC, Trenly commented
@Msftbot .zip

2022-11-08 21:42 UTC, ItzLevvie approved these changes, later dismissed

2022-11-09 23:50 UTC, ItzLevvie commented
@msftbot .zip

2022-11-10 13:55 UTC, KaranKad commented
As this build is officially promoted by ffmpeg site should we change `PackageIdentifier` to `FFmpeg.FFmpeg`?

2022-11-10 14:15 UTC, SpecterShell commented
> As this build is officially promoted by ffmpeg site should we change `PackageIdentifier` to `FFmpeg.FFmpeg`?

FFmpeg promotes two different builds:

https://www.gyan.dev/ffmpeg/builds/
https://github.com/BtbN/FFmpeg-Builds/releases

So I use this complicated `PackageIdentifier` in case another one would be added to winget-pkgs repo as well.
Don't worry. I have added a moniker `ffmpeg` so that if user types `winget install ffmpeg` it will install this one by default.

2022-11-12 16:31 UTC, ItzLevvie submitted a review, later dismissed

2022-11-12 17:56 UTC, ItzLevvie commented
@msftbot .zip

2023-01-20 14:51 UTC, junaga commented
For real, why isn't this merging? This is pipeline is too complicated. Can we _please_ get the package up.

2023-01-20 15:26 UTC, Trenly commented
> For real, why isn't this merging? This pipeline is to complicated. Can we _please_ get the package up.

https://github.com/microsoft/winget-pkgs/issues/87300

2023-01-27 07:35 UTC, sitiom commented
Please link this PR to #859

2023-01-27 08:12 UTC, sitiom requested changes

2023-01-27 08:12 UTC, sitiom commented on manifests/g/Gyan/CodexFFmpeg/5.1.2/Gyan.CodexFFmpeg.installer.yaml
> +    PortableCommandAlias: ffprobe
Fix `RelativeFilePath`:
```suggestion
  - RelativeFilePath: .\ffmpeg-5.1.2-full_build\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: .\ffmpeg-5.1.2-full_build\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: .\ffmpeg-5.1.2-full_build\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
```

2023-01-27 12:27 UTC, sitiom requested changes
https://github.com/GyanD/codexffmpeg/issues/64#issuecomment-1406424272:
> @GyanD
> The pkg name should be just ffmpeg, not codexffmpeg. The latter is the name of the site.

2023-01-31 17:53 UTC, stephengillie commented
@wingetbot waivers Add Validation-Executable-Error

2023-02-01 00:38 UTC, Trenly approved these changes

2023-02-01 22:51 UTC, stephengillie approved these changes

2023-02-01 22:52 UTC, merged

2023-02-01 23:59 UTC, rlaphoenix commented
After installation the aliases do not work for me. Tried many restarts, pwsh, powershell, and cmd. None work.
The environment path added was `C:\Users\...\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe` but it needs to be `C:\Users\Justin\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-5.1.2-full_build\bin` before it works.

2023-02-01 23:59 UTC, rlaphoenix commented
After installation the aliases do not work for me. Tried many restarts, pwsh, powershell, and cmd. None work.
The environment path added was `C:\Users\...\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe` but it needs to be `C:\Users\...\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-5.1.2-full_build\bin` before it works.

2023-02-02 08:06 UTC, mstevens83 commented
After installation this does not work for me. It seems like the aliases are incorrect.
@rlaphoenix reported the same issue but it seems his post got deleted?

2023-02-02 08:07 UTC, mstevens83 commented
Hi rlaphoenix, I have the same issue. Your post is deleted though, did you
fix the issue yourself? I'm interested to know how.
Regards, Matthias

Op do 2 feb. 2023 om 00:59 schreef rlaphoenix ***@***.***>:

> After installation the aliases do not work for me. Tried many restarts,
> pwsh, powershell, and cmd. None work.
> The environment path added was
> C:\Users\...\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe
> but it needs to be
> C:\Users\Justin\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-5.1.2-full_build\bin
> before it works.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/winget-pkgs/pull/87327#issuecomment-1412924728>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAVIP2ORGO6GQPAO3KMGZWTWVL2F5ANCNFSM6AAAAAARV46M6E>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-02-02 08:11 UTC, sitiom commented
Works fine.
![image](https://user-images.githubusercontent.com/56180050/216267783-af9262c9-4947-4307-ad9d-64c9a4f71077.png)

2023-02-02 08:37 UTC, rlaphoenix commented
> After installation this does not work for me. It seems like the aliases are incorrect. @rlaphoenix reported the same issue but it seems his post got deleted?

I deleted as I moved discussion to https://github.com/microsoft/winget-pkgs/issues/95349 and I invite you guys to as well.