New version: Vromans.ChordPro version 5.990.0.1
microsoft/winget-pkgs pull request #87438
Opened 2022-11-03 17:05 UTC by vedantmgoyal2009

### Result: Installation Failed
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | ChordPro |     |
| Version     | 5.990.0.1     |  |
| Publisher   | ChordPro.ORG   |       |
| ProductCode |           |     |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [3633](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/3387480327>)

2022-11-05 01:56 UTC, Trenly requested changes

2022-11-05 01:56 UTC, Trenly commented on manifests/v/Vromans/ChordPro/5.990.0.1/Vromans.ChordPro.locale.en-US.yaml
> +PackageVersion: 5.990.0.1
```suggestion
PackageVersion: 5.990.0.1.0
```

2022-11-05 01:56 UTC, Trenly commented on manifests/v/Vromans/ChordPro/5.990.0.1/Vromans.ChordPro.installer.yaml
> +PackageVersion: 5.990.0.1
```suggestion
PackageVersion: 5.990.0.1.0
```

2022-11-05 01:56 UTC, Trenly commented on manifests/v/Vromans/ChordPro/5.990.0.1/Vromans.ChordPro.yaml
> +PackageVersion: 5.990.0.1
```suggestion
PackageVersion: 5.990.0.1.0
```

2022-11-08 22:10 UTC, ItzLevvie approved these changes

2022-11-08 22:32 UTC, merged