New version: Glodon.CADReader.CN version 5.17.3.88
microsoft/winget-pkgs pull request #87490
Opened 2022-11-04 06:58 UTC by vedantmgoyal2009

### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | CAD快速看图 | CAD快速看图v5.17.3.88    |
| Version     | 5.17.3.88     |  |
| Publisher   | 广联达科技股份有限公司   | 广联达科技股份有限公司      |
| ProductCode |           | {DDD659B5-6B07-4F5A-A0D3-9E8D3147E165}_is1    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [3644](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/3391716898>)

2022-11-05 01:21 UTC, Trenly requested changes

2022-11-05 01:21 UTC, Trenly commented on manifests/g/Glodon/CADReader/CN/5.17.3.88/Glodon.CADReader.CN.installer.yaml
> +- Architecture: x86
Probably needs AppsAndFeaturesEntries for matching by the DisplayName

2022-11-08 21:46 UTC, ItzLevvie approved these changes, later dismissed

2022-11-09 23:39 UTC, ItzLevvie approved these changes

2022-11-10 00:17 UTC, merged