New package: UrBackup.UrBackup.Server version 2.5.26
microsoft/winget-pkgs pull request #87527
Opened 2022-11-04 13:57 UTC by solomoncyj

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/87527)

2022-11-04 22:03 UTC, Trenly requested changes

2022-11-04 22:03 UTC, Trenly commented on manifests/u/UrBackup/UrBackup/Server/2.5.26/UrBackup.UrBackup.Server.installer.yaml
> +  InstallerSha256: 911D2325D55AEC1F2BE1C09EC983CC9562A4F40B4834E7F6B518FFD909073893
```suggestion
  InstallerSha256: 911D2325D55AEC1F2BE1C09EC983CC9562A4F40B4834E7F6B518FFD909073893
  AppsAndFeaturesEntries:
  - DisplayName: UrBackupServer (remove only)
```

2022-11-04 22:03 UTC, Trenly commented on manifests/u/UrBackup/UrBackup/Server/2.5.26/UrBackup.UrBackup.Server.locale.en-US.yaml
> +PackageName: UrBackup Server
```suggestion
PackageName: UrBackupServer
```

2022-11-07 20:52 UTC, stephengillie approved these changes

2022-11-07 20:54 UTC, merged