DellInc.Command.Monitor version 10.8.0.284
microsoft/winget-pkgs pull request #87528
Opened 2022-11-04 14:43 UTC by svenriebedell

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-11-04 17:25 UTC, Trenly requested changes

2022-11-04 17:25 UTC, Trenly commented on manifests/d/DellInc/Command/Monitor/10.8.0.284/DellInc.Command.Monitor.locale.en-US.yaml
> +- Dell Command
```suggestion
- dell-command
```

2022-11-04 17:25 UTC, Trenly commented on manifests/d/DellInc/Command/Monitor/10.8.0.284/DellInc.Command.Monitor.locale.en-US.yaml
> +PackageIdentifier: DellInc.Command.Monitor
```suggestion
PackageIdentifier: Dell.CommandMonitor
```

2022-11-04 17:25 UTC, Trenly commented on manifests/d/DellInc/Command/Monitor/10.8.0.284/DellInc.Command.Monitor.yaml
> +PackageIdentifier: DellInc.Command.Monitor
```suggestion
PackageIdentifier: Dell.CommandMonitor
```

2022-11-04 17:25 UTC, Trenly commented on manifests/d/DellInc/Command/Monitor/10.8.0.284/DellInc.Command.Monitor.installer.yaml
> +PackageIdentifier: DellInc.Command.Monitor
```suggestion
PackageIdentifier: Dell.CommandMonitor
```

2022-11-04 17:25 UTC, Trenly commented on manifests/d/DellInc/Command/Monitor/10.8.0.284/DellInc.Command.Monitor.installer.yaml
> +  InstallerSwitches:
Please also include SilentWithProgress switch

2022-11-15 22:17 UTC, ItzLevvie approved these changes

2023-12-10 03:55 UTC, closed without merging