New package: UrBackup.UrBackup.Client version 2.5.20
microsoft/winget-pkgs pull request #87526
Opened 2022-11-04 13:49 UTC by solomoncyj

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

2022-11-04 22:04 UTC, Trenly requested changes

2022-11-04 22:04 UTC, Trenly commented on manifests/u/UrBackup/UrBackup/Client/2.5.20/UrBackup.UrBackup.Client.locale.en-US.yaml
> +PackageName: UrBackup Client
```suggestion
PackageName: UrBackup
```

2022-11-04 22:04 UTC, Trenly commented on manifests/u/UrBackup/UrBackup/Client/2.5.20/UrBackup.UrBackup.Client.installer.yaml
> +  InstallerSha256: 01162281156E922EEDCC623A209FF2113D8433C494503962D33547754B8B95A3
```suggestion
  InstallerSha256: 01162281156E922EEDCC623A209FF2113D8433C494503962D33547754B8B95A3
  AppsAndFeaturesEntries:
  - DisplayName: UrBackup (remove only)
```

2022-11-07 20:24 UTC, stephengillie approved these changes

2022-11-07 20:25 UTC, merged