HydrusNetwork.HydrusNetwork version 505b
microsoft/winget-pkgs pull request #88229
Opened 2022-11-12 12:42 UTC by Ryonez

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-11-12 12:44 UTC, Ryonez commented
@microsoft-github-policy-service agree

2022-11-12 18:58 UTC, ItzLevvie requested changes

2022-11-12 18:58 UTC, ItzLevvie commented on manifests/h/HydrusNetwork/HydrusNetwork/505b/HydrusNetwork.HydrusNetwork.installer.yaml
> +PackageVersion: 505b
```suggestion
PackageVersion: v505b
```
This must match Control Panel.

2022-11-12 18:58 UTC, ItzLevvie commented on manifests/h/HydrusNetwork/HydrusNetwork/505b/HydrusNetwork.HydrusNetwork.locale.en-US.yaml
> +PackageVersion: 505b
```suggestion
PackageVersion: v505b
```
This must match Control Panel.

2022-11-12 18:58 UTC, ItzLevvie commented on manifests/h/HydrusNetwork/HydrusNetwork/505b/HydrusNetwork.HydrusNetwork.yaml
> +PackageVersion: 505b
```suggestion
PackageVersion: v505b
```
This must match Control Panel.

2022-11-12 22:46 UTC, Ryonez commented
My apologies Levvie, I'll keep that mind with any further work I do. Changes have been made.

2022-11-12 22:57 UTC, Ryonez commented
Screw it, I can't see an easy way to change the path...
Using wincreate to make a new on here: https://github.com/microsoft/winget-pkgs/pull/88253

2022-11-12 22:57 UTC, closed without merging

2022-11-13 12:51 UTC, mdanish-kh commented
> Screw it, I can't see an easy way to change the path...

fyi: You can do this easily here in GitHub by pressing the <kbd>.</kbd> (dot) key on your keyboard. That'll open up the changes brought in by this PR in VSCode Online where you can easily rename the folder from the explorer menu 
![image](https://user-images.githubusercontent.com/88161975/201522347-bacc3521-33f8-44ed-b434-3530a16c59bb.png)

Once you've made your changes, you can stage and commit them from the Source Control menu on the left (the changes are automatically pushed).

2022-11-14 05:48 UTC, Ryonez commented
Thank you, that is really neat @mdanish-kh. Though I do note it warns me it can't find the source branch for the pull.

2022-11-14 07:20 UTC, mdanish-kh commented
> Thank you, that is really neat @mdanish-kh. Though I do note it warns me it can't find the source branch for the pull.

That's probably because you deleted the branch. The tip was just an fyi for future PRs.

2022-11-14 07:23 UTC, Ryonez commented
Heh, forgot about that.