New version: LinwoodCloud.Butterfly.Nightly version 1.6.0-alpha.1
microsoft/winget-pkgs pull request #89722
Opened 2022-11-25 21:16 UTC by CodeDoctorDE

### Pull request has been automatically created using 🛫 [WinGet Releaser](https://github.com/vedantmgoyal2009/winget-releaser).

2022-11-25 21:37 UTC, russellbanks submitted a review, later dismissed

2022-11-25 22:11 UTC, russellbanks commented
@wingetbot run

2022-12-01 18:31 UTC, stephengillie commented
Hi @CodeDoctorDE,

This prompt pops up during install, despite `scope: machine` being set in `LinwoodCloud.Butterfly.Nightly.installer.yaml`. I couldn't find an installer switch to evade this prompt. Are you aware of one? 

![image](https://user-images.githubusercontent.com/114952565/205132230-6a06651f-cc8f-47d3-a6bf-68011840f858.png)

2022-12-01 18:33 UTC, CodeDoctorDE commented
Oh I see, I use inno setup. I will take a look how I can bypass it

2022-12-03 06:58 UTC, CodeDoctorDE commented
I found out we need to add `/CURRENTUSER` to the command args: https://jrsoftware.org/ishelp/index.php?topic=setup_privilegesrequiredoverridesallowed
How can I add it?

2022-12-05 17:26 UTC, stephengillie commented
@CodeDoctorDE,

Today, Defender finds a trojan in the installer. 
![image](https://user-images.githubusercontent.com/114952565/205702419-80fdc67c-d4b5-45f5-8c47-65bcccd3c556.png)

2022-12-05 18:18 UTC, CodeDoctorDE commented
Hmm, that can't be the case. The app is 100% open-source and I build the app and the installer with github actions

2022-12-05 20:01 UTC, CodeDoctorDE commented
/AzurePipelines run

2022-12-06 08:59 UTC, russellbanks requested changes
Custom covers all cases, not just silent.

2022-12-06 08:59 UTC, russellbanks commented on manifests/l/LinwoodCloud/Butterfly/Nightly/1.6.0-alpha.1/LinwoodCloud.Butterfly.Nightly.installer.yaml
> +    Silent: /CURRENTUSER
```suggestion
    Custom: /CURRENTUSER
```

2022-12-06 09:02 UTC, russellbanks requested changes
The scope needs setting for each installer. It is currently set to machine whilst the installer switch is shown as currentuser. It would be best to keep the machine scope, adding a second entry with the same url with a switch for machine installation.

2022-12-06 09:05 UTC, russellbanks requested changes

2022-12-06 09:05 UTC, russellbanks commented on manifests/l/LinwoodCloud/Butterfly/Nightly/1.6.0-alpha.1/LinwoodCloud.Butterfly.Nightly.installer.yaml
> +Installers:
```suggestion
Installers:
- Architecture: neutral
  Scope: machine
  InstallerUrl: https://github.com/LinwoodCloud/Butterfly/releases/download/v1.6.0-alpha.1/linwood-butterfly-windows-setup.exe
  InstallerSha256: 95AB80E1C47ED0FEDB218858AD650F85D6114EFB5F5E65004E22610E82328D9E
  InstallerSwitches:
    Custom: /ALLUSERS
```

2022-12-06 09:05 UTC, russellbanks commented on manifests/l/LinwoodCloud/Butterfly/Nightly/1.6.0-alpha.1/LinwoodCloud.Butterfly.Nightly.installer.yaml
> +- Architecture: neutral
```suggestion
- Architecture: neutral
  Scope: user
```

2022-12-06 09:05 UTC, russellbanks commented on manifests/l/LinwoodCloud/Butterfly/Nightly/1.6.0-alpha.1/LinwoodCloud.Butterfly.Nightly.installer.yaml
> +Scope: machine
```suggestion
```

2022-12-06 09:29 UTC, CodeDoctorDE commented
Oh thanks. I think two installers will confuse people.

2022-12-06 13:36 UTC, CodeDoctorDE commented
Finally 🎉

2022-12-06 14:40 UTC, russellbanks approved these changes

2022-12-06 14:40 UTC, ghost approved these changes

2022-12-06 16:01 UTC, merged