Submitting RoslynPad version 17.0.0
microsoft/winget-pkgs pull request #90739
Opened 2022-12-07 09:34 UTC by aelij

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-12-07 13:29 UTC, Trenly requested changes

2022-12-07 13:30 UTC, Trenly commented
@msftbot zip

2022-12-07 13:32 UTC, aelij commented on manifests/r/RoslynPad/RoslynPad/17.0.0/RoslynPad.RoslynPad.yaml
> +ManifestType: singleton
Is that required? The docs say that's needed only for multi-locale packages:

> The singleton format is only valid for packages containing a single installer and a single locale. If more than one installer or locale is provided, the multiple YAML file format and schema must be used.

2022-12-07 13:35 UTC, Trenly commented on manifests/r/RoslynPad/RoslynPad/17.0.0/RoslynPad.RoslynPad.yaml
> +ManifestType: singleton
While it still works, the multi-manifest format is preferred as it is easiest for maintaining / upgrading in the future.
https://github.com/microsoft/winget-pkgs/blob/695e87ea5e657a4b9be7446b8f8b8c8d283a2fd1/doc/manifest/schema/1.2.0/singleton.md?plain=1#L18

2022-12-07 13:46 UTC, aelij commented
@Trenly the validation is failing because I've used schema version 1.4.0 (needed to support zip). Can this PR be merged now or do I need to wait for a non-preview release of winget that supports it?

2022-12-07 15:10 UTC, aelij commented on manifests/r/RoslynPad/RoslynPad/17.0.0/RoslynPad.RoslynPad.yaml
> +ShortDescription: C# editor and runner based on Roslyn
BTW this is not required since YAML requires a whitespace before a comment

2022-12-07 15:21 UTC, Trenly commented
> @Trenly the validation is failing because I've used schema version 1.4.0 (needed to support zip). Can this PR be merged now or do I need to wait for a non-preview release of winget that supports it?

https://github.com/microsoft/winget-pkgs/issues/87300

@msftbot zip

2022-12-09 09:25 UTC, ItzLevvie approved these changes, later dismissed

2023-02-09 04:54 UTC, Trenly commented
[Policy] Reset Feedback

2023-02-09 04:54 UTC, Trenly commented
@wingetbot run

2023-02-09 05:52 UTC, Trenly commented
[Policy] Dependencies

Has a runtime Dependency on Dotnet.Desktop.Runtime.7
![image](https://user-images.githubusercontent.com/12611259/217729524-14378f31-283a-4ffb-9b7d-c8d3223879b5.png)

2023-02-23 22:41 UTC, Trenly commented
[Policy] Blocking-Issue

2023-02-24 18:18 UTC, aelij commented
@Trenly What is the blocking issue? Also, why does the PR build get canceled?

2023-02-24 18:26 UTC, aelij commented
/AzurePipelines run

2023-02-24 18:30 UTC, Trenly commented
> @Trenly What is the blocking issue? Also, why does the PR build get canceled?

The blocking issue is that .NET Desktop Runtime is a dependency for the application to run. Even though the dependency is in the manifest, Dependency support is still experimental, so until Dependencies are in a stable 1.5 release, the dependencies are a blocking-issue

Not sure why the PR build gets canceled, it just happens sometimes and is a known issue

2023-02-24 18:34 UTC, aelij commented
@Trenly So can I publish it without the Dependency yaml element? The app's docs indicate you have to install the .NET SDK to use it.

2023-02-24 18:36 UTC, Trenly commented
> @Trenly So can I publish it without the Dependency yaml element?

No.

> The app's docs indicate you have to install the .NET SDK to use it.

This is exactly why it is blocked. Because you have to have the .NET SDK, the dependencies are required, but winget only supports dependencies as an experimental feature. Once dependencies are no longer experimental, this PR will be able to be merged

2023-07-23 17:25 UTC, ItzLevvie approved these changes

2023-08-02 20:32 UTC, aelij commented
@ItzLevvie I've updated the package to the latest release. Can this be merged now?

2023-08-03 11:52 UTC, ItzLevvie commented
[Policy] Dependencies

2023-08-03 11:52 UTC, ItzLevvie commented
[Policy] Blocking-Issue

2023-11-28 22:17 UTC, stephengillie commented
Manual Validation ended with: 
![image](https://github.com/microsoft/winget-pkgs/assets/114952565/623e0804-687b-4c26-a0b1-a46e013f8507)

2023-11-28 22:26 UTC, stephengillie commented
Hi @aelij,

This package displays the above message even with `Microsoft.DotNet.AspNetCore.8` preinstalled. Can you help me to find the correct dependency?

2023-11-28 22:52 UTC, aelij commented
@stephengillie the app needs a .NET SDK of any supported version. It should not be a dependency, as the users can choose the version according to their needs.

2023-12-01 21:03 UTC, stephengillie approved these changes

2023-12-01 21:03 UTC, merged