New package: mulaRahul.Keyviz version 1.0.6
microsoft/winget-pkgs pull request #91471
Opened 2022-12-15 06:48 UTC by sitiom

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

2022-12-16 20:01 UTC, stephengillie commented on manifests/m/mulaRahul/Keyviz/1.0.6/mulaRahul.Keyviz.installer.yaml
> +Installers:
```suggestion
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
```

2022-12-16 20:04 UTC, stephengillie commented on manifests/m/mulaRahul/Keyviz/1.0.6/mulaRahul.Keyviz.installer.yaml
> +Installers:
Not sure why the validation pipeline didn't catch this. The installer installs fine, but the program requires VCRedist 2015 to launch. 
![image](https://user-images.githubusercontent.com/114952565/208179731-97c15403-062a-4517-9ac1-19913b9927b8.png)

2022-12-17 10:48 UTC, mdanish-kh requested changes
Version is marketed as `1.0.6` but the version written to ARP/Registry is `1.0.7` (probably a small mistake in the installer). Should be brought up to the publisher to resolve this inconsistency before we accept it into WinGet.

2022-12-17 10:49 UTC, mdanish-kh commented
@msftbot Area-External
@msftbot Blocking-Issue

2022-12-18 13:19 UTC, mdanish-kh commented
@msftbot reset feedback

2022-12-18 13:21 UTC, mdanish-kh approved these changes

2022-12-18 14:01 UTC, merged