New version: Joplin.Joplin version 2.9.17
microsoft/winget-pkgs pull request #91748
Opened 2022-12-18 10:21 UTC by joshuaprince

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-12-18 13:26 UTC, Overrevvv approved these changes, later dismissed

2022-12-18 21:31 UTC, mdanish-kh requested changes

2022-12-18 21:31 UTC, mdanish-kh commented on manifests/j/Joplin/Joplin/2.9.17/Joplin.Joplin.locale.en-US.yaml
> +Copyright: Copyright (c) 2016-2021 Laurent Cozic
```suggestion
Copyright: Copyright (c) 2016-2022 Laurent Cozic
```
Copyright was updated in https://raw.githubusercontent.com/laurent22/joplin/dev/LICENSE

2022-12-18 21:32 UTC, mdanish-kh commented
Also waiting on https://github.com/microsoft/winget-pkgs/pull/91776 to get merged so that duplicate hash conflict gets resolved.

2022-12-19 15:36 UTC, mdanish-kh commented
@wingetbot run

2022-12-19 15:38 UTC, mdanish-kh approved these changes

2022-12-19 16:28 UTC, merged