v2rayA.v2rayA version 2.0.1-1
microsoft/winget-pkgs pull request #92325
Opened 2022-12-27 08:34 UTC by MarksonHon

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-12-27 08:35 UTC, MarksonHon commented
There is an error that I cannot use winget to install version 2.0.1, so I submit it again as version 2.0.1-1.

2022-12-27 17:08 UTC, Trenly requested changes
Please change the existing 2.0.1 manifest to use the new URLs, as the version hasn't changed in control panel, so there is no way for winget to differentiate 2.0.1 and 2.0.1-1

2022-12-27 17:08 UTC, Trenly commented on manifests/v/v2rayA/v2rayA/2.0.1-1/v2rayA.v2rayA.installer.yaml
> +PackageVersion: 2.0.1-1
```suggestion
PackageVersion: 2.0.1
```
Must match control panel due to the already existing versions

2022-12-27 17:08 UTC, Trenly commented on manifests/v/v2rayA/v2rayA/2.0.1-1/v2rayA.v2rayA.locale.en-US.yaml
> +PackageVersion: 2.0.1-1
```suggestion
PackageVersion: 2.0.1
```
Must match control panel due to the already existing versions

2022-12-27 17:08 UTC, Trenly commented on manifests/v/v2rayA/v2rayA/2.0.1-1/v2rayA.v2rayA.yaml
> +PackageVersion: 2.0.1-1
```suggestion
PackageVersion: 2.0.1
```
Must match control panel due to the already existing versions

2022-12-29 16:10 UTC, mdanish-kh requested changes
You would also need to rename the version directory under `manifests/v/v2rayA/v2rayA` from `2.0.1-1` to `2.0.1`.

One quick way to do it would be right here in GitHub Web by pressing the <kbd>.</kbd> (dot) key that'll open this PR in VSCode Online. Find and rename the directory from explorer tab on the left. Afterwards, you can stage and commit your changes from the Source Control tab on the left (the changes are automatically pushed)

2023-01-12 22:03 UTC, closed without merging