adds ruby with devkit 3.2
microsoft/winget-pkgs pull request #92456
Opened 2022-12-28 21:18 UTC by baywet

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2022-12-29 14:37 UTC, baywet commented
This is caused by changes in the installed, I've created an issue to get to the bottom of that https://github.com/oneclick/rubyinstaller2/issues/326

2022-12-29 18:18 UTC, mdanish-kh requested changes
Must match Registry values

2022-12-29 18:39 UTC, mdanish-kh requested changes

2022-12-29 18:39 UTC, mdanish-kh commented on manifests/r/RubyInstallerTeam/RubyWithDevKit/3/2/3.2.0-1/RubyInstallerTeam.RubyWithDevKit.3.2.installer.yaml
> +  SilentWithProgress: /silent /allusers
```suggestion
```
We don't need silent switches when Installer type is set to `inno`. We'll add scope specific flags at the installer level.

2022-12-29 18:39 UTC, mdanish-kh commented on manifests/r/RubyInstallerTeam/RubyWithDevKit/3/2/3.2.0-1/RubyInstallerTeam.RubyWithDevKit.3.2.installer.yaml
> +Scope: machine
```suggestion
```
Going to add scope at the installer level and pass the switches there.

2022-12-29 18:39 UTC, mdanish-kh commented on manifests/r/RubyInstallerTeam/RubyWithDevKit/3/2/3.2.0-1/RubyInstallerTeam.RubyWithDevKit.3.2.installer.yaml
> +  InstallerSha256: D82313EED91F3210C3CFAC42214497477F6919A540C6CA0F237D25C3810040E2
```suggestion
  InstallerSha256: D82313EED91F3210C3CFAC42214497477F6919A540C6CA0F237D25C3810040E2
  Scope: machine
  InstallerSwitches:
    Custom: /ALLUSERS
```

2022-12-29 18:39 UTC, mdanish-kh commented on manifests/r/RubyInstallerTeam/RubyWithDevKit/3/2/3.2.0-1/RubyInstallerTeam.RubyWithDevKit.3.2.installer.yaml
> +    ProductCode: RubyInstaller-3.2-x64-mingw-ucrt_is1
```suggestion
    ProductCode: RubyInstaller-3.2-x64-mingw-ucrt_is1
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-3.2.0-1/rubyinstaller-devkit-3.2.0-1-x64.exe
  InstallerSha256: D82313EED91F3210C3CFAC42214497477F6919A540C6CA0F237D25C3810040E2
  AppsAndFeaturesEntries:
  - DisplayName: Ruby 3.2.0-1-x64
    ProductCode: RubyInstaller-3.2-x64-mingw-ucrt_is1
  Scope: user
  InstallerSwitches:
    Custom: /ALLUSERS
```
Another installer entry for user scope.

2022-12-29 18:39 UTC, mdanish-kh commented on manifests/r/RubyInstallerTeam/RubyWithDevKit/3/2/3.2.0-1/RubyInstallerTeam.RubyWithDevKit.3.2.installer.yaml
> +  InstallerSha256: 891C0F05CDA258049C36ACEF1401B5DD19A7EFB277108D2170DB34C6770AE282
```suggestion
  InstallerSha256: 891C0F05CDA258049C36ACEF1401B5DD19A7EFB277108D2170DB34C6770AE282
  Scope: machine
  InstallerSwitches:
    Custom: /ALLUSERS
```

2022-12-29 18:39 UTC, mdanish-kh commented on manifests/r/RubyInstallerTeam/RubyWithDevKit/3/2/3.2.0-1/RubyInstallerTeam.RubyWithDevKit.3.2.installer.yaml
> +    ProductCode: RubyInstaller-3.2-i386-mingw32_is1
```suggestion
    ProductCode: RubyInstaller-3.2-i386-mingw32_is1
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-3.2.0-1/rubyinstaller-devkit-3.2.0-1-x86.exe
  InstallerSha256: 891C0F05CDA258049C36ACEF1401B5DD19A7EFB277108D2170DB34C6770AE282
  AppsAndFeaturesEntries:
  - DisplayName: Ruby 3.2.0-1-x86
    ProductCode: RubyInstaller-3.2-i386-mingw32_is1
  Scope: user
  InstallerSwitches:
    Custom: /CURRENTUSER
```
Another installer entry for user scope.

2022-12-29 19:52 UTC, baywet commented
@mdanish-kh thanks for the suggestions!

2022-12-29 20:05 UTC, mdanish-kh commented
@baywet Looks like this version just got pulled by the publisher :/ https://github.com/oneclick/rubyinstaller2/releases, The URLs were working an hour or so earlier.

2022-12-29 20:11 UTC, baywet commented
@mdanish-kh noticed that as well. Let's give them a day or two to put it back up, I'll update the hashes if necessary.

2022-12-30 11:59 UTC, larskanis commented
Sorry, I published the binaries, before they were final. But now they are.

2022-12-30 13:05 UTC, baywet commented
@larskanis no worries, thanks for letting us know. I just pushed an update with the updated URLs + hashes. Hopefully this one is the right one, thanks everyone for the help!

2022-12-30 16:25 UTC, mdanish-kh requested changes
@baywet I'm wondering whether this package should now be under `manifests/r/RubyInstallerTeam/Ruby/3/2` as I don't see `devkit` in the InstallerUrl 👀

2022-12-30 16:30 UTC, baywet commented
@mdanish-kh good catch, bad copy paste on my side, fixed.

2022-12-30 16:37 UTC, mdanish-kh approved these changes
No worries :) Looks like we're good to go now

2022-12-30 18:12 UTC, merged