lencx.ChatGPT version 0.7.4
microsoft/winget-pkgs pull request #92812
Opened 2023-01-03 09:33 UTC by manudss

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-01-03 09:35 UTC, manudss commented
@microsoft-github-policy-service agree

2023-01-03 14:11 UTC, KaranKad requested changes

2023-01-03 18:23 UTC, KaranKad requested changes

2023-01-03 18:23 UTC, KaranKad commented on manifests/l/lencx/ChatGPT/0.7.4/lencx.ChatGPT.locale.en-US.yaml
> +PackageName: ChatGPT Desktop Application
```suggestion
PackageName: ChatGPT
```
![image](https://user-images.githubusercontent.com/71691514/210417973-1d6e9330-517a-4af7-b707-acb77d922e20.png)
This should match control panel

2023-01-04 13:37 UTC, KaranKad approved these changes

2023-01-04 13:39 UTC, merged