added: sharkdp/bat/0.22.1
microsoft/winget-pkgs pull request #94719
Opened 2023-01-26 17:13 UTC by neomax7

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-01-26 17:15 UTC, neomax7 commented
manifest version 1.4 with zip

2023-01-26 17:16 UTC, neomax7 commented
@sitiom 
I have corrected the folder name :)

2023-01-26 17:45 UTC, neomax7 commented
v1.4 with zip

2023-01-26 23:20 UTC, sitiom requested changes

2023-01-26 23:20 UTC, sitiom commented on manifests/s/sharkdp/bat/0.22.1/sharkdp.bat.installer.yaml
> +InstallerType: zip
```suggestion
InstallerType: zip
ReleaseDate: 2022-09-11
```

2023-01-26 23:20 UTC, sitiom commented on manifests/s/sharkdp/bat/0.22.1/sharkdp.bat.locale.en-US.yaml
> +ShortDescription: A cat(1) clone with syntax highlighting and Git integration.
```suggestion
Publisher: David Peter
PublisherUrl: https://david-peter.de/
Author: David Peter
PackageName: bat
PackageUrl: https://github.com/sharkdp/bat
License: Apache-2.0, MIT
LicenseUrl: https://github.com/sharkdp/bat#license
Copyright: Copyright (c) 2018-2021 bat-developers
CopyrightUrl: https://github.com/sharkdp/bat#license
ShortDescription: A cat(1) clone with syntax highlighting and Git integration.
Tags:
- cli
- rust
- cat
ReleaseNotesUrl: https://github.com/sharkdp/bat/releases/tag/v0.22.1
```

2023-01-31 05:07 UTC, sitiom requested changes
Requires VCRedist dependency

2023-01-31 05:07 UTC, sitiom commented on manifests/s/sharkdp/bat/0.22.1/sharkdp.bat.installer.yaml
> +    InstallerSha256: 7B66CD89DDDF6872164CD925D4C26A14D4A7DBB6A98983EB8542677CD823358E
```suggestion
    InstallerSha256: 7B66CD89DDDF6872164CD925D4C26A14D4A7DBB6A98983EB8542677CD823358E
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x86
```

2023-01-31 05:07 UTC, sitiom commented on manifests/s/sharkdp/bat/0.22.1/sharkdp.bat.installer.yaml
> +    InstallerSha256: D14028B3579DF7A5E1B85E5B565FFFD33B5E4096DF0C719F98F8381CE1DCCE6D
```suggestion
    InstallerSha256: D14028B3579DF7A5E1B85E5B565FFFD33B5E4096DF0C719F98F8381CE1DCCE6D
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x64
```

2023-02-01 03:14 UTC, sitiom commented
@neomax7 Try closing and reopening all your open PRs so that the validation pipelines are rerun.

2023-02-03 11:43 UTC, closed without merging