AntonyCourtney.Tad version 0.11.0
microsoft/winget-pkgs pull request #95253
Opened 2023-02-01 08:05 UTC by dpprdan

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-02-01 22:47 UTC, stephengillie commented
/azp run

2023-02-06 20:12 UTC, dpprdan commented
/azp run

2023-02-09 04:35 UTC, Trenly requested changes

2023-02-09 04:35 UTC, Trenly commented on manifests/a/AntonyCourtney/Tad/0.11.0/AntonyCourtney.Tad.installer.yaml
> +- Architecture: x86
```suggestion
- Architecture: x64
```
![image](https://user-images.githubusercontent.com/12611259/217718785-065f4606-e453-47f5-b0a7-59ecd097928f.png)

2023-02-14 00:01 UTC, stephengillie approved these changes

2023-02-14 00:01 UTC, merged