New version: Appest.Dida version 4.4.1.0
microsoft/winget-pkgs pull request #95408
Opened 2023-02-02 13:55 UTC by vedantmgoyal2009

### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | 滴答清单 | 滴答清单 版本 4.4.1.0    |
| Version     | 4.4.1.0     | 4.4.1.0 |
| Publisher   | 杭州随笔记网络技术有限公司   | 杭州随笔记网络技术有限公司      |
| ProductCode |           | {1A434D02-8C9A-41A2-9BBE-C97A1E31ABC1}_is1    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [5719](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/4074835636>)

2023-02-07 23:22 UTC, stephengillie commented
/AzurePipelines run

2023-02-08 19:22 UTC, rodrigoborgesdeoliveira requested changes

2023-02-08 19:22 UTC, rodrigoborgesdeoliveira commented on manifests/a/Appest/Dida/4.4.1.0/Appest.Dida.installer.yaml
> +  InstallerSha256: 5E01556B4F0EA6D0C6D3BB96DEA064DCBF2E5FAD87F6BB1D1C71DB9120EB9761
```suggestion
  InstallerSha256: 0BD707696BAB9572CA606F91170494BAF5499C3BE8509DC914299DDDC7D1D03E
```

2023-02-08 19:22 UTC, rodrigoborgesdeoliveira commented on manifests/a/Appest/Dida/4.4.1.0/Appest.Dida.installer.yaml
> +  InstallerSha256: A4175507F2D3AD73C8A9AF84AEF9C4AB515E3718FC201B9245D6FA21535F889E
```suggestion
  InstallerSha256: 116AAD8AC3CCB8289FA7884C7C18E7892B1F7AE3401401DFC5A5CC4F6305963B
```

2023-02-17 20:09 UTC, ItzLevvie commented
Close with reason: Merge conflicts;

2023-02-17 20:09 UTC, closed without merging