Update: Neovim.Neovim.Nightly version 0.9.0
microsoft/winget-pkgs pull request #95641
Opened 2023-02-05 05:28 UTC by nvim-winget

### Pull request has been automatically created using 🛫 [WinGet Releaser](https://github.com/vedantmgoyal2009/winget-releaser).

2023-02-05 15:40 UTC, russellbanks approved these changes

2023-02-06 20:06 UTC, stephengillie commented
/azp run

2023-02-06 21:22 UTC, rodrigoborgesdeoliveira requested changes

2023-02-06 21:22 UTC, rodrigoborgesdeoliveira commented on manifests/n/Neovim/Neovim/Nightly/0.9.0/Neovim.Neovim.Nightly.installer.yaml
> +  InstallerSha256: 321E345E00AFE420E356E34B755FFC9D9F821272BC31B4E6F8988852AFD61A5E
```suggestion
  InstallerSha256: 0cc957c2053b75deefdba32ddb65a4293d7818c36891f0da4f7982aa962594f8
```

2023-02-06 21:22 UTC, rodrigoborgesdeoliveira commented on manifests/n/Neovim/Neovim/Nightly/0.9.0/Neovim.Neovim.Nightly.installer.yaml
> +  InstallerSha256: 321E345E00AFE420E356E34B755FFC9D9F821272BC31B4E6F8988852AFD61A5E
The product code might have changed as well.

2023-02-08 19:26 UTC, russellbanks commented
Close with reason: superseded by #95845;

2023-02-09 00:25 UTC, Trenly commented
Close with reason: Cleanup of merge conflicts from fabricbot errors;

2023-02-09 00:25 UTC, closed without merging