AntiMicroX.antimicrox version 3.3.3
microsoft/winget-pkgs pull request #95821
Opened 2023-02-07 16:53 UTC by afermar

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-02-07 20:37 UTC, stephengillie commented on manifests/a/AntiMicroX/antimicrox/3.3.3/AntiMicroX.antimicrox.locale.en-US.yaml
> +PackageName: AntiMicroX
```suggestion
PublisherUrl: https://github.com/AntiMicroX
PublisherSupportUrl: https://github.com/AntiMicroX/antimicrox/issues
PackageName: AntiMicroX
PackageUrl: https://github.com/AntiMicroX/antimicrox
License: GPL v3
LicenseUrl: https://github.com/AntiMicroX/antimicrox/blob/master/LICENSE
```

2023-02-07 23:36 UTC, stephengillie commented on manifests/a/AntiMicroX/antimicrox/3.3.3/AntiMicroX.antimicrox.locale.en-US.yaml
> +License: GPL v3
```suggestion
```

2023-02-07 23:37 UTC, stephengillie commented on manifests/a/AntiMicroX/antimicrox/3.3.3/AntiMicroX.antimicrox.locale.en-US.yaml
> +License: GPL v3
Apologies, I missed that the license was already added.

2023-02-08 23:41 UTC, denelon commented
/azp run

2023-02-10 16:56 UTC, Trenly requested changes
```
--> Comparing ARP Entries

DisplayName DisplayVersion Publisher ProductCode
----------- -------------- --------- -----------
AntiMicroX  3.3.3          Humanity  AntiMicroX
```

2023-02-10 16:56 UTC, Trenly commented on manifests/a/AntiMicroX/antimicrox/3.3.3/AntiMicroX.antimicrox.locale.en-US.yaml
> +Publisher: AntiMicroX
```suggestion
Publisher: Humanity
```
This should match Control Panel

2023-02-10 18:04 UTC, Trenly approved these changes

2023-02-10 18:05 UTC, merged