Olympus.Olympus version 21.01.11.07
microsoft/winget-pkgs pull request #95906
Opened 2023-02-08 17:12 UTC by lemonjacob

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-02-09 21:15 UTC, Trenly commented
@lemonjacob - I'm not sure what happened, but anytime I try to check out the commit to test it, I get `fatal: reference is not a tree: 028644f4fa8de97784ce4022c5af7cf9cd8adbf2`. Is there any way you could try re-pushing to the branch?

2023-02-10 03:09 UTC, lemonjacob commented
> @lemonjacob - I'm not sure what happened, but anytime I try to check out the commit to test it, I get `fatal: reference is not a tree: 028644f4fa8de97784ce4022c5af7cf9cd8adbf2`. Is there any way you could try re-pushing to the branch?

I think I fixed it

2023-02-10 03:10 UTC, Trenly commented
> > @lemonjacob - I'm not sure what happened, but anytime I try to check out the commit to test it, I get `fatal: reference is not a tree: 028644f4fa8de97784ce4022c5af7cf9cd8adbf2`. Is there any way you could try re-pushing to the branch?
> 
> I think I fixed it

Thanks! Looks like git is detecting it as a valid tree now, will test!

2023-02-10 03:18 UTC, Trenly requested changes
[Policy] Dependencies
@Stephengillie / @denelon - Hardware too please

![image](https://user-images.githubusercontent.com/12611259/217990951-2b520fda-ee55-428c-8e9e-fe0782850a0f.png)

2023-02-10 03:18 UTC, Trenly commented on manifests/o/Olympus/Olympus/21.01.11.07/Olympus.Olympus.installer.yaml
> +PackageIdentifier: Olympus.Olympus
```suggestion
PackageIdentifier: EverestAPI.Olympus
```

2023-02-10 03:18 UTC, Trenly commented on manifests/o/Olympus/Olympus/21.01.11.07/Olympus.Olympus.locale.en-US.yaml
> +PackageIdentifier: Olympus.Olympus
```suggestion
PackageIdentifier: EverestAPI.Olympus
```

2023-02-10 03:18 UTC, Trenly commented on manifests/o/Olympus/Olympus/21.01.11.07/Olympus.Olympus.yaml
> +PackageIdentifier: Olympus.Olympus
```suggestion
PackageIdentifier: EverestAPI.Olympus
```

2023-02-10 03:18 UTC, Trenly commented on manifests/o/Olympus/Olympus/21.01.11.07/Olympus.Olympus.installer.yaml
> +  Dependencies:
Dependencies currently aren't supported.

2023-02-10 03:19 UTC, Trenly commented
[Policy] Dependencies

2023-02-10 03:41 UTC, closed without merging