ndd开源组织.Notepad-- version 1.22.1
microsoft/winget-pkgs pull request #95958
Opened 2023-02-09 07:39 UTC by rtrobin

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-02-09 07:41 UTC, rtrobin commented
@microsoft-github-policy-service agree

2023-02-09 13:56 UTC, Trenly requested changes

2023-02-09 13:56 UTC, Trenly commented on manifests/n/ndd开源组织/Notepad--/1.22.1/ndd开源组织.Notepad--.locale.en-US.yaml
> +PublisherSupportUrl: https://github.com/cxasm/notepad--
Support URL should not be the same as Package URL

2023-02-09 13:56 UTC, Trenly commented on manifests/n/ndd开源组织/Notepad--/1.22.1/ndd开源组织.Notepad--.locale.en-US.yaml
> +PrivacyUrl: https://github.com/cxasm/notepad--
Privacy URL should not be the same as PackageURL

2023-02-09 13:56 UTC, Trenly commented on manifests/n/ndd开源组织/Notepad--/1.22.1/ndd开源组织.Notepad--.locale.en-US.yaml
> +PublisherUrl: https://github.com/cxasm/notepad--
Publisher URL should not be the same as Package URL

2023-02-09 13:56 UTC, Trenly commented on manifests/n/ndd开源组织/Notepad--/1.22.1/ndd开源组织.Notepad--.locale.en-US.yaml
> +Copyright: https://github.com/cxasm/notepad--/blob/main/LICENSE
This needs to be the actual copyright text, not a link to it

2023-02-09 13:56 UTC, Trenly commented on manifests/n/ndd开源组织/Notepad--/1.22.1/ndd开源组织.Notepad--.locale.en-US.yaml
> +ShortDescription: Notepad-- Setup
Please provide a better description of what Notepad-- does

2023-02-09 13:56 UTC, Trenly commented on manifests/n/ndd开源组织/Notepad--/1.22.1/ndd开源组织.Notepad--.locale.en-US.yaml
> +Description: https://github.com/cxasm/notepad--/blob/main/LICENSE
Description should not be a URL

2023-02-09 13:56 UTC, Trenly commented on manifests/n/ndd开源组织/Notepad--/1.22.1/ndd开源组织.Notepad--.locale.en-US.yaml
> +ReleaseNotesUrl: https://github.com/cxasm/notepad--/releases
This should be a direct link to the release notes for this version

2023-02-09 13:56 UTC, Trenly commented on manifests/n/ndd开源组织/Notepad--/1.22.1/ndd开源组织.Notepad--.installer.yaml
> +  InstallerSha256: CBC55446BE8C03395CCC8E9FF2C3EDEC3F23F2DDD314230819653FA1EE59F2CA
```suggestion
Installers:
- InstallerUrl: https://github.com/cxasm/notepad--/releases/download/Notepad--v1.22/Notepad--v1.22.1-Installer.exe
  Architecture: x64
  InstallerType: inno
  InstallerSha256: CBC55446BE8C03395CCC8E9FF2C3EDEC3F23F2DDD314230819653FA1EE59F2CA
  Scope: machine
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerUrl: https://github.com/cxasm/notepad--/releases/download/Notepad--v1.22/Notepad--v1.22.1-Installer.exe
  Architecture: x64
  InstallerType: inno
  InstallerSha256: CBC55446BE8C03395CCC8E9FF2C3EDEC3F23F2DDD314230819653FA1EE59F2CA
  Scope: user
  InstallerSwitches:
    Custom: /CURRENTUSER
```

2023-02-10 22:40 UTC, Trenly approved these changes

2023-02-10 22:40 UTC, merged