Upgrade fix - Splashtop.SplashtopStreamer Version: 3.5.4.0
microsoft/winget-pkgs pull request #96227
Opened 2023-02-11 06:30 UTC by NJT145

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-02-11 07:32 UTC, OverRevvv approved these changes

2023-02-12 13:52 UTC, OverRevvv approved these changes

2023-02-12 20:16 UTC, mdanish-kh requested changes

2023-02-12 20:16 UTC, mdanish-kh commented on manifests/s/Splashtop/SplashtopStreamer/3.5.4.0/Splashtop.SplashtopStreamer.installer.yaml
> +UpgradeBehavior: uninstallPrevious
```suggestion
UpgradeBehavior: install
AppsAndFeaturesEntries:
- InstallerType: msi
  ProductCode: '{B7C5EA94-B96A-41F5-BE95-25D78B486678}'
```
The upgrade failure is due to installer technology mismatch. The logs say that 
```
2023-02-12 11:52:34.091 [CLI ] Installer [X86,exe,Machine,en-US] not applicable: Installed package type 'msi' is not compatible with installer type exe
```
The application is actually an msi installer packaged into an exe. Setting the InstallerType to msi should resolve the issue as I've manually tested it in a VM.

2023-02-13 00:41 UTC, closed without merging