MineOnline.MineOnline version 4.8.8
microsoft/winget-pkgs pull request #96220
Opened 2023-02-11 03:03 UTC by robinuniverse

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-02-11 03:07 UTC, robinuniverse commented
@microsoft-github-policy-service agree

2023-02-11 20:00 UTC, Trenly requested changes
Since this is a repackaged exe, I don't believe we can accept it, given that it doesn't come from the original publisher

2023-02-11 23:03 UTC, robinuniverse commented
> Since this is a repackaged exe, I don't believe we can accept it, given that it doesn't come from the original publisher

Would it make it kosher if I were to set the source of the MSI download from the MineOnline repo itself? I am a contributor and could probably swing it, but I didn't want to gum up the original repo

2023-02-12 13:53 UTC, OverRevvv approved these changes

2023-02-14 00:44 UTC, stephengillie commented
This package requires a version of the Java Runtime Environment, possibly from the package `Oracle.JavaRuntimeEnvironment`, to run. 
![image](https://user-images.githubusercontent.com/114952565/218608539-df161382-fc77-4e2c-977b-8f064bb7a73f.png)

2023-02-14 02:35 UTC, robinuniverse commented
> This package requires a version of the Java Runtime Environment, possibly from the package `Oracle.JavaRuntimeEnvironment`, to run. ![image](https://user-images.githubusercontent.com/114952565/218608539-df161382-fc77-4e2c-977b-8f064bb7a73f.png)

Looks like I still have more to learn about packaging MSI's! I will see about including a JRE redist in the binary as part of the install process next weekend and report back on my progress here. thank you for your time 👍

2023-12-15 19:37 UTC, stephengillie commented
/AzurePipelines run

2023-12-15 20:45 UTC, stephengillie commented
/AzurePipelines run

2023-12-28 22:21 UTC, stephengillie commented on manifests/m/MineOnline/MineOnline/4.8.8/MineOnline.MineOnline.installer.yaml
> +PackageVersion: 4.8.8
```suggestion
PackageVersion: 4.8.8
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Oracle.JavaRuntimeEnvironment
```

2024-01-06 05:16 UTC, closed without merging