Add LightZoneProject.LightZone
microsoft/winget-pkgs pull request #96448
Opened 2023-02-13 03:33 UTC by ktgw0316

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-02-13 21:06 UTC, mdanish-kh requested changes

2023-02-13 21:06 UTC, mdanish-kh commented on manifests/l/LightZoneProject/LightZone/4.2.4/LightZoneProject.LightZone.locale.en-US.yaml
> +PublisherUrl: https://github.com/ktgw0316/LightZone/
```suggestion
PublisherUrl: https://github.com/ktgw0316/
```

2023-02-13 21:06 UTC, mdanish-kh commented on manifests/l/LightZoneProject/LightZone/4.2.4/LightZoneProject.LightZone.locale.en-US.yaml
> +PackageUrl: https://github.com/ktgw0316/LightZone/releases/download/4.2.4/LightZone_Installer_4.2.4_20220227_windows-x64.exe
```suggestion
PackageUrl: https://github.com/ktgw0316/LightZone
```

2023-02-13 21:06 UTC, mdanish-kh commented on manifests/l/LightZoneProject/LightZone/4.2.4/LightZoneProject.LightZone.locale.en-US.yaml
> +ShortDescription: a professional-level digital darkroom and photo editor
```suggestion
ShortDescription: A professional-level digital darkroom and photo editor.
```

2023-02-13 21:06 UTC, mdanish-kh commented on manifests/l/LightZoneProject/LightZone/4.2.4/LightZoneProject.LightZone.locale.en-US.yaml
> +License: BSD-3-Clause
```suggestion
License: BSD-3-Clause
LicenseUrl: https://github.com/ktgw0316/LightZone/blob/master/COPYING
```

2023-02-14 03:05 UTC, ktgw0316 commented on manifests/l/LightZoneProject/LightZone/4.2.4/LightZoneProject.LightZone.installer.yaml
> +PackageVersion: 4.2.4
> If you're the developer of the package, I would highly recommend writing a DisplayVersion String to Registry

Thank you for the great suggestion!  I'll add it in next release of the package.

2023-02-14 13:32 UTC, mdanish-kh approved these changes

2023-02-14 13:33 UTC, merged