New version: ULAB.PaintAid version 2.3.4.1
microsoft/winget-pkgs pull request #96938
Opened 2023-02-16 15:12 UTC by SpecterShell

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

2023-02-16 16:00 UTC, ItzLevvie approved these changes, later dismissed

2023-02-16 18:24 UTC, rodrigoborgesdeoliveira requested changes

2023-02-16 18:24 UTC, rodrigoborgesdeoliveira commented on manifests/u/ULAB/PaintAid/2.3.4.1/ULAB.PaintAid.installer.yaml
> +  InstallerSha256: 901DEE2C9F5574FFBF8546BC8EBA68F17702A309DC964BA9A493D9A3DCC5F546
Hi @SpecterShell, this is the correct hash for this installer.
```suggestion
  InstallerSha256: E351BF44E556AB72DFC91FE19111BA8064912EB83F7EE36CF803A6339FC410BB
```

2023-02-17 00:09 UTC, ItzLevvie commented
@wingetbot run

2023-02-17 00:30 UTC, ItzLevvie commented
@wingetbot run

2023-02-17 02:04 UTC, ItzLevvie approved these changes

2023-02-17 03:11 UTC, merged