NicoJeskeIT.MasterVolumeSync version 1.0.7
microsoft/winget-pkgs pull request #97643
Opened 2023-02-23 20:05 UTC by nicojeske

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-02-23 20:06 UTC, nicojeske commented
@microsoft-github-policy-service agree

2023-02-24 19:21 UTC, mdanish-kh requested changes
Note: The metadata comments are optional for you to include but they would make for a more complete manifest.

2023-02-24 19:21 UTC, mdanish-kh commented on manifests/n/NicoJeskeIT/MasterVolumeSync/1.0.7/NicoJeskeIT.MasterVolumeSync.locale.en-US.yaml
> +PackageName: Master Volume Sync
```suggestion
PackageName: MasterVolumeSync
PackageUrl: https://github.com/nicojeske/MasterVolumeSync
```
Should match Control Panel / Apps&Features / Registry's `DisplayName` key as WinGet relies on the metadata from registry for matching upgrades.

Also suggested additional metadata.

2023-02-24 19:21 UTC, mdanish-kh commented on manifests/n/NicoJeskeIT/MasterVolumeSync/1.0.7/NicoJeskeIT.MasterVolumeSync.locale.en-US.yaml
> +Publisher: Nico Jeske IT
```suggestion
Publisher: Nico Jeske IT
PublisherUrl: https://nicojeske.de/
PublisherSupportUrl: https://github.com/nicojeske/MasterVolumeSync/issues
```
Additional metadata

2023-02-24 19:21 UTC, mdanish-kh commented on manifests/n/NicoJeskeIT/MasterVolumeSync/1.0.7/NicoJeskeIT.MasterVolumeSync.locale.en-US.yaml
> +License: MIT License
```suggestion
License: MIT License
LicenseUrl: https://github.com/nicojeske/MasterVolumeSync/blob/master/LICENSE.MD
Copyright: Copyright (c) 2022 Nico Jeske
CopyrightUrl: https://github.com/nicojeske/MasterVolumeSync/blob/master/LICENSE.MD
ReleaseNotes: |-
  - Muting the selected output device will now also mute the "What u hear" device. (#3)
ReleaseNotesUrl: https://github.com/nicojeske/MasterVolumeSync/releases/tag/1.0.7
```
Additional metadata

2023-02-24 19:21 UTC, mdanish-kh commented on manifests/n/NicoJeskeIT/MasterVolumeSync/1.0.7/NicoJeskeIT.MasterVolumeSync.installer.yaml
> +PackageVersion: 1.0.7
```suggestion
PackageVersion: 1.0.7
ReleaseDate: 2022-06-25
```
Additional metadata

2023-02-24 20:39 UTC, nicojeske commented
Thank you, @mdanish-kh, for your review. Your feedback is greatly appreciated. I must admit that I was not aware of all the metadata fields that you pointed out. I had assumed that wingetcreate would inform me about possible additional metadata.

I did end up removing the PublisherURL field, as the pipeline did seem to have problems connecting to the site (403 forbidden). This access seems to be blocked by Cloudflare, as my internal monitoring shows no 403 response from the website.

2023-02-25 10:46 UTC, mdanish-kh commented
> I had assumed that wingetcreate would inform me about possible additional metadata.

wingetcreate is designed to let publishers quickly create and submit a manifest with the required fields. If you wish to have a detailed manifest, you could use another manifest authoring tool supported by the WinGet team [YamlCreate.ps1](https://github.com/microsoft/winget-pkgs/blob/master/doc/tools/YamlCreate.md).
 
> I did end up removing the PublisherURL field, as the pipeline did seem to have problems connecting to the site (403 forbidden). This access seems to be blocked by Cloudflare, as my internal monitoring shows no 403 response from the website.

In that case, you could update it to link to your GitHub profile if you wish to.

2023-02-25 10:47 UTC, mdanish-kh approved these changes

2023-02-25 10:47 UTC, merged