donkrage.regpack version 1.51
microsoft/winget-pkgs pull request #97700
Opened 2023-02-24 16:21 UTC by donkrage

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-02-24 18:23 UTC, stephengillie commented on manifests/d/donkrage/regpack/1.51/donkrage.regpack.locale.en-US.yaml
> +PackageName: regpack
```suggestion
PackageName: regpack
PackageUrl: https://github.com/donkrage/regpack
```

2023-02-24 18:24 UTC, stephengillie commented
@wingetbot waivers Add Validation-No-Executables

2023-02-28 03:08 UTC, Trenly commented
I get a 404 when testing

2023-03-02 15:57 UTC, Trenly requested changes
This application doesn't seem to write any entries to Control panel, so there is no way for winget to know if it is installed or not

2023-03-07 16:03 UTC, stephengillie commented
/AzurePipelines run

2023-03-27 11:31 UTC, ItzLevvie commented
Close with reason: Stale pull request;

2023-03-27 11:31 UTC, closed without merging