CPUID.CPU-Z version 2.05
microsoft/winget-pkgs pull request #98117
Opened 2023-03-01 17:17 UTC by BigThunderSR

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/98117)

2023-03-01 18:12 UTC, mdanish-kh requested changes

2023-03-01 18:12 UTC, mdanish-kh commented on manifests/c/CPUID/CPU-Z/2.05/CPUID.CPU-Z.locale.en-US.yaml
> +  - Preliminary support for NVIDIA RTX 4000 GPUs
```suggestion
ReleaseNotes: |-
  - Intel Xeon Sapphire Rapids platform.
  - Preliminary support for AMD Storm Peak platform.
  - Zhaoxin KX-6000G/4 CPU.
  - Intel Core i9-13900/K/F/KF, Core i7-13700/K/F/KF, Core i5-13600/K/F/KF, Core i5-13500, 
    Core i5-13400 and Core i3-13100
  - Intel ARC A770, A750, A580 (ACM-G10) and A380 (ACM-G11) GPUs
  - Support for multipliers > 64x on AMD Ryzen 7000
  - Preliminary support for NVIDIA RTX 4000 GPUs
```
Full ReleaseNotes

2023-03-01 18:13 UTC, mdanish-kh commented on manifests/c/CPUID/CPU-Z/2.05/CPUID.CPU-Z.installer.yaml
> +UpgradeBehavior: install
```suggestion
UpgradeBehavior: install
ReleaseDate: 2023-03-01
```

2023-03-01 18:23 UTC, mdanish-kh requested changes
If we're adding ReleaseNotes, we should add them exactly as they are written in the website; https://github.com/microsoft/winget-pkgs/pull/98117#discussion_r1122136475

2023-03-01 19:13 UTC, mdanish-kh requested changes

2023-03-01 19:13 UTC, mdanish-kh commented on manifests/c/CPUID/CPU-Z/2.05/CPUID.CPU-Z.installer.yaml
> +ReleaseDate: 2023-03-01
```suggestion
```
My apologies, I did not see the ReleaseDate was already present at the end of file

2023-03-01 19:22 UTC, mdanish-kh approved these changes

2023-03-01 20:17 UTC, merged

2023-03-13 16:38 UTC, hez2010 commented
The sha256 in the manifest is incorrect. Now we can no longer install CPU-Z due to hash mismatch.