Pikcube.OrangeJuiceModMaker version 0.9.6
microsoft/winget-pkgs pull request #98139
Opened 2023-03-01 22:20 UTC by pikcube

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-03-02 02:52 UTC, stephengillie commented
Hi @pikcube,

The program is prompting for install location:
![image](https://user-images.githubusercontent.com/114952565/222318668-fe6ea1b1-e2fb-4a4f-a693-0a92ba287038.png)

Is there an installer switch to specify the location and bypass the prompt?

2023-03-02 04:16 UTC, Trenly commented
@stephengillie - Try `/ALLUSERS` for machine scope and `/CURRENTUSER` for user scope, since that is an inno installer

2023-03-02 22:33 UTC, pikcube commented
And that's what I get for not remembering to uninstall my app before testing it. @Trenly is spot on, that's what needed fixed. I tested it on my local copy and I just fixed it on GitHub so we'll see if it runs now.

2023-03-02 22:34 UTC, pikcube commented
I didn't find an option for a scope switch in winget so I added /AllUsers as a Custom switch, but if there is a way to change that I can.

2023-03-02 23:26 UTC, Trenly requested changes

2023-03-02 23:26 UTC, Trenly commented on manifests/p/Pikcube/OrangeJuiceModMaker/0.9.6/Pikcube.OrangeJuiceModMaker.installer.yaml
> +    Custom: /AllUsers
```suggestion
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/pikcube/OrangeJuiceModMaker/releases/download/v0.9.6/OJSetup.exe
  InstallerSha256: 545112664F22CD6D2A03AD8643D641241EE8FC7CD34823E4A6AA46BC9D75A4C6
  InstallerSwitches:
    Silent: /SILENT
    Custom: /ALLUSERS
  Scope: machine
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/pikcube/OrangeJuiceModMaker/releases/download/v0.9.6/OJSetup.exe
  InstallerSha256: 545112664F22CD6D2A03AD8643D641241EE8FC7CD34823E4A6AA46BC9D75A4C6
  InstallerSwitches:
    Silent: /SILENT
    Custom: /CURRENTUSER
  Scope: user
```

2023-03-02 23:28 UTC, Trenly commented
Being inno, the silent switch should already be known by the cli; Using the custom switch is correct for the scope, but the actual Scope also needs to be specified for the installer. Adding a second installer node (as shown in the suggestion) can be used to account for both the user scope and machine scope

2023-03-02 23:41 UTC, pikcube commented
> Being inno, the silent switch should already be known by the cli; Using the custom switch is correct for the scope, but the actual Scope also needs to be specified for the installer. Adding a second installer node (as shown in the suggestion) can be used to account for both the user scope and machine scope

That was exactly what I was trying to do, thank you!

2023-03-03 00:22 UTC, pikcube commented
/AzurePipelines run

2023-03-03 03:28 UTC, stephengillie commented
/AzurePipelines run

2023-03-03 03:50 UTC, stephengillie commented
/AzurePipelines run

2023-03-03 16:34 UTC, stephengillie approved these changes

2023-03-03 16:34 UTC, merged