ExacqTechnologies.exacqVisionClient version 22.12.2.0
microsoft/winget-pkgs pull request #98396
Opened 2023-03-03 17:34 UTC by camatthew

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-03-03 21:22 UTC, stephengillie commented
Hi @camatthew,

The installer isn't unattended:
![image](https://user-images.githubusercontent.com/114952565/222831728-7d46b57a-6388-48e8-be56-2e3b78461ab0.png)

Is there an installer switch to bypass this and have the installer perform the install automatically?

2023-03-03 21:27 UTC, camatthew commented
/S should do it

2023-03-16 21:20 UTC, stephengillie commented on manifests/e/ExacqTechnologies/exacqVisionClient/22.12.2.0/ExacqTechnologies.exacqVisionClient.installer.yaml
> +  ProductCode: '{133D0A53-AABC-48AE-98DA-B85512C51E78}'
```suggestion
  ProductCode: '{133D0A53-AABC-48AE-98DA-B85512C51E78}'
  InstallerSwitches:
    Custom: /quiet
```

2023-03-16 21:20 UTC, stephengillie commented on manifests/e/ExacqTechnologies/exacqVisionClient/22.12.2.0/ExacqTechnologies.exacqVisionClient.installer.yaml
> +  ProductCode: '{133D0A53-AABC-48AE-98DA-B85512C51E78}'
Using `/S` gives the installer switch menu:
![image](https://user-images.githubusercontent.com/114952565/225755105-63b62182-1e1a-438f-8ef6-7b2beb372aa4.png)

2023-03-17 02:55 UTC, camatthew commented
Let's see if you comment worked. Thanks for the suggestion, I have been extremely busy with my college class I'm taking write now so I haven't had time to fix this.

2023-03-17 13:56 UTC, Trenly requested changes

2023-03-17 13:56 UTC, Trenly commented on manifests/e/ExacqTechnologies/exacqVisionClient/22.12.2.0/ExacqTechnologies.exacqVisionClient.installer.yaml
> +    Custom: /quiet
@stephengillie's suggestion will make it so all installs are silent, even if the user requests an interactive one.
```suggestion
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /passive
```

2023-03-17 16:41 UTC, stephengillie commented on manifests/e/ExacqTechnologies/exacqVisionClient/22.12.2.0/ExacqTechnologies.exacqVisionClient.installer.yaml
> +    SilentWithProgress: /passive
```suggestion
```

2023-03-17 16:58 UTC, stephengillie commented on manifests/e/ExacqTechnologies/exacqVisionClient/22.12.2.0/ExacqTechnologies.exacqVisionClient.installer.yaml
> +    SilentWithProgress: /passive
```suggestion
    Custom: /quiet
```

2023-03-17 16:59 UTC, stephengillie commented on manifests/e/ExacqTechnologies/exacqVisionClient/22.12.2.0/ExacqTechnologies.exacqVisionClient.installer.yaml
> +    SilentWithProgress: /passive
Testing in a Windows 11 VM, this has been the only combination that results in an unattended install. It appears there may not be a way to display the progress bar with an unattended install.

2023-03-23 22:32 UTC, stephengillie approved these changes

2023-03-23 22:32 UTC, merged