SamyGo.RemoteLANControl version 0.8
microsoft/winget-pkgs pull request #98663
Opened 2023-03-06 20:46 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-03-14 19:07 UTC, Trenly requested changes

2023-03-14 19:07 UTC, Trenly commented on manifests/s/SamyGo/RemoteLANControl/0.8/SamyGo.RemoteLANControl.installer.yaml
> +  NestedInstallerType: exe
```suggestion
  NestedInstallerType: portable
```

2023-03-14 19:07 UTC, Trenly commented on manifests/s/SamyGo/RemoteLANControl/0.8/SamyGo.RemoteLANControl.locale.en-US.yaml
> +License: http://download.samygo.tv/PC%20Applications/Remote%20LAN%20Control%20(v0.8).zip
```suggestion
License: Proprietary
```

2023-03-14 19:07 UTC, Trenly commented on manifests/s/SamyGo/RemoteLANControl/0.8/SamyGo.RemoteLANControl.locale.en-US.yaml
> +ShortDescription: SamyGO Remote LAN
Please provide a better short description of what the package does

2023-03-17 13:59 UTC, Trenly approved these changes

2023-03-23 18:05 UTC, upintheairsheep commented
merge?

2023-03-27 21:02 UTC, merged