Samsung.DataMigration version 14.0.162
microsoft/winget-pkgs pull request #99332
Opened 2023-03-13 16:52 UTC by upintheairsheep

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-03-14 15:11 UTC, Trenly requested changes

2023-03-14 15:11 UTC, Trenly commented on manifests/s/Samsung/DataMigration/14.0.162/Samsung.DataMigration.installer.yaml
> +PackageVersion: 14.0.162
```suggestion
PackageVersion: 2.0
```
Writes `2.0` to the control panel when the install works

2023-03-14 15:11 UTC, Trenly commented on manifests/s/Samsung/DataMigration/14.0.162/Samsung.DataMigration.locale.en-US.yaml
> +Publisher: Macrovision Corporation
```suggestion
Publisher: Samsung
```
Writes `Samsung` to control panel

2023-03-14 15:11 UTC, Trenly commented on manifests/s/Samsung/DataMigration/14.0.162/Samsung.DataMigration.locale.en-US.yaml
> +PackageName: Samsung Data Migration Tool for SSDs
```suggestion
PackageName: Samsung Data Migration
```

2023-03-14 15:11 UTC, Trenly commented on manifests/s/Samsung/DataMigration/14.0.162/Samsung.DataMigration.yaml
> +PackageVersion: 14.0.162
```suggestion
PackageVersion: 2.0
```
Writes `2.0` to the control panel when the install works

2023-03-27 11:58 UTC, closed without merging

2023-03-27 20:08 UTC, upintheairsheep commented
Re-open please