Cimbali.pympress version 1.7.2: Added x86 architecture installer
microsoft/winget-pkgs pull request #99527
Opened 2023-03-15 07:37 UTC by paulo-haas

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

2023-03-15 16:19 UTC, Trenly requested changes

2023-03-15 16:19 UTC, Trenly commented on manifests/c/Cimbali/pympress/1.7.2/Cimbali.pympress.installer.yaml
> +ProductCode: '{8DBAA4EF-FA88-4C57-88CD-1DAAC4879887}'
```suggestion
```

2023-03-15 16:19 UTC, Trenly commented on manifests/c/Cimbali/pympress/1.7.2/Cimbali.pympress.installer.yaml
>    InstallerSha256: 3044D8DC8A27FDAF31AF7E53CD4F3E0C09CC223A0BDBC1D80AF1679ED0A1A87C
```suggestion
  InstallerSha256: 3044D8DC8A27FDAF31AF7E53CD4F3E0C09CC223A0BDBC1D80AF1679ED0A1A87C
  ProductCode: '{8DBAA4EF-FA88-4C57-88CD-1DAAC4879887}'
```

2023-03-15 16:19 UTC, Trenly commented on manifests/c/Cimbali/pympress/1.7.2/Cimbali.pympress.installer.yaml
> +  InstallerSha256: B81C273A0D5475BBD2C4707091D3B9D41AD030BBF06BA7AF2B5AE8C26B31E2F4
```suggestion
  InstallerSha256: B81C273A0D5475BBD2C4707091D3B9D41AD030BBF06BA7AF2B5AE8C26B31E2F4
  ProductCode: '{36D84668-75A2-4157-99FC-F3FD8D6346EB}'
```

2023-03-16 21:47 UTC, stephengillie approved these changes

2023-03-16 21:47 UTC, merged