New version: Cimbali.pympress version 1.8.0
microsoft/winget-pkgs pull request #99526
Opened 2023-03-15 07:30 UTC by paulo-haas

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

2023-03-15 16:26 UTC, Trenly requested changes

2023-03-15 16:26 UTC, Trenly commented on manifests/c/Cimbali/pympress/1.8.0/Cimbali.pympress.installer.yaml
> +ProductCode: '{8DBAA4EF-FA88-4C57-88CD-1DAAC4879887}'
```suggestion
```

2023-03-15 16:26 UTC, Trenly commented on manifests/c/Cimbali/pympress/1.8.0/Cimbali.pympress.installer.yaml
> +  InstallerSha256: 2610AF28A7A0150D0C41F2F02D29178C55F74C7BFE7AA0F5992FCFCA49FB0522
```suggestion
  InstallerSha256: 2610AF28A7A0150D0C41F2F02D29178C55F74C7BFE7AA0F5992FCFCA49FB0522
  ProductCode: '{D6AE5C63-326E-4F27-B1C1-CD1E04B187E7}'
```

2023-03-15 16:26 UTC, Trenly commented on manifests/c/Cimbali/pympress/1.8.0/Cimbali.pympress.installer.yaml
> +  InstallerSha256: 24cbd4c5fa5dfa1fd58feb93c766b48f220516518982d4927590893b7b52ca1f
```suggestion
  InstallerSha256: 24CBD4C5FA5DFA1FD58FEB93C766B48F220516518982D4927590893B7B52CA1F
  ProductCode: '{50E9CAB7-CDCD-4C61-BFE9-015C32EEA70D}'
```

2023-03-16 21:37 UTC, stephengillie approved these changes

2023-03-16 21:38 UTC, merged