New Package: Morpheus.Bazarr version 1.2.0
microsoft/winget-pkgs pull request #99640
Opened 2023-03-16 10:54 UTC by babblebauble

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99640)

2023-03-17 14:16 UTC, Trenly requested changes

2023-03-17 14:16 UTC, Trenly commented on manifests/m/Morpheus/Bazarr/1.2.0/Morpheus.Bazarr.installer.yaml
> +    SilentWithProgress: /SILENT
```suggestion
```
These should be the default anyways because you specified inno

2023-03-17 18:20 UTC, stephengillie commented
/AzurePipelines run

2023-03-20 19:26 UTC, stephengillie commented
Hi @babblebauble,

The application installed normally, but there doesn't seem to be a main executable. How do we launch this application?

2023-03-20 20:32 UTC, babblebauble commented
> Hi @babblebauble,
> 
> The application installed normally, but there doesn't seem to be a main executable. How do we launch this application?

Hi

The installer should create a start menu shortcut that launches the Web UI. Alternately, one can input the IP address and port (http://localhost:6767) into your browser to launch the Web UI.

2023-03-21 19:57 UTC, stephengillie commented
Hi @babblebauble,

The application installed normally, but didn't seem to install any executables, only these 2 files:
```
C:\Users\User\AppData\Roaming\foobar2000\user-components\foo_monkeymote\foo_monkeymote.dll
C:\Users\User\AppData\Roaming\foobar2000\user-components\foo_monkeymote\foo_monkeymote_uninstall.exe
```

2023-03-21 20:45 UTC, stephengillie commented
> The installer should create a start menu shortcut that launches the Web UI. Alternately, one can input the address and port (http://localhost:6767) into your browser to launch the Web UI.

The Start menu shortcut isn't being created, but manually navigating to the locally hosted website works well: 
![image](https://user-images.githubusercontent.com/114952565/226736286-aff85976-e10e-4064-95d2-c7550b222b60.png)

2023-03-22 12:01 UTC, babblebauble commented
> The Start menu shortcut isn't being created, but manually navigating to the locally hosted website works well.

I'm not able to recreate this issue on my end. Tested out a few times and the installer always creates an internet shortcut on the start menu to launch the Web UI: 
![Capture](https://user-images.githubusercontent.com/96543907/226898773-236dd1e7-58c4-4c00-aa0e-7202f60ad281.PNG)

2023-03-24 22:20 UTC, stephengillie approved these changes

2023-03-24 22:20 UTC, merged