New version: Puppet.pdk version 2.7.0
microsoft/winget-pkgs pull request #99885
Opened 2023-03-18 08:15 UTC by chelnak

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

2023-03-18 20:18 UTC, mdanish-kh requested changes

2023-03-18 20:18 UTC, mdanish-kh commented on manifests/p/Puppet/pdk/2.7.0/Puppet.pdk.locale.en-US.yaml
> +ShortDescription: Puppet.pdk
```suggestion
ShortDescription: |
  The Puppet Development Kit (PDK) includes key Puppet code development and testing tools for
  Linux, Windows, and OS X workstations, so you can install one package with the tools
  you need to create and validate new modules.
```
Need a better ShortDescription

2023-03-18 20:18 UTC, mdanish-kh commented on manifests/p/Puppet/pdk/2.7.0/Puppet.pdk.locale.en-US.yaml
> +# PrivacyUrl:
```suggestion
PublisherSupportUrl: https://github.com/puppetlabs/pdk/issues
PrivacyUrl: https://www.puppet.com/legal/privacy-policy
```
additional metadata

2023-03-19 10:16 UTC, chelnak commented
@mdanish-kh Thank you for the suggestions! They should be committed now.

2023-03-19 10:21 UTC, mdanish-kh approved these changes

2023-03-19 17:05 UTC, merged